### ISSUE TITLE
Not available at requested geography error

### ISSUE THREAD

**Issue by plnnr** [walkerke/tidycensus#100]
This fails:

    pop_by_race_10 <- get_decennial(geography = "tract", 
                                variables = 'P0090002', 
                                year = 2010, sumfile = "sf1", state = "41", 
                                county = "051", 
                                summary_var = 'P0090001',
                                geometry = T)
With this error message:

    Error : One or more of your requested variables is likely not available at the requested geography.  
    Please refine your selection.

But I know it is available at the tract level.

**Comment by plnnr** [comment]
Also chyeah boi, I submitted issue #100!

**Comment by walkerke** [comment]
The Census Bureau changed variable IDs for many variables in the 2010 decennial Census, usually removing extra 0s (see #91 ).  This makes your code fail (though it would have worked with the old endpoint).  The code below works, however, with the latest version of tidycensus (0.8.1): 

```r
pop_by_race_10 <- get_decennial(geography = "tract", 
                            variables = 'P009002', 
                            year = 2010, sumfile = "sf1", state = "41", 
                            county = "051", 
                            summary_var = 'P009001',
                            geometry = T)
```
