### ISSUE TITLE
Problem with finding variable names in 2010 Census 

### ISSUE THREAD

**Issue by cryerger** [walkerke/tidycensus#102]
I am having an issue with variable name recognition for the 2010 census.  This works for 2000:

m80 <- get_decennial(geography = "state", variables = "P001001", year = 2000)

but a similar-looking line does not work for 2010: 

m80 <- get_decennial(geography = "state", variables = "P001001", year = 2010).

I searched for this variable and found it (had not changed) using 
v15 <- load_variables(2010, "sf1", cache = TRUE),

so I have some confidence that I am using the correct variable name here. I tried some other variants of this variable name and had similar problems.  Is there something else that is missing, or have the variable names been changed in some other way?  If the latter is the case, where could I find this?

**Comment by walkerke** [comment]
@cryerger the new Census API endpoints all appear to be down right now, you aren't doing anything wrong.  I know the team at the Census Bureau has been rolling out a lot of changes which might explain it.  If you need 2010 data urgently it appears that the old endpoint is still working, so you could use the censusapi package or use `devtools::install_version()` to grab an older version of tidycensus that uses those endpoints.  

@loganpowell just checking - I note that all the new endpoints are down.  Is this temporary or is this something I should address?

**Comment by cryerger** [comment]
Thank you for this update - I am teaching a college class where we planned to use this data (and previous versions of the course were built upon this 2010 data).  Would you be able to say a bit more about how to use this older version or the censusapi package or point me in the right direction for resources?  I want to make sure that whatever solution I present to my students is stable.

Thank you!

**Comment by walkerke** [comment]
I sent a note to Census about the status of these endpoints - hopefully they'll be back up soon.  If you want to use the old endpoints (which are still up, and working) you can install tidycensus 0.4.6 with `devtools::install_version("tidycensus", version = "0.4.6", repos = "http://cran.us.r-project.org")`.  

Documentation for the censusapi package is here: https://hrecht.github.io/censusapi/.  You can get data from all of the Census APIs with this package; you just need to know a bit about how the endpoints are formatted.

**Comment by walkerke** [comment]
@cryerger I just heard back from the Census Bureau and they've fixed the API issue so your code will work as expected with the latest version of tidycensus (0.8.1); I've just checked and can confirm this.
