### ISSUE TITLE
get_acs creates a long progress bar in rendered html

### ISSUE THREAD

**Issue by Babakjfard** [walkerke/tidycensus#109]
Thank you vey much for your great work. Very helpful. I have an issue with get_acs. as the title says the rendered html page from my R-Markdown creates a large progress bar. I have tried these options, non working:
`options(get_acs.show_progress = FALSE)
options(readr.show_progress = FALSE)`

also, have used `message=FALSE`, and `warning=FALSE` in the header of the chunk.  No results. [here is a link](https://awesome-galileo-7f9544.netlify.com/2018/08/heatwave-in-the-town-of-brookline-ma/) to the published page.

Thank you very much for your help

**Comment by walkerke** [comment]
There are two ways to do this.  One: use shapefile caching with `options(tigris_use_cache = TRUE)`; this will read in the geometry from a cache instead of downloading after the first time you download it.  

The other: use `results = "hide"` in your code chunk definition.  E.g.: 

```
{r, results = "hide"}
```
