### ISSUE TITLE
Zip code data?

### ISSUE THREAD

**Issue by jakeander** [walkerke/tidycensus#11]
This must be easy but I can't seem to extract zip code data. Is the geography part of get_acs() need to be a specific zip code qualifier?

**Comment by walkerke** [comment]
You can get zip code data by setting `geography = "zip code tabulation area` or `geography = "zcta"`.  For example: 

```
zc <- get_acs(geography = "zip code tabulation area", variables = "B19013_001",
              summary_var = "B01001_001", geometry = TRUE)
```

Right now, you have to get ZCTAs for the whole country and then subset yourself within R, though I may add a `starts_with` parameter in the future, like the one that is in __tigris__.

**Comment by jakeander** [comment]
Just wanted to say thanks for the assistance. Works perfect. Excellent package!

**Comment by walkerke** [comment]
No problem - thanks for using the package!  Let me know if anything else comes up.
