### ISSUE TITLE
Package option to suppress console output

### ISSUE THREAD

**Issue by ummel** [walkerke/tidycensus#111]
Be default, get_acs() and similar functions report messages and progress bar to console. For example:

> get_acs(geography = "tract", variables = "B19013_001", state = "TX", county = "Tarrant", geometry = TRUE)
> Getting data from the 2012-2016 5-year ACS
> Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
> Using FIPS code '48' for state 'TX'
> Using FIPS code '439' for 'Tarrant County'
>   |===============================================================================================================================================| 100%

It would be nice to have a package option to suppress console output. As is, putting get_acs(), etc. in a wrapper function causes the user's own messages to be swamped by get_acs().

**Comment by coreysparks** [comment]
Are you using R markdown? If you are, then in the beginning of your code chunk, you can put ` ```{r, results='hide']}`


` ```{r, results='hide']}

get_acs(geography = "tract", variables = "B19013_001", state = "TX", county = "Tarrant", geometry = TRUE)

``` `

and you won't see the progress bar in the output

**Comment by walkerke** [comment]
I've improved this a bit with the latest version of tidycensus (e.g. with multi-county block group calls).  However for custom functions I'd recommend using `suppressMessages()` or @coreysparks's suggestion in RMarkdown.
