### ISSUE TITLE
Error fetching B11016 (and possibly all B tables?)

### ISSUE THREAD

**Issue by arilamstein** [walkerke/tidycensus#112]
When I try to fetch table [B11016](https://factfinder.census.gov/bkmk/table/1.0/en/ACS/15_5YR/B11016/0500000US48015) with `get_acs` I get an error:

````
> df = get_acs(geography = "county", state="michigan", year = 2016, table = "B11016")
Getting data from the 2012-2016 5-year ACS
Error in variables_from_table_acs(table, year, survey2, cache_table) : 
  object 'survey2' not found
````

In fact, I have a list of 11 B tables that I am trying to get, and I get the same error when I try to fetch any of them.

At first I thought that I might have incorrect syntax. But the above code works just fine when I give it a subject table. E.g.

````
> df = get_acs(geography = "county", state="michigan", year = 2016, table = "S1902")
Getting data from the 2012-2016 5-year ACS
Using the ACS Subject Tables
Using FIPS code '26' for state 'Michigan'
Using the ACS Subject Tables
Using FIPS code '26' for state 'Michigan'
Using the ACS Subject Tables
Using FIPS code '26' for state 'Michigan'
````

Is this a known issue? Is it possible to use TidyCensus to get the B tables?

**Comment by walkerke** [comment]
Hey Ari - that's a bug I fixed in https://github.com/walkerke/tidycensus/commit/0589270a04bc9163d30cec4d6b56e0a64f47d3d1.  Re-install from GitHub and it should work.

**Comment by arilamstein** [comment]
Thank you!
