### ISSUE TITLE
API Key error 

### ISSUE THREAD

**Issue by tk2125** [walkerke/tidycensus#114]
Using get_acs to get census tract data and getting the following error:

Error: Your API call has errors.  The API message returned is There was an error while running your query.  We've logged the error and we'll correct it ASAP.  Sorry for the inconvenience..

**Comment by walkerke** [comment]
Sounds like it was an API hiccup given the message (that's the Census Bureau's message).  

That said - when you file an issue please provide a minimal reproducible example that the developer can test (e.g. https://robjhyndman.com/hyndsight/minimal-reproducible-examples/).  If you only post an error message without the code that generated the error, it's not possible for the developer to debug it.
