### ISSUE TITLE
Problem with PCT variable

### ISSUE THREAD

**Issue by jlegewie** [walkerke/tidycensus#115]
Hi,

I am not sure whether this is an issue or whether I am doing something wrong. 'PCT' are population tables that cover geographies to the census tract level. They don't show up in `load_variables` but I can pull them with `get_decennial`. Here is an example:

```
vars <- load_variables(2010, "sf1", cache = TRUE)
table(vars$name == "PCT012001")
get_decennial(geography = "state", variables = "PCT012001", year = 2010)
```

The census API also shows the PCT variables/tables at
https://api.census.gov/data/2010/sf1/variables.html

**Comment by jlegewie** [comment]
Great. Note that there are also HCT tables and some others that I never used. Here is a full list of the different table types (PL is probably irrelevant):

- 'P' are population tables
- 'H' are housing tables
- 'PCT' are population tables that cover geographies to the census tract level
- 'HCT' are housing tables that cover geographies to the census tract level
- 'PCO' are population tables that cover geographies to the county level
- 'HCO' are housing tables to the county level
- 'PL' are tables derived from the Redistricting Data (P.L. 94-171) Summary File (Census 2000 only).

**Comment by walkerke** [comment]
Just pushed a quick fix.  Note that if you are using caching for the variables datasets you'll need to go in and manually delete the old one; you can find the location at `rappdirs::user_cache_dir("tidycensus")`.  I'll probably put in some logic to overwrite existing datasets without those variables before the next CRAN release.

**Comment by nmpeterson** [comment]
I just installed the latest version of tidycensus (0.11) and only variables with a `P` or `H` prefix are present in the results of `load_variables(2010, "sf1")` (I'm specifically looking for the `PCO` variables). I have tried this with and without `cache=TRUE` and removed the old cached file before doing so.

**Comment by mfherman** [comment]
@nmpeterson Thanks for the report!

@walkerke Looks like this was an oversight when I updated `load_variables()`. If you haven't already submitted to CRAN, maybe hold off until this is fixed? Should be a quick one, I think.

**Comment by walkerke** [comment]
@mfherman I haven't submitted yet, no worries!  Let's get this fixed and then I'll send it to CRAN.
