### ISSUE TITLE
Demographic profile tables for ZCTA

### ISSUE THREAD

**Issue by coreysparks** [walkerke/tidycensus#116]
I'm doing the following query to get demographic profile tables for Zip code tabulation areas:
`
acs<-get_acs(geography = "zcta", year = 2014,
                variables=c( "DP05_0001E", "DP03_0009P", "DP03_0062E", "DP03_0119PE") ,
                geometry = F, output = "wide")
`

And getting the error: 
`
Getting data from the 2010-2014 5-year ACS
Using the ACS Data Profile
Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.
`

the query works if I use a non-DP table, but not when I use the DP tables. I checked and ZCTA's have the DP tables on factfinder, and they list these tables: [here](https://api.census.gov/data/2014/acs/acs5/profile/variables.html) as being available on the API.

any suggestions would be greatly appreciated!

**Comment by coreysparks** [comment]
as a note, I can get what I need from `censusapi`

`
zcsdat<-getCensus(
  name = "acs5/profile",
  vars = c("DP05_0001E", "DP03_0009P", "DP03_0062E", "DP03_0119PE"),
  region = "zip code tabulation area:*",
  vintage = 2013,
  key = "mykey"
)
`

so it's possible

**Comment by walkerke** [comment]
@coreysparks thanks for filing.  It's an issue with the new ACS API endpoints; you are using the old endpoint (which is working) but the new endpoint (which I've written into tidycensus) is not working for ZCTAs prior to 2015.  I'll need to ping Census about this but in the meantime using censusapi is a good idea.

**Comment by walkerke** [comment]
@coreysparks I've just tested, and your code now works!

```r
> get_acs(geography = "zcta", 
+         year = 2014, 
+         variables = c("DP05_0001E", "DP03_0009P", "DP03_0062E", "DP03_0119PE") , 
+         geometry = F, 
+         output = "wide")
Getting data from the 2010-2014 5-year ACS
Using the ACS Data Profile
# A tibble: 33,120 x 10
   GEOID NAME  DP05_0001E DP05_0001M DP03_0009PE DP03_0009PM DP03_0062E DP03_0062M
   <chr> <chr>      <dbl>      <dbl>       <dbl>       <dbl>      <dbl>      <dbl>
 1 00601 ZCTA…      18088        295        33           4        10833       1531
 2 00602 ZCTA…      40859        154        27.8         3        16353        977
 3 00603 ZCTA…      53162        657        24.7         2.7      16323        872
 4 00606 ZCTA…       6415        264         9.2         6.3      14138       2157
 5 00610 ZCTA…      28805        163        13.8         2.6      17265       1065
 6 00612 ZCTA…      66251       1289        18.9         2.4      17752        783
 7 00616 ZCTA…      10466        906        10.1         3.5      15115       2164
 8 00617 ZCTA…      24917        134        17.2         3.3      15461       1514
 9 00622 ZCTA…       6589       1001         9.9         6.5      14993       3916
10 00623 ZCTA…      44117       1001        12.3         2.7      17044       1186
# … with 33,110 more rows, and 2 more variables: DP03_0119PE <dbl>, DP03_0119PM <dbl>
```

**Comment by coreysparks** [comment]
Thanks!
