### ISSUE TITLE
Cannot get variables for GCT2701

### ISSUE THREAD

**Issue by arilamstein** [walkerke/tidycensus#119]
I am trying to use `tidycensus` to get county data for [GCT2701 PERCENT WITHOUT HEALTH INSURANCE COVERAGE](https://factfinder.census.gov/bkmk/table/1.0/en/ACS/16_5YR/GCT2701.ST05/0400000US26) but can get neither the variables nor the data.

Here is how I attempted to get the variable names:
```
all_tbl_vars = load_variables(year = 2016, dataset = "acs5", cache = TRUE)

str = paste0("^GCT", table)
table_vars = all_tbl_vars %>%
  filter(str_detect(name, str)) 
# A tibble: 0 x 3
# ... with 3 variables: name <chr>, label <chr>, concept <chr>
```

Here is how I am attempting to get the data:
```
df = get_acs(geography = "county", 
             state     = "michigan", 
             table     = "GCT2701", 
             year      = 2016, 
             survey    = "acs5", 
             output    = "wide") 
Getting data from the 2012-2016 5-year ACS
Using FIPS code '26' for state 'Michigan'
No encoding supplied: defaulting to UTF-8.
Error: Your API call has errors.  The API message returned is .
```

Does `tidycensus` support working with the GCT tables?

**Comment by walkerke** [comment]
I don't see geographic comparison tables in the API though perhaps I just can't find it.  Perhaps the censusapi package could do it but I'm not seeing those listed as valid variables in the ACS docs.  Might be a question to ask on the Census Slack channel.

**Comment by arilamstein** [comment]
Thanks for the quick reply Kyle. I just asked there and will update this thread with the answer.

**Comment by arilamstein** [comment]
I just heard back from Census that they do not currently provide access to GCT tables via the API.
