### ISSUE TITLE
fails to retrieve congressional district level data for 115th Congress

### ISSUE THREAD

**Issue by soungl** [walkerke/tidycensus#120]
Hello.

Is there a way to retrieve Decennial Census 2010 data for the 115th Congress? I can only get data for the 111th Congress? See below for my code. Thank you.

vars10 <- c(seasonalHome = "H005006", # vacant for seasonal, recreational, or occasional use
            totalHome = "H001001", # total number of homoes in 2010
            pop2010 = "P001001") # total population in 2010

get_decennial(geography = geo,
                variables = vars10,
                year = 2010,
                state = c("NH", "ME", "VT", "NY"),
                geometry = FALSE)

**Comment by walkerke** [comment]
You can't get decennial Census data for the 115th Congress; you'd need to use `get_acs()` for that as the decennial data only correspond to the congress that was in session at the time of the count.
