### ISSUE TITLE
ACS 5 year not available at requested geography

### ISSUE THREAD

**Issue by nbrazil** [walkerke/tidycensus#122]
This fails on a Windows Machine

```
 testing <- get_acs(geography = "county" , 
                    year = 2009 , 
                    variables = c(var1 = "B25077_001", 
                                  var2 = "B19013_001"), 
                    state = "CA", survey= "acs5")
```

I get this

```
Getting data from the 2005-2009 5-year ACS
Using FIPS code '06' for state 'CA'
Error: One or more of your requested variables is likely not available at the requested geography.  Please refine your selection.
```

Also, when I try to view the  variables

`v1 <- load_variables(2009, "acs5", cache=TRUE)`

I get

```
Error: lexical error: invalid char in json text.
                                       <html><head><title>Error report
                     (right here) ------^
```

All other 5-year ACS works.  Moreover, the above code works on my Mac laptop.

**Comment by walkerke** [comment]
It looks like Census hasn't yet migrated the 2005-2009 ACS to the new endpoint which I'm using in `get_acs()`.  I'll fix this.  My guess is that you have an older version of tidycensus installed on your Mac which is using the old endpoint.

**Comment by ulfelder** [comment]
I just installed `tidycensus` and am getting the same "lexical error" response whenever I try to use `get_acs()`, even just copying and pasting an example from your vignette.

**Comment by walkerke** [comment]
My guess is that you need to activate your Census API key (see https://github.com/walkerke/tidycensus/issues/117).  Have you done this?

**Comment by ulfelder** [comment]
@walkerke, my apologies, I had not activated the key. I did that, and now the code runs fine. Thank you.

**Comment by bbrewington** [comment]
Maybe build the check for active census api key into the function, so the error message is more informative?

**Comment by walkerke** [comment]
@bbrewington I've added an error message explaining @ulfelder's error as of https://github.com/walkerke/tidycensus/commit/7173758f62b547107e41c855ee2269e29a968d19.  I'll put some error handling into `load_variables()` to account for if a user requests a dataset that doesn't exist yet.

**Comment by walkerke** [comment]
@nbrazil just pushed a fix to revert to the old API endpoint for 2005-2009.  However the old endpoints are slated to be removed at the end of the month, so I don't know if this is a long-term fix.

**Comment by evansklodge** [comment]
This code:

acs5 <- load_variables(year = 2009, "acs5", cache = TRUE)

returns the same error discussed above:

Error: lexical error: invalid char in json text.
                                       <html><head><title>Error report
                     (right here) ------^

Any thoughts?

**Comment by abuabara** [comment]
Your problem is the year. ACS 5y started just in 2013, as you can see here: https://www.census.gov/programs-surveys/acs/guidance/estimates.html

> This code:
> 
> acs5 <- load_variables(year = 2009, "acs5", cache = TRUE)
> 
> returns the same error discussed above:
> 
> Error: lexical error: invalid char in json text.
> <title>Error report
> (right here) ------^
> 
> Any thoughts?

**Comment by evansklodge** [comment]
I'm pretty sure that's not correct. The ACS definitely has 5-year data for 2005-2009. Here's an example dataset from FactFinder:

https://factfinder.census.gov/faces/tableservices/jsf/pages/productview.xhtml?src=bkmk

**Comment by abuabara** [comment]
Sorry. Your link doesn't open here. You are right, I don't know. To me any year after 2010 works.

**Comment by mfherman** [comment]
Just submitted PR #166 that should fix this bug. @walkerke fixed the API endpoint for 2009 for getting data in #122, but this fixes it in  `load_variables()` too. 

@evansklodge when this PR is merged, can you test to make sure it is working on your end for 2009.

**Comment by evansklodge** [comment]
Forgot to reply to this earlier, but yes! Works perfectly now. Thank you very much.
