### ISSUE TITLE
Error in gather_(data, key_col = compat_as_lazy(enquo(key)), value_col = compat_as_lazy(enquo(value)), : unused argument (-NAME)

### ISSUE THREAD

**Issue by hafix00** [walkerke/tidycensus#123]
I am getting this error message even when I try a code as simple as this:

cuyahogaPop <- get_decennial(geography = "county", year = "2010", state = "OH", variable = "P0010001")

**Comment by walkerke** [comment]
Census has changed the decennial variable IDs.  This works: 

```r
cuyahogaPop <- get_decennial(geography = "county", state = "OH", variable = "P001001")
```
