### ISSUE TITLE
?get_acs state parameter

### ISSUE THREAD

**Issue by arilamstein** [walkerke/tidycensus#124]
I have a case where I need to get data for multiple states. The documentation (and the fact that the parameter is singular) makes it sound like the the function can only get data for one state at a time. Here's the documentation for the `state` parameter for `?get_acs`:

``
The state for which you are requesting data. State names, postal codes, and FIPS codes are accepted. Defaults to NULL.
``

However, the parameter can indeed handle a vector of states:

```
get_acs(geography = "county", 
         state     = c("michigan", "illinois"), 
         table     = "B01001")
Getting data from the 2012-2016 5-year ACS
Using FIPS code '26' for state 'Michigan'
Using FIPS code '17' for state 'Illinois'
```

I wonder if it makes sense to change the parameter name to `states`. If I hadn't decided to test this myself I would have written this in multiple calls.

**Comment by walkerke** [comment]
Some geographies like counties can take multiple states, but many others (e.g. tracts, school districts) cannot, so I'm going to keep `state` the way it is.  However - I would welcome a PR to modify the documentation.

**Comment by arilamstein** [comment]
Done.

Now that I'm looking at the documentation more closely, there might be room for other changes. For example, the `state` parameter says: "Defaults to NULL." While this is accurate, it also doesn't tell me what it means to have the variable be NULL. If it means "all states", then it might be useful to change the last sentence to be something like "If NULL, then get data for all states".
