### ISSUE TITLE
Comparison Profile tables

### ISSUE THREAD

**Issue by arilamstein** [walkerke/tidycensus#126]
It looks like `tidycensus` does not currently support the Comparison Profile (CP) tables. E.g.:
```
get_acs(geography = "county", 
       state     = "michigan", 
       table     = "CP03", 
       year      = 2016, 
       survey    = "acs5", 
       output    = "wide")

Getting data from the 2012-2016 5-year ACS
Using FIPS code '26' for state 'Michigan'
No encoding supplied: defaulting to UTF-8.
Error: Your API call has errors.  The API message returned is .
```
According to [the Census API page](https://api.census.gov/data.html) there is currently support for the Comparison tables, although it is listed as "BETA".

I'm curious if you are planning to add support for this tables, and if so, what the relative priority of adding them is.

**Comment by walkerke** [comment]
@arilamstein this is the first request I've received for the Comparison tables, so I hadn't been considering implementing it.  It may be something I do at some point but it's not a top priority at the moment.  __ censusapi__ can do it so you may want to check that out.

**Comment by walkerke** [comment]
In case anyone happens upon this old issue; I went ahead and implemented this today, so Ari's code above will now work (as of today, GitHub version only; it'll be in tidycensus 1.2 on CRAN when that is published).
