### ISSUE TITLE
get_acs for 5years bug

### ISSUE THREAD

**Issue by AnastasiiaFR** [walkerke/tidycensus#127]
Good day,

When trying to pull the data:

v16 <- load_variables(year = 2016, dataset = "acs5", cache = TRUE)
View(v16)

data <- get_acs(geography = "county", state = "MA", variable = "B25060_001")

get the error:

No encoding supplied: defaulting to UTF-8.
Error: lexical error: invalid char in json text.
                                       <html>     <head>         <titl
                     (right here) ------^

Tried all optioned proposed here but did not work....Kindly advise

**Comment by walkerke** [comment]
@AnastasiiaFR have you activated your Census API key?  Make sure to click the activation link in the email Census sends you with the key.  Then try again and your code should work.

**Comment by AnastasiiaFR** [comment]
@walkerke, thank you so much! Was digging into error and missed the obvious thing...
