### ISSUE TITLE
get_acs() fails with dev version of {tibble}

### ISSUE THREAD

**Issue by mfherman** [walkerke/tidycensus#128]
I just updated to the dev version of `tibble` (1.4.99.9005) from GitHub and am getting this error I haven't seen before:

``` r
library(tidycensus)

data <- get_acs(geography = "county", state = "MA", variable = "B25060_001")
#> Getting data from the 2012-2016 5-year ACS
#> Error: Columns 1, 2, 3, 4, 5 must be named.
Call `rlang::last_error()` to see a backtrace
```
When I run `rlang::last_error()` I see the following:

```r
<error>
message: Columns 1, 2, 3, 4, 5 must be named.
class:   `rlang_error`
backtrace:
 ─tidycensus::get_acs(geography = "county", state = "MA", variable = "B25060_001")
 ─tidycensus:::load_data_acs(...)
 ─dplyr::tbl_df(fromJSON(content))
 ─tibble::as_data_frame(data)
 ─tibble:::as_tibble.matrix(x, ...)
 ─tibble:::as_tibble.data.frame(m, ...)
 ─tibble:::as_tibble.list(unclass(x), ..., .rows = .rows, .name_repair = .name_repair)
 ─tibble:::set_repaired_names(x, .name_repair)
 ─tibble:::repaired_names(names(x), .name_repair = .name_repair)
 ─tibble:::check_unique(new_name)
Call `summary(rlang::last_error())` to see the full backtrace
```
Rolling back to the CRAN version of `tibble` (1.4.2)  fixes the error.

**Comment by walkerke** [comment]
Thanks @mfherman!  In the past I've found it difficult to debug these downstream issues in the tidyverse as the API sometimes changes.  However this will hopefully give some time to fix this before they release the updated package.

**Comment by josiekre** [comment]
I'm on `tibble` (1.4.2) and still getting this same error.

**Comment by mgaughan2019** [comment]
I'm having this same error with tibble 2.0.1. Any updates on a solution?

**Comment by mfherman** [comment]
@mgaughan2019 Do you have the latest version of tidycensus (0.9) installed? If so, could you share the code and error messages that you're seeing, as well as the results of running `sessionInfo()`?

**Comment by mgaughan2019** [comment]
@mfherman Updating tidycensus solved the issue. Thanks for the tip.
