### ISSUE TITLE
Block as invalid geography or geography hierarchy

### ISSUE THREAD

**Issue by MattDaviz** [walkerke/tidycensus#13]
Following your example from your personal website [here](https://walkerke.github.io/2017/06/comparing-metros/), I'm attempting to look at rent rates, but at a block level rather than a census tract level. I used your exact code, but attempted to change 'tract' to 'block', 'block group', or 'blockgroup' to no avail. This might be a simple fix, I just haven't found any examples of how to use block data in your tidycensus package yet. 

When I run the code below, I receive the following error message: 
> Error: You have specified an invalid geography or a geography hierarchy that is currently unavailable in tidycensus. Please visit http://api.census.gov/data/2015/acs5/geography.html for available geographies. tidycensus currently supports geographies nested within states and/or counties.

On your site, it looks as though block group is supported at geography level 150. 

```
library(tidycensus)
library(tidyverse)
library(tigris)
library(sf)
options(tigris_class = "sf")
options(tigris_use_cache = TRUE)
# census_api_key("YOUR KEY HERE")

rent <- get_acs(geography = "block", variables = "DP04_0134", 
                state = c("WA", "OR", "CA"), geometry = TRUE)
```

Thanks for any and all help!

**Comment by tiernanmartin** [comment]
👍 I'd also like to see block groups and blocks added to the list of accessible census geographies.

@MattDaviz FYI - rent data is available at the block group level, but not at the block level. Tenure type is available at the block level, but only for the decennial census (2000, 2010) - check out these summary tables to see if any of the subjects meet your needs:

- [Household Population and Household Type by Tenure: 2010 (QT-H2)](https://factfinder.census.gov/faces/tableservices/jsf/pages/productview.xhtml?pid=DEC_10_SF1_QTH2&prodType=table)
- [Household Population and Household Type by Tenure: 2010 (QT-H3)](https://factfinder.census.gov/faces/tableservices/jsf/pages/productview.xhtml?pid=DEC_10_SF1_QTH3&prodType=table)

**Comment by walkerke** [comment]
Thanks @tiernanmartin, that is correct.  

Block groups and blocks are available in __tidycensus__ - they are just available by county or counties within a given state.  So, for total population for Teton County, Wyoming at the block group and block levels: 

```r
library(tidycensus)
census_api_key("5ed58a5745802102fb83d4eec5d1f7326f65ffab")

teton15 <- get_acs(geography = "block group", variables = "B01003_001", 
                   state = "WY", county = "Teton", geometry = TRUE)

teton10 <- get_decennial(geography = "block", variables = "P0010001", 
                         state = "WY", county = "Teton", geometry = TRUE)
```

**Comment by tiernanmartin** [comment]
Thanks for clarifying, @walkerke . 

Might be helpful to add these as examples in the `get_acs` documentation if you haven't already.

**Comment by walkerke** [comment]
Good idea - I'll add to the docs.
