### ISSUE TITLE
get_decennial cannot pull more than three variables simultaneously for 2000 sf3

### ISSUE THREAD

**Issue by mafichman** [walkerke/tidycensus#132]
Starting last night, many of my students reported errors downloading SF3 data from the 2000 census. After a lot of tweaking to each parameter, we determined that we could only call a maximum of 3 variables at a time.

We also had sporadic failures using the 2000 sf3 that yielded the same error. These failures didn't seem to be systematic, and the errors are not specific.

```{r chunk1, echo=TRUE}
tracts.2000 <- get_decennial(geography = "tract",
                              year = 2000,
                              variables = c("P033001", "P033002", "P033003", "P033004"),
                             geometry = FALSE, sumfile = "sf3",
                              state = "PA",
                              county = "Philadelphia",
                              output = "wide")
```
This yields the following message (and error) console readout:

Getting data from the 2000 decennial Census
Using FIPS code '42' for state 'PA'
Using FIPS code '101' for 'Philadelphia County'
Error : Your API call has errors.  The API message returned is There was an error while running your query.  We've logged the error and we'll correct it ASAP.  Sorry for the inconvenience..
Error in UseMethod("select_") : 
  no applicable method for 'select_' applied to an object of class "character"

**Comment by walkerke** [comment]
That error message suggests an error on the API side, so there isn't anything I'll be able to do about it.  I do know that the API has been in a bit of flux so I'll monitor that.  You can also ping Census at https://gitter.im/uscensusbureau/general#.

**Comment by mafichman** [comment]
Thanks @walkerke - the timing is very inopportune, my graduate city planning students are undertaking some semester-ending projects and most are using tidycensus to do so!

**Comment by walkerke** [comment]
@mafichman I just tried running your code and it worked for me.  Could you try again?
