### ISSUE TITLE
get_acs() error for any variables in 2010 ACS 5 Year

### ISSUE THREAD

**Issue by gpreston958** [walkerke/tidycensus#134]
Potentially related thread: https://github.com/walkerke/tidycensus/issues/132

However, unlike with the 2000 Decennial SF3, the download of 2010 ACS fails regardless of number of variables or variable ID used.
```
tracts.2010 <- get_acs(geography = "tract", 
                       year = 2010, 
                       variables = c("B02001_001E"), 
                       geometry = FALSE,
                       state = "PA", 
                       county = "Philadelphia", 
                       output = "wide")
```
This yields the following error message:

Getting data from the 2006-2010 5-year ACS
Using FIPS code '42' for state 'PA'
Using FIPS code '101' for 'Philadelphia County'
Error: Your API call has errors.  The API message returned is There was an error while running your query.  We've logged the error and we'll correct it ASAP.  Sorry for the inconvenience..

**Comment by walkerke** [comment]
@gpreston958 I just ran your code and it worked for me.  Could you try again?  BTW your error message suggests an API-level problem which appears to have been resolved by Census.

**Comment by gpreston958** [comment]
Yes - it appears there was an API problem with the Census. Thanks!
