### ISSUE TITLE
Accessing 2017 5-Year ACS data

### ISSUE THREAD

**Issue by Tireur289** [walkerke/tidycensus#137]
On December 6, Census will release 5-year ACS data for 2013-2017.  Will this be available through TidyCensus then, or at some later time?  Would setting "year" to 2017 be necessary, or will tidycensus default to the most recent 5-year period?

**Comment by camille-s** [comment]
As far as I know, there shouldn't be any API changes, but do you anticipate any changes to helper functions like `load_variables`? Anything that folks can help with?

**Comment by walkerke** [comment]
@camille-s everything should work right away, including `load_variables()`.  If you see something though, let me know, thanks!

**Comment by walkerke** [comment]
I can confirm that it is working as expected!

**Comment by walkerke** [comment]
@plnnr Looks like the 2013-2017 data is not yet available by state for tracts (it works if you specify a county).  I'm not sure if, or when, they'll make this available.
