### ISSUE TITLE
Not able to download Accessing 2017 5-Year ACS  Block group level data

### ISSUE THREAD

**Issue by TDeLaNN** [walkerke/tidycensus#138]
I was able to download tract level data, but I got this error message when I tried to download block group level data. 
Error message: The API message returned is error: unknown/unsupported geography heirarchy.

So this script worked:
CensusCal <- st_sf(get_acs(geography = "tract",
                        table =  "B01003",
                        year = 2017,
                        survey = "acs5",
                        state = "OR",
                        county = "Multnomah",
                        geometry = TRUE,
                        keep_geo_vars = TRUE,
                        key = census_api_key))

But this did not work:
CensusCal <- st_sf(get_acs(geography = "block group",
                        table =  "B01003",
                        year = 2017,
                        survey = "acs5",
                        state = "OR",
                        county = "Multnomah",
                        geometry = TRUE,
                        keep_geo_vars = TRUE,
                        key = census_api_key))

The only difference is "geography" setting (tract vs. block group). 
Do you know why?

Thank you,

**Comment by larcat** [comment]
Seconding this -- works fine for prior years but is not working for 2017.

**Comment by walkerke** [comment]
just tested - this now works after a Census API update!
