### ISSUE TITLE
Error grabbing decennial block data.

### ISSUE THREAD

**Issue by larcat** [walkerke/tidycensus#140]
See below:
```
> api_url <- paste0("https://api.census.gov/data/2010/sf1?get=P0010001,NAME&for=block:*&in=state:21%20county:001&key=", Sys.getenv("CENSUS_API_KEY"))
> test <- fromJSON(api_url)
> head(test)
[[1]]
[1] "P0010001" "NAME"     "state"    "county"   "tract"    "block"   

[[2]]
[1] "50"         "Block 1000" "21"         "001"        "970100"     "1000"      

[[3]]
[1] "0"          "Block 1001" "21"         "001"        "970100"     "1001"      

[[4]]
[1] "49"         "Block 1002" "21"         "001"        "970100"     "1002"      

[[5]]
[1] "42"         "Block 1003" "21"         "001"        "970100"     "1003"      

[[6]]
[1] "12"         "Block 1004" "21"         "001"        "970100"     "1004"      

> test <- get_decennial(geography = "block", variables = "P0010001", 
+                       state = "KY", county = "001", output = "tidy")
Getting data from the 2010 decennial Census
Using FIPS code '21' for state 'KY'
Error : One or more of your requested variables is likely not available at the requested geography.  Please refine your selection.
Error in gather.default(., key = variable, value = value, -GEOID, -NAME) : 
  object 'NAME' not found
> test <- get_decennial(geography = "block", variables = "P0010001", 
+                       state = "KY", county = 001, output = "tidy")
Getting data from the 2010 decennial Census
Using FIPS code '21' for state 'KY'
Error : One or more of your requested variables is likely not available at the requested geography.  Please refine your selection.
Error in gather.default(., key = variable, value = value, -GEOID, -NAME) : 
  object 'NAME' not found
```

**Comment by larcat** [comment]
And for posterity:
`
> temp_decennial_total_pop_pull <- function(){
+   
+   ### Decennial (block level) for broadband.
+   
+     ky <- unique(fips_codes$county_code[which(fips_codes$state == "KY")])
+ 
+     totalpop <- map_df(ky, function(x) {
+ 
+       cur_api_url <- paste0("https://api.census.gov/data/2010/sf1?get=P0010001,NAME&for=block:*&in=state:21%20county:", x, "&key=", 
+                             Sys.getenv("CENSUS_API_KEY"))
+       
+       cur_json <- fromJSON(api_url)
+       
+       json_file <- lapply(cur_json, function(x) {
+         x[sapply(x, is.null)] <- NA
+         unlist(x)
+       })
+       
+       cur_df <- as.data.frame(do.call("rbind", json_file), stringsAsFactors = FALSE)
+       names(cur_df) <- cur_df[1, ]
+       cur_df <- cur_df[-1, ]
+     })
+ 
+     return(totalpop)
+   }
> test <- temp_decennial_total_pop_pull()
> head(test)
  P0010001       NAME state county  tract block
1       50 Block 1000    21    001 970100  1000
2        0 Block 1001    21    001 970100  1001
3       49 Block 1002    21    001 970100  1002
4       42 Block 1003    21    001 970100  1003
5       12 Block 1004    21    001 970100  1004
6       17 Block 1005    21    001 970100  1005
> 

> print(dim(test))
[1] 124440      6
`

**Comment by walkerke** [comment]
Census recently changed variable names for the decennial Census for the new endpoints.  So, the following call works using the variable `P001001`: 

```r
test <- get_decennial(geography = "block", variables = "P001001", 
                      state = "KY", county = "001")

> test
# A tibble: 1,037 x 4
   GEOID         NAME                                              variable value
   <chr>         <chr>                                             <chr>    <dbl>
 1 210019701001… Block 1045, Block Group 1, Census Tract 9701, Ad… P001001      0
 2 210019701001… Block 1048, Block Group 1, Census Tract 9701, Ad… P001001      0
 3 210019701001… Block 1049, Block Group 1, Census Tract 9701, Ad… P001001      0
 4 210019701001… Block 1052, Block Group 1, Census Tract 9701, Ad… P001001      0
 5 210019701001… Block 1033, Block Group 1, Census Tract 9701, Ad… P001001      0
 6 210019701001… Block 1003, Block Group 1, Census Tract 9701, Ad… P001001     42
 7 210019701001… Block 1000, Block Group 1, Census Tract 9701, Ad… P001001     50
 8 210019701001… Block 1006, Block Group 1, Census Tract 9701, Ad… P001001     28
 9 210019701001… Block 1019, Block Group 1, Census Tract 9701, Ad… P001001    106
10 210019701001… Block 1001, Block Group 1, Census Tract 9701, Ad… P001001      0
# ... with 1,027 more rows
```

The examples you've provided making calls to the API directly use the old API endpoint, which is scheduled to be removed on December 31.

**Comment by larcat** [comment]
> 
> 
> Census recently changed variable names for the decennial Census for the new endpoints. So, the following call works using the variable `P001001`:
> 
> ```r
> test <- get_decennial(geography = "block", variables = "P001001", 
>                       state = "KY", county = "001")
> 
> > test
> # A tibble: 1,037 x 4
>    GEOID         NAME                                              variable value
>    <chr>         <chr>                                             <chr>    <dbl>
>  1 210019701001… Block 1045, Block Group 1, Census Tract 9701, Ad… P001001      0
>  2 210019701001… Block 1048, Block Group 1, Census Tract 9701, Ad… P001001      0
>  3 210019701001… Block 1049, Block Group 1, Census Tract 9701, Ad… P001001      0
>  4 210019701001… Block 1052, Block Group 1, Census Tract 9701, Ad… P001001      0
>  5 210019701001… Block 1033, Block Group 1, Census Tract 9701, Ad… P001001      0
>  6 210019701001… Block 1003, Block Group 1, Census Tract 9701, Ad… P001001     42
>  7 210019701001… Block 1000, Block Group 1, Census Tract 9701, Ad… P001001     50
>  8 210019701001… Block 1006, Block Group 1, Census Tract 9701, Ad… P001001     28
>  9 210019701001… Block 1019, Block Group 1, Census Tract 9701, Ad… P001001    106
> 10 210019701001… Block 1001, Block Group 1, Census Tract 9701, Ad… P001001      0
> # ... with 1,027 more rows
> ```
> 
> The examples you've provided making calls to the API directly use the old API endpoint, which is scheduled to be removed on December 31.

Gah, my apologies. Good old _user error_. Thanks for taking the time to correct me :)

**Comment by samantaraymadhu6** [comment]
Hi,
I want to run the below code including the year 1990. Is there anyway we can add as the table name is P0010001 in 1990

kenton_pop90_10 <- map_df(c(2000, 2010), function(x) {
  get_decennial(
    geography = "county",
    variables = c(totalpop = "P001001"),
    dataset = "sf1",
    state = "KY",
    county = "kenton",
    year = x
  ) %>%
    mutate(year = x)
})
