### ISSUE TITLE
API error pulling 2017 ACS data

### ISSUE THREAD

**Issue by TBleess** [walkerke/tidycensus#141]
I am attempting to run an R script using the tidycensus package to download 2017 5 year ACS data for the US. Ideally it will call for the data for every table barring a few to load as one wide table that I will later chop into pieces to load in my database.

This works fine using 2016 ACS and earlier data with a little tweaking of the variables dropped. (Thank you so much!) But with the 2017 ACS data, I eventually get "There was an error while running your query. We've logged the error and we'll correct it ASAP." It's not any particular variable that is causing the error, sometimes I get it after it's looped through 20 variables, sometimes it will get through a few thousand before throwing this error. The code I'm running is below. Any ideas? I suspect it's an API issue so I'm reaching out to the Census Bureau about it as well.

library(tidycensus)

vars2017 <- load_variables(2017, "acs5")
vars2017 <- vars2017[-c(1,2,3,4),]
vars2017 <- vars2017[-c(25072:25106),]
vars2017 <- vars2017[-c(23349),]
tablevector <- vars2017$name
tablevector <- sub("E$","",tablevector)
tablevector <- sub("M$","",tablevector)
tablevector <- unique(tablevector)

acs500 <- function(geotype){
  x = 1
  for (i in 1:length(tablevector)){
    if ((i %% 500) == 0 | i == length(tablevector)){
      tv500 = tablevector[x:i]
      if (x == 1){
        acstab <- get_acs(geography = geotype, variables = tv500, year = 2017, output = "wide")
      }
      else{
        acstab <- cbind(acstab, get_acs(geography = geotype, variables = tv500, year = 2017, output = "wide"))
      }
      print(paste(x,i))
      x = x + 500
    }
  }
  acstab <- acstab[, !duplicated(colnames(acstab))]
  return(acstab)
}

usacs <- acs500("us")

**Comment by walkerke** [comment]
That error message refers to something on the API end - I know that there were some issues as Census rolled out the new data to the API.  Are you still experiencing the issue?

**Comment by TBleess** [comment]
Still have the issue, suspect there's no chance it will be fixed in the near future. Got all the state, county and place data downloaded by working in small chunks, I'll have to use a more manual process with the tracts and block groups.

**Comment by walkerke** [comment]
@TBleess sounds good.  with the government shutdown I've been noticing intermittent issues that can be resolved sometimes by trying again.  I will say that for bulk pulls I tend to recommend using NHGIS instead of tidycensus as you won't have to worry about API instability.
