### ISSUE TITLE
get_acs() and get_decennial() are failing

### ISSUE THREAD

**Issue by howardjp** [walkerke/tidycensus#144]
I am having some issues with`get_decennial()` and `get_acs()`.  Specifically, as of this week, calls to both are failing with similar errors about the data format.

# Environment

* MacOS Mojave 10.14.2 (18C54)
* R 3.5.2
  * All libraries up to date.

# Steps to Reproduce

See attached Jupyter notebook output.
[tidycensus-test.pdf](https://github.com/walkerke/tidycensus/files/2741385/tidycensus-test.pdf)

    library(tidycensus)
    test_tract_pop <- get_decennial(geography = "tract", state = "01", county = "001", variables = "P001001", year = 2010)

**Comment by mfherman** [comment]
Hmm. I'm not able to reproduce this error on my machine or on RStudio Cloud. Are you using you the most recent development version of `tidycensus` from GitHub? 

Also, could you share the results of `devtools::session_info()`

**Comment by howardjp** [comment]
Well, update to the current master branch worked.  So there you go!

**Comment by walkerke** [comment]
Thanks again @mfherman!  @howardjp - I've sent a new version to CRAN which is now up there (source version, binaries coming soon).
