### ISSUE TITLE
Issue obtaining spatial attributes from data

### ISSUE THREAD

**Issue by erstearns** [walkerke/tidycensus#147]
Hi there,

Let me lead by saying this is a great package! 

I am trying to simply grab a total population table as an sf tibble and am encountering an issue. 

**Code:**
`acs_geo <- get_acs(geography = "county",
                   variables = "B25001_001E",
                   year = 2009,
                   survey = "acs5",
                   geometry = TRUE
                   )`

**Error message:**
Error in CPL_read_ogr(dsn, layer, as.character(options), quiet, type,  : 
  Open failed.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file

I looked into this issue and seems like it is often related to a file path issue, and also I came across a closed issue here related to the dev vs CRAN `tidyr` package -- I made sure I am using the CRAN version.

Further details about my system and package library can be found below. Any help with this is greatly appreciated.

Best,
Erin Stearns

**OS**
Ubuntu 18.04

**R version**
3.4.4

**Package version info:**
`attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2    tidyr_0.8.2       tidycensus_0.9   
[4] data.table_1.11.4 censusapi_0.4.1  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18        pillar_1.3.0        compiler_3.4.4     
 [4] bindr_0.1.1         class_7.3-14        tools_3.4.4        
 [7] uuid_0.1-2          jsonlite_1.5        lattice_0.20-38    
[10] tibble_1.4.2        pkgconfig_2.0.1     rlang_0.3.1        
[13] DBI_1.0.0           rstudioapi_0.7      curl_3.2           
[16] rgdal_1.3-4         yaml_2.2.0          spData_0.2.9.3     
[19] e1071_1.6-8         dplyr_0.7.6         httr_1.3.1         
[22] stringr_1.3.1       xml2_1.2.0          hms_0.4.2          
[25] rappdirs_0.3.1      tigris_0.7          classInt_0.2-3     
[28] grid_3.4.4          tidyselect_0.2.5    glue_1.3.0         
[31] spDataLarge_0.2.7.1 sf_0.6-3            R6_2.2.2           
[34] foreign_0.8-71      pacman_0.4.6        sp_1.3-1           
[37] readr_1.1.1         purrr_0.2.5         magrittr_1.5       
[40] units_0.6-0         maptools_0.9-3      assertthat_0.2.0   
[43] rvest_0.3.2         stringi_1.2.4       crayon_1.3.4 `

**Comment by abuabara** [comment]
Not sure ... I notice that if you turn geometry = FALSE the code works
Probably it is something related to the "shapefile". Probably the US counties shapefile is too big.

**Comment by abuabara** [comment]
```
> get_acs(geography = "county", variables = "B25001_001", year = 2015, survey = "acs5", geometry = T)
Getting data from the 2011-2015 5-year ACS
Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
Simple feature collection with 3220 features and 5 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -179.1489 ymin: 17.88328 xmax: 179.7785 ymax: 71.36516
epsg (SRID):    4269
proj4string:    +proj=longlat +datum=NAD83 +no_defs
First 10 features:
   GEOID                     NAME   variable estimate moe                       geometry
1  01001  Autauga County, Alabama B25001_001    22582  66 MULTIPOLYGON (((-86.9212 32...
2  01003  Baldwin County, Alabama B25001_001   106422 151 MULTIPOLYGON (((-88.02858 3...
3  01005  Barbour County, Alabama B25001_001    11810 123 MULTIPOLYGON (((-85.74803 3...
4  01007     Bibb County, Alabama B25001_001     8971  79 MULTIPOLYGON (((-87.42194 3...
5  01009   Blount County, Alabama B25001_001    23860  92 MULTIPOLYGON (((-86.96336 3...
6  01011  Bullock County, Alabama B25001_001     4465 117 MULTIPOLYGON (((-85.99916 3...
7  01013   Butler County, Alabama B25001_001     9919  73 MULTIPOLYGON (((-86.90894 3...
8  01015  Calhoun County, Alabama B25001_001    53296 149 MULTIPOLYGON (((-86.14623 3...
9  01017 Chambers County, Alabama B25001_001    16936  76 MULTIPOLYGON (((-85.59343 3...
10 01019 Cherokee County, Alabama B25001_001    16242  75 MULTIPOLYGON (((-85.84384 3...
```

**Comment by walkerke** [comment]
Thanks for filing!  That's a bug.  Cartographic boundary files don't exist for 2009 so I should include logic to fetch an alternative dataset.  I'll fix that.

**Comment by abuabara** [comment]
```
> get_acs(geography = "county", variables = "B25001_001", year = 2009, survey = "acs5", geometry = F)
Getting data from the 2005-2009 5-year ACS
# A tibble: 3,221 x 5
   GEOID NAME                     variable   estimate   moe
   <chr> <chr>                    <chr>         <dbl> <dbl>
 1 01001 Autauga County, Alabama  B25001_001    19882    49
 2 01003 Baldwin County, Alabama  B25001_001    99645   206
 3 01005 Barbour County, Alabama  B25001_001    12956   203
 4 01007 Bibb County, Alabama     B25001_001     8706   220
 5 01009 Blount County, Alabama   B25001_001    21935    99
 6 01011 Bullock County, Alabama  B25001_001     4850    66
 7 01013 Butler County, Alabama   B25001_001    10393    80
 8 01015 Calhoun County, Alabama  B25001_001    53553   386
 9 01017 Chambers County, Alabama B25001_001    16846   149
10 01019 Cherokee County, Alabama B25001_001    14690   154
# … with 3,211 more rows
```

**Comment by mfherman** [comment]
For now, you can grab 2009 shapefiles for counties directly from the Census and then join them with the data downloaded via `get_acs()`.

https://www.census.gov/cgi-bin/geo/shapefiles2009/national-files

**Comment by walkerke** [comment]
This should now work in the dev version: 

```r
library(tidycensus)
library(sf)
library(tidyverse)

acs_geo <- get_acs(geography = "county", 
                   variables = "B25001_001E", 
                   year = 2009, survey = "acs5", 
                   geometry = TRUE)

> acs_geo
Simple feature collection with 3221 features and 5 fields (with 6 geometries empty)
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -179.1473 ymin: 17.88481 xmax: 179.7785 ymax: 71.35256
epsg (SRID):    4269
proj4string:    +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs
# A tibble: 3,221 x 6
   GEOID NAME            variable  estimate   moe                                                  geometry
   <chr> <chr>           <chr>        <dbl> <dbl>                                        <MULTIPOLYGON [°]>
 1 01001 Autauga County… B25001_0…    19882    49 (((-86.41312 32.70739, -86.41303 32.68768, -86.41296 32.…
 2 01003 Baldwin County… B25001_0…    99645   206 (((-87.76515 31.29735, -87.7636 31.29725, -87.74871 31.2…
 3 01005 Barbour County… B25001_0…    12956   203 (((-85.35541 32.14717, -85.32444 32.14715, -85.25775 32.…
 4 01007 Bibb County, A… B25001_0…     8706   220 (((-87.06574 33.24691, -87.04483 33.24667, -87.02685 33.…
 5 01009 Blount County,… B25001_0…    21935    99 (((-86.48693 34.26021, -86.45288 34.25931, -86.45183 34.…
 6 01011 Bullock County… B25001_0…     4850    66 (((-85.91913 32.27437, -85.89845 32.27494, -85.8985 32.2…
 7 01013 Butler County,… B25001_0…    10393    80 (((-86.4754 31.9644, -86.45078 31.96458, -86.4482 31.964…
 8 01015 Calhoun County… B25001_0…    53553   386 (((-85.73897 33.96846, -85.7121 33.96691, -85.66665 33.9…
 9 01017 Chambers Count… B25001_0…    16846   149 (((-85.40268 33.10862, -85.39839 33.1086, -85.3946 33.10…
10 01019 Cherokee Count… B25001_0…    14690   154 (((-85.51371 34.52417, -85.51211 34.51825, -85.50838 34.…
# … with 3,211 more rows
```

Additional check: 

```r
al <- filter(acs_geo, str_detect(NAME, "Alabama"))
plot(al["estimate"])
```
![image](https://user-images.githubusercontent.com/4872833/54274436-17c80800-4556-11e9-95d5-06681f79a2e0.png)

Please let me know if anything is not working, however.
