### ISSUE TITLE
Tidycensus issue

### ISSUE THREAD

**Issue by arwclark** [walkerke/tidycensus#150]
I'm a MAC user and I've spent hours trying to load Tidycensus. I've read the previous posts and I've loaded "units" "rgdal" and get this message:
The downloaded binary packages are in
/var/folders/rk/s0crss2j4gl4rhl6j1t92f_r0000gn/T//Rtmp4d37rw/downloaded_packages

library(tidycensus)
Error: package or namespace load failed for ‘tidycensus’:
.onLoad failed in loadNamespace() for 'sf', details:
call: get(genname, envir = envir)
error: object 'group_map' not found

**Comment by mfherman** [comment]
Can you make sure your installed packages are up-to-date by running `update.packages()`? Because the error is referencing the `group_map()` function from the latest version of `dplyr`, I'm guessing you have an older version of `dplyr` that is in someway preventing `sf` from loading properly.

If updating all your packages doesn't help, can you share more information about your setup like your operating system, R version, and the results of running `sessionInfo()`?

**Comment by arwclark** [comment]
Matt,

I tried and got this message:

The downloaded binary packages are in
/var/folders/rk/s0crss2j4gl4rhl6j1t92f_r0000gn/T//RtmppHRsIW/downloaded_packages
> library(tidycensus)
Error: package or namespace load failed for ‘tidycensus’ in get(method, envir = home):
lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/dplyr/R/dplyr.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4], :
restarting interrupted promise evaluation
2: In get(method, envir = home) :
restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
> install.packages("dplyr")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/dplyr_0.8.0.1.tgz'
Content type 'application/x-gzip' length 6587031 bytes (6.3 MB)
==================================================
downloaded 6.3 MB


The downloaded binary packages are in
/var/folders/rk/s0crss2j4gl4rhl6j1t92f_r0000gn/T//RtmppHRsIW/downloaded_packages



I did the update.packages and replied "yes" to each inquiry.  


Info from sessionInfo:

> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats graphics grDevices utils datasets methods base

loaded via a namespace (and not attached):
[1] Rcpp_1.0.0 pillar_1.3.1 compiler_3.5.2 plyr_1.8.4
[5] bindr_0.1.1 class_7.3-15 tools_3.5.2 tibble_2.0.1
[9] gtable_0.2.0 pkgconfig_2.0.2 rlang_0.3.1 DBI_1.0.0
[13] rstudioapi_0.9.0 yaml_2.2.0 xfun_0.5 bindrcpp_0.2.2
[17] e1071_1.7-0.1 httr_1.4.0 knitr_1.21 xml2_1.2.0
[21] rappdirs_0.3.1 classInt_0.3-1 grid_3.5.2 tidyselect_0.2.5
[25] glue_1.3.0 R6_2.4.0 ggplot2_3.1.0 purrr_0.3.1
[29] magrittr_1.5 scales_1.0.0 units_0.6-2 assertthat_0.2.0
[33] rvest_0.3.2 colorspace_1.4-0 lazyeval_0.2.1 munsell_0.5.0
[37] crayon_1.3.4


Thank you,

Agenia

**Comment by mfherman** [comment]
Sorry you're still having trouble installing, @arwclark. It stilll looks like a `dplyr` installation issue to me. Try this:

```
remove.packages("dplyr")
install.packages("dplyr", dependencies = TRUE)
```
Then run `packageVersion("dplyr")` to confirm you have the most recent version -- it should return `‘0.8.0.1’`. After that, give `library(tidycensus)` a try again.

**Comment by arwclark** [comment]
I'd delinquent saying, "THANK YOU."
