### ISSUE TITLE
Block geography no longer working with get_decennial

### ISSUE THREAD

**Issue by arthurgailes** [walkerke/tidycensus#151]
```
tidycensus::get_decennial(geography = "block", variables = "H001001", 
  state = "CA", county = "Alameda")
```

This code works at block group and tract geographies

**Comment by walkerke** [comment]
It appears as though block by county wildcards were removed.  I'll contact Census about this and see if they can fix it.

**Comment by jdsher** [comment]
Don't know if it helps, but block groups can work in some counties but not others.

**Comment by jdsher** [comment]
```
get_decennial("block group",
                         state = "WA",
                         year = 2010,
                         county = c("King", "Kitsap"),
                         variable = "P001001",
                         geometry = FALSE)
```
does not work, but ...
`get_decennial("block group",
                         state = "WA",
                         year = 2010,
                         county = "King",
                         variable = "P001001",
                         geometry = FALSE)`
does

**Comment by walkerke** [comment]
@arthurgailes just tested - this code now works again (tidycensus version 0.9.1).

**Comment by arthurgailes** [comment]
Thanks!

**Comment by arthurgailes** [comment]
I think this update broke the block group function call:
```
tidycensus::get_decennial(geography = "block group", variables = "H001001", 
    state = "CA", county = "Alameda")
```

This now works at block and tract, but not block group.

**Comment by abuabara** [comment]
looks like a census issue ... read here: https://stackoverflow.com/questions/54262394/error-when-using-get-decennial-to-get-2010-block-group-data-but-can-get-block

since you have block data, a work-around I would suggest to create the data at the BG level:

```
library(dplyr)
data <- tidycensus::get_decennial(geography = "block", 
                                  variables = "H001001", 
                                  year = 2010,
                                  state = "CA", 
                                  county = "Alameda",
                                  geometry = FALSE,
                                  quiet = TRUE) %>%
    mutate(new_GEOID = substr(GEOID, 1, nchar(GEOID)-3)) %>%
    group_by(new_GEOID) %>%
    summarize(new_value = sum(value, na.rm = TRUE)) %>%
    mutate(variable = "H001001") %>%
    select(.,c("GEOID" = "new_GEOID", "variable", "value" = "new_value"))
```
 

> I think this update broke the block group function call:
> 
> ```
> tidycensus::get_decennial(geography = "block group", variables = "H001001", 
>     state = "CA", county = "Alameda")
> ```
> 
> This now works at block and tract, but not block group.
