### ISSUE TITLE
get_estimates() MSA geography not working

### ISSUE THREAD

**Issue by jamgreen** [walkerke/tidycensus#154]
I am writing a lab for a course looking to get the population estimates for metropolitan statistical areas, but both of the following calls error out:

``dc <- get_estimates(geography = "metropolitan statistical area/micropolitan statistical area", product = "population", time_series = TRUE)

dc <-  get_estimates(geography = "combined statistical area", product = "population", time_series = TRUE)
``
In checking the census API documentation, MSAs or CBSAs do not seem to be valid geographies:
[https://api.census.gov/data/2017/pep/population/geography.html](https://api.census.gov/data/2017/pep/population/geography.html)

What error am I making in the call here or is this an open issue?

**Comment by mfherman** [comment]
I'm not sure why MSAs and CBSAs are not available for 2017 through the API, but you could use 2016 data if that works for your lab. Perhaps @loganpowell or @walkerke know why they are not available for 2017?

https://api.census.gov/data/2016/pep/population/geography.html

``` r
library(tidycensus)

get_estimates(
  geography = "metropolitan statistical area/micropolitan statistical area",
  product = "population",
  year = "2016"
  )
#> # A tibble: 1,890 x 4
#>    NAME                             GEOID variable  value
#>    <chr>                            <chr> <chr>     <dbl>
#>  1 Aberdeen, SD Micro Area          10100 POP       43080
#>  2 Aberdeen, WA Micro Area          10140 POP       71628
#>  3 Abilene, TX Metro Area           10180 POP      170364
#>  4 Ada, OK Micro Area               10220 POP       38330
#>  5 Adjuntas, PR Micro Area          10260 POP       18314
#>  6 Adrian, MI Micro Area            10300 POP       98504
#>  7 Aguadilla-Isabela, PR Metro Area 10380 POP      309696
#>  8 Akron, OH Metro Area             10420 POP      702221
#>  9 Alamogordo, NM Micro Area        10460 POP       65410
#> 10 Albany, GA Metro Area            10500 POP      152219
#> # … with 1,880 more rows
```

<sup>Created on 2019-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jamgreen** [comment]
AH! Okay...yeah, not sure why 2017 doesn't play nice, but I can use the 2016 data. Thank you so much. I reckon this should stay open until we get clarification on the 2017 issue, but this is good to know.

**Comment by loganpowell** [comment]
I'm actually not sure why MSAs aren't in the 2017 pep. Can you send an email to cnmp.developers.list@census.gov to make the inquiry?

**Comment by walkerke** [comment]
@jamgreen so I just tried this for 2018: 

```r
get_estimates(
  geography = "metropolitan statistical area/micropolitan statistical area",
  product = "population",
  year = 2018
)
```

And I get: 

```
# A tibble: 1,890 x 4
   NAME                             GEOID variable  value
   <chr>                            <chr> <chr>     <dbl>
 1 Aberdeen, SD Micro Area          10100 POP       43191
 2 Aberdeen, WA Micro Area          10140 POP       73901
 3 Abilene, TX Metro Area           10180 POP      171451
 4 Ada, OK Micro Area               10220 POP       38247
 5 Adjuntas, PR Micro Area          10260 POP       17302
 6 Adrian, MI Micro Area            10300 POP       98266
 7 Aguadilla-Isabela, PR Metro Area 10380 POP      289735
 8 Akron, OH Metro Area             10420 POP      704845
 9 Alamogordo, NM Micro Area        10460 POP       66781
10 Albany, GA Metro Area            10500 POP      153009
# … with 1,880 more rows
```

2017 still does not work, so we'll have to ping Census again about that.

**Comment by mfherman** [comment]
@jvanloon93 The characteristics products are only available at the national, state, and county level, but not at the MSA level. See the Census API documentation for available geographies:

https://api.census.gov/data/2018/pep/charagegroups/geography.html

**Comment by mfherman** [comment]
Just a note, that I finally emailed this API bug to the developers list. Sorry it took me so long!

**Comment by walkerke** [comment]
Closing this; we now have 2018 and 2019 PEP availability (in the GitHub version for 2019) for CBSAs in `get_estimates()` and there does not appear to be movement on the 2017 dataset, so there isn't much we can do on this side.  Time series estimates are still available with `time_series = TRUE`.
