### ISSUE TITLE
get_acs county matching problem

### ISSUE THREAD

**Issue by gerwathome** [walkerke/tidycensus#161]
Modifying your example in the get_acs() documentation pulling median income for "Tarrant" county to "Harris" county causes an error.  Interestingly, changing the county to "Harris " works.  Perhaps there is a patterning matching issue, where calling for Harris without a trailing space returns both Harris and Harrison counties?

**Comment by abuabara** [comment]
this happens to me too, i usually have to put a space after harris, ou write the full name "harris county"

**Comment by mfherman** [comment]
@gerwathome  If you download the latest github version of the package, you should now see better error handling on multiple county matches.
