### ISSUE TITLE
get_acs returning NA values for 2017 language tables 

### ISSUE THREAD

**Issue by dkori** [walkerke/tidycensus#162]
The following get_acs call returns only NA values for the estimate and margin of error for each county:

get_acs(geography="county",state="VA",year=2017, variables=c("Var"="B16001_001"))

However, the function properly retrieves the data for 2014:

get_acs(geography="county",state="VA",year=2014, variables=c("Var"="B16001_001")). 

The underlying data for 2017 can be found here:
https://factfinder.census.gov/bkmk/table/1.0/en/ACS/17_1YR/B16001/0400000US51

**Comment by abuabara** [comment]
Hey,

Two problems.

1) the variables you just include the variables ... no need to "var"=

2) You need to declare the survey. Indeed ACS5 years has no estimates. But ACS1 year do have. And it is what your link shows.

Do the following, will work:

```
tidycensus::get_acs(geography="county",
                    state="VA",
                    year=2017,
                    survey = "acs1",
                    variables=c("B16001_001"))
```

**Comment by dkori** [comment]
Thanks for the response! I'm closing this issue because the code snippet you provided seems to deliver results that match the factfinder website, however it looks like language data for most counties is still missing. Any idea why that may be?

**Comment by abuabara** [comment]
Glad about it.

What variable number are you using to fetch the language data? So far, all the ones I tried are working just fine. Honestly I just tried a couple of them.

**Comment by dkori** [comment]
When I run the snippet you provided, I'm seeing missing values for most counties, even for B16001_001 which should just be the total population for the county (see picture below). I don't think it's a problem with tidycensus, because it looks like those values are also missing in the table on the factfinder website as well. 
![image](https://user-images.githubusercontent.com/10734057/58256310-c8b00780-7d3c-11e9-9f5c-53a4efda01f4.png)

**Comment by abuabara** [comment]
Howdy. I live in Texas and I'm not familiar with these counties. Probably this is happening because the population/sample size of each place. Look here: https://www.census.gov/programs-surveys/acs/guidance/estimates.html

**Comment by mfherman** [comment]
If you don't need to look at the county level, you could use [PUMAs](https://www.census.gov/programs-surveys/geography/guidance/geo-areas/pumas.html) , which are areas that have at least 100,000 people. There is data available for this variable for all 56 PUMAs in Virginia in the 5-year ACS.

``` r
library(tidycensus)

va_langauge <- get_acs(
  geography = "public use microdata area",
  state = "VA",
  year = 2017,
  survey = "acs5",
  variables = "B16001_001"
  )
#> Getting data from the 2013-2017 5-year ACS

head(va_langauge)
#> # A tibble: 6 x 5
#>   GEOID   NAME                                     variable  estimate   moe
#>   <chr>   <chr>                                    <chr>        <dbl> <dbl>
#> 1 5101301 Arlington County (North) PUMA, Virginia  B16001_0~   109122  1360
#> 2 5101302 Arlington County (South) PUMA, Virginia  B16001_0~   106630  1351
#> 3 5104101 Chesterfield County (East)--James River~ B16001_0~   100587  1609
#> 4 5104102 Chesterfield County (Central)--Chester ~ B16001_0~   113184  1745
#> 5 5104103 Chesterfield County (West)--Brandermill~ B16001_0~   101832  1453
#> 6 5110701 Loudoun County (Northeast)--Sterling & ~ B16001_0~   103782  1317
```

<sup>Created on 2019-05-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dkori** [comment]
@abuabara good thought, but many of those counties have populations well over 100,000 (Arlington county's is over 200,000 in 2017, for example), so I don't think that's it. 

I think there must be something wrong with the underlying  data for the 2017 vintage. If you run the code snippet that you provided earlier, but pass the arguments (year=2014 and survey="acs5"), it returns values for every county. However, it doesn't return values for any county with (year=2017 and survey="acs5"), and it only returns values for those three counties for (year=2017 and survey="acs1"). Fortunately, it does seem that tidycensus itself is at least pulling data that matches the factfinder tool. 

@mfherman thanks for the tip regarding the PUMA geography! For this project I should be fine just using the old 2014 data, but I'm sure this will come in handy in the future.
