### ISSUE TITLE
Error in get_decenial

### ISSUE THREAD

**Issue by thk686** [walkerke/tidycensus#164]
This command:

county_area_water <- get_decennial("county", "AREAWATR", geometry = TRUE, state = 48)

generates: 

Getting data from the 2010 decennial Census
Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
Error : Your API call has errors.  The API message returned is <html><head><title>Error report</title></head><body><h1>HTTP Status 404 - /data/2010/dec/sf3</h1></body></html>.
Error in gather_(data, key_col = compat_as_lazy(enquo(key)), value_col = compat_as_lazy(enquo(value)),  : 
  unused argument (-NAME)

**Comment by walkerke** [comment]
I don't have tidycensus set up to retrieve water area (or related variables like that) - just the demographic statistics.  I'd recommend {tigris} instead for this information: 

```r
library(tigris)
tx_counties <- counties("TX", class = "sf")
dplyr::glimpse(tx_counties)

Observations: 254
Variables: 18
$ STATEFP  <chr> "48", "48", "48", "48", "48", "48", "48", "48", "48", "48"…
$ COUNTYFP <chr> "327", "189", "011", "057", "077", "361", "177", "147", "2…
$ COUNTYNS <chr> "01383949", "01383880", "01383791", "01383814", "01383824"…
$ GEOID    <chr> "48327", "48189", "48011", "48057", "48077", "48361", "481…
$ NAME     <chr> "Menard", "Hale", "Armstrong", "Calhoun", "Clay", "Orange"…
$ NAMELSAD <chr> "Menard County", "Hale County", "Armstrong County", "Calho…
$ LSAD     <chr> "06", "06", "06", "06", "06", "06", "06", "06", "06", "06"…
$ CLASSFP  <chr> "H1", "H1", "H1", "H1", "H1", "H1", "H1", "H1", "H1", "H1"…
$ MTFCC    <chr> "G4020", "G4020", "G4020", "G4020", "G4020", "G4020", "G40…
$ CSAFP    <chr> NA, NA, "108", "544", NA, NA, NA, "206", NA, NA, NA, NA, N…
$ CBSAFP   <chr> NA, "38380", "11100", "38920", "48660", "13140", NA, "1430…
$ METDIVFP <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ FUNCSTAT <chr> "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A"…
$ ALAND    <dbl> 2336237920, 2602115387, 2354581675, 1312707024, 2819787559…
$ AWATER   <dbl> 613559, 246678, 12219587, 1361884769, 72591143, 118488848,…
$ INTPTLAT <chr> "+30.8843921", "+34.0684364", "+34.9641790", "+28.4417191"…
$ INTPTLON <chr> "-099.8539616", "-101.8228879", "-101.3566363", "-096.5795…
$ geometry <MULTIPOLYGON [°]> MULTIPOLYGON (((-99.82187 3..., MULTIPOLYGON …
```

If you want to go directly through the Census API, you can construct such a query using the {censusapi} package.
