### ISSUE TITLE
Trouble accessing other Census Bureau datasets

### ISSUE THREAD

**Issue by jamesrrae** [walkerke/tidycensus#167]
I ran into an issue when trying to follow the steps for accessing other Census Bureau datasets. Below is some code that I took from here (https://walkerke.github.io/tidycensus/articles/other-datasets.html):

```
library(tidycensus)
library(tidyverse)
options(tigris_use_cache = TRUE)

us_components <- get_estimates(geography = "state", product = "components")
```
Although I have my api key loaded, I get the following error message:

```
Error: Your API call has errors.  The API message returned is There was an error while running your query.  We've logged the error and we'll correct it ASAP.  Sorry for the inconvenience..
```
This seems like a solution is in the works, but in the meantime, is there another way I can access the other Census Bureau datasets in that can avoid this error (maybe through a different call?)

**Comment by mfherman** [comment]
This part of the error message: `There was an error while running your query.  We've logged the error and we'll correct it ASAP.  Sorry for the inconvenience.` is the response from the Census API. I see that error intermittently and usually rerunning the call a little later fixes the problem.

I was just able to run the following code without a problem:

``` r
library(tidycensus)

us_components <- get_estimates(geography = "state", product = "components")
head(us_components)
#> # A tibble: 6 x 4
#>   NAME       GEOID variable  value
#>   <chr>      <chr> <chr>     <dbl>
#> 1 Alabama    01    BIRTHS    58389
#> 2 Alaska     02    BIRTHS    11163
#> 3 Arizona    04    BIRTHS    85634
#> 4 Arkansas   05    BIRTHS    38236
#> 5 California 06    BIRTHS   487916
#> 6 Colorado   08    BIRTHS    67638
```

<sup>Created on 2019-06-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@jamesrrae Please let us know if you're still seeing an error with this.
