### ISSUE TITLE
Wrap get_acs()'s and get_decennial()'s recursive calls in purrr::insistently()?

### ISSUE THREAD

**Issue by NikKrieger** [walkerke/tidycensus#174]
Have you considered wrapping `get_acs()`'s and `get_decennial()`'s recursive calls (which occur, for example, when setting `geography = "block group"` and `county = NULL`) in `purrr::insistently()`?

For example, if a user wants block-group-level data for all of Texas, these functions recursively call themselves on each of the >200 Texas counties using `purrr::map()`, but if even one of these counties has a blip in the connection, the entire data pull will fail. `insistently()` basically makes it try again.

Right now you have:

```
map(
  county,
  ~{suppressMessages(
    get_acs(<get_acs_args>)
  )}
)
```

Have you considered doing this?:

```
map(
  county,
  ~{suppressMessages(
    insistently(get_acs)(<get_acs_args>)
  )}
)
```

You can even make it only try a maximum of `n` times like this:

```
map(
  county,
  ~{suppressMessages(
    insistently(get_acs, rate = rate_delay(max_times = n))(<get_acs_args>)
  )}
)
```

(see `` ?purrr::`rate-helpers` `` for more options)

Just a suggestion. Perhaps you already know about these options and have a reason for not doing it!

**Comment by walkerke** [comment]
Great idea!

**Comment by walkerke** [comment]
This is now implemented as of https://github.com/walkerke/tidycensus/commit/dec4f8ef3fcc6615f5895b4bb2426c57e239d4f8.
