### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle) :  details

### ISSUE THREAD

**Issue by Luna0129** [walkerke/tidycensus#176]
Hi I'm having trouble running functions in tidycensus package. I'm following this tutorial https://walkerke.github.io/tidycensus/articles/basic-usage.html

Whichever function I ran, I got this error message:
`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Resolving timed out after 10000 milliseconds`

Do you know what is the problem? The api key is loaded and activated, firewalls are down. I suspect it's a proxy problem and tried multiple ways from here https://stackoverflow.com/questions/6467277/proxy-setting-for-r (none of them worked) 

Thank you!

**Comment by mfherman** [comment]
Hi @Luna0129, this does indeed look like a proxy problem to me. Can you get any internet data via R? For example, do you get the following output when you run either of the calls below?

``` r
httr::GET("https://api.census.gov/data/2017/acs/acs1?get=NAME,group(B01001)&for=us:1")
#> Response [https://api.census.gov/data/2017/acs/acs1?get=NAME,group(B01001)&for=us:1]
#>   Date: 2019-07-30 13:39
#>   Status: 200
#>   Content-Type: application/json;charset=utf-8
#>   Size: 4.33 kB
#> [["NAME","GEO_ID","B01001_001E","B01001_001M","B01001_002E","B01001_002M...

httr::GET("http://google.com")
#> Response [http://www.google.com/]
#>   Date: 2019-07-30 13:39
#>   Status: 200
#>   Content-Type: text/html; charset=ISO-8859-1
#>   Size: 11.5 kB
#> <!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" l...
#> </style><style>body,td,a,p,.h{font-family:arial,sans-serif}body{margin:0...
#> if (!iesg){document.f&&document.f.q.focus();document.gbqf&&document.gbqf...
#> }
#> })();</script><div id="mngb"> <div id=gbar><nobr><b class=gb1>Search</b>...
#> function _F_installCss(c){}
```
<sup>Created on 2019-07-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mgoadric** [comment]
I just encountered the same issue when trying to use tidycensus in a Kaggle-hosted notebook. I was also not able to get either of the two follow-up httr:GET queries to return, both timed-out. I was able to access the census API through tidycensus when running from my own Rstudio setup.

**Comment by buchmayne** [comment]
I just got this same error message completely out of the blue. I am able to get internet data from within R, I used the same get request to google and got a status 200 code. I tried using tidycensus with my home internet connection and also through my work VPN. From my home network I got this error message:

`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to api.census.gov port 443: Operation timed out`

and when I tried through my company's VPN I got the same error as OP:
`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [api.census.gov] Connection timed out after 10000 milliseconds`

Does this augur that the census API is down? I googled it and checked their twitter but didn't see anything mentioned.

**Comment by walkerke** [comment]
@buchmayne Did the `GET()` request that Matt posted above to the Census API work?  Also what was the tidycensus call you tried?

**Comment by buchmayne** [comment]
@walkerke The `GET()` request to the census also didn't work, and any tidycensus call would produce that error. I specifically got an error running `load_variables()` and a `get_acs()` call that was working just moments before. I reset my R environment and that didn't fix the problem. I ended up just taking a break and when I returned to my work 20 minutes later everything was working fine again. 

To me it seems like the census API was just down for a short period of time but I wasn't able to find any reporting of it. I apologize if this isn't helpful on your end, but it really doesn't seem to be a tidycensus issue from what I can gather. When I googled the error message this closed issue came up and I just wanted to add my experience given it was slightly different than the other two posters.

**Comment by tripwright** [comment]
@walkerke I just received this error:

`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer [api.census.gov]:
Recv failure: Connection reset by peer`

When trying to run:
`tract_income_data <- get_acs(geography = "tract", variables = "B19013_001", state = target_state, county = target_county, geometry = TRUE, year = 2022)`

I was successfully able to a response by running the `GET()` request to the census.

`httr::GET("https://api.census.gov/data/2017/acs/acs1?get=NAME,group(B01001)&for=us:1")
Response [https://api.census.gov/data/2017/acs/acs1?get=NAME,group(B01001)&for=us:1]
  Date: 2026-04-30 18:26
  Status: 200
  Content-Type: application/json;charset=utf-8
  Size: 4.33 kB
[["NAME","B01001_001E","B01001_001EA","B01001_001M","B01001_001MA","B01001_002E","B01001_002EA"...`

Maybe the Census API is down? Unsure if you have any additional insight here.

**Comment by walkerke** [comment]
Perhaps a transient error?  I'm not seeing issues on my end.

**Comment by tripwright** [comment]
@walkerke Yes, appears so. All is well now. Thanks!
