### ISSUE TITLE
More info on ZCTA 

### ISSUE THREAD

**Issue by dmellish** [walkerke/tidycensus#179]
Hi, I was wondering how you know which ZCTA's to use? I'm not sure if we would just use the ZIPs for the level of data we want? To clarify, suppose I want to find the population for a city with multiple zip codes, how do I know which ZCTA's to use?

**Comment by mfherman** [comment]
ZCTAs are close approximations of USPS zip codes. You can read more about them here:

https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html

You can get ZCTA data for the entire US and then filter to include certain zip codes. Here for example, I get all zipcodes that start with `112`.

``` r
library(tidyverse)
library(tidycensus)

zcta_data <- get_acs(
  geography = "zcta",
  variables = "B19013_001"
  )
#> Getting data from the 2013-2017 5-year ACS

zcta_data %>% 
  filter(str_detect(GEOID, "^112"))
#> # A tibble: 37 x 5
#>    GEOID NAME        variable   estimate   moe
#>    <chr> <chr>       <chr>         <dbl> <dbl>
#>  1 11201 ZCTA5 11201 B19013_001   116446  5186
#>  2 11203 ZCTA5 11203 B19013_001    48140  1937
#>  3 11204 ZCTA5 11204 B19013_001    47341  2261
#>  4 11205 ZCTA5 11205 B19013_001    51574  2582
#>  5 11206 ZCTA5 11206 B19013_001    34122  2123
#>  6 11207 ZCTA5 11207 B19013_001    35809  1664
#>  7 11208 ZCTA5 11208 B19013_001    39588  1871
#>  8 11209 ZCTA5 11209 B19013_001    69578  2544
#>  9 11210 ZCTA5 11210 B19013_001    62202  2791
#> 10 11211 ZCTA5 11211 B19013_001    66113  4041
#> # ... with 27 more rows
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dmellish** [comment]
Ah gotcha. The project I'm working on uses ZIP's for certain data. Suppose I defined this list of zips to be zip_list<-c(60321,62367). Would a good way to estimate certain acs variables for those zips be data[GEOID %in% zip_list]?

**Comment by mfherman** [comment]
I think that would be a great way to do it. Here is one option using dplyr::filter() and another option using `[]` to subset the data.

The reason you can't get ZCTAs for specific counties or states via the API is that a single ZCTA can cross county and state boundaries, so you have to do the subsetting manually with the actual ZCTAs you need.
``` r
library(tidyverse)
library(tidycensus)

zcta_data <- get_acs(
  geography = "zcta",
  variables = "B19013_001"
  )
#> Getting data from the 2013-2017 5-year ACS

zip_list <- c(11222, 11223)

zcta_data %>% 
  filter(GEOID %in% zip_list)
#> # A tibble: 2 x 5
#>   GEOID NAME        variable   estimate   moe
#>   <chr> <chr>       <chr>         <dbl> <dbl>
#> 1 11222 ZCTA5 11222 B19013_001    78287  5209
#> 2 11223 ZCTA5 11223 B19013_001    46310  2894

zcta_data[zcta_data$GEOID %in% zip_list, ]
#> # A tibble: 2 x 5
#>   GEOID NAME        variable   estimate   moe
#>   <chr> <chr>       <chr>         <dbl> <dbl>
#> 1 11222 ZCTA5 11222 B19013_001    78287  5209
#> 2 11223 ZCTA5 11223 B19013_001    46310  2894
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dmellish** [comment]
Would a way of getting closer to a city level estimate for a variable be through something like a census block or tract?

**Comment by mfherman** [comment]
Depending on the boundaries of the city you are interested in are defined, you could use census designated place (CDP), county, metropolitan statistical area (MSA), or a collection of tracts/blocks. In general, I'd say any of these geographies are better than using ZCTAs, unless for example you have other data at the zip level that you are analyzing.

You can see all the geography options available through tidycensus here:
https://walkerke.github.io/tidycensus/articles/basic-usage.html#geography-in-tidycensus

Here's an example of getting data for CDPs in New York state that start with "New York": 

``` r
library(tidycensus)
library(tidyverse)

place_data <- get_acs(
  geography = "place",
  variables = "B01003_001",
  state = "NY"
)
#> Getting data from the 2013-2017 5-year ACS

place_data %>% 
  filter(str_detect(NAME, "^New York"))
#> # A tibble: 2 x 5
#>   GEOID   NAME                             variable   estimate   moe
#>   <chr>   <chr>                            <chr>         <dbl> <dbl>
#> 1 3651000 New York city, New York          B01003_001  8560072    NA
#> 2 3651011 New York Mills village, New York B01003_001     3581   450
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dmellish** [comment]
Thank you sir, CDP is exactly what I need!
