### ISSUE TITLE
Option to choose 1-year or 5-year ACS estimates

### ISSUE THREAD

**Issue by mfherman** [walkerke/tidycensus#18]
I just started exploring tidycensus today and I love it so far. One quick question: is there a way to specify using 1-year or 5-year estimates? It looks like it's defaulting to pulling 5-year estimates which is great for small geographies, but sometimes I'd rather use 1-year estimates for larger/more populated areas. I know the acs package allows this choice. 

As much more of an R user than programmer, I can't help with actually implementing this feature, but would certainly use it!

**Comment by walkerke** [comment]
This functionality is now supported as of https://github.com/walkerke/tidycensus/pull/25.  Updates off to CRAN soon!
