### ISSUE TITLE
Novice - Capability of tidycensus to "generate" a GEOID rollup?

### ISSUE THREAD

**Issue by LevelThink** [walkerke/tidycensus#181]
Do not know if I should post this question here...

Relative novice regarding tidycensus and github...

Several days ago, I wondered if it was possible to readily extract all of the GEOIDs for all  Census Tracts, ZCTAs and Block Groups for a particular city.

In essence, it would be a “GEOID Rollup.”   Of course, one would have to consider the allocation factors – i.e. ZCTAs relative to Block Groups if there are Block Groups that are in more than one ZCTA, etc.

Did not consider using tidycensus.

Reviewing the websites of MCDC, HUD, Census.gov, etc. and plan to cobble together my own list in MS Excel.

Can tidycensus perform such a task - just the GEOIDs and the allocation factors ?

Please advise if questions such as this should be posted elsewhere.

**Comment by mfherman** [comment]
This is a pretty good place to ask, @LevelThink!

I'm not entirely clear on what your expected output is, but if you're looking to identify all the ZCTAs, tracts, and block groups in a given city, here's one approach.

The basic idea is we get geometries for all the geographies and then perform a spatial join with the boundaries of a city to get the intersecting ZCTAs, tracts, and blocks. This might not be what you're after, but if you clarify a little more, it sounds like something that is possible using tidycensus and some other R tools.

``` r
library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)

# get olympia city geometry
olympia <- places(state = "WA", cb = TRUE, class = "sf") %>% 
  select(place_fips = GEOID, place_name = NAME) %>% 
  filter(place_name == "Olympia")

# get zcta data/geometry data
zcta <- get_acs(
  geography = "zcta",
  variables = "B01003_001",
  geometry = TRUE
  )
#> Getting data from the 2013-2017 5-year ACS

# get tract acs data/geometry for thurston county, wa
tract <- get_acs(
  geography = "tract",
  variables = "B01003_001",
  state = "WA",
  county = "Thurston",
  geometry = TRUE
  )
#> Getting data from the 2013-2017 5-year ACS

# get block group acs data/geometry for thurston county, wa
bg <- get_acs(
  geography = "block group",
  variables = "B01003_001",
  state = "WA",
  county = "Thurston",
  geometry = TRUE
  )
#> Getting data from the 2013-2017 5-year ACS

# make a list of the 3 geographies
geo_list <- lst(zcta, tract, bg)

# define function to perform spatial join and drop unneeded columns
intersect_select <- function(x, y){
  intersect <- st_join(x, y)
  intersect %>% 
    st_drop_geometry() %>% 
    select(GEOID, variable, estimate, moe)
}

# apply intersect function to each geography and combine into a single data frame
olympia_ids <- map_dfr(geo_list, ~ intersect_select(olympia, .x), .id = "geo_type")
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar

head(olympia_ids, 10)
#>    geo_type       GEOID   variable estimate  moe
#> 1      zcta       98501 B01003_001    41951 1282
#> 2      zcta       98502 B01003_001    32889 1081
#> 3      zcta       98503 B01003_001    37820 1005
#> 4      zcta       98506 B01003_001    17862  839
#> 5      zcta       98512 B01003_001    29866  858
#> 6      zcta       98516 B01003_001    23241 1209
#> 7     tract 53067010100 B01003_001     3250  231
#> 8     tract 53067010200 B01003_001     5350  380
#> 9     tract 53067010300 B01003_001     5530  499
#> 10    tract 53067010400 B01003_001     3286  221
```

<sup>Created on 2019-07-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by LevelThink** [comment]
Thanks for the insight!

This is great - Exactly what I had envisioned of creating in MS Excel using the BI functionality and joining multiple disparate data sets.  However, not sure if I would have gotten there as quickly.

Any thought/comment regarding on the feasibility of including allocation factors for the instances whereby there is overlap of the geographical unit.  

For example, there are many zip codes overlapping multiple census tracts and it would be great to be able to readily determine proportionality - percentage of zip code in a census tract, etc.

If including allocation factors is not feasible then what is presented so far is fine.

Thanks again for the insight.

**Comment by mfherman** [comment]
Yes, you can definitely do this in R. Take a look at the [areal package](https://slu-opengis.github.io/areal/articles/areal-weighted-interpolation.html) which has functions for areal weighted interpolation using `sf` objects, which is the output format of `tidycensus::get_acs()`. Under the hood, `areal` uses some functions from the `sf` package, including [st_interpolate_aw()](https://r-spatial.github.io/sf/reference/st_interpolate_aw.html)

The general workflow is getting your data at the ZCTA level and at the tract level. And then do something like `areal::aw_interpolate(zip_df, source = tract_df)`. If you check out the link above to the areal package, there is a detailed vignette going through the interpolation process.
