### ISSUE TITLE
tidycensus load fails on RStudio Cloud with undefined symbol

### ISSUE THREAD

**Issue by frankhecker** [walkerke/tidycensus#183]
On RStudio Cloud doing library(tidycensus) fails with the following error message:

Error: package or namespace load failed for ‘tidycensus’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.6/rgdal/libs/rgdal.so':
  /home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.6/rgdal/libs/rgdal.so: undefined symbol: _ZN10OGRFeature11SetGeometryEP11OGRGeometry

I'm guessing this is an RStudio Cloud-specific problem, since tidycensus loads fine on my own Rstudio server deployment, and used to load OK on Rstudio.cloud until about a week or two ago. However I'd like to try to narrow down what might be causing this so I can submit a problem report for RStudio Cloud.

Rstudio.cloud allows users to start a shell session, so I can check on the underlying Ubuntu system and what's installed on it, but I can't install or update anything myself.  Is there anything in particular I could look at to help troubleshoot this?

**Comment by mfherman** [comment]
Yup, this is an RStudio Cloud issue. It sounds like the recently updated the GDAL installation on RStudio Cloud. Take a look at this thread: https://community.rstudio.com/t/problems-with-loading-rgdal-library-after-rstudio-cloud-maintenance-on-7-25/36180/3?u=mfherman

From my read of it, it should be working now, so you might try reinstalling rgdal and/or tidycensus so it uses the new GDAL.  But if that doesn’t help, I would recommend posting on that thread as the RStudio staff are quite responsive.

**Comment by frankhecker** [comment]
Thanks for the response! Yes, reinstalling the rgdal package fixed this. Closing this issue.

Thanks again!
