### ISSUE TITLE
2012 acs5 block group error

### ISSUE THREAD

**Issue by chrowe** [walkerke/tidycensus#185]
## Code
```
 get_acs(geography = "block group",
               variables = "B01001_001",
               survey = "acs5",
               state = "VT"
               year = 2012
               )
```

## Error
```
Error message: The API message returned is error: unknown/unsupported geography heirarchy.
```

**Comment by mfherman** [comment]
This is the same issue as #173. It appears that block group data is not available for 2012 and earlier via the Census API. See this page for available geographies:

https://api.census.gov/data/2012/acs/acs5/examples.html

Actually, I just tried to get block group data via American Fact Finder and it is not there for 2011 or 2012. I'm not sure if there is a reason this data isn't available for those years. Perhaps @loganpowell knows?

**Comment by loganpowell** [comment]
I don't know why the data wouldn't be in AFF, but I do know that the majority of current work is dedicated to setting up for the 2020 and 2018 ACS (historic data takes reverse chronological priority).

If you want to know more you could try asking Maureen.A.Brauning@census.gov

**Comment by mfherman** [comment]
Thanks, @loganpowell. I’ll reach out to Maureen.

**Comment by walkerke** [comment]
Closing as this is an issue on the Census API side.

**Comment by plnnr** [comment]
just came here to comment how the census bureau has a barely functional end-use product (data.census.gov) and is encouraging people to use the APIs... yet we can't even get block group data prior to 2012 via the API!
