### ISSUE TITLE
SF does not install on our AWS Rstudio System - Is there a work around TidyCensus

### ISSUE THREAD

**Issue by pzm5** [walkerke/tidycensus#192]
When I try to install TidyCensus on our AWS Linux Redhat Server version of Rstudio,  it does not install because this version of R does not include SF and GDAL.  Is there a way I could incorporate some work around packages such as RGDAL when try to install TidyCensus.

================================================== downloaded 8.2 MB  trying URL 'https://cran.rstudio.com/src/contrib/tigris_0.8.2.tar.gz' Content type 'application/x-gzip' length 73459 bytes (71 KB) ================================================== downloaded 71 KB  trying URL 'https://cran.rstudio.com/src/contrib/tidycensus_0.9.2.tar.gz' Content type 'application/x-gzip' length 1622701 bytes (1.5 MB) ================================================== downloaded 1.5 MB  * installing *source* package ‘sf’ ... ** package ‘sf’ successfully unpacked and MD5 sums checked ** using staged installation configure: CC: gcc -m64 -std=gnu99 configure: CXX: g++ -m64 -std=gnu++11 checking for gdal-config... /usr/bin/gdal-config checking gdal-config usability... yes configure: GDAL: 1.11.4 checking GDAL version >= 2.0.1... no configure: error: sf is not compatible with GDAL versions below 2.0.1 ERROR: configuration failed for package ‘sf’ * removing ‘/opt/sas/shared/homes/pmcmurrayoa01/R/x86_64-redhat-linux-gnu-library/3.6/sf’ Warning in install.packages :   installation of package ‘sf’ had non-zero exit status ERROR: dependency ‘sf’ is not available for package ‘tigris’ * removing ‘/opt/sas/shared/homes/pmcmurrayoa01/R/x86_64-redhat-linux-gnu-library/3.6/tigris’ Warning in install.packages :   installation of package ‘tigris’ had non-zero exit status ERROR: dependencies ‘sf’, ‘tigris’ are not available for package ‘tidycensus’ * removing ‘/opt/sas/shared/homes/pmcmurrayoa01/R/x86_64-redhat-linux-gnu-library/3.6/tidycensus’ Warning in install.packages :   installation of package ‘tidycensus’ had non-zero exit status  The downloaded source packages are in 	‘/tmp/RtmpJlchS2/downloaded_packages’
--
 
> | >
>

**Comment by mfherman** [comment]
I think your best bet is to try to upgrade the GDAL version on your server and then install sf. If this isn't an option, you might look at the [censusapi](https://github.com/hrecht/censusapi) or [acs](https://cran.r-project.org/package=acs) packages for R as alternatives to tidycensus.

**Comment by walkerke** [comment]
I concur with @mfherman's assessment; either upgrade GDAL so you can install {sf} (which is a good idea for any data science work anyway) or use one of the Census packages that don't have spatial dependencies.
