### ISSUE TITLE
1 year ACS limitation on 2010, 2011 data

### ISSUE THREAD

**Issue by tallishmatt** [walkerke/tidycensus#199]
1 year ACS data exists back to 2010, so I was curious to find that tidycensus throws an error when requesting 1 year ACS data for 2010 and 2011. It seems like this limitation may be an artificial one?  

On initial exploration, I found that the census data API does allow for 1 year ACS data back to 2010 (see [this data call](https://api.census.gov/data/2010/acs/acs1?get=NAME,B23001_010E,B23001_010M&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:*) for example). After poking through the tidycensus source code (specifically, the [load_data_acs](https://github.com/walkerke/tidycensus/blob/master/R/load_data.R) subcommand) to learn how tidycensus interacts with the API, I used the same command structure to make my own call from within R:

```
library(httr) 
call <- GET("https://api.census.gov/data/2010/acs/acs1", 
            query = list(get = "NAME,B23001_010E,B23001_010M",
                         "for" = "metropolitan statistical area/micropolitan statistical area:*",
                          key = "YOUR API KEY HERE")) 
http_status(call)
```

When this worked, I edited the tidycensus command `get_acs` to remove the pre-2012 stop located in the following code:
```
  if (survey == "acs1") {
    if (year < 2012) {
      stop("The acs1 data is currently available beginning in 2012. Please select a different year.", call. = FALSE)
    }
    message("The one-year ACS provides data for geographies with populations of 65,000 and greater.")
  }
```

This all seems to work--I've tested a handful of small data pulls from the 2010 and 2011 ACS using tidycensus with this small modification and they function and appear accurate. For example:

```
library(tidycensus)
library(tidyverse)

trace("get_acs", edit=TRUE) # remove lines 45-48, click save

dat <- as_tibble() 

ACS_YEARS <- 2010:2018
for (YEAR in ACS_YEARS){
  input <- get_acs(geography="county", table="B23001", survey="acs1", year=YEAR, output="wide",
                  state="17", county="031", cache_table=TRUE)
  
  dat <- mutate(input, year=YEAR) %>% 
    select(year, everything()) %>% 
    bind_rows(dat)
}

View(dat)
```

I'm curious if this is a holdover from some previous API limitation that no longer applies?  Perhaps there is some other reason I am not aware of to avoid accessing this data this way.

**Comment by wat3rm3ll0n** [comment]
I have encountered similar issues and I believe this may be a legacy warning. The ACS now has 1-year estimates available back to [2010](https://api.census.gov/data/2010/acs/acs1/). I think Census hasn't yet updated their [documentation](https://www.census.gov/data/developers/data-sets/acs-1year.html) to reflect this availability as they currently only state that the 1 year estimates are available from 2011 forward. I'm not sure what the reason for this is, so perhaps it's worth someone trying to reach out to someone at Census if anyone has a contact to see if there's any reason we shouldn't be pulling back to 2010 for the 1 year estimates?

**Comment by mfherman** [comment]
I don't know of any reason not to get the 2010 and 2011 1-year estimates from the API. @tallishmatt, if you submit a pull request with your changes to the code (and documentation), I imagine @walkerke would accept it!

**Comment by tallishmatt** [comment]
Pull request #204
