### ISSUE TITLE
`Ticycensus` Package Loading Depends on `units` Package 

### ISSUE THREAD

**Issue by LucasPuente** [walkerke/tidycensus#2]
Running `devtools::install_github("walkerke/tidycensus")` and then `library(tidycensus)` in a new R session will give you this error:
```
Error : object ‘set_units’ is not exported by 'namespace:units'
Error: package or namespace load failed for ‘tidycensus’
```

You can resolve that by simply running `library(units)` before `library(tidycensus)`. In the future, it might be a good idea for `units` to be imported by `tidycensus`, though.

**Comment by walkerke** [comment]
Thanks for your note.  What OS are you using?

**Comment by LucasPuente** [comment]
![screen shot 2017-05-24 at 5 34 32 pm](https://cloud.githubusercontent.com/assets/14006647/26431133/565f61ea-40a7-11e7-92b6-b01e3b1b0c8a.png)

**Comment by walkerke** [comment]
Thanks - this is helpful.  __tidycensus__ does not use any functions from the __units__ package directly - this should be picked up by __sf__ (and is on my Windows OS).  However I'll investigate further and import __units__ if need be, so I'll keep this issue open.

**Comment by walkerke** [comment]
Do you get the same error when you run `library(sf)` independent of tidycensus?

**Comment by LucasPuente** [comment]
No

**Comment by walkerke** [comment]
Would you mind re-installing __tidycensus__ and testing again for me?  I've added __units__ to `Imports` in the latest version, so I'd like to see if that solves the issue.  Thanks!

**Comment by walkerke** [comment]
I haven't heard anything further about this, so I am closing this issue.  If you or anyone else reading this is still experiencing problems, please re-open the issue and I'll debug further.
