### ISSUE TITLE
relax sf dependency

### ISSUE THREAD

**Issue by mwillumz** [walkerke/tidycensus#20]
I wonder if you'd consider relaxing the sf dependency or splitting the mapping and api components of tidycensus into separate packages in the future. The reason I ask is that I'm using rstudio in scientific linux and current gdal libraries are not available (thus no sf). 

Ideally we'd work on a different distro here but it also occurred to me that the api functionality could be separated from the geospatial stuff.

Thanks for the package!

**Comment by walkerke** [comment]
Thanks for using the package!  I don't have plans to do this at the moment.  The geo part of tidycensus is in another package - it uses the **tigris** package under the hood - and non-spatial Census packages are available on CRAN (__acs__ and __censusapi__).  You might consider taking a look at those packages.
