### ISSUE TITLE
Blank API error returned

### ISSUE THREAD

**Issue by ezmckinn** [walkerke/tidycensus#205]
Hi there - 

I am using tidyverse 1.3.0, tinycensus 0.9.2 and rlang 0.4.1. I am just trying to call ACS data. I have an active API key. I am running the following code:

census_api_key("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", install = TRUE, overwrite = TRUE) 
readRenviron("~/.Renviron") #update R to use census key.

test <- get_acs(geography = "state",
                   survey = "acs1",
                   table = "A00001",
                   year = 2017)

...and getting the following error:

"Error: Your API call has errors. The API message returned is ."

It doesn't tell me what the problem is; the API doesn't even give me a pointer. I have tried updating all the relevant packages, which hasn't worked. Any other suggestions?

**Comment by mfherman** [comment]
That's not a great error message from the Census -- it really should give you some more help. But, the problem is that `A00001` is not a table available from the Census API. From a little googling it looks like `A00001` is related to total population. For that, you want table `B01003`.

If you want a way to see what tables and variables are available through tidycensus, you can use the `load_variables()`function to create a data frame with the names and descriptions of all the variables. See below for examples of both:

``` r
library(tidycensus)

get_acs(
  geography = "state",
  survey = "acs1",
  table = "B01003",
  year = 2017
  )
#> Getting data from the 2017 1-year ACS
#> The one-year ACS provides data for geographies with populations of 65,000 and greater.
#> # A tibble: 52 x 5
#>    GEOID NAME                 variable   estimate   moe
#>    <chr> <chr>                <chr>         <dbl> <dbl>
#>  1 01    Alabama              B01003_001  4874747    NA
#>  2 02    Alaska               B01003_001   739795    NA
#>  3 04    Arizona              B01003_001  7016270    NA
#>  4 05    Arkansas             B01003_001  3004279    NA
#>  5 06    California           B01003_001 39536653    NA
#>  6 08    Colorado             B01003_001  5607154    NA
#>  7 09    Connecticut          B01003_001  3588184    NA
#>  8 10    Delaware             B01003_001   961939    NA
#>  9 11    District of Columbia B01003_001   693972    NA
#> 10 12    Florida              B01003_001 20984400    NA
#> # … with 42 more rows


vars <- load_variables(2017, "acs1", cache = TRUE)
head(vars)
#> # A tibble: 6 x 3
#>   name       label                           concept                            
#>   <chr>      <chr>                           <chr>                              
#> 1 B00001_001 Estimate!!Total                 UNWEIGHTED SAMPLE COUNT OF THE POP…
#> 2 B00002_001 Estimate!!Total                 UNWEIGHTED SAMPLE HOUSING UNITS    
#> 3 B01001_001 Estimate!!Total                 SEX BY AGE                         
#> 4 B01001_002 Estimate!!Total!!Male           SEX BY AGE                         
#> 5 B01001_003 Estimate!!Total!!Male!!Under 5… SEX BY AGE                         
#> 6 B01001_004 Estimate!!Total!!Male!!5 to 9 … SEX BY AGE
```

<sup>Created on 2019-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ezmckinn** [comment]
Thank you so much! This fixed it. I appreciate you taking the time.
