### ISSUE TITLE
No MOE for variable causing error

### ISSUE THREAD

**Issue by ryanrosenberg** [walkerke/tidycensus#206]
I'm getting an error when I try to access the `B98021` table from the ACS, and I believe it's due to the questions in the table not having MOEs but not being marked as such in the data loading functions.

Getting this error specifically: `Error: Your API call has errors.  The API message returned is error: error: unknown variable 'B98021_001M'.`

**Comment by mfherman** [comment]
Thanks for the report! Here is a reprex of the error:

``` r
library(tidycensus)

get_acs(
  table = "B98021",
  geography = "state"
)
#> Getting data from the 2013-2017 5-year ACS
#> Error: Your API call has errors.  The API message returned is error: error: unknown variable 'B98021_001M'.
```

<sup>Created on 2019-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

To fix this, we need to add the variables without MOEs to this vector and tidycensus will not add the MOEs to the API call. When I have a chance in the next day to two, I'll add the variables here. Just from a brief look, we'll need to add all the variables from tables B98011, B98012, B98013, B98014, B98021, B98022, B98031, all of which are currently causing the same error as above.

https://github.com/walkerke/tidycensus/blob/739f28b3454d1c49b645731365daca0aedbf1af4/R/load_data.R#L3

To do a more systematic look at this, I think I can grab all the variables that don't have something like Bxxxxx_xxxM in the attributes column (https://api.census.gov/data/2017/acs/acs5/variables.html) and make sure each of these variables is the in the `no_moes` vector linked above.

**Comment by ryanrosenberg** [comment]
Thanks! That all makes sense to me. I've found a workaround by accessing the API directly in the meantime, so no rush on my end.

**Comment by mfherman** [comment]
This is now fixed in the dev version of tidyverse on GitHub. Just do a `remotes::install_github("walkerke/tidycensus")` and you should be up and running.
