### ISSUE TITLE
get_acs() for geography "tract" year 2012 is not completing the pull

### ISSUE THREAD

**Issue by ejrivera6** [walkerke/tidycensus#207]
I am pulling data for 2012 and 2017 for tract, place, and county subdivision. The only function I am having this issue with are tracts for 2012. The function stays in a loop and never completes. Once I cancel the pull I get an error that the path exists. 

#set up states
us <- unique(fips_codes$state)[1:51] 
owner_tract12 <- map_df(us, function(x) {
  get_acs(geography = "tract",
          survey = "acs5",
          year = 2012,
          variables =  c(white = 'B25003A_001',
                                black = 'B25003B_001',
                                amindian_Ak = 'B25003C_001',
                                asian = 'B25003D_001',
                                hawaiian_pi = 'B25003E_001',
                                other = 'B25003F_001',
                                hispanic = 'B25003I_001',
                                two = 'B11001G_001'),
          summary_var = "B25003_001",
          state = x)
})

`Error:` Path exists and overwrite is FALSE

Thank you for your help!

**Comment by mfherman** [comment]
Does the function work for one state? Or maybe two small states? The code looks code to me and runs when I try Vermont and New Hampshire. You might just be getting an API error somewhere in the many calls you need to get all tracts in the US.

If you're not able to make it work for all states in one call, you could loop over smaller sets of states, or as an alternative, you might try downloading all tracts from [IPUMS](https://www.nhgis.org/) instead of tidycensus.

``` r
library(tidyverse)
library(tidycensus)

owner_tract12 <- map_df(c("VT", "NH"), function(x) {
  get_acs(geography = "tract",
          survey = "acs5",
          year = 2012,
          variables = c(white = 'B25003A_001',
                        black = 'B25003B_001',
                        amindian_Ak = 'B25003C_001',
                        asian = 'B25003D_001',
                        hawaiian_pi = 'B25003E_001',
                        other = 'B25003F_001',
                        hispanic = 'B25003I_001',
                        two = 'B11001G_001'),
          summary_var = "B25003_001",
          state = x)
})
#> Getting data from the 2008-2012 5-year ACS
#> Getting data from the 2008-2012 5-year ACS

head(owner_tract12)
#> # A tibble: 6 x 7
#>   GEOID    NAME                 variable  estimate   moe summary_est summary_moe
#>   <chr>    <chr>                <chr>        <dbl> <dbl>       <dbl>       <dbl>
#> 1 5000595~ Census Tract 9570, ~ two             13    10        1590          94
#> 2 5000595~ Census Tract 9570, ~ white         1573    92        1590          94
#> 3 5000595~ Census Tract 9570, ~ black            4     8        1590          94
#> 4 5000595~ Census Tract 9570, ~ amindian~        0     9        1590          94
#> 5 5000595~ Census Tract 9570, ~ asian            0     9        1590          94
#> 6 5000595~ Census Tract 9570, ~ hawaiian~        0     9        1590          94
```

<sup>Created on 2019-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ejrivera6** [comment]
It works for the other geographies (places and county subdivisions). I will go to IPUMS, thank you.

**Comment by mfherman** [comment]
I think the issue with tracts is that there are just so many to get for the whole US, so it is slow via the API and if you run into an error in one of the many API calls, the whole thing may fail.

**Comment by walkerke** [comment]
I'm going to work on some broader performance improvements in the next couple months so I'll take a look at this.  To @mfherman's point - I generally recommend against using tidycensus for large data pulls given that it might be hitting the API a bunch of times and subject to API hiccups.  NHGIS is a nice option and you might also consider the {totalcensus} package which is designed for bulk Census data pulls.

**Comment by walkerke** [comment]
@ejrivera6 Using the most recent version of tidycensus on GitHub (0.9.4) I just ran your code successfully, so I'm closing this issue.
