### ISSUE TITLE
error returning "zcta" geography for get_decennial()

### ISSUE THREAD

**Issue by AmandaGottschall** [walkerke/tidycensus#210]
I believe that the _zip code tabulation area_ (_zcta_) geography is available for the 2010 decennial Census summary file 1 (_sf1_).  However, I am getting an error when requesting this geography in the **get_decennial()** function.  

Ultimately, I want zcta-level data for the entire country.  But specifying only the _geography_ argument returns the following error:

> Error: ZCTA data for the decennial Census is only available by state from tidycensus.

So starting with a single state's zcta-level data (before putting this into the **purrr::map_dfr()** function to append all state calls into a single data frame), the following error is returned: 

`TEST_IL_ZCTA <- get_decennial(geography = "zcta", 
                                                    variables = c("P005003", "P005004", "P005006", "P004003"), 
                                                    year = 2010,
                                                    summary_var = "P001001", 
                                                    state = "IL", 
                                                    sumfile = "sf1", 
                                                    geometry = FALSE)`

> Getting data from the 2010 decennial Census
> Using FIPS code '17' for state 'IL'
> Error : Your API call has errors.  The API message returned is <html><head><title>Error report</title></head><body><h1>HTTP Status 404 - /data/2010/dec/sf3</h1></body></html>.
> Error in gather_(data, key_col = compat_as_lazy(enquo(key)), value_col = compat_as_lazy(enquo(value)),  : 
>   unused argument (-NAME)

Making the same call as above but for the _county_ geography instead of _zcta_ executes successfully: 

`TEST_IL <- get_decennial(geography = "county", 
                                                    variables = c("P005003", "P005004", "P005006", "P004003"), 
                                                    year = 2010,
                                                    summary_var = "P001001", 
                                                    state = "IL", 
                                                    sumfile = "sf1", 
                                                    geometry = FALSE)`

Am I making an error in how I'm requesting zcta-level 2010 decennial Census data?  Or is there an issue with retrieving _zcta_ geography (by state or for the entire country) in the **get_decennial()** function?

I'm using R version 3.5.1 and tidycensus version 0.9.2 - here is other information on my session (excluding the unattached packages):

`sessionInfo()`

> R version 3.5.1 (--)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.6 LTS
> 
> Matrix products: default
> BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.18.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] tidycensus_0.9.2 Rook_1.1-1       RJSONIO_1.3-1.2  Cairo_1.5-6

**Comment by AmandaGottschall** [comment]
I also want to say that the **tidycensus** package is terrific!  It's made things so much easier for me and this is the first snafu that I've run into.  Thanks for all of the development and maintenance work that you've put into this package!!

**Comment by walkerke** [comment]
I appreciate your note!  It looks like Census changed the internals of how it handles ZCTAs in 2010.  The good news is I think now we can get ZCTA data for the whole country.  I'll push a fix.

**Comment by AmandaGottschall** [comment]
How exciting that we should be able to get ZCTA data for the whole country!  Thanks for your prompt reply and pushing a fix.

**Comment by walkerke** [comment]
This now works in the GitHub version and you can also get ZCTAs for the whole country by omitting the state argument.

**Comment by AmandaGottschall** [comment]
Fantastic!  Thanks so much for the speedy turnaround on this issue!

**Comment by rickyars** [comment]
I'm using version 0.9.9.5 and getting the same 404 error when using `get_decennial` with `zcta`. Do I need to install from GitHub?

**Comment by mfherman** [comment]
@rickyars can you post the specific code and error messages you are getting? If you are looking for 2000 census data, you will need to install the GH version to access (see #293).

**Comment by rickyars** [comment]
```
> racevars <- c(White = "P005003", Black = "P005004", Asian = "P005006", Hispanic = "P004003")
> 
> # P001001 is total population
> harris_z <- get_decennial(
+   geography = "zcta",
+   variables = racevars,
+   state = "TX",
+   county = c("Harris County"),
+   geometry = TRUE,
+   summary_var = "P001001",
+   cb = FALSE)
Getting data from the 2010 decennial Census
Using FIPS code '48' for state 'TX'
Using FIPS code '201' for 'Harris County'
Error : Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.
Using Census Summary File 1
Error in gather.default(., key = variable, value = value, -GEOID, -NAME) : 
  object 'NAME' not found
```
I updated to the GitHub version and I'm still seeing the issue (2010 census data)

**Comment by rickyars** [comment]
I'm an idiot. Do I have to grab the zipcodes for all the US?

**Comment by mfherman** [comment]
No worries @rickyars! Because ZCTAs cross county boundaries you can't request ZCTAs in a particular county. See #287 where we discuss the ability to request a subset of ZCTAs. Hopefully this will be added to a future version of tidycensus.
