### ISSUE TITLE
lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by mattwilliamson13** [walkerke/tidycensus#22]
Running the following:
`med_inc_2000 <- get_decennial(geography = "county", variables = "PCT045001", year = 2000, sumfile="sf3", state = "Maryland", output = 'wide')`

results in: 
Using FIPS code '24' for state 'Maryland'
Error : lexical error: invalid char in json text.
          1"], ["31653","Prince George"s County","24","033"], ["38112"
                     (right here) ------^

Looking at the county names for Maryland shows: "Prince George's County" (without the double quotes). I'm not sure how to fix this error (unless there is a way to make it search by FIPS rather than county name). Any assistance would be appreciated.

Update: this also happens in Iowa for "O'Brien County" Iowa. The apostrophe seems to cause problems in accessing the censusapi

**Comment by walkerke** [comment]
Looks like this is happening at the level of the Census API.  For example, the raw call you are making is as follows: 

https://api.census.gov/data/2000/sf3?get=PCT045001,NAME&for=county:*

Apostrophes in this call are using double quotes.  __tidycensus__ gets the NAME column by default to give users more information about their data.  I think this is fixable on __tidycensus__'s end but I'll also send a note to Census about this.

**Comment by mattwilliamson13** [comment]
Thanks, I actually really appreciate the use of the NAME column for the reason you describe - I just couldn’t figure out how to get around it. Really appreciate any help you can offer.
Best,
M
Matt Williamson
Ph.D. Candidate
Graduate Group in Ecology
University of California, Davis

**Comment by mattwilliamson13** [comment]
Also, the error doesn’t seem to occur for total population or many other demographics (just on the median income).

Matt Williamson
Ph.D. Candidate
Graduate Group in Ecology
University of California, Davis

**Comment by walkerke** [comment]
Sounds like it's a bug in the 2000 SF3 API, but not the SF1 API.

**Comment by mattwilliamson13** [comment]
Correct. And it's only on the sf3 call, I think

Sent from my iPhone

**Comment by walkerke** [comment]
I've fixed this in https://github.com/walkerke/tidycensus/commit/b33732dcba0bc6802ef96425495a2b11ed830739.
