### ISSUE TITLE
get_acs() not working for CBSA geography

### ISSUE THREAD

**Issue by dkori** [walkerke/tidycensus#224]
Per the [geography guide here](https://walkerke.github.io/tidycensus/articles/basic-usage.html#geography-in-tidycensus), I have been trying to retrieve CBSA level data in Pennsylvania. Both of the code attempts below return "The API message returned is error: unknown/unsupported geography heirarchy."

`get_acs(geography="cbsa",year=2017,
                         variables=c(total_pop = "B01001_001"),
                         state="PA")`
`get_acs(geography="metropolitan statistical area/micropolitan statistical area",year=2017,
                         variables=c(total_pop = "B01001_001"),
                         state="PA")`

**Comment by mfherman** [comment]
That looks to be typo in the tidycensus documentation. CBSA/MSA boundaries can cross state lines, so you can't query for MSAs in a given state. To achieve what you're looking for, the easiest way is to probably to pull all MSAs and the subset to just the ones that contain PA. 

``` r
library(tidyverse)
library(tidycensus)

get_acs(
  geography = "metropolitan statistical area/micropolitan statistical area",
  year = 2017,
  variables = c(total_pop = "B01001_001"),
  ) %>% 
  filter(str_detect(NAME, "PA"))
#> Getting data from the 2013-2017 5-year ACS
#> # A tibble: 37 x 5
#>    GEOID NAME                                         variable  estimate   moe
#>    <chr> <chr>                                        <chr>        <dbl> <dbl>
#>  1 10900 Allentown-Bethlehem-Easton, PA-NJ Metro Area total_pop   832790    NA
#>  2 11020 Altoona, PA Metro Area                       total_pop   124736    NA
#>  3 14100 Bloomsburg-Berwick, PA Metro Area            total_pop    84917    NA
#>  4 14620 Bradford, PA Micro Area                      total_pop    42070    NA
#>  5 16540 Chambersburg-Waynesboro, PA Metro Area       total_pop   153003    NA
#>  6 20180 DuBois, PA Micro Area                        total_pop    80539    NA
#>  7 20700 East Stroudsburg, PA Metro Area              total_pop   167306    NA
#>  8 21500 Erie, PA Metro Area                          total_pop   277794    NA
#>  9 23900 Gettysburg, PA Metro Area                    total_pop   101589    NA
#> 10 25420 Harrisburg-Carlisle, PA Metro Area           total_pop   565008    NA
#> # ... with 27 more rows
```

<sup>Created on 2020-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Note, the first result, Allentown-Bethlehem-Easton, PA-NJ Metro Area, is an example of a MSA that crosses state boundaries.

**Comment by dkori** [comment]
Perfect, thank you!
