### ISSUE TITLE
'HTTP Status 404' for acs1 and acs3 in 2009

### ISSUE THREAD

**Issue by tiernanmartin** [walkerke/tidycensus#227]
I am unable to download data from the 2009 acs1 or acs3. 

My `get_acs()` query seems to be working fine for the 2009 ac5 as well as the 2008 and 2010 acs1/acs3—it's only 2009 acs1/acs3 that are giving me trouble.

Any idea what might be causing this?

<details>
<summary>Reprex</summary>

``` r
library(tidycensus)

get_acs(geography = "county", 
          variables = "B01003_001", 
          year = 2009,
          state = 53, 
          survey = "acs1")

## Getting data from the 2009 1-year ACS
## The one-year ACS provides data for geographies with populations of 65,000 and greater.
## Error: Your API call has errors.  The API message returned is <html><head><title>Error report</title></head><body><h1>HTTP Status 404 - /data/2009/acs1</h1></body></html>.

get_acs(geography = "state", 
          variables = "B01003_001", 
          year = 2009,
          state = 53, 
          survey = "acs3")

## Getting data from the 2007-2009 3-year ACS
## The three-year ACS provides data for geographies with populations of 20,000 and greater.
## Error: Your API call has errors.  The API message returned is <html><head><title>Error report</title></head><body><h1>HTTP Status 404 - /data/2009/acs3</h1></body></html>.
```
</details>

**Comment by walkerke** [comment]
Just pushed a fix to GitHub.  When the API migrated to the new endpoint we were playing whack-a-mole with errors a bit as not all datasets moved over at the beginning; at the time 2009 data were only available from the old endpoint, so we hard-coded that restriction.  I just checked and removed this limitation in tidycensus which makes both your queries work correctly.
