### ISSUE TITLE
2017 five year Subject Tables Error Out

### ISSUE THREAD

**Issue by jamgreen** [walkerke/tidycensus#228]
I am seeking to pull the poverty tables S1701_C01_001 and S1701_C01_002 from the five year subject tables. The current call:

``asdf <- get_acs(geography = "tract",
                 variables =  "S1701_C01_001",
                year = 2017,
               survey = "acs5/subject",
               state = "OR", county = "Multnomah",
                 geometry = FALSE,
                 output = "wide")
``

Returns the following error:

``
Using the ACS Subject Tables
Using FIPS code '41' for state 'OR'
Using FIPS code '051' for 'Multnomah County'
Error: Your API call has errors.  The API message returned is <html><head><title>Error report</title></head><body><h1>HTTP Status 404 - /data/2017/acs/acs5/subject/subject</h1></body></html>.
``

Is this a signal that the subject tables are not currently accessible via the API or is this an error on my part?

**Comment by walkerke** [comment]
The subject tables are supported; you just don't need to request them directly as `get_acs()` infers where to look from the variable name.  For example: 

```r
library(tidycensus)

get_acs(geography = "tract", variables = "S1701_C01_001", year = 2017, state = "OR", county = "Multnomah", geometry = FALSE, output = "wide")
```
```
Getting data from the 2013-2017 5-year ACS
Using the ACS Subject Tables
Using FIPS code '41' for state 'OR'
Using FIPS code '051' for 'Multnomah County'
# A tibble: 171 x 4
   GEOID       NAME                                         S1701_C01_001E S1701_C01_001M
   <chr>       <chr>                                                 <dbl>          <dbl>
 1 41051002701 Census Tract 27.01, Multnomah County, Oregon           3211            162
 2 41051003803 Census Tract 38.03, Multnomah County, Oregon           4499            466
 3 41051004601 Census Tract 46.01, Multnomah County, Oregon           3017            227
 4 41051006300 Census Tract 63, Multnomah County, Oregon              4015            266
 5 41051006402 Census Tract 64.02, Multnomah County, Oregon           5977            472
 6 41051007000 Census Tract 70, Multnomah County, Oregon              8292            468
 7 41051007201 Census Tract 72.01, Multnomah County, Oregon           2239            299
 8 41051003802 Census Tract 38.02, Multnomah County, Oregon           3487            187
 9 41051003901 Census Tract 39.01, Multnomah County, Oregon           7963            521
10 41051005500 Census Tract 55, Multnomah County, Oregon              2805            208
# … with 161 more rows
```

I'll plug in something for the next release that catches this sort of error.
