### ISSUE TITLE
Error in bind_rows_(x, .id) : Argument 6 must be length 1, not 0

### ISSUE THREAD

**Issue by amgsharma** [walkerke/tidycensus#23]
Command: 
v15 <- load_variables(2015, "acs5", cache = FALSE)

as per the instructions on : 
https://walkerke.github.io/tidycensus/articles/basic-usage.html#searching-for-variables

Output: 
Error in bind_rows_(x, .id) : Argument 6 must be length 1, not 0

Thoughts?

**Comment by walkerke** [comment]
Yes - see https://github.com/walkerke/tidycensus/issues/21.  I'm working on a fix for this.
