### ISSUE TITLE
Get_acs failing at tract level with geometry only for 2014 and 2015

### ISSUE THREAD

**Issue by dkori** [walkerke/tidycensus#231]
This is a toy example with the specific state and county I'm working with, but it seems to be consistent for many states and counties:
`test<-get_acs(year=2014, variable="B01001_001",
              geography="tract",state="PA",
              county="Allegheny",
              geometry=TRUE)`

The code works for 2010-2013, and 2016-2018, but not for 2014 or 2015. It also runs for all years if I set geometry to false, so it seems to be an issue with the shape files for those years. 

I can definitely work around it by pulling tracts from tigris, but I'd like to avoid rewriting some working code if this is either a temporary issue on the census side or a quick fix.

**Comment by walkerke** [comment]
Your code runs correctly for me.  It might be an issue with corrupted shapefile downloads - that happens from time to time with the Census website.  Let me know if the problem continues and we can get it figured out - and if so, could you post the error message you are getting and the results of `sessionInfo()`?

**Comment by dkori** [comment]
Looks like I'm still having the issue, here's the output: 

`Getting data from the 2010-2014 5-year ACS
Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
Using FIPS code '42' for state 'PA'
Using FIPS code '003' for 'Allegheny County'
Cannot open layer cb_2014_42_tract_500k
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Opening layer failed.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file`

And here's the sessionInfo: 
`> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_4.1.0   sf_0.7-3         tidyr_0.8.2      dplyr_0.8.3      tidycensus_0.9.6

loaded via a namespace (and not attached):
 [1] zip_2.0.1        Rcpp_1.0.3       pillar_1.4.2     compiler_3.5.3   class_7.3-15     tools_3.5.3     
 [7] packrat_0.5.0    uuid_0.1-2       jsonlite_1.6.1   tibble_2.1.3     lattice_0.20-38  pkgconfig_2.0.3 
[13] rlang_0.4.2      DBI_1.0.0        rstudioapi_0.10  curl_3.3         rgdal_1.4-2      e1071_1.7-0     
[19] httr_1.4.0       stringr_1.4.0    xml2_1.2.0       hms_0.4.2        rappdirs_0.3.1   tigris_0.7      
[25] classInt_0.3-1   grid_3.5.3       tidyselect_0.2.5 glue_1.3.1       R6_2.4.1         foreign_0.8-71  
[31] sp_1.3-1         purrr_0.3.3      readr_1.3.1      magrittr_1.5     units_0.6-2      maptools_0.9-5  
[37] assertthat_0.2.1 rvest_0.3.2      stringi_1.4.3    crayon_1.3.4    `

**Comment by walkerke** [comment]
I think the corrupted file is in your temporary directory and R is trying to read from it.  Can you try again but before doing so set `options(tigris_use_cache = TRUE)` to save the shapefile to your personal cache directory?

**Comment by dkori** [comment]
That fixed it, thanks for your help! 
I'm having a little trouble understanding why this fixed it, if options(tigris_use_cache=FALSE), does R first check to see if there's a version in the temporary directory? I would have thought it would retrieve the shapefile from remote if tigris_use_cache is set to false.
