### ISSUE TITLE
Census API not available

### ISSUE THREAD

**Issue by kuriwaki** [walkerke/tidycensus#232]
Thanks for the great package. Since today, `get_acs` gives the same error that also gets displayed at https://api.census.gov/data/key_signup.html

Is the decomissioning of FactFinder related to this? I worry that the unavailability will be permanent.

![image](https://user-images.githubusercontent.com/8290417/78198204-d30b5980-7455-11ea-8b5d-2b7d0dd0238e.png)

**Comment by mfherman** [comment]
This is just a temporary issue. All the census API products are having issues. Hopefully it’s resolved tomorrow.

**Comment by kuriwaki** [comment]
Thank you. Looks like it works now.
