### ISSUE TITLE
tidycensus isn't creating the correct query

### ISSUE THREAD

**Issue by jefunes** [walkerke/tidycensus#237]
I failed to retrieve data I was able to retrieve last night. today it stopped working. see the message below: 
Getting data from the 2014-2018 5-year ACS
Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
Using FIPS code '11' for state 'DC'
No encoding supplied: defaulting to UTF-8.
Error: You have supplied an invalid or inactive API key. To obtain a valid API key, visit https://api.census.gov/data/key_signup.html. To activate your key, be sure to click the link provided to you in the email from the Census Bureau that contained your key.

arch_engi_occ_var <- c("C24010_009","C24010_045")
arch_engi_occ <- get_acs(geography = "tract", variables = arch_engi_occ_var , state="DC", geometry = TRUE, year=2018)

**Comment by walkerke** [comment]
Your code works fine for me.  Are you using a different API key that may not have been activated?

**Comment by jefunes** [comment]
the same key. it was working last night. today it stopped working

**Comment by jefunes** [comment]
I emailed census people. this is what i got 

So we did some digging and that code looks like it's coming from an R package called tidycensus.  Is that what you are using?  It looks like the tidycensus isn't creating the correct query, but we can't verify on this end.  He suggest contacting the tidycensus developer for help.  I'm sorry I couldn't help.

**Comment by walkerke** [comment]
Have you been hitting the API a lot and possibly got blocked?  Try running your code again with the argument `show_call = TRUE` and paste the URL into a web browser to see what comes up.  Given that I am running your code successfully, it isn't likely an issue on the tidycensus side of things.

**Comment by jefunes** [comment]
yesterday, a few tables. today, it did not work at all. 

I got the same message: 
Getting data from the 2014-2018 5-year ACS
Using FIPS code '11' for state 'DC'
No encoding supplied: defaulting to UTF-8.
Error: You have supplied an invalid or inactive API key. To obtain a valid API key, visit https://api.census.gov/data/key_signup.html. To activate your key, be sure to click the link provided to you in the email from the Census Bureau that contained your key.

arch_engi_occ_var <- c("C24010_009","C24010_045")
arch_engi_occ_DC <- get_acs(geography = "County", variables =arch_engi_occ_var, state="DC", year=2018, show_call=TRUE)

**Comment by walkerke** [comment]
it appears that your API key is getting blocked for some reason.  I'd give it a little time then try again, or go ahead and request a new one from Census.

**Comment by jefunes** [comment]
I just requested a key, but they sent me the same key, it still does not work. :(

**Comment by walkerke** [comment]
Try requesting from a different email address then which should generate a different key if yours is not working.  Closing this as this is an API-level issue; you might consider contacting Census again to see what is going on with your key.

**Comment by walkerke** [comment]
@jefunes The only other thing I can think of is that there is a problem with how R is storing your API key.  Have you installed your key with `census_api_key("your key here", install = TRUE)`?  Check your .Renviron file with `usethis::edit_r_environ()` and make sure the key in there is your actual API key.

**Comment by jefunes** [comment]
thanks for your help and reply. it is somehow frustrating, I did run it and got a separate window with this: 
CENSUS_API_KEY='xxxxxxxxxxxxxxxxxxxxxx'
