### ISSUE TITLE
Error in as.character(x) :    cannot coerce type 'closure' to vector of type 'character'

### ISSUE THREAD

**Issue by mta614** [walkerke/tidycensus#238]
Hi there--trying to run a pretty simple script and having the subject line issue be thrown. Here's what I'm running:

`library(tidycensus)`

`vars = c("B19013_001","B19013_002")`

`result <- get_acs(geography = "county", 
                      variables = vars,
                      state = "NY",
                      county = "047",
                      output = "wide")`

If I replace `vars` with just a string (e.g. `B19013_001`), the script runs just fine. Not sure what's up as my `vars` is a vector of character strings.

**Comment by szimmer** [comment]
The issue is that there is no variable "B19013_002". See below:

``` r
library(tidycensus)
library(tidyverse)
v18 <- load_variables(year=2018, dataset="acs5", cache = TRUE)

v18 %>%
  filter(str_detect(name, "B19013")) %>%
  select(name)
#> # A tibble: 10 x 1
#>    name       
#>    <chr>      
#>  1 B19013_001 
#>  2 B19013A_001
#>  3 B19013B_001
#>  4 B19013C_001
#>  5 B19013D_001
#>  6 B19013E_001
#>  7 B19013F_001
#>  8 B19013G_001
#>  9 B19013H_001
#> 10 B19013I_001


vars = c("B19013_001","B19013A_001")

result <- get_acs(geography = "county", variables = vars, state = "NY", 
                  county = "047", output = "wide")
#> Getting data from the 2014-2018 5-year ACS
```

<sup>Created on 2020-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mta614** [comment]
Ah, silly me. I should've checked for that, as those fields were from a project I did two years ago and I don't know if they were accurate then or part of a test/playing around. Thank you!
