### ISSUE TITLE
load_variables error

### ISSUE THREAD

**Issue by ZellW** [walkerke/tidycensus#24]
It seems like my error is unque since I can find no references or it occurring with others.  (That's a bad sign for me.)

Using your example:  v15 <- load_variables(2015, "acs5", cache = FALSE)

gives this error:  **Error in bind_rows_(x, .id) : incompatible sizes (1 != 0)**

Any ideas?

**Comment by walkerke** [comment]
Can you re-install the package from GitHub and then try again?  If the error persists, could you show me the results of your `sessionInfo()`?

**Comment by ZellW** [comment]
install from GitHub solved my issues.  Sorry to bother you with this - I should have done this first.  FYI, this message was displayed as the function was running:

at_depth() is deprecated, please use `modify_depth()` instead

**Comment by walkerke** [comment]
Thanks for the note - looks like I wasn't running the latest version of __purrr__.  I've updated this in https://github.com/walkerke/tidycensus/commit/9256eef5afaf3ff6e007dc17cea1832281510575.

**Comment by jasparkatt** [comment]
Just an FYI...i successfully updated my tidycensus package via gh_install_packages("tidycensus" ref=9256eef) resulting in no errors as in issue #21 or the warning noted by @ZellW . I did however receive that deprecation warning when i first did gh_install_packages("tidycensus" ref="c1c5ec5")
