### ISSUE TITLE
get_acs() doesn't work with tibble  V 3

### ISSUE THREAD

**Issue by dcaud** [walkerke/tidycensus#243]
I  downgraded tibble with 
`install_version("tibble", version = "2.1.3", repos = "http://cran.us.r-project.org")`
and things worked again.

**Comment by mfherman** [comment]
Have you tried upgrading to the most recent github version of tidycensus? It should be working with tibble 3.0 and the upcoming dplyr 1.0 release.

**Comment by krlmlr** [comment]
Related: https://github.com/tidyverse/tibble/issues/764.

**Comment by walkerke** [comment]
Using the CRAN version of tidycensus and tibble v3.0.0, I show:

```r
> library(tidycensus)
> packageVersion("tibble")
[1] ‘3.0.0’
> packageVersion("tidycensus")
[1] ‘0.9.9.2’
> 
> get_acs(geography = "state",
+         variables = "B01002_001")
Getting data from the 2014-2018 5-year ACS
# A tibble: 52 x 5
   GEOID NAME                 variable   estimate   moe
   <chr> <chr>                <chr>         <dbl> <dbl>
 1 01    Alabama              B01002_001     38.9   0.1
 2 02    Alaska               B01002_001     34     0.1
 3 04    Arizona              B01002_001     37.4   0.1
 4 05    Arkansas             B01002_001     37.9   0.1
 5 06    California           B01002_001     36.3   0.1
 6 08    Colorado             B01002_001     36.6   0.1
 7 09    Connecticut          B01002_001     40.8   0.2
 8 10    Delaware             B01002_001     40.2   0.2
 9 11    District of Columbia B01002_001     33.9   0.1
10 12    Florida              B01002_001     41.9   0.1
# … with 42 more rows
```

Closing as this appears to be addressed with package updates.

**Comment by krlmlr** [comment]
On that note, thanks for updating tidycensus and sorry for the hassle, I believe I missed your package when checking downstream dependencies for tibble 3.0.0.

**Comment by walkerke** [comment]
@krlmlr no need to apologize!  We appreciate all the work you put in maintaining these packages.
