### ISSUE TITLE
Decennial Census Variables load_variables

### ISSUE THREAD

**Issue by paragemini** [walkerke/tidycensus#249]
load_variables() : Decennial Census data variables are loading incorrectly and/or incompletely. This can lead to the use of incorrect data and improper analysis.

**Comment by walkerke** [comment]
@paragemini Can you please elaborate with an example?

**Comment by paragemini** [comment]
Yes.  When using this command 
load_variables(year = 2010, dataset = "sf1")

tables like P6, P7, and P12 do not show up whereas one can find them at data.census. gov .

![image](https://user-images.githubusercontent.com/13204081/81979645-f0097f80-95f2-11ea-81c8-738241d64f91.png)

**Comment by walkerke** [comment]
@paragemini it's a difference of nomenclature between data.census.gov and the way that tidycensus interacts with the Census API.  Before the API enabled a `groups` parameter, we wrote the `table` argument to detect groups of variables based on the variable name.  So your table `P12` is identified in tidycensus as `P012`, which is a common prefix for variables in that table: 

```
> library(tidycensus)
> sf1 <- load_variables(2010, "sf1", cache = TRUE)
> dplyr::filter(sf1, stringr::str_detect(name, "P012"))
# A tibble: 490 x 3
   name    label                        concept   
   <chr>   <chr>                        <chr>     
 1 P012001 Total                        SEX BY AGE
 2 P012002 Total!!Male                  SEX BY AGE
 3 P012003 Total!!Male!!Under 5 years   SEX BY AGE
 4 P012004 Total!!Male!!5 to 9 years    SEX BY AGE
 5 P012005 Total!!Male!!10 to 14 years  SEX BY AGE
 6 P012006 Total!!Male!!15 to 17 years  SEX BY AGE
 7 P012007 Total!!Male!!18 and 19 years SEX BY AGE
 8 P012008 Total!!Male!!20 years        SEX BY AGE
 9 P012009 Total!!Male!!21 years        SEX BY AGE
10 P012010 Total!!Male!!22 to 24 years  SEX BY AGE
# … with 480 more rows
```

So your requested table can be obtained with the argument `table = "P012"`: 

```
> get_decennial("state", table = "P012")
Getting data from the 2010 decennial Census
# A tibble: 2,548 x 4
   GEOID NAME        variable    value
   <chr> <chr>       <chr>       <dbl>
 1 01    Alabama     P012001   4779736
 2 02    Alaska      P012001    710231
 3 04    Arizona     P012001   6392017
 4 05    Arkansas    P012001   2915918
 5 06    California  P012001  37253956
 6 22    Louisiana   P012001   4533372
 7 21    Kentucky    P012001   4339367
 8 08    Colorado    P012001   5029196
 9 09    Connecticut P012001   3574097
10 10    Delaware    P012001    897934
# … with 2,538 more rows
```

We might consider a re-factor at some stage to use `groups` in the API which would allow for consistent naming with data.census.gov.  This isn't a top development priority for me at the moment, however, as the functionality would essentially replicate what is already available in the package.

**Comment by paragemini** [comment]
Thank you, Kyle, for this. I did not know about the convention. I think it will be really helpful if this is documented somewhere in the package. As usual, your package is amazing and I look forward to the new improved version of it. Thanks!
