### ISSUE TITLE
all census tracts with shift_geo = T

### ISSUE THREAD

**Issue by SreejaSN** [walkerke/tidycensus#251]
Hi, 

I'm trying to get the geometry  for all the census tracts in the country, with AL and HI shifted. I tried
`
us <- unique(fips_codes$state)[1:51]
tract_map<- reduce(
  map(us, function(x) {
    get_acs(geography = "tract", variables = "B01003_001",
            state = x, geometry = TRUE, shift_geo = T )
  }),
  rbind
)`

but I get an error message saying:  

> Error: `shift_geo` is only available when requesting geometry for the entire US 

Am I missing some very obvious solution here? Thanks!

**Comment by mfherman** [comment]
Hi there, the shifted geometries are only available for states and counties. They actually come from the [albersusa package](https://github.com/hrbrmstr/albersusa). You could create your own version using tracts and then join the tidycensus data to the geomerty.

**Comment by SreejaSN** [comment]
Ah, got it. Thanks for pointing me in the right direction!
