### ISSUE TITLE
Orange County Population Map Colors are Not Correct

### ISSUE THREAD

**Issue by michiel1134** [walkerke/tidycensus#257]
Thank you incredibly much for posting these examples.  This is regarding the article you posted at:

https://walker-data.com/tidycensus/articles/spatial-data.html

I do notice a discrepancy with the Orange County population map.   As a local resident, I can attest that the colors representing populations are reversed.  According to the legend, the yellow shaded region has the highest population.  But this area is a state park.  The darker colors are the more populous census tracts.  I'm not seeing the error in your code that reflect this.

**Comment by walkerke** [comment]
Hi @michiel1134 - thanks for your note.  The map shows median household income, not total population.  The yellow area covers the Newport Coast area of Newport Beach, which has the highest median household income in Orange County according to the ACS.

**Comment by michiel1134** [comment]
That explains it! Thanks for your prompt response.  I've been working so much on populations I missed that important detail.
