### ISSUE TITLE
Error after updating rgdal

### ISSUE THREAD

**Issue by abuabara** [walkerke/tidycensus#260]
after updating rgdal today I get the following message. Tried to reinstall, no success.
any tip? thanks!

```
> library(tidycensus)
Error: package or namespace load failed for ‘tidycensus’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so, 6): Library not loaded: /usr/local/opt/gdal/lib/libgdal.20.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so
  Reason: image not found
```

**Comment by abuabara** [comment]
Nevermind. Solved.
1. brew install gdal
2. brew install pkg-config
3. library(devtools)
4. install.packages("rgdal", configure.args = c("--with-proj-lib=/usr/local/lib/", "--with-proj-include=/usr/local/include/"))
5. install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local/lib/")
library(devtools)
6. Restart R and tidycensus and sf will load properly.

**Comment by mfherman** [comment]
Thanks for leaving those clues for how you fixed it! If anyone else finds this issue and has a similar problem, these are useful places to look for more info:

https://github.com/r-spatial/sf/issues/1317#issuecomment-603928225
https://github.com/r-spatial/sf/issues/1312#issuecomment-605256918
