### ISSUE TITLE
Requesting total population for tract-level data

### ISSUE THREAD

**Issue by acnieves** [walkerke/tidycensus#266]
Hi, 

I understand that there might not be an easy way to download the total population variable at the tract-level for all states, only by individual states. What is the easiest way to pull this data? Will this be featured be added?

Thanks!

**Comment by mfherman** [comment]
Hi @acnieves -- you should be able to get tract-level data for all states. It might take a minute or two to download and parse, but this code works with the most recent version of tidycensus:

```r
tract_pop <- get_acs(
  geography = "tract",
  state = state.abb,
  variables = "B01001_001"
  )
```

**Comment by acnieves** [comment]
Thanks so much! I really appreciate it.

Best,
Amber

**Comment by walkerke** [comment]
@mfherman's answer is correct.  One slight modification - R's built-in `state.abb` object only includes _states_, strictly, so if you want to include DC or Puerto Rico you'd need to do `c(state.abb, "DC", "PR")` for the `state` argument instead.
