### ISSUE TITLE
Bug or better error message needed?: Multiple values on summary_var in get_acs()

### ISSUE THREAD

**Issue by badbayesian** [walkerke/tidycensus#267]
I was looking at a couple different of total and marginal variables such as income, poverty. It seems that the current implementation forces you to choose one summary variable per pull but doesn't give a good error message on the subject. Do you want to be strict with forcing only one summary vars or do you want to allow users to use multiple summary variables? I am happy to implement either case.

```
library(tidycensus)
vars <- c("B17001_002", "B02001_003", "B02001_001")
summary_vars <- c("B18140_001", "B17001_001")
dc_dat <- get_acs(geography = "tract",
                  variables = vars,
                  summary_var = summary_vars,
                  state = "dc",
                  geometry = TRUE,
                  year = 2018)

Error: Problem with `mutate()` input `summary_moe`.
x object 'summary_moe' not found
ℹ Input `summary_moe` is `round(summary_moe * moe_factor, 0)`.
```

**Comment by walkerke** [comment]
I think an error message makes sense here; I'd probably recommend using `output = "wide"` when multiple summary variable-equivalents are used.  The idea behind the summary variable was when in long (`"tidy"`) format, percentages/ratios/etc. could be computed easily for variables in the same table.  For multiple summary variables this gets a bit convoluted, and with `dplyr::across()` row-wise calculations over multiple columns in wide format are now straightforward.
