### ISSUE TITLE
Trouble Accessing PUMS functions

### ISSUE THREAD

**Issue by tribzi** [walkerke/tidycensus#272]
Hi. I'm attempting to access PUMS data with `get_pums()` according to the instructions in [your post here](https://walker-data.com/tidycensus/articles/pums-data.html#pums-data-dictionaries). However, the tidycensus package does not install with `get_pums()` or the `pums_variables` dataset as described. I tried downloading the package from CRAN `install.packages("tidyverse")` and neither function nor dataset showed up. When I downloaded the package from this github repo with devtools `install.github("walkerke/tidycensus")` the package downloaded with the documentation for `get_pums()` but when I tried to use the function it cannot be found. The `pums_variables` set is also not present.

Using R v4.0.2 in Rstudio 1.2.1335.

Thanks for your work on the package and your help.

**Comment by walkerke** [comment]
Can you post the results of your `sessionInfo()`, along with the code you've tried?

**Comment by mfherman** [comment]
The function from devtools to install from GitHub is `devtools::install_github("walkerke/tidycensus")`, not `install.github()` -- perhaps you weren't able to install the current GitHub version?

**Comment by walkerke** [comment]
It works for me with a fresh install on RStudio Cloud - try what @mfherman posted and ping us if it isn't working.

**Comment by tribzi** [comment]
Thank you! @mfherman's github install command worked for me and all the PUMS functions look to be working.
