### ISSUE TITLE
get_pums recode into factors not character 

### ISSUE THREAD

**Issue by szimmer** [walkerke/tidycensus#273]
It would be convenient if when recoding, the recoded variable is an ordered factor. This would be very beneficial when making plots. Examples include the variable SCHL (educational attainment). By default, if plotting something by level of education with the recoded variable, it will be alphabetical. If an ordered factor was used instead, this would be much more convenient and plot in a logical order. This is more a feature request than an issue.

**Comment by mfherman** [comment]
That is a great idea, @szimmer! I wonder though if we would have to manually select which variables it makes sense to make into a ordered factor. SCHL makes perfect sense, but what about something like COW (class of worker) where the levels can't be ordered meaningfully?

**Comment by szimmer** [comment]
With something like COW, the levels would match the order of most publications which is a nice benefit.

**Comment by szimmer** [comment]
I've started working on this here: https://github.com/szimmer/tidycensus/tree/recode_orderedfactors

**Comment by walkerke** [comment]
This is implemented as of tidycensus 0.10.2.
