### ISSUE TITLE
Number of Congressional Districts

### ISSUE THREAD

**Issue by arilamstein** [walkerke/tidycensus#277]
I am a bit confused by the output of calling `get_acs` for the geography "congressional district".

```
df = tidycensus::get_acs("congressional district", table="B03002", output="wide", cache_table=TRUE)
nrow(df) # 440
```

According to [wikipedia](https://en.wikipedia.org/wiki/List_of_United_States_congressional_districts) there are 435 voting members of the House. So I would understand if this returned 435. But there's more. I assume that these are non-voting representatives, which Wikipedia describes like this:

> In addition, each of the five inhabited U.S. territories and the federal district of Washington, D.C. sends a non-voting delegate to the House of Representatives.

That reads like there should be 441 (the 435 voting members + each of the 5 inhabited terrorites + 1 for DC).

Also, Wikipedia has a whole section on non-voting members that is a bit confusing, since it includes everyone historic ever there, including non-seated, non-voted representatives.

Is there a way to have this call just return districts for the voting members? If not, can you please recommend a way to trunc this dataframe so that it only includes voting members? 

I'm currently doing an analysis and I just discovered that different dataframes have a different number of rows, which is confusing. What is even more confusing is that both of those dataframes can be "correct", since there are different "types" of members.

I think it makes sense for me to limit my analysis to just voting members, so if I could trunk this dataframe to that it would be great.

**Comment by szimmer** [comment]
This was a bit strange. Here's what I found - there are 3 "not defined" districts plus Puerto Rico and DC which totals 440.


``` r
library(tidyverse)
library(tidycensus)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1


df <- get_acs("congressional district", table="B03002", output="wide",
              cache_table=TRUE)
#> Getting data from the 2014-2018 5-year ACS
#> Loading ACS5 variables for 2018 from table B03002 and caching the dataset for faster future access.

df_adj <- df %>%
  separate(NAME, into=c("District", "State"), sep=",", remove=FALSE)

nrow(df_adj)
#> [1] 440

# three districts are undefined, not sure what this means
df_adj %>%
  filter(B03002_001E ==0) %>%
  select(GEOID, NAME)
#> # A tibble: 3 x 2
#>   GEOID NAME                                                             
#>   <chr> <chr>                                                            
#> 1 09ZZ  Congressional Districts not defined (116th Congress), Connecticut
#> 2 17ZZ  Congressional Districts not defined (116th Congress), Illinois   
#> 3 26ZZ  Congressional Districts not defined (116th Congress), Michigan

# 2 are non-voting (DC and PR)
df_adj %>%
  filter(str_sub(GEOID,1,2) %in% c("72", "11")) %>%
  select(GEOID, NAME)
#> # A tibble: 2 x 2
#>   GEOID NAME                                                                   
#>   <chr> <chr>                                                                  
#> 1 1198  Delegate District (at Large) (116th Congress), District of Columbia    
#> 2 7298  Resident Commissioner District (at Large) (116th Congress), Puerto Rico

# 2 + 3 + 435 = 440
```

<sup>Created on 2020-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by arilamstein** [comment]
Thanks so much @szimmer . I am trying to cache some Congressional District data into Choroplethr. In that package I adopted a convention of only including States + DC. Because of that it likely makes sense to remove PR from this dataset. 

However, that still leaves those "not defined" districts in 3 states. I don't know what they mean, but at least it gives me a place to start looking.

**Comment by arilamstein** [comment]
I'll include this for the sake of completeness:

```
# This returns 6, but Connecticut only have 5 reps: https://en.wikipedia.org/wiki/Connecticut's_congressional_districts#Historical_and_present_district_boundaries
filter(df_adj, State==" Connecticut") 

# This returns 19, but Illinois only has 18 reps 
# https://en.wikipedia.org/wiki/Illinois%27s_congressional_districts
filter(df_adj, State==" Illinois") 

# this returns 15, but Michigan only haS 14 reps: 
# https://en.wikipedia.org/wiki/Michigan%27s_congressional_districts
filter(df_adj, State==" Michigan") 
```

@loganpowell, can you comment on why the API is returning Congressional Districts with a District Number of `ZZ`?

I feel like `tidycensus` needs to make a decision here. It could just return whatever the API returns (which it's doing now), but then it should probably document this in the function help, or emit a warning. As @szimmer pointed out, currently these rows are getting 0, which feels dangerous, because R will use that value if you e.g. call `mean` on a column.

The alternatives I see are to encode all values in these rows as NA, or simply remove all districts with code `ZZ`.

**Comment by loganpowell** [comment]
I'm not a data SME, but here's what I found:

https://www.census.gov/geographies/mapping-files/2019/dec/rdo/116-congressional-district-bef.html

*In Connecticut, Illinois, and Michigan the state participant did not assign the congressional districts to cover all of the state or equivalent area. The code “ZZ” has been assigned to areas with no congressional district defined (usually large water bodies). These unassigned areas are treated within state as a single congressional district for purposes of data presentation.*

**Comment by arilamstein** [comment]
@walkerke I just wrote a function that filters out Congressional Districts that have a district code of 98 (non-voting member) or ZZ (undefined district). It also throws an error if it returns more than 435 unique regions. I am planning to call it on all the data I get from `get_acs` for Congressional Districts. I would be happy to contribute it (or something similar) to tidycensus as well. I think it's a fair assumption that people who want these stats are primarily interested in stats limited to voting members.

```r
#' Remove non-voting Congressional Districts from a data.frame
#'
#' The data.frame must have a column named region with a 4-character Congressional District code.
#' Remove districts that have a district code of 98 (non-voting) or ZZ (undefined district). See 
#' https://www.census.gov/geographies/mapping-files/2019/dec/rdo/116-congressional-district-bef.html
#' At the time this function was created, tidycensus returned 5 non-voting districts. See 
#' https://github.com/walkerke/tidycensus/issues/277
#' @param df A data.frame. Must have a column named region that contains character vectors of length 4. The first 2 characters should be a state FIPS code and the second 2 characters should be a Congressional District Number
#' @importFrom dplyr filter
#' @export
filter_to_voting_congressional_districts = function(df)
{
  stopifnot("region" %in% colnames(df))
  stopifnot(is.character(df$region))
  stopifnot(all(nchar(df$region) == 4))
  
  invalid_district_numbers = c("98", "ZZ")
  df = dplyr::filter(df, !(substr(region, 3, 4) %in% invalid_district_numbers))
  
  # there are exactly 435 voting members of the house of representatives, 
  # so we should never return more than that many values
  # https://en.wikipedia.org/wiki/List_of_United_States_congressional_districts
  stopifnot(length(unique(df$region)) <= 435)
  
  df
}
```

**Comment by walkerke** [comment]
Thanks all for the discussion!  I'd take a look at a PR that adds this as an option to `get_acs()`.  I'm a bit hesitant about getting too opinionated about what tidycensus returns from the API by default; for example `geography = "tract"` returns data for water-only Census tracts as well (see the discussion here: https://github.com/walkerke/tidycensus/issues/68).

**Comment by arilamstein** [comment]
> Thanks all for the discussion! I'd take a look at a PR that adds this as an option to `get_acs()`. I'm a bit hesitant about getting too opinionated about what tidycensus returns from the API by default; for example `geography = "tract"` returns data for water-only Census tracts as well (see the discussion here: #68).

Got it. I'm working with a client right now, but afterwards I will look into making a PR for this. I just added the filter code to the latest version of Choroplethr. 

I understand your concern about when to simply return what Census gives you vs. when to "editoralize". I faced the same thing with Choroplethr's Census maps. Ultimately I felt I had to remove the Aleutian Islands that crossed the Antimeridian because they completely threw off the map. Removing PR felt more controversial, but I did it since I thought most people would want that.

In this case, I think that removing the `ZZ` districts feels like a safe choice. Most people simply don't know that they exist. 

Removing the DC and PR districts is a bit dicier. But again, these are political districts, and those members have no political power, so I would still lean towards removing them by default. If for no other reason that, again, I think most people looking at this geography probably care exclusively about Voting Members.

**Comment by mfherman** [comment]
I tend to agree with @walkerke here. Even though those Congressional Districts may be confusing, my sense is that most users would expect tidycensus to return everything from an API call. It also opens up a potential package maintenance challenge if and when Census geographies change.
