### ISSUE TITLE
"nation" geography?

### ISSUE THREAD

**Issue by arilamstein** [walkerke/tidycensus#278]
I am having trouble getting a nation-wide statistic and am not sure why. The following all works:

```{r}
get_acs(geography = "state", table="B19049")
get_acs(geography = "county", table="B19049")
get_acs(geography = "zcta", table="B19049")
```

The `geography` param in the help for `?get_acs` does not list valid geographies. I tried "nation" but it failed:

```{r}
get_acs(geography = "nation", table="B19049")
Getting data from the 2014-2018 5-year ACS
Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.
```

However, that data seems to be available on data.census.gov: https://data.census.gov/cedsci/all?q=B19049&hidePreview=false&tid=ACSDT1Y2018.B19049

I am not sure if the API doesn't support nation-wide statistics, or if this is a limitation of `tidycensus`. Can someone please advise? I also looked through the code for `get_acs` but could not get any hints. Thanks.

**Comment by walkerke** [comment]
Hi @arilamstein!  You'll want `geography = "us"`: 

```r
> library(tidycensus)
> get_acs(geography = "us", table="B19049")
Getting data from the 2014-2018 5-year ACS
# A tibble: 5 x 5
  GEOID NAME          variable   estimate   moe
  <chr> <chr>         <chr>         <dbl> <dbl>
1 1     United States B19049_001    60293   140
2 1     United States B19049_002    31189    95
3 1     United States B19049_003    65893   277
4 1     United States B19049_004    72912   246
5 1     United States B19049_005    43680    60
``` 

For reference, all of the supported geographies are viewable at https://walker-data.com/tidycensus/articles/basic-usage.html#geography-in-tidycensus.

**Comment by arilamstein** [comment]
Thank you for the speedy reply Kyle!

Is there anywhere that lists all the valid geographies? If not, do you
think it would be helpful to add that to the documentation under `@param
geography`?

So instead of:

geography

The geography of your data.

It might read:

geography

The geography of your data. Must be one of "us", "state", "county", "zcta",
etc.

**Comment by walkerke** [comment]
Yes, I've got them all here: https://walker-data.com/tidycensus/articles/basic-usage.html#geography-in-tidycensus.  Perhaps we could add that as a link in the package docs.
