### ISSUE TITLE
Madison county New York block group GEOIDs do not match

### ISSUE THREAD

**Issue by dthill196** [walkerke/tidycensus#279]
I have a function for processing data through tidycensus looking at NY state. The function has worked fine until I got to Madison county.The function downloads 2010 and 2018 data at the block group level, summarizes the data, and then merges the data together to the geometry.

When I do this, I end up with 30 block groups that do not match between 2010 and 2018. They appear to have different GEOIDs. Each data frame (2010 and 2018) has 47 block groups, but they appear to have different sets of GEOIDs.

This is the function that produces the block group data object.

    censusGeo_BG <- block_groups("New York", county = county_sewer, cb = TRUE)

    county_sewer <- "Madison"

    datagrab_BG_function <- function(x){
  
      dataGrab_2010 <- get_decennial(geography = "block group",
                                 state = "NY",
                                 county = county_sewer,
                                 year = 2010,
                                 variables = c(population_BG_2010 = "H010001",
                                               group_quartersPop = "P029026",
                                               group_quartersNursing = "P042005"
                                 ),
                                 moe_level = 95)
  
      #no margin of error for decennial census
      wwCensus_2010 <- dataGrab_2010 %>% 
    spread(variable, value) %>% 
    distinct()
  
  
      dataGrab_2018 <- get_acs(geography = "block group",
                           state = "NY",
                           county = county_sewer,
                           variables = c(population_BG_2018 = "B01001_001",
                                         housing_units = "B25001_001",
                                         vacant_units = "B25002_003",
                                         owner_occupied = "B25002_002",
                                         Male_age_65_66 = "B01001_020",
                                         Male_age_67_69 = "B01001_021",
                                         Male_age_70_74 = "B01001_022",
                                         Male_age_75_79 = "B01001_023",
                                         Male_age_80_84 = "B01001_024",
                                         Male_age_85_plus = "B01001_025",
                                         F_age_65_66 = "B01001_044",
                                         F_age_67_69 = "B01001_045",
                                         F_age_70_74 = "B01001_046",
                                         F_age_75_79 = "B01001_047",
                                         F_age_80_84 = "B01001_048",
                                         F_age_85_plus = "B01001_049",
                                         black_alone = "B02001_003",
                                         Amer_indian = "B02001_004",
                                         Asian = "B02001_005",
                                         Pacific_islander = "B02001_006",
                                         Other_race = "B02001_007",
                                         Two_or_more_races = "B02001_008",
                                         hispanic_pop = "B03003_003",
                                         median_house_value = "B25077_001",
                                         Total_Education = "B15003_001",
                                         overHS1 = "B15003_017",
                                         overHS2 = "B15003_018",
                                         overHS3 = "B15003_019",
                                         overHS4 = "B15003_020",
                                         overHS5 = "B15003_021",
                                         overHS6 = "B15003_022",
                                         overHS7 = "B15003_023",
                                         overHS8 = "B15003_024",
                                         overHS9 = "B15003_025"
                           ),
                           year = 2018)
  
      wwCensus_2018 <- dataGrab_2018 %>% 
    dplyr::select(-moe) %>% 
    spread(variable, estimate) %>% 
    distinct()
  
  
      wwCensus_2018 <- wwCensus_2018 %>% 
    mutate(
      Over64_Per = (Male_age_65_66 + Male_age_67_69 +Male_age_70_74 +
                      Male_age_75_79 + Male_age_80_84 + Male_age_85_plus +
                      F_age_65_66 + F_age_67_69 + F_age_70_74 +
                      F_age_75_79 + F_age_80_84 + F_age_85_plus),
      Nonwhite_Pop = (black_alone + Amer_indian + Asian + Pacific_islander + Other_race + Two_or_more_races),
      Under_HS_tot = (overHS1 + overHS2 + overHS3 + overHS4 + overHS5 + overHS6 +
                        overHS7 + overHS8 +overHS9))
  
  
      wwCensus_2018 <- wwCensus_2018 %>% 
        dplyr::select(GEOID, population_BG_2018, owner_occupied, Over64_Per, housing_units, vacant_units, black_alone, 
        hispanic_pop, Nonwhite_Pop, Total_Education, Under_HS_tot)
      wwCensus <- left_join(wwCensus_2010, wwCensus_2018, by = "GEOID")
      #ratio which can be multiplied by 2010 value to determine the increase or decrease in population
  
      #
      #merge to shapefile loaded earlier
      wwCensusGeo_change <- merge(censusGeo_BG, wwCensus, by = "GEOID")
  
    }

I have tried using census tracts but there appears to be the same problem. Any other county I have tried (Cayuga, Saratoga, Onondaga) all work fine.

The issue appears to be with the 2018 data.

**Comment by mfherman** [comment]
Looks like the numbering of Madison Country tracts and block groups changed in 2011. It doesn't look like the boundaries changed at all, so you should just be able to rename/crosswalk these changed block groups.

> Census Tract and Block Group changes in New York State
For the 2011 ACS data release, there are tract numbering corrections and minor geographic definition changes to census tracts in Madison, Oneida and Richmond counties, New York. The census tract changes in Madison and Oneida Counties are the result of corrections to the Oneida American Indian Reservation boundary after the 2010 Census tract definitions had been finalized. The change to the census tracts in Richmond County corrects a tract boundary definition error.
>
> Madison County, New York
In Madison County, the numbering of nine census tracts changed, but their geographic definitions remain the same as their 2010 census tract definitions.
Census Tract 9401.01 is now 0301.01
Census Tract 9401.02 is now 0301.02
Census Tract 9401.03 is now 0301.03
Census Tract 9402.00 is now 0302.00
Census Tract 9403.00 is now 0303.00
Census Tract 9404.01 is now 0304.01
Census Tract 9404.03 is now 0304.03
Census Tract 9406.00 is now 0306.00
Census Tract 9407.00 is now 0304.02

https://www.census.gov/programs-surveys/acs/technical-documentation/table-and-geography-changes/2011/geography-changes.html

**Comment by dthill196** [comment]
Sincere thanks; I was unable to find this change myself so I really appreciate it!

**Comment by mfherman** [comment]
Glad to help....it took me a while to find :)
