### ISSUE TITLE
Download one-year estimates

### ISSUE THREAD

**Issue by elmerleeZ** [walkerke/tidycensus#28]
Hi Kyle, I am wondering if tidycensus could be used to download one-year estimates from Census. That would be really helpful. Thank you! - Elmer

**Comment by walkerke** [comment]
Thanks to @keberwein __tidycensus__ can already do this.  For example, for median household income by place from the 2016 1-year ACS, use the `survey` parameter:

```r
income <- get_acs(geography = "place", variables = "B19013_001", survey = "acs1", endyear = 2016)
```

**Comment by optimific** [comment]
Are 1-year estimates from 2011-2014 supported? The ACS 1-year endpoint changed from "acs1" to "acs/acs1" in 2015.

**Comment by walkerke** [comment]
not at the moment; but it'll be a quick fix.

**Comment by walkerke** [comment]
Fixed now in https://github.com/walkerke/tidycensus/commit/14d0356d07408e7c1b89303b436c42cdf43ae5bd.

**Comment by elmerleeZ** [comment]
Hi Professor Walker, I've tried your code to download one year acs data, and it worked perfectly for year 2012-2016. But for year 2011, e.g. with the code: 
`income <- get_acs(geography = "place", variables = "B19013_001", survey = "acs1", endyear = 2011)` 
R returns the error: `Error: Column dataset must be a 1d atomic vector or a list`

And for year 2010, e.g. with the code`income <- get_acs(geography = "place", variables = "B19013_001", survey = "acs1", endyear = 2010)`, 
R returns the error: `Error: lexical error: invalid char in json text.
                                       <html><head><title>Error report
                     (right here) ------^` 

Do you know what's the reason for this problem?

**Comment by walkerke** [comment]
2011 data is only available for congressional districts and tidycensus is not configured to work with its unique format: https://www.census.gov/data/developers/data-sets/acs-1year.2011.html.  If this is something you need, the censusapi package can do it if you configure the call correctly.
