### ISSUE TITLE
Allow for variable filters/subsets in get_pums()

### ISSUE THREAD

**Issue by mfherman** [walkerke/tidycensus#284]
Just leaving this here to think about implementing. As per [this thread](https://twitter.com/gebeloffnyt/status/1296091076554633216), the PUMS API allows for filters in the API call to return a subset of the data. For example, this call only returns unemployed men between the age of 25 and 50 in Vermont:

```
https://api.census.gov/data/2018/acs/acs1/pums?get=PWGTP&AGEP=25:50&SEX=1&ESR=3&ucgid=0400000US50
```

This could be very useful to cut down on the size of the data returned, especially when pulling data for multiple states and/or the entire US.

**Comment by szimmer** [comment]
This is very useful! It hopefully can also be used to just get data for a set of PUMAs and not entire states.

**Comment by mfherman** [comment]
Thanks for the input! Selecting PUMAs is possible via the API, so it definitely could be implemented in get_acs()

```
https://api.census.gov/data/2018/acs/acs1/pums?get=PWGTP&AGEP=25:50&SEX=1&ESR=3&ucgid=7950000US5000100,7950000US5000200
```

**Comment by walkerke** [comment]
Oh interesting about the PUMAs @mfherman!  That could work similarly to the `county` argument in `get_acs()` where a user could specify a state and a vector of PUMAs and we could assemble the `ucgid` query parameter internally before sending to the API.  That should be straightforward.  

For the data subsets: I'll have to give some thought about how to do this but it'll be great to add it.

**Comment by mfherman** [comment]
The only place where the PUMA selection could be tricky is if you wanted to get PUMAs from more than one state in a single `get_pums()` call. I can imagine this might be useful if you want PUMAs in a metro area that covers multiple states. In that case, maybe you could supply a named vector of state/PUMA pairs?

**Comment by walkerke** [comment]
I've got an implementation of this going in https://github.com/walkerke/tidycensus/pull/345.  Users can specify a named list of variables along with their desired filters.  For example, let's say you want to return people who changed residences in the past year in Utah between the ages of 16 and 64: 

```r
library(tidycensus)

filtered_pums <- get_pums(
  variables = "PUMA",
  state = "UT",
  variables_filter = list(
    AGEP = 16:64,
    MIG = 3
  ),
  recode = TRUE,
)
```

```
> filtered_pums
# A tibble: 16,658 x 10
   SERIALNO   SPORDER  WGTP PWGTP  AGEP PUMA  ST    MIG   ST_label MIG_label        
   <chr>        <dbl> <dbl> <dbl> <dbl> <chr> <chr> <chr> <ord>    <ord>            
 1 201500000…       1     0     6    22 49003 49    3     Utah/UT  No, different ho…
 2 201500000…       1    29    29    40 21001 49    3     Utah/UT  No, different ho…
 3 201500001…       1     0     4    36 35004 49    3     Utah/UT  No, different ho…
 4 201500001…       1     0     5    19 35002 49    3     Utah/UT  No, different ho…
 5 201500001…       1    21    21    40 21001 49    3     Utah/UT  No, different ho…
 6 201500001…       2    21    23    57 21001 49    3     Utah/UT  No, different ho…
 7 201500001…       1     7     7    52 57002 49    3     Utah/UT  No, different ho…
 8 201500001…       2     7     8    26 57002 49    3     Utah/UT  No, different ho…
 9 201500002…       1    12    12    34 53001 49    3     Utah/UT  No, different ho…
10 201500002…       2    12    15    32 53001 49    3     Utah/UT  No, different ho…
# … with 16,648 more rows
```

I still have a couple things to smooth out - but @mfherman, @szimmer let me know if you have any thoughts about this implementation.

**Comment by walkerke** [comment]
Merged the PR, so I'm closing this issue.  This thread represents massive usage improvement for microdata generally speaking, so I'm very excited about it.  I'm already using it in multiple projects!
