### ISSUE TITLE
Issues with `SEMP`

### ISSUE THREAD

**Issue by arilamstein** [walkerke/tidycensus#286]
The [2018 1 year ACS PUMS Data Dictionary](https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2018.pdf) describes `SEMP` like this:

```
Self-employment income past 12 months (signed, use ADJINC to adjust SEMP to constant dollars)
bbbbbb       .N/A (less than 15 years old)
0            .None
-10000..-4 .Loss of $4 to $10000 (Rounded and bottom-coded)
4..999999  .$4 to $999999 (Rounded and top-coded)
```

I have two issues when I try to use this data in TidyCensus:
```{r}
df = get_pums("SEMP",
             state = "utah", 
             year = 2018, 
             survey = "acs1",
             recode = TRUE)

class(df$SEMP)
[1] "numeric"
any(is.na(df$SEMP))
[1] FALSE
```
It is unclear to me if the API is returning any values as `bbbbbb` here. I would assume so. If so, is TidyCensus encoding them as 0 or NA? If TidyCensus is encoding them as 0 then it becomes difficult to e.g. calculate the percentage of people who are reporting any Self Employed Income, because children are being encoded as 0, as opposed to NA.

The second issue is that the Data Dictionary says that -10k is the bottom-coded value. But the actual minimum value in the dataset is -10,001.

```{r}
> summary(df$SEMP)
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-10001.0      0.0      0.0   -909.1      0.0 319000.0 
```

I don't have a lot of experience with PUMS data. But since they explicitly say that -10,000 is the bottom-coded value, I expected that to the lowest value returned. Can someone here please explain why the lowest value returned is actually -10,001?

Thanks.

**Comment by arilamstein** [comment]
Here is the response I just got from Census:

> Thank you for contacting the U.S. Census Bureau with your inquiry.  
  
 > The API is set up this way by design. Any values that would have been blank in the main files are indicated by a special negative value in the API. When the ACS PUMS API are added to the [discovery tool](https://api.census.gov/data.html), you will be able to see this documented by clicking on the variable. In the meantime, you can confirm the values by exploring the variable in MDAT.  
  
> * Visit data.census.gov/mdat
> * Select your vintage (e.g. **American Community Survey 1-year estimates public use microdata sample; 2018**)
> * Click **Next** in the lower right
> * Search the variable name: **SEMP**
> * Click **Details**
> * View the descriptions and value for N/A

> You can repeat this process for other variables of interest

 > Thank you for contacting us with your feedback.

> Best regards,

**Comment by mfherman** [comment]
Thanks for posting this, @arilamstein. Because the PUMS API is so new and still not documented, I think we should wait until the official documentation comes out and see what the best approach is. My concern about manually identifying the variables that need to be recoded into NA values is that it may require a lot of maintenance as different vintages of PUMS data may have different output formats from the API.

**Comment by walkerke** [comment]
I agree @mfherman - dealing with this too much on a case-by-case could generate more work for us in the future.  Closing this for now and we can re-visit once the API is documented.
