### ISSUE TITLE
1990 & 2000 decennial API endpoint update

### ISSUE THREAD

**Issue by Daniel-Kuhlmann** [walkerke/tidycensus#293]
I'm sure this is something you're already aware of, but do you know when the get_decennial() command will be updated with the new API endpoints? I'm using 0.9.9.5 and neither 1990 nor 2000 calls are working.

**Comment by mfherman** [comment]
Hi @Daniel-Kuhlmann! If you install the GitHub version of tidycensus (`remotes::install_girthub("walkerke/tidycensus"`), you'll be able to access 2000 SF1 data from the new endpoint. As soon as the Census migrates 2000 SF3 and 1990 SF1 and SF to the new endpoint, they should start working with `get_decennial()`.

**Comment by walkerke** [comment]
@mfherman Given that there is no timeline (as far as I know) for 1990 & and 2000 SF3 on the new endpoint, I'm thinking about adding an informative error message, bumping tidycensus to version 0.10 (instead of 1.0) once I merge the open PRs, and waiting on 1.0 until all is "working again" on the Census side of things.

**Comment by mfherman** [comment]
That sounds reasonable. Frustrating that there is no ETA from the Census Bureau on this! It also may be helpful to pin this issue so that others running in to the same problem (like #295) will see the issue.

**Comment by walkerke** [comment]
Summary File 3 is now available again for 2000 and we are supporting it again in tidycensus.  Still no update on 1990.  You can grab the GitHub version to work with it today; I'm planning a CRAN submission tomorrow.

**Comment by walkerke** [comment]
As far as I know, the 1990 endpoint is not coming back.  Closing this issue.
