### ISSUE TITLE
Cannot download block group data from ACS

### ISSUE THREAD

**Issue by xiaofanliang** [walkerke/tidycensus#294]
I am trying to download ACS data for a particular county on the block group level. 

When I run the following:
```
block = get_acs(geography = 'block group', variables='B19013_001', state = 'GA', county = 'Chatham', geometry = TRUE)
```
The error message outputs:
```
Getting data from the 2013-2017 5-year ACS
Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
Using FIPS code '13' for state 'GA'
Using FIPS code '051' for 'Chatham County'
Error: Cannot open "/private/var/folders/8s/tbnzsm_95577r9z6n2vqpjfr0000gn/T/Rtmpbofi9D"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
```

I tried with a different county in a different state, and the same error message persists 
```
block = get_acs(geography = 'block group', variables='B19013_001', state = 'CA',  county = 'San Francisco', geometry = TRUE)
```

Any idea what is causing the issue? It seems like the endpoint to open the data is not finding its way to data? 

Thanks!

**Comment by walkerke** [comment]
Hi @xiaofanliang - occasionally this error comes up when tidycensus cannot download shapefiles from the Census Bureau website.  The solution is almost always "try again later."  I've tested both of your examples and they are working for me.  Also - I notice that your default year is 2017 which means you are running an older version of the package; I'd recommend updating.

**Comment by xiaofanliang** [comment]
Updated the package solved the problem! Thanks!
