### ISSUE TITLE
Error while running the decennial function for 1990

### ISSUE THREAD

**Issue by samantaraymadhu6** [walkerke/tidycensus#299]
Hi,
I want to run the below code including the year 1990. Is there anyway we can add as the table name is P0010001 in 1990.
Though I am aware of the issue with decennial endpoint not working, just checking if there is any other way.

kenton_pop90_10 <- map_df(c(2000, 2010), function(x) {
get_decennial(
geography = "county",
variables = c(totalpop = "P001001"),
dataset = "sf1",
state = "KY",
county = "kenton",
year = x
) %>%
mutate(year = x)
})

Can anyone please help..

**Comment by mfherman** [comment]
Right now, you can't get any 1990 data from the API. Another source of decennial data is [NHGIS](https://www.nhgis.org/user-resources/data-availability#table-data).
