### ISSUE TITLE
Feature Request: Download by Table

### ISSUE THREAD

**Issue by leehach** [walkerke/tidycensus#30]
I would like to request specifying a table (e.g. `"B25036"`) and getting all the variables associated with that table, instead of having to specify each variable.

At the moment I'm building them with something like:

```
library(stringr)
housing_vars = paste("B25036", str_pad(1:21, 3, pad = "0"), sep = "_")
x = get_acs("state", housing_vars, ...)
```

**Comment by walkerke** [comment]
I’ve been mulling this over for a little while.  I’ll put this on the agenda before the package’s next CRAN release.

**Comment by walkerke** [comment]
FYI - I'm working on this now in https://github.com/walkerke/tidycensus/tree/tables.  You can keep an eye on that for updates.

**Comment by walkerke** [comment]
This is now implemented in the development version for ACS detailed tables.  I'll add this functionality for the decennial Census as well then send to CRAN.

**Comment by walkerke** [comment]
Request by table name now works for decennial Census tables as well.  I have a little more cleaning up to do then the updates are off to CRAN.
