### ISSUE TITLE
CRAN update

### ISSUE THREAD

**Issue by mountainMath** [walkerke/tidycensus#301]
I get errors in the following call using the current CRAN version, which triggers Travis check errors for me downstream in the {tongfen} package.
```
get_decennial(geography="tract", state="CA", variables = "H011001", year = 2000, output="wide")
```
The current dev version works fine though. Not a big deal at this point, just wondering when the next update will land on CRAN?

**Comment by walkerke** [comment]
Hopefully soon - I was planning for today but I'm chasing down a bug at the moment before I submit.  I'll update you here!

**Comment by mountainMath** [comment]
Great, thanks! No rush.

**Comment by walkerke** [comment]
The new version is on CRAN now!

**Comment by walkerke** [comment]
Credit to the CRAN team - the new version is up there as of this morning!
