### ISSUE TITLE
Problems with load variables command in tidycensus

### ISSUE THREAD

**Issue by PeterBN-VT** [walkerke/tidycensus#304]
I am getting the following error when trying to load variables from the 2000 decennial census 
Error in open.connection(x, "rb") : HTTP error 404.

Here is the code I am running:

varlist00<-load_variables(2000, "sf1", cache=TRUE)

The code works for 2010, but is not working for 2000.

**Comment by walkerke** [comment]
This is fixed as of version 0.10.2, which is now on CRAN - so re-install and you should be set.  However, as a heads up: the Census Bureau has removed the 2000 SF3 API so that won't work any longer.
