### ISSUE TITLE
get_decennial breaks when passing in 49 or more variable names?

### ISSUE THREAD

**Issue by buchmayne** [walkerke/tidycensus#305]
I think I came across some rather strange behavior. I have included my session info and hopefully a reproducible example below. Basically when I pass a vector of 49 or more variable names to get_decennial it breaks, returning an error explaining that the implicit left_join failed.

I maintain some code that is effectively a wrapper around tidycensus to automate pulling data for a specific report. This issue came up after upgrading tidycensus (from 0.9.9 I believe) to 0.10.2. Any thoughts? I tried to find the relevant join occurring in the source code but couldn't easily spot it. One thing I noticed is that when I run the get_decennial function with 49 or more variables there are two census API print statements rather than one. 

Thanks again for all your collective work on developing and maintaining such an awesome package. If this issue requires lots of work or refactoring I am also happy to volunteer if that would be helpful. 

Best, 

```
library(tidycensus)
sessionInfo()
```

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidycensus_0.10.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         pillar_1.4.6       compiler_4.0.2     class_7.3-17       tools_4.0.2        uuid_0.1-4         jsonlite_1.7.1     lifecycle_0.2.0   
 [9] tibble_3.0.3       lattice_0.20-41    pkgconfig_2.0.3    rlang_0.4.7        DBI_1.1.0          rstudioapi_0.11    rgdal_1.5-16       e1071_1.7-3       
[17] dplyr_1.0.2        httr_1.4.2         stringr_1.4.0      xml2_1.3.2         hms_0.5.3          generics_0.0.2     vctrs_0.3.4        rappdirs_0.3.1    
[25] tigris_1.0         classInt_0.4-3     grid_4.0.2         tidyselect_1.1.0   glue_1.4.2         sf_0.9-6           R6_2.4.1           foreign_0.8-80    
[33] sp_1.4-2           purrr_0.3.4        tidyr_1.1.2        readr_1.3.1        magrittr_1.5       ellipsis_0.3.1     units_0.6-7        maptools_1.0-2    
[41] rvest_0.3.6        KernSmooth_2.23-17 stringi_1.5.3      crayon_1.3.4      

```
# A vector of variable names from the 2010 SF1 Census
example_sf1_2010_vars <- c(
  "H017001", "H017002", "H017003", "H017004", "H017005", "H017006", "H017007", 
  "H017008", "H017009", "H017010", "H017011", "H017012", "H017013", "H017014",
  "H017015", "H017016", "H017017", "H017018", "H017019", "H017020", "H017021", 
  "H017A001", "H017A002", "H017A003", "H017A004", "H017A005", "H017A006", 
  "H017A007", "H017A008", "H017A009", "H017A010", "H017A011", "H017A012",
  "H017A013", "H017A014", "H017A015", "H017A016", "H017A017", "H017A018",
  "H017A019", "H017A020", "H017A021", "H017B001", "H017B002", "H017B003",
  "H017B004", "H017B005", "H017B006", "H017B007", "H017B008", "H017B009",
  "H017B010", "H017B011", "H017B012", "H017B013", "H017B014", "H017B015",
  "H017B016", "H017B017", "H017B018", "H017B019", "H017B020", "H017B021", 
  "H017C001", "H017C002", "H017C003", "H017C004", "H017C005", "H017C006",
  "H017C007", "H017C008", "H017C009", "H017C010", "H017C011", "H017C012",
  "H017C013", "H017C014", "H017C015", "H017C016", "H017C017", "H017C018", 
  "H017C019", "H017C020", "H017C021", "H017D001", "H017D002", "H017D003", 
  "H017D004", "H017D005", "H017D006", "H017D007", "H017D008", "H017D009",
  "H017D010", "H017D011", "H017D012", "H017D013", "H017D014", "H017D015", 
  "H017D016"
)

# passing in the first 48 variable names works
this_works_1 <- get_decennial(
  geography = "place",
  variables = example_sf1_2010_vars[1:48],
  year = 2010,
  state = "OR"
  )
```
Getting data from the 2010 decennial Census
Using FIPS code '41' for state 'OR'
```
# passing in the first 49 variable names doesn't work
this_doesnt_work_1 <- get_decennial(
  geography = "place",
  variables = example_sf1_2010_vars[1:49],
  year = 2010,
  state = "OR"
)
```
Getting data from the 2010 decennial Census
Using FIPS code '41' for state 'OR'
Using FIPS code '41' for state 'OR'
Error in UseMethod("left_join") : 
    no applicable method for 'left_join' applied to an object of class "NULL"
```
# but it isn't the specific variables causing the issue, as this works
but_this_works <- get_decennial(
  geography = "place",
  variables = example_sf1_2010_vars[48:49],
  year = 2010,
  state = "OR"
)

# further more this works as it is length 48
this_works_2 <- get_decennial(
  geography = "place",
  variables = example_sf1_2010_vars[51:98],
  year = 2010,
  state = "OR"
)

# passing in length 49 or more variables doesn't work
this_doesnt_work_2 <- get_decennial(
  geography = "place",
  variables = example_sf1_2010_vars[51:99],
  year = 2010,
  state = "OR"
)
```
Getting data from the 2010 decennial Census
Using FIPS code '41' for state 'OR'
Using FIPS code '41' for state 'OR'
Error in UseMethod("left_join") : 
    no applicable method for 'left_join' applied to an object of class "NULL"

**Comment by walkerke** [comment]
So... when I was putting in some error handling to account for the removal of the 2000 SF3 API, I accidentally commented out a line I shouldn't have and missed it during testing, which triggered this error.  Just pushed an updated version, install from GitHub and you should be good to go!
