### ISSUE TITLE
Problem with loading tidycensus package

### ISSUE THREAD

**Issue by Saidiibrahim** [walkerke/tidycensus#307]
After installing the package using `install.packages("tidycensus")`, when load the package using `library("tidycensus")` I get this error:

Error: package or namespace load failed for ‘tidycensus’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘rgdal’

How can I fix this? Thanks.

**Comment by mfherman** [comment]
Hi @Saidiibrahim, have you tried to install `rgdal` as noted in the error message? You can do this by running:

```
install.package("rgdal")
```
