### ISSUE TITLE
2019 PUMS

### ISSUE THREAD

**Issue by walkerke** [walkerke/tidycensus#311]
@mfherman - the 2019 1-year PUMS data are scheduled to land on data.census.gov (and by consequence the API) on Thursday.  As opposed to the aggregated ACS data which just "works" out of the box in tidycensus, I'll want to keep an eye on this given that the PUMS API is still undocumented.  Plus, there are some references to the year in our code that (correctly) hard-code the year so we'll want to adjust that after some testing.  Once we get this cleaned up I'm going to send a new version to CRAN.

**Comment by mfherman** [comment]
Absolutely! Earlier today (after I saw the slack post) I was looking into this. I have a PR ready to go that adds 2019 data dictionary to `pums_variables`and I think takes care of the hard coding. 

I’ll push it later tonight and we can both do some testing after the data is available later this week.

**Comment by walkerke** [comment]
Did some testing this morning, all looks to be working!  I'll run through a couple more examples and then send up to CRAN by the end of the week.

**Comment by mfherman** [comment]
Nice -- I'm glad it's working! I did notice a little bug in the recoding of 5 year 2014-2018 data that has to do with leading zeros being dropped from that year/survey data dictionary in pums_variables. I make a PR with an update to the data dictionary that would be good to include before you send to CRAN.

**Comment by walkerke** [comment]
perfect, thanks!
