### ISSUE TITLE
Add wildcards to get all block or block group data in a state in get_decennial()

### ISSUE THREAD

**Issue by mfherman** [walkerke/tidycensus#316]
Reminded by [this question](https://github.com/walkerke/tidycensus/issues/71#issuecomment-721215159), and it appears that block and block group wildcards now work to allow all blocks or block groups in a state:

https://api.census.gov/data/2000/dec/sf1?get=P001001,NAME&for=block:*&in=state:50&in=county:*&in=tract:*
https://api.census.gov/data/2010/dec/sf1?get=P001001,NAME&for=block%20group:*&in=state:50&in=county:*&in=tract:*

So seems like we can remove some of the logic that iterates through the counties and pulls each block group and simplify with inserting these wildcards instead.

**Comment by walkerke** [comment]
I note that Census has added wildcard support for block groups in the 5-year ACS starting with 2013-2017.  I'm going to poke around at this as this would speed things up significantly for state-level block group pulls.
