### ISSUE TITLE
Unable to download ACS 2018 5-yr block group data

### ISSUE THREAD

**Issue by josephholler** [walkerke/tidycensus#320]
I have no issue downloading tract data for Brooklyn as follows:
`bronxTractsDP <- get_acs(state="NY", county="005", geography="tract", variables=c(pop_re="DP05_0070", white="DP05_0077"),
                       year=2018, geometry=TRUE, output="wide", key="1fb2d48d1ae3f73a19d620f258ec9f823ad09b25")`

Changing the geography to block group as follows:
`bronxBlockGroupsDP <- get_acs(state="NY", county="005", geography="block group", variables=c(pop_re="DP05_0070", white="DP05_0077"),
                         year=2018, geometry=TRUE, output="wide", key="1fb2d48d1ae3f73a19d620f258ec9f823ad09b25")`
yields a quick fail with the error:
`Getting data from the 2014-2018 5-year ACS
Using the ACS Data Profile
Using FIPS code '36' for state 'NY'
Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.`

Removing the county (querying for all of New York) as follows:
`NYBlockGroupsDP <- get_acs(state="NY", geography="block group", variables=c(pop_re="DP05_0070", white="DP05_0077"),
                              year=2018, geometry=TRUE, output="wide", key="1fb2d48d1ae3f73a19d620f258ec9f823ad09b25")`

yields this error (including results of `last_error()` and `last_trace()`)
```R
Getting data from the 2014-2018 5-year ACS
Fetching block group data by county and combining the result.
Error: Request failed after 3 attempts
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/purrr_error_rate_excess>
Request failed after 3 attempts
Backtrace:
  1. tidycensus::get_acs(...)
  5. purrr::map(...)
  6. tidycensus:::.f(.x[[i]], ...)
 12. purrr:::insist_get_acs(...)
 13. purrr::rate_sleep(rate, quiet = quiet)
 14. purrr:::stop_rate_excess(rate)
Run rlang::last_trace() to see the full context.
> rlang::last_trace()
<error/purrr_error_rate_excess>
Request failed after 3 attempts
Backtrace:
     x
  1. \-tidycensus::get_acs(...)
  2.   +-`%>%`(...)
  3.   | \-base::eval(lhs, parent, parent)
  4.   |   \-base::eval(lhs, parent, parent)
  5.   \-purrr::map(...)
  6.     \-tidycensus:::.f(.x[[i]], ...)
  7.       +-`%>%`(...)
  8.       | \-base::eval(lhs, parent, parent)
  9.       |   \-base::eval(lhs, parent, parent)
 10.       +-base::suppressMessages(...)
 11.       | \-base::withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
 12.       \-purrr:::insist_get_acs(...)
 13.         \-purrr::rate_sleep(rate, quiet = quiet)
 14.           \-purrr:::stop_rate_excess(rate)
```
Please forgive & correct me if I'm missing something trivial. I've used tidycensus for block group data previously, but cannot get anything to work at that level of the census hierarchy today.

**Comment by walkerke** [comment]
Hi @josephholler - thank you for filing the issue.  The problem is that the Data Profile is not available at the block group level; the lowest you can go is the Census tract.  This means that you'll have to either use tract-level data or construct the block group data in the Data Profile from the Detailed Tables.

**Comment by josephholler** [comment]
Thanks!  In fact it was something trivial.

**Comment by josephholler** [comment]
For anyone stumbling upon this thread because of similar problems: you have a better chance of downloading block group data using variables from the B/C tables, but many variables (including poverty status) may still be unavailable as low as the block group level.

**Comment by EREEEJproject** [comment]
Hi @walkerke - getting the same/similar error for a typical detailed table call for "block group"; whereas "tract", "county" and/or "state" is fine.  The following call results in the `rlang::last_error():` as stated by @josephholler:

`get_acs(geography = "block group", variables = c("B03002_001", "B03002_003"), state =c("NM", "MN", "MI", "NJ", "GA"),  geometry = FALSE)`

**Comment by walkerke** [comment]
@EREEEJproject the issue right now is that we don't have tidycensus configured to pull all block groups for multiple states in a single call.  Fortunately, the workaround isn't that much more code: 

```r
library(tidycensus)
library(tidyverse)

my_data <- map_df(c("NM", "MN", "MI", "NJ", "GA"), ~{
  get_acs(geography = "block group",
          variables = c("B03002_001", "B03002_003"),
          state = .x)
})
```

**Comment by EREEEJproject** [comment]
Thanks @walkerke, appreciate it.  this gets past the previous error, but its producing an empty `.zip`, suggesting block group at census endpoint may be out right now.  Suggest code works fine on `tract` level however.  TY.
