### ISSUE TITLE
Constructing population density variable for all census tracts of USA (excluding AK,HI and PR)

### ISSUE THREAD

**Issue by malhotraaastha** [walkerke/tidycensus#324]
I am trying to construct population density variable at the census tract level for all states of USA, excluding Alaska and Hawaii. I first use the following code to get data for population counts at the census tract level:

us <- unique(fips_codes$state)[1:51]

tract_demography <- map_df(us, function(x) {
  get_acs(geography = "tract", variables = c(median_income = "B19013_001", totpopn = "B01003_001"), 
          state = x, geometry = T, output = "wide")})%>%
  clean_names() %>% 
  na.omit() %>% 
  st_transform(utm_crs) %>%
  separate(name, into=c("TRACT","COUNTY", "STATE"), sep="\\,") %>%
  mutate(STATE = trimws(STATE)) %>%
  filter(! STATE %in% c("Alaska", "Hawaii", "Puerto Rico")) 

After this I use the tigris package to get the land area (in square miles):

tracts <- map_df(us, function(x) {
  tracts(state = x, cb = T, year = 2017, class = "sf")}) %>%
  clean_names() %>% 
  na.omit() %>% 
  st_transform(utm_crs) %>%
  mutate(area = aland / 2589988) %>% # converting meters to square miles
  select(geoid, area)

I wonder how I can join these two datasets "by= geoid" so that I can add the land area to my "tract_demography" dataset, and finally construct population density variable.  I also think that the "geo-id" won't perfectly match in the two datasets that I construct here. Any help would be greatly appreciated.

Thanks!

**Comment by mfherman** [comment]
Hi @malhotraaastha! You're really close, I think. Below is a slightly simplified version of your code that makes the population density calculation for all tracts in Vermont (for speed's sake). You should be able to iterate over a version of this code to do that same for all other states.

The general workflow here is to download the ACS data with no geometries. Download the tract geometries from tigris, which includes the land area of each tract. Join the tract geometries with the ACS data using the `GEOID` column that is shared across both ACS data and tract geometries and calculate the population density. The nice thing about doing it this way is that you end up with an `sf` object of the tract geometries so you can easily map the results.

``` r
library(tidycensus)
library(tigris)
library(tidyverse)
library(sf)
options(tigris_use_cache = TRUE)

# get acs population data
acs_data <- get_acs(
  geography = "tract",
  variables = c(median_income = "B19013_001", totpopn = "B01003_001"),
  state = "VT",
  output = "wide"
  )

# get tract geometries and calculate land area per square mile
tract_geo <- tracts(state = "VT", cb = TRUE) %>%
  st_transform(5070) %>%
  mutate(area = ALAND / 2589988) %>%
  select(GEOID, area)

# join tract geometry with acs data and calculate population density
tract_pop_dens <- tract_geo %>% 
  left_join(acs_data, by = "GEOID") %>% 
  mutate(pop_dens = totpopnE / area)

# map!
tract_pop_dens %>% 
  ggplot(aes(fill = pop_dens)) +
  geom_sf() +
  scale_fill_viridis_c(trans = "log10") +
  theme_void()
```

![](https://i.imgur.com/VENClCP.png)

<sup>Created on 2020-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by walkerke** [comment]
Thanks @mfherman!  @malhotraaastha I'll also alert you to a little-known argument in tidycensus, `keep_geo_vars`, which will return area in square meters by default, simplifying this process: 

```r
library(tidycensus)
library(tidyverse)

wy_tracts <- get_acs(
  geography = "tract",
  variables = "B01003_001",
  state = "WY",
  geometry = TRUE,
  keep_geo_vars = TRUE
) %>%
  mutate(area_sqmi = ALAND / 2589988) %>%
  select(GEOID, area_sqmi)

wy_tracts
```

```
Simple feature collection with 132 features and 2 fields
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: -111.0546 ymin: 40.99475 xmax: -104.0522 ymax: 45.00582
geographic CRS: NAD83
First 10 features:
         GEOID pop_per_sqmi                       geometry
1  56011950200    2.2051332 POLYGON ((-105.0854 44.6206...
2  56013940202   10.8423591 POLYGON ((-108.7948 42.9280...
3  56019955100    0.6231824 POLYGON ((-107.3697 44.5583...
4  56021001200 1985.2733320 POLYGON ((-104.8477 41.1928...
5  56029965300    1.1746579 POLYGON ((-111.0546 45.0009...
6  56033000400 2251.0228364 POLYGON ((-106.9884 44.8134...
7  56033000600    5.4080206 POLYGON ((-107.9115 45.0006...
8  56039967600    1.3865294 POLYGON ((-111.0536 44.6662...
9  56041975300    8.6705181 POLYGON ((-111.0466 41.1560...
10 56001962700   15.4861134 POLYGON ((-105.8344 41.4089...
```

**Comment by mfherman** [comment]
@walkerke Amazing! I guess I need to read the tidycensus docs more carefully 😂

**Comment by walkerke** [comment]
@mfherman :joy: honestly, I don't always remember everything we've put in there... haha

**Comment by malhotraaastha** [comment]
Thank you so much @mfherman and @walkerke! This is extremely helpful.

**Comment by malhotraaastha** [comment]
@mfherman and @kylewalker I would really appreciate your suggestion with
the following problem:

I created a dataset with several variables(including population density)
from the census data using #tidycensus package at the tract level. I am
trying to join this spatial data with another shapefile (not census
related) and I have been facing a lot of problems in doing so. Both data
sets have a geometry column, and I am trying to use st_join to join the two
but that doesn't work.

I am using st_join(data1, data2, largest = TRUE)


To be clear, I am just trying to add another column to my dataset with
census variables from another non-census shapefile. The shape file contains
the regions that are under wind ISO (Independent System Operators )
territories shapefile. Any direction here would be very helpful.

Thanks in advance for your help.

**Comment by mfherman** [comment]
Hi @malhotraaastha. From how you describe your issue, it seems like you don't need to do a spatial join between the census data and your other dataset. I think the easiest way to make this join would be to ensure there is a common column in both the tract data and the other data that identifies the census tract. In the example below I am using GEOID as the unique identifier to join a spatial data frame to a non-spatial data frame with additoinal data.

``` r
library(tidycensus)
library(tidyverse)

wy_tracts <- get_acs(
  geography = "tract",
  variables = "B01003_001",
  state = "WY",
  geometry = TRUE,
  keep_geo_vars = TRUE
  ) %>%
  mutate(area_sqmi = ALAND / 2589988) %>%
  select(GEOID, area_sqmi)
#> Getting data from the 2015-2019 5-year ACS
#> Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
#>   |                                                                              |                                                                      |   0%  |                                                                              |====                                                                  |   6%  |                                                                              |========                                                              |  12%  |                                                                              |=========                                                             |  13%  |                                                                              |================                                                      |  23%  |                                                                              |====================                                                  |  29%  |                                                                              |========================                                              |  35%  |                                                                              |==========================                                            |  38%  |                                                                              |================================                                      |  46%  |                                                                              |====================================                                  |  52%  |                                                                              |=========================================                             |  58%  |                                                                              |===========================================                           |  61%  |                                                                              |=================================================                     |  70%  |                                                                              |=====================================================                 |  75%  |                                                                              |=========================================================             |  81%  |                                                                              |===========================================================           |  84%  |                                                                              |===============================================================       |  90%  |                                                                              |=================================================================     |  93%  |                                                                              |======================================================================| 100%

# i'm just making up some random data here that has a GEOID column
# that matches the GEOIDS of the census tracts
other_data <- data.frame(
  GEOID = wy_tracts$GEOID,
  other_var = runif(length(wy_tracts), 0, 1)
  )

# join tracts (with geometry) to non-spatial data frame using GEOID as key
wy_tracts %>% 
  left_join(other_data, by = "GEOID")
#> Simple feature collection with 132 features and 3 fields
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: -111.0546 ymin: 40.99475 xmax: -104.0522 ymax: 45.00582
#> geographic CRS: NAD83
#> First 10 features:
#>          GEOID    area_sqmi other_var                       geometry
#> 1  56037970602    0.5782919 0.2023363 POLYGON ((-109.464 41.50329...
#> 2  56013000400 1358.0892973 0.6424835 POLYGON ((-110.0532 44.0080...
#> 3  56013000300 4752.6537976 0.0770414 POLYGON ((-109.3258 42.8687...
#> 4  56039967600 3858.5550273 0.2023363 POLYGON ((-111.0536 44.6662...
#> 5  56021000401    5.7967987 0.6424835 POLYGON ((-104.8379 41.0842...
#> 6  56011950200 2008.9489121 0.0770414 POLYGON ((-105.0856 44.5418...
#> 7  56033000500 1561.7117519 0.2023363 POLYGON ((-107.302 44.5706,...
#> 8  56023978000 1508.7548479 0.6424835 POLYGON ((-111.0468 42.5049...
#> 9  56035000102 2385.6307157 0.0770414 POLYGON ((-110.5342 43.2831...
#> 10 56035000101 2500.8510086 0.2023363 POLYGON ((-110.6234 42.7792...
```

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
