### ISSUE TITLE
error with get_decennial() 2010

### ISSUE THREAD

**Issue by mjwebster** [walkerke/tidycensus#326]
I have some code I wrote months ago that worked perfectly fine. Today it's throwing an error. 

`library(tidycensus)
census_api_key(Sys.getenv("CENSUS_API_KEY"))
variable_list <- load_variables("2010", "sf1",  cache = FALSE)
my_vars <-  variable_list %>% filter(str_detect(name, "^PCT012"), str_length(name)==9) %>% pull(name)
age_singleyr <-  get_decennial(geography = "state", variables = my_vars, year = "2010", state="MN", show_call=TRUE)
`

I gives me this error: 
`Error in UseMethod("left_join") : 
  no applicable method for 'left_join' applied to an object of class "NULL"`

I tried pulling just a couple variables from that PCT012 table and this code worked just fine

`test <-  get_decennial(geography="us",variables=c("PCT012001", "PCT012002") , year="2010")`

I had it show the API call to try to troubleshoot. It's supposed to grab 209 variables. If I'm reading this correctly, it looks like it's getting all the way to that last one then it throws the error. (However I don't know enough about how to read an API call to know what's going on here)

`Getting data from the 2010 decennial Census
Using FIPS code '27' for state 'MN'
Census API call: https://api.census.gov/data/2010/dec/sf1?get=PCT012001%2CPCT012002%2CPCT012003%2CPCT012004%2CPCT012005%2CPCT012006%2CPCT012007%2CPCT012008%2CPCT012009%2CPCT012010%2CPCT012011%2CPCT012012%2CPCT012013%2CPCT012014%2CPCT012015%2CPCT012016%2CPCT012017%2CPCT012018%2CPCT012019%2CPCT012020%2CPCT012021%2CPCT012022%2CPCT012023%2CPCT012024%2CPCT012025%2CPCT012026%2CPCT012027%2CPCT012028%2CPCT012029%2CPCT012030%2CPCT012031%2CPCT012032%2CPCT012033%2CPCT012034%2CPCT012035%2CPCT012036%2CPCT012037%2CPCT012038%2CPCT012039%2CPCT012040%2CPCT012041%2CPCT012042%2CPCT012043%2CPCT012044%2CPCT012045%2CPCT012046%2CPCT012047%2CPCT012048%2CNAME&for=state%3A27
Using FIPS code '27' for state 'MN'
Census API call: https://api.census.gov/data/2010/dec/sf1?get=PCT012049%2CPCT012050%2CPCT012051%2CPCT012052%2CPCT012053%2CPCT012054%2CPCT012055%2CPCT012056%2CPCT012057%2CPCT012058%2CPCT012059%2CPCT012060%2CPCT012061%2CPCT012062%2CPCT012063%2CPCT012064%2CPCT012065%2CPCT012066%2CPCT012067%2CPCT012068%2CPCT012069%2CPCT012070%2CPCT012071%2CPCT012072%2CPCT012073%2CPCT012074%2CPCT012075%2CPCT012076%2CPCT012077%2CPCT012078%2CPCT012079%2CPCT012080%2CPCT012081%2CPCT012082%2CPCT012083%2CPCT012084%2CPCT012085%2CPCT012086%2CPCT012087%2CPCT012088%2CPCT012089%2CPCT012090%2CPCT012091%2CPCT012092%2CPCT012093%2CPCT012094%2CPCT012095%2CPCT012096%2CNAME&for=state%3A27
Using FIPS code '27' for state 'MN'
Census API call: https://api.census.gov/data/2010/dec/sf1?get=PCT012097%2CPCT012098%2CPCT012099%2CPCT012100%2CPCT012101%2CPCT012102%2CPCT012103%2CPCT012104%2CPCT012105%2CPCT012106%2CPCT012107%2CPCT012108%2CPCT012109%2CPCT012110%2CPCT012111%2CPCT012112%2CPCT012113%2CPCT012114%2CPCT012115%2CPCT012116%2CPCT012117%2CPCT012118%2CPCT012119%2CPCT012120%2CPCT012121%2CPCT012122%2CPCT012123%2CPCT012124%2CPCT012125%2CPCT012126%2CPCT012127%2CPCT012128%2CPCT012129%2CPCT012130%2CPCT012131%2CPCT012132%2CPCT012133%2CPCT012134%2CPCT012135%2CPCT012136%2CPCT012137%2CPCT012138%2CPCT012139%2CPCT012140%2CPCT012141%2CPCT012142%2CPCT012143%2CPCT012144%2CNAME&for=state%3A27
Using FIPS code '27' for state 'MN'
Census API call: https://api.census.gov/data/2010/dec/sf1?get=PCT012145%2CPCT012146%2CPCT012147%2CPCT012148%2CPCT012149%2CPCT012150%2CPCT012151%2CPCT012152%2CPCT012153%2CPCT012154%2CPCT012155%2CPCT012156%2CPCT012157%2CPCT012158%2CPCT012159%2CPCT012160%2CPCT012161%2CPCT012162%2CPCT012163%2CPCT012164%2CPCT012165%2CPCT012166%2CPCT012167%2CPCT012168%2CPCT012169%2CPCT012170%2CPCT012171%2CPCT012172%2CPCT012173%2CPCT012174%2CPCT012175%2CPCT012176%2CPCT012177%2CPCT012178%2CPCT012179%2CPCT012180%2CPCT012181%2CPCT012182%2CPCT012183%2CPCT012184%2CPCT012185%2CPCT012186%2CPCT012187%2CPCT012188%2CPCT012189%2CPCT012190%2CPCT012191%2CPCT012192%2CNAME&for=state%3A27
Using FIPS code '27' for state 'MN'
Census API call: https://api.census.gov/data/2010/dec/sf1?get=PCT012193%2CPCT012194%2CPCT012195%2CPCT012196%2CPCT012197%2CPCT012198%2CPCT012199%2CPCT012200%2CPCT012201%2CPCT012202%2CPCT012203%2CPCT012204%2CPCT012205%2CPCT012206%2CPCT012207%2CPCT012208%2CPCT012209%2CNAME&for=state%3A27
Error in UseMethod("left_join") : 
  no applicable method for 'left_join' applied to an object of class "NULL"`

**Comment by walkerke** [comment]
This is the same issue as in https://github.com/walkerke/tidycensus/issues/305; it is fixed now in the GitHub version of tidycensus (I tested and your code works fine).  

More broadly - I'd like to overhaul how these sorts of scenarios are handled which I'll track in another issue.
