### ISSUE TITLE
get_acs 1 year is not working for 2007 data

### ISSUE THREAD

**Issue by vfuentesc** [walkerke/tidycensus#329]
Hi Kyle!
I am new in Github and R. So, I'm not sure if this is the right place for this issue. I've been working with `get_acs `a a couple of months ago without problems. For instance, I retrieved information from table B17002_001 for the 2007 year. Nevertheless, I just tried again today and got the following error "Error: ACS support in tidycensus begins with the 2005-2009 5-year ACS. Consider using decennial Census data instead.". I went over Census data and [it indeed exists](https://api.census.gov/data/2007/acs/acs1?get=NAME,B17002_001E&for=state:*) .  Could be the error part of the URL generating process in `get_acs`?
Thanks in advance,
Victor

**Comment by mfherman** [comment]
Thanks for raising the issue, @vfuentesc. Looks like data for the 1-year ACS in the API goes back to 2005 (the 5-year begins in 2009). So I think we should be able to support pulling 1-year data starting in 2005. I'll put together a brief PR that enables this.

**Comment by vfuentesc** [comment]
Thank you, @mfherman!
