### ISSUE TITLE
get_acs() error for 5-yr ACS 2012 and earlier 

### ISSUE THREAD

**Issue by deanhardy** [walkerke/tidycensus#335]
When downloading block group data for 5-yr ACS data beginning 2012 and before, it times out. I get the following error:

Getting data from the 2008-2012 5-year ACS
Fetching block group data by county and combining the result.
Error: Request failed after 3 attempts

Works fine for 2013 through 2019 5-yr ACS data. I haven't tried it on 3-yr or 1-yr data. I've tried both with and without geometry, so geometry = FALSE and geometry = TRUE. Both give same error. I've also tried switching up the variables, but same result. I've only tried block_groups, and haven't tested other geographies.

**Comment by walkerke** [comment]
I just reviewed the Census docs, and unfortunately it appears that block groups are unavailable from the ACS APIs prior to the 2009-2013 5-year ACS.  For example, see here: https://api.census.gov/data/2010/acs/acs5/examples.html.  The smallest geography available is the Census tract, so you may need to go with that for your project or explore other options (I believe NHGIS has block groups for these ACS samples).
