### ISSUE TITLE
confusing error message in to_survey()

### ISSUE THREAD

**Issue by edavidaja** [walkerke/tidycensus#336]
Based on the [docs](https://walker-data.com/tidycensus/articles/pums-data.html#modeling-with-pums-data), I think `SERIALNO and PUMA must both be present in input data.` might be a clearer message than [the current one](https://github.com/walkerke/tidycensus/blob/616776c5ac5613f48782946469020417776c0d0f/R/pums.R#L200), but I'm submitting as an issue rather than a PR in case I'm missing something.

Thank you so much for this feature.

**Comment by walkerke** [comment]
Yes, you are correct.  Thanks for having a look!
