### ISSUE TITLE
load_variables() error for 3-yr ACS 2008

### ISSUE THREAD

**Issue by ocnrandolph** [walkerke/tidycensus#337]
Hi, 

I'm trying to access ACS 3-year data (endpoint 2008) and 2008 ACS 1-year data, but no matter what, I'm getting the following error messages: 

_Error message 1:_
> acs_08_3yr_vars <- load_variables(2008, "acs3", cache = TRUE)
Error in load_variables(2008, "acs3", cache = TRUE) : 
  The current acs3 survey contains data from 2012-2013. Please select a different year.

Census.gov provides the following message regarding ACS 3-year estimates: "*ACS 3-year estimates have been discontinued. The 2005-2007, 2006-2008, 2007-2009, 2008-2010, 2009-2011, 2010-2012 and 2011-2013 ACS 3-year estimates **will remain available to data users**, but no new 3-year estimates will be produced."

Since the years I'm interested in (2006-2008) fall within this range, I'm not sure what this first error message means or how to work around it. When I check out the variables and geographies [here](https://api.census.gov/data/2008/acs/acs3.html), I can see that these data definitely exist. Am I missing something? 

_Error message 2:_
> acs_08_1yr_vars <- load_variables(2008, "acs1", cache = TRUE)
Error: lexical error: invalid char in json text.
                                       <html><head><title>Error report
                     (right here) ------^
Here's an image of this second error message in case that helps--I can't get it to copy and paste accurately here.
![err_msg_2_2008_acs1yr](https://user-images.githubusercontent.com/70925823/104049513-b0f3f400-51aa-11eb-96f4-3c7cc04f269f.png)
  
I don't know what to make of this error message either. Please advise!

Thanks in advance for your help!

**Comment by mfherman** [comment]
Hi @ocnrandolph --

I'm unable to reproduce your error. What version of tidycensus do you have installed? I would recommend installing the most recent GitHub version and trying again. To install:

```r
remotes::install_github("walkerke/tidycensus")
```

See below for some example code using 3-year ACS.

``` r
library(tidycensus)

acs_08_3yr_vars <- load_variables(2008, "acs3")

acs_08_3yr_vars
#> # A tibble: 28,054 x 3
#>    name       label                           concept                           
#>    <chr>      <chr>                           <chr>                             
#>  1 B00001_001 Estimate!!Total                 UNWEIGHTED SAMPLE COUNT OF THE PO~
#>  2 B00002_001 Estimate!!Total                 UNWEIGHTED SAMPLE HOUSING UNITS   
#>  3 B01001_001 Estimate!!Total                 SEX BY AGE                        
#>  4 B01001_002 Estimate!!Total!!Male           SEX BY AGE                        
#>  5 B01001_003 Estimate!!Total!!Male!!Under 5~ SEX BY AGE                        
#>  6 B01001_004 Estimate!!Total!!Male!!5 to 9 ~ SEX BY AGE                        
#>  7 B01001_005 Estimate!!Total!!Male!!10 to 1~ SEX BY AGE                        
#>  8 B01001_006 Estimate!!Total!!Male!!15 to 1~ SEX BY AGE                        
#>  9 B01001_007 Estimate!!Total!!Male!!18 and ~ SEX BY AGE                        
#> 10 B01001_008 Estimate!!Total!!Male!!20 years SEX BY AGE                        
#> # ... with 28,044 more rows

get_acs(
  geography = "state",
  variables = "B01003_001",
  year = 2008,
  survey = "acs3"
  )
#> The 3-year ACS provides data for geographies with populations of 20,000 and greater.
#> Getting data from the 2006-2008 3-year ACS
#> # A tibble: 52 x 5
#>    GEOID NAME                 variable   estimate   moe
#>    <chr> <chr>                <chr>         <dbl> <dbl>
#>  1 01    Alabama              B01003_001  4625354     0
#>  2 02    Alaska               B01003_001   681235     0
#>  3 04    Arizona              B01003_001  6343952     0
#>  4 05    Arkansas             B01003_001  2830047     0
#>  5 06    California           B01003_001 36418499     0
#>  6 08    Colorado             B01003_001  4844568     0
#>  7 09    Connecticut          B01003_001  3493006     0
#>  8 10    Delaware             B01003_001   861804     0
#>  9 11    District of Columbia B01003_001   588373     0
#> 10 12    Florida              B01003_001 18182321     0
#> # ... with 42 more rows

get_acs(
  geography = "state",
  variables = "B01003_001",
  year = 2012,
  survey = "acs1"
  )
#> The 1-year ACS provides data for geographies with populations of 65,000 and greater.
#> Getting data from the 2012 1-year ACS
#> # A tibble: 52 x 5
#>    GEOID NAME                 variable   estimate   moe
#>    <chr> <chr>                <chr>         <dbl> <dbl>
#>  1 01    Alabama              B01003_001  4822023    NA
#>  2 02    Alaska               B01003_001   731449    NA
#>  3 04    Arizona              B01003_001  6553255    NA
#>  4 05    Arkansas             B01003_001  2949131    NA
#>  5 06    California           B01003_001 38041430    NA
#>  6 08    Colorado             B01003_001  5187582    NA
#>  7 09    Connecticut          B01003_001  3590347    NA
#>  8 10    Delaware             B01003_001   917092    NA
#>  9 11    District of Columbia B01003_001   632323    NA
#> 10 12    Florida              B01003_001 19317568    NA
#> # ... with 42 more rows
```

<sup>Created on 2021-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ocnrandolph** [comment]
Hi Matt,

Thank you so much for your quick and helpful response! I'm new to R, so I'm not sure how to check what version of tidycensus I had installed previously (unfortunately I went straight to attempting to use the code you sent me, but maybe I can play around with R and see if the version was the issue after all). In the meantime though, `remotes::install_github("walkerke/tidycensus")` did the trick! I'm able to retrieve 2008 ACS data, and everything is looking as it should! 

Thank you again! 

Oluchi

**Comment by mfherman** [comment]
Glad you got it up and running! One way to check the package version is to run the following:

``` r
packageVersion("tidycensus")
#> [1] '0.11'
```

<sup>Created on 2021-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ocnrandolph** [comment]
Wonderful! R seems to be full of lots of helpful functions with names that make sense. Thank you for pointing me in the right direction re both of these issues!
