### ISSUE TITLE
Adjusting margin of error calculations for multiple zero estimates

### ISSUE THREAD

**Issue by ldaly** [walkerke/tidycensus#34]
Hi, I have a question about the MOE functions--have you considered adjusting the derived MOE function for aggregated estimates that include multiple zero estimates?

Some Census documentation recommends using only one MOE from a 0 estimate when there are multiple 0 estimates in order to avoid unnaturally inflating the SE (see Census document [here](https://www2.census.gov/programs-surveys/acs/tech_docs/accuracy/MultiyearACSAccuracyofData2015.pdf), p.21).
 
I see in the source code of moe_sum (and in testing the function on my data) multiple zeros aren't accounted for. Might this be something added to the function in the future?

Thanks--and PS, many thanks for creating this package.

**Comment by walkerke** [comment]
Thanks for the suggestion!  Yes, I can add this.

**Comment by walkerke** [comment]
I've pushed this update in https://github.com/walkerke/tidycensus/commit/040c0b97e67ddf6767b711c10d1a2abe808e2264.  Let's take an example of the black population age 25 to 44 by household income in Benton County, Oregon, which has a lot of zero estimates.  The published estimate and MOE for this group is 107 and 94, respectively.  

```r
library(tidycensus)
library(tidyverse)

vars <- paste0("B19037B_0", 20:35)

benton <- get_acs(geography = "county", variables = vars, 
                  state = "OR", county = "Benton") 

benton

# A tibble: 16 x 5
   GEOID                  NAME    variable estimate   moe
   <chr>                 <chr>       <chr>    <dbl> <dbl>
 1 41003 Benton County, Oregon B19037B_020       21    25
 2 41003 Benton County, Oregon B19037B_021        0    28
 3 41003 Benton County, Oregon B19037B_022       52    73
 4 41003 Benton County, Oregon B19037B_023        8    13
 5 41003 Benton County, Oregon B19037B_024        0    28
 6 41003 Benton County, Oregon B19037B_025        0    28
 7 41003 Benton County, Oregon B19037B_026        0    28
 8 41003 Benton County, Oregon B19037B_027        0    28
 9 41003 Benton County, Oregon B19037B_028        0    28
10 41003 Benton County, Oregon B19037B_029        9    16
11 41003 Benton County, Oregon B19037B_030       17    23
12 41003 Benton County, Oregon B19037B_031        0    28
13 41003 Benton County, Oregon B19037B_032        0    28
14 41003 Benton County, Oregon B19037B_033        0    28
15 41003 Benton County, Oregon B19037B_034        0    28
16 41003 Benton County, Oregon B19037B_035        0    28
```

We can get column summaries with dplyr: 

```r
benton %>%
  summarize(estsum = sum(estimate), 
            moesum = moe_sum(moe, estimate))

# A tibble: 1 x 2
  estsum   moesum
   <dbl>    <dbl>
1    107 87.70405
```

The old way still works, but throws a warning message: 

```r
benton %>%
  summarize(estsum = sum(estimate), 
            moesum = moe_sum(moe))

# A tibble: 1 x 2
  estsum   moesum
   <dbl>    <dbl>
1    107 124.6274
Warning message:
You have not specified the estimates associated with the margins of error.  In the event that your calculation involves multiple zero estimates, this will unnaturally inflate the derived margin of error.
```

The function works with wide-form datasets, but can be tedious as users will need to identify the columns in the calculation.  Also - when used with dplyr, users should not name the newly-derived columns `estimate` and `moe` if deriving a summed estimate and `moe_sum` in the same mutate call, as this will produce incorrect results.
