### ISSUE TITLE
404 errors when using get_decennial for year 2000

### ISSUE THREAD

**Issue by djkpf** [walkerke/tidycensus#340]
Hi! Love the package.

I am getting a 404 error when I try grab data from the 2000 Census, and it is not clear to me why. The same call works for the 2010 Census.

`get_decennial(geography = "us", year = 2000,
                    variables = "P001001", show_call = TRUE)`

Thanks!

**Comment by mfherman** [comment]
Hi @djkpf! Your code is working for me right now. My guess is that it was a temporary connectivity issue with the Census API.

``` r
tidycensus::get_decennial(
  geography = "us",
  year = 2000,
  variables = "P001001",
  show_call = TRUE
  )
#> Getting data from the 2000 decennial Census
#> Census API call: https://api.census.gov/data/2000/dec/sf1?get=P001001%2CNAME&for=us%3A%2A
#> Using Census Summary File 1
#> # A tibble: 1 x 4
#>   GEOID NAME          variable     value
#>   <chr> <chr>         <chr>        <dbl>
#> 1 1     United States P001001  281421906
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mfherman** [comment]
...adding if you're still have issue, make sure you have the most recent version of tidycensus installed (0.11.4).
