### ISSUE TITLE
Install+Load tidycensus, "no package called ‘rappdirs’"? And 'get_acs', 'census_api_key' not working.

### ISSUE THREAD

**Issue by jmendoza-sv** [walkerke/tidycensus#344]
I've installed tidycensus and load it alongside tidyverse. However, when loading tidycensus, I get the following:

```
> library(tidycensus)
Error: package or namespace load failed for ‘tidycensus’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘rappdirs’
```

I've looked all over StackOverflow and elsewhere for the issue with the **rappdirs** package, and have tried to install it on its own to no avail, failing each time.

Furthermore, the **census_api_key** and **get_acs** functions aren't working for me? 

```
Error in get_acs("county", table = "B27001", year = 2016, output = "tidy",  : 
  could not find function "get_acs"

Error in census_api_key("e6da31e2914908e9aecec9097bbea7510acaee97") : 
  could not find function "census_api_key"
```

Thanks for your patience with me, this is actually my first time commenting for help on someone's git for their own package. FYI I am running Mac OS High Sierra 10.13.6, maybe that has something to do with it.

**Comment by mfherman** [comment]
HI @jmendoza-sv. It seems like you're missing the rappdirs package, which is a (recursive) dependency of tidycensus. I would recommend (re)installing rappdirs by restarting your R session and running:

```
install.packages("rappdirs")
```

What is the error you get when trying to install rappdirs?

**Comment by jmendoza-sv** [comment]
> What is the error you get when trying to install rappdirs?

Hi Matt, thanks for responding so quickly. This was the error I got:

```
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/rappdirs_0.3.3.tgz'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/rappdirs_0.3.3.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/rappdirs_0.3.3.tgz'
Warning in install.packages :
  download of package ‘rappdirs’ failed
```

I decided to go straight to the source and download the .gz file and insert the folder into my Library. This didn't work, I had grabbed the most recent version and tried again to install **tidycensus** and the errors it gave me were around it not finding the right .rds file in a Meta/ folder. So instead, I downloaded the appropriate Mac OS binaries. Found it had said file in the folder, put it in my Library path, and ran my install code once more - finally worked! 

Hope this helps anyone else who runs in to this issue.

**Comment by mfherman** [comment]
Glad you got it up and running!
