### ISSUE TITLE
Cache PUMS data

### ISSUE THREAD

**Issue by pshmell** [walkerke/tidycensus#346]
Hi, just wondering whether caching PUMS data is a possibility. When I try to add `cache = TRUE` to a `get_pums` call it fails. 

When pulling, eg, PUMS from all states the files are large of course, so caching would be nice. I could just download my data directly and read it into R, but would be easier if I could store it. Couldn't find any documentation on this. Thanks, appreciate all the work put into this.

**Comment by walkerke** [comment]
You are correct, this is not possible at the moment.  I do really like this idea and I've had this on my mind for a while.  I think it would be a bit of a lift development-wise so I can't speak to any timetables for implementation.  I'd likely introduce a dependency on the {memoise} package (http://memoise.r-lib.org/) and handle that way.

**Comment by pshmell** [comment]
Ok thanks for confirming. What I've done for now is just write_csv my large pulls and load them back into memory from the hard file later on. Works fine, but would be nice to do it within the function I suppose. Anyways, great project.

**Comment by mfherman** [comment]
@pshmell you might consider using `write_rds()` or some other file format that also stores column types (instead of csv) for intermediate storage, since reading the csv back in might give you some issues with detecting the correct types.
