### ISSUE TITLE
Cannot coerce type 'closure' to vector of type 'character'

### ISSUE THREAD

**Issue by moonican** [walkerke/tidycensus#35]
Thanks for creating this awesome package. I am using it for the first time and just copy/pasting some code to see how it works and I get an error. Can you help me troubleshoot?

Here is what I pasted in RStudio:

`library(tidycensus)
library(tidyverse)
options(tigris_use_cache = TRUE)

orange <- get_acs(state = "CA", county = "Orange", geography = "tract", 
                  variables = "B19013_001", geometry = TRUE)

head(orange)`

Here is what RStudio gave me in return:

`> orange <- get_acs(state = "CA", county = "Orange", geography = "tract",  variables = "B19013_001", geometry = TRUE)
Using FIPS code '06' for state 'CA'
Using FIPS code '059' for 'Orange County'
[1] "Server error Internal Server Error Server error: (500) Internal Server Error"
Error in as.character(x) : 
  cannot coerce type 'closure' to vector of type 'character'

`
Thanks,
Monica

**Comment by moonican** [comment]
Ok, update: I had an old version of R that did not support something and triggered the error. I have since updated to 3.4.2 and ran your code with success! Thanks.

**Comment by walkerke** [comment]
Glad to hear you've got it working!

**Comment by aeonstone** [comment]
I am actually running into a similar error. I made sure to update my version of R and Rstudio before posting because that seemed to fix the issue for the prior person. My error is a Client Error (400)

Here is what I am running

```
library(tidycensus)
library(tidyverse)
census_api_key("xxxxx")
age <- get_acs(table = "B01001", state = "SD", county = "Custer", geography = "county") 
```

And here is what I get back

```
> age <- get_acs(table = "B01001", state = "SD", county = "Custer", geography = "county")
Using FIPS code '46' for state 'SD'
Using FIPS code '033' for 'Custer County'
[1] "Client error Bad Request Client error: (400) Bad Request"
Error in as.character(x) : 
  cannot coerce type 'closure' to vector of type 'character'
```

**Comment by moonican** [comment]
I am actually getting this issue again myself. Not sure how to resolve.

**Comment by walkerke** [comment]
Can you post the code that is triggering the error?

**Comment by walkerke** [comment]
@aeonstone the reason for the error you are experiencing is because tidycensus does not support single-geography queries at the moment.  So, to get the data you need: 

```r
library(tidycensus)
library(tidyverse)

age <- get_acs(table = "B01001", state = "SD", geography = "county") %>%
  filter(str_detect(NAME, "Custer"))

age

# A tibble: 49 x 5
   GEOID                        NAME   variable estimate   moe
   <chr>                       <chr>      <chr>    <dbl> <dbl>
 1 46033 Custer County, South Dakota B01001_001     8394    NA
 2 46033 Custer County, South Dakota B01001_002     4195    60
 3 46033 Custer County, South Dakota B01001_003      196    16
 4 46033 Custer County, South Dakota B01001_004      252    56
 5 46033 Custer County, South Dakota B01001_005      160    52
 6 46033 Custer County, South Dakota B01001_006      213    41
 7 46033 Custer County, South Dakota B01001_007       60    37
 8 46033 Custer County, South Dakota B01001_008       15    17
 9 46033 Custer County, South Dakota B01001_009       45    40
10 46033 Custer County, South Dakota B01001_010       66    58
# ... with 39 more rows
```

I may add this functionality in the future (as it makes more sense now that tidycensus supports tables) but in the meantime you can use tidyverse tools to get the data you need as in the example above.

**Comment by moonican** [comment]
Ah ok, maybe I have the same issue as @aeonstone, then. I am able to get dfCounty and dfMadisonCounty to load, but not dfBlocks. My goal is to get blocks for Madison County, Alabama.

Thanks for the help.

```
race_vars = c("B03002_003", "B03002_004", "B03002_006", "B03002_012")

dfCounty = get_acs(
  geography = "county", state="AL", variables = race_vars , year = 2015, 
  output = "wide",geometry=TRUE
) 
dfMadisonCounty = get_acs(
  geography = "county", state="AL", variables = race_vars , year = 2015, 
  output = "wide",geometry=TRUE
) %>% filter(str_detect(NAME,"Madison"))

dfBlocks = get_acs(
  geography = "block", state="AL", variables = race_vars , year = 2015, 
  output = "wide",geometry=TRUE
) 
```

**Comment by walkerke** [comment]
The issue above is that block data is not available in the American Community Survey; you can only get it from the decennial Census.  The smallest geography available in the ACS is the block group.  I've included an error message in https://github.com/walkerke/tidycensus/commit/7e403c36e3e8a0fe8b5cd021391462619d8e7a14 explaining this.  

Your request for the 2010 Census, however, would look like this: 

```r
library(tidycensus)

racevars <- c(white = "P0050003", black = "P0050004", 
              asian = "P0050006", hispanic = "P0040003")

dfBlocks <- get_decennial(geography = "block", state = "AL", 
                          county = "Madison", variables = racevars, 
                          output = "wide", geometry = TRUE)

dfBlocks

Simple feature collection with 15427 features and 6 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -86.79006 ymin: 34.47563 xmax: -86.25577 ymax: 34.99234
epsg (SRID):    4269
proj4string:    +proj=longlat +datum=NAD83 +no_defs
# A tibble: 15,427 x 7
             GEOID white black asian hispanic       NAME
             <chr> <dbl> <dbl> <dbl>    <dbl>      <chr>
 1 010890005031021     0     0     1        0 Block 1021
 2 010890005011026     0     9     0        0 Block 1026
 3 010890005021008     3    24     0        0 Block 1008
 4 010890005011012     3    39     1        0 Block 1012
 5 010890005021004     7    20     1        0 Block 1004
 6 010890005011031     8    36     0        5 Block 1031
 7 010890021002089     0     0     0        0 Block 2089
 8 010890023005026    11     5     0        0 Block 5026
 9 010890023005014     5     0     0        0 Block 5014
10 010890023005040    13     3     0        3 Block 5040
# ... with 15,417 more rows, and 1 more variables: geometry <S3:
#   sfc_MULTIPOLYGON>
```

**Comment by moonican** [comment]
Thank you!

**Comment by dana-rg** [comment]
First, I love this package!!  Enthusiastically.


I had a similar issue but I don’t think its because of the Census geography limitations. I’m also not sure what is causing @aeonstone’s issue, since that doesn’t appear to be a geography limitation.
I’m running R 3.5.0, tidycensus 0.4.6, tidyverse 1.2.1 on Windows 7.

Here’s my code:

library(tidycensus)
census_api_key("XX")

EducationVariables <-  c(EduTotal = "B16010_001", Edu1 = "B16010_002", Edu2 = "B16010_015", Edu3 = "B16010_028", Edu4 = "B16010_041")

Eduation <- get_acs(geography = "zcta", variables = EducationVariables, year = 2011, survey = "acs5", state = "CA", output = "wide") 

And here’s my console:

> Eduation <- get_acs(geography = "zcta", variables = EducationVariables, year = 2011, survey = "acs5", state = "CA", output = "wide")
Getting data from the 2007-2011 5-year ACS
Using FIPS code '06' for state 'CA'
Client error Bad Request Client error: (400) Bad Request
Error in as.character(x) : 
  cannot coerce type 'closure' to vector of type 'character'

However, it works when I do tracts instead of zcta, or remove the request for California data:

> Eduation <- get_acs(geography = "tract", variables = EducationVariables, year = 2011, survey = "acs5", state = "CA", output = "wide") 
Getting data from the 2007-2011 5-year ACS
Using FIPS code '06' for state 'CA'
> 
> Eduation <- get_acs(geography = "zcta", variables = EducationVariables, year = 2011, survey = "acs5", output = "wide")
Getting data from the 2007-2011 5-year ACS


>
