### ISSUE TITLE
survey_mean invalid type list

### ISSUE THREAD

**Issue by Calsimeth** [walkerke/tidycensus#350]
While working through the pums data example (https://walker-data.com/tidycensus/articles/pums-data.html) I encountered an error in the "Calculating standard errors" section where the following code is executed:

vt_survey_design %>% 
  mutate(ba_above = SCHL %in% c("21", "22", "23", "24")) %>% 
  filter(AGEP >= 25) %>% 
  group_by(PUMA, SEX_label) %>% 
  summarize(
    age_25_up = survey_total(vartype = "ci"),
    ba_above = survey_total(ba_above, vartype = "ci"),
    ba_pct = survey_mean(ba_above, vartype = "ci")
    )

When I do so the survey_mean command returns the following error:

Error: Problem with `summarise()` input `ba_pct`.
x invalid type (list) for variable '__SRVYR_TEMP_VAR__'
i Input `ba_pct` is `survey_mean(ba_above, vartype = "ci")`.
i The error occurred in group 1: PUMA = "00100", SEX_label = "Male".
Run `rlang::last_error()` to see where the error occurred.

Last_error outputs the following:

<error/dplyr_error>
Problem with `summarise()` input `ba_pct`.
x invalid type (list) for variable '__SRVYR_TEMP_VAR__'
i Input `ba_pct` is `survey_mean(ba_above, vartype = "ci")`.
i The error occurred in group 1: PUMA = "00100", SEX_label = "Male".
Backtrace:
  1. `%>%`(...)
 14. base::.handleSimpleError(...)
 15. dplyr:::h(simpleError(msg, call))
Run `rlang::last_trace()` to see the full context.

Looks to me like ba_above is being interpreted as a list for some reason.

This issue may have nothing to do with how tidycensus works but the example shown ought to work.

**Comment by mfherman** [comment]
Thanks so much for the report @Calsimeth! This has to do with a change that was made in srvyr 1.0 which I hadn't noticed until now (http://gdfe.co/srvyr/news/index.html). Basically, you are now able to refer to newly created variables within the a `summarize()` call and so when we try to calculate the total and mean of `ba_above`, we get the error the second time around because it is trying to use the newly calculated `ba_above` as the input to `survey_mean()`. 

So, the simple fix is to just to change the newly created variable names in that `summarize()` call. Something like this will work:

``` r
library(tidycensus)
library(tidyverse)
library(srvyr)

vt_pums_rep_weights <- get_pums(
  variables = c("PUMA", "SEX", "AGEP", "SCHL"),
  state = "VT",
  survey = "acs1",
  year = 2018,
  recode = TRUE,
  rep_weights = "person"
  )
#> Getting data from the 2018 1-year ACS Public Use Microdata Sample

vt_survey_design <- to_survey(vt_pums_rep_weights)

vt_survey_design %>% 
  mutate(ba_above = SCHL %in% c("21", "22", "23", "24")) %>% 
  filter(AGEP >= 25) %>% 
  group_by(PUMA, SEX_label) %>% 
  summarize(
    age_25_up = survey_total(vartype = "ci"),
    ba_above_n = survey_total(ba_above, vartype = "ci"),
    ba_above_pct = survey_mean(ba_above, vartype = "ci")
    )
#> # A tibble: 8 x 11
#> # Groups:   PUMA [4]
#>   PUMA  SEX_label age_25_up age_25_up_low age_25_up_upp ba_above_n
#>   <chr> <ord>         <dbl>         <dbl>         <dbl>      <dbl>
#> 1 00100 Male          72680        70216.        75144.      34113
#> 2 00100 Female        77966        75671.        80261.      36873
#> 3 00200 Male          52278        50826.        53730.      15831
#> 4 00200 Female        55162        53643.        56681.      20248
#> 5 00300 Male          45634        44743.        46525.      14869
#> 6 00300 Female        49546        48576.        50516.      21527
#> 7 00400 Male          45960        45067.        46853.      12788
#> 8 00400 Female        48601        47783.        49419.      18980
#> # ... with 5 more variables: ba_above_n_low <dbl>, ba_above_n_upp <dbl>,
#> #   ba_above_pct <dbl>, ba_above_pct_low <dbl>, ba_above_pct_upp <dbl>
```

<sup>Created on 2021-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


When I have a sec, I'll update the vignette. Hope this works for you!

**Comment by walkerke** [comment]
Thanks @mfherman for looking into this so swiftly!
