### ISSUE TITLE
Avoid downloading blocks shapefile multiple times in same function call.

### ISSUE THREAD

**Issue by leehach** [walkerke/tidycensus#36]
When using `get_decennial` to download block geometries and requesting multiple counties, tidycensus is (a) downloading the much larger state-level blocks shapefile rather than using the county-level shapefiles, and (b) downloading it once for each county.

For example, to grab all blocks for New York City:

```r
nyc = get_decennial("tract", "P0010001", state = "NY", county = c("Bronx", "Kings", "New York", "Queens", "Richmond"), geometry = TRUE, output = "wide")
```

This will download the New York state blocks shapefile tl_2010_36_tabblock10.zip which is 183MB, and it will download it five times for a total download of ~915MB. It would be better to download the five county shapefiles, tl_2010_36005_tabblock10.zip, tl_2010_36047_tabblock10.zip, etc., for a total download of ~4.1MB.

**Comment by walkerke** [comment]
Thanks for your suggestion, this is definitely do-able.  It'll require some updates to __tigris__ as it pulls in block shapefiles by state then subsets by county (as more recent TIGER/Line datasets don't make block shapefiles available by county, but 2010 does).  

In the meantime I'd recommend using __tigris__ caching with `options(tigris_use_cache = TRUE)`; it'll download the New York shapefile once and then you won't need to download again.

**Comment by leehach** [comment]
I don't think I even realized the more recent TIGER/Line datasets offer blocks by state (no less county), since ACS doesn't release any block-level data.

In any event, I did figure out to use caching to at least avoid multiple downloads of the large file.

**Comment by walkerke** [comment]
I've pushed an update to tigris (https://github.com/walkerke/tigris/commit/f2e053f21f4fbd128a885dedb35f5a40b0ea0898) that allows for the requested behavior.  Block data with geometry for 2010 is now much, much faster!  Thanks for the suggestion.
