### ISSUE TITLE
tidycensus hex logo

### ISSUE THREAD

**Issue by walkerke** [walkerke/tidycensus#360]
Now that @mfherman has added migration flows functionality to tidycensus it is time for a version 1.0 release of the package.  Before we do this, we'd like to design a hex logo for the package!  Matt and I have some ideas but neither of us are graphic designers.  If any tidycensus users would like to contribute an idea for a logo, please post here!

**Comment by cgthigpen** [comment]
Maybe a [population pyramid](https://images.populationpyramid.net/capture/?selector=%23pyramid-share-container&url=https%3A%2F%2Fwww.populationpyramid.net/%3Fshare%3Dtrue)? Or some [question text and bubbles from the census form](https://www.kentreporter.com/wp-content/uploads/2020/03/21121010_web1_cv-HowTo-Census-allKC-200401-Census-Form_1.jpg)?

**Comment by nmpeterson** [comment]
I think a choropleth map of the lower 48 (in the Albers Equal Area projection, of course) showing something basic like population density of each state could reflect the package's usefulness for getting both numeric and spatial data, as well as the geographic extent of that data.
