### ISSUE TITLE
Person-level data: 'cols' must select at least one column error?

### ISSUE THREAD

**Issue by pshmell** [walkerke/tidycensus#365]
Hi there, getting an odd error while trying to pull some person-level data from ACS-1 year PUMS.

At first I was trying to pull both household-level and person-level variables in the same request, and it threw this error:
`Error: 'cols' must select at least one column`

So I pulled my person-level variable (AGEP) out. Then I tried to pull AGEP with its own request:
`AGEP <- get_pums(variables = "AGEP", state = "all", year = 2019, survey = "acs1")`

But I'm still getting the same 'cols' error. Struggling to understand what's going on with this one. It appears to be downloading all of the data (gets to "Downloading: 120MB", which seems right) but then failing to put this into a dataframe... Any ideas?

**Comment by pshmell** [comment]
Here's the backtrace
`Backtrace:
  1. tidycensus::get_pums(variables = "AGEP", state = "all", survey = "acs1")
 11. tidyr:::pivot_longer.data.frame(...)
 12. tidyr::build_longer_spec(...)
Run `rlang::last_trace()` to see the full context.`

**Comment by walkerke** [comment]
Thanks for filing the issue @pshmell - I can confirm the error on my end.  FWIW it is not happening when you request a specific state, only when the state is `"all"`.  I'll look into it!

**Comment by mfherman** [comment]
I think this is happening because the `ST` variable is not getting added back into the default variables to download from the API when `state = "all"`. We added a little logic to add it back in when a variable filter is requested: https://github.com/walkerke/tidycensus/blob/4515b6f6057aca6421011de0c3d7ca247f18bbc3/R/load_data.R#L767-L770
But this logic is missing from the `else` condition. 

I'm testing out a simple fix and when I confirm it works, I can push the change.

**Comment by mfherman** [comment]
@walkerke #366 should take care of this -- can you just do a quick check that it is working for you before you merge?

**Comment by walkerke** [comment]
```
> AGEP <- get_pums(variables = "AGEP", state = "all", year = 2019, survey = "acs1")
Getting data from the 2019 1-year ACS Public Use Microdata Sample
Requesting data for the entire United States. This can take several minutes to complete.
Downloading: 140 MB     > 
> 
> AGEP
# A tibble: 3,239,553 x 6
   SERIALNO      SPORDER  WGTP PWGTP  AGEP ST   
   <chr>           <dbl> <dbl> <dbl> <dbl> <chr>
 1 2019GQ0000001       1     0    71    35 18   
 2 2019GQ0000004       1     0    67    25 48   
 3 2019GQ0000007       1     0    24    21 18   
 4 2019GQ0000010       1     0    52    49 04   
 5 2019GQ0000013       1     0    28    18 06   
 6 2019GQ0000016       1     0    32    33 12   
 7 2019GQ0000019       1     0    55    28 53   
 8 2019GQ0000022       1     0    61    41 29   
 9 2019GQ0000025       1     0    52    19 51   
10 2019GQ0000028       1     0    24    36 08   
# … with 3,239,543 more rows
```

Thanks Matt as always!

**Comment by pshmell** [comment]
Cool, thank you. As ever, great library.
