### ISSUE TITLE
Discussion: future of `shift_geo`

### ISSUE THREAD

**Issue by walkerke** [walkerke/tidycensus#368]
Raising this for discussion @mfherman / any of you in the tidycensus user community who are interested:

I've recently added the `shift_geometry()` version to tigris which will be going up on CRAN soon.  `shift_geometry()` offers a few improvements over the current way this is implemented in tidycensus, as it operates on arbitrary shapes as opposed to using stored datasets (and includes Puerto Rico).  This allows any tidycensus dataset to be shifted and rescaled and makes it easier to overlay non-tidycensus datasets on top, if requested.  The time difference for use is a little slower, but not a huge deal in my opinion.  

```r
library(tictoc)
library(tigris)
library(tidycensus)
options(tigris_use_cache = TRUE)

tic()
get_acs(
  geography = "county",
  variables = "B01001_001",
  geometry = TRUE,
  resolution = "20m"
) %>%
  shift_geometry()
toc()

# 1.941 sec elapsed

tic()
get_acs(
  geography = "county",
  variables = "B01001_001",
  geometry = TRUE,
  shift_geo = TRUE
)
toc()

# 1.306 sec elapsed
```

There are two options to consider, then, for implementation of `shift_geometry()` in tidycensus: 

1. Use `shift_geometry()` internally and enable the `shift_geo` argument for all tidycensus datasets, or 
2. Deprecate `shift_geo` and encourage people to use `shift_geometry()` directly.  

Right now I'm partial to option 2 as it may be clearer to users what is happening and enforces consistency across tidycensus and non-tidycensus geometry shifts, but I'd be open to discussion on this point.

**Comment by mfherman** [comment]
I like option 2 as well. There is a bit of magic with `shift_geo = TRUE` and so I think requiring the separate step will make more explicit what is actually happening. We can add a depreciation warning to alert users that we recommend using`shift_geometry()`.

I wonder if we should re-export `shift_geometry()` so that users can access it just by attaching tidycensus? Not sure what the best practice is on this.

**Comment by walkerke** [comment]
I've deprecated `shift_geo` throwing a warning to use `tigris::shift_geometry()` instead as I submitted the new version of tigris to CRAN today.  Got a little cleanup to do then I'd like to get all these updates up to CRAN as well!
