### ISSUE TITLE
Get ACS Function Returning Error That Didn't Happen A Couple Months Ago

### ISSUE THREAD

**Issue by zmoore152** [walkerke/tidycensus#371]
**Describe the bug:**
I wrote this code a couple of months ago and it was running fine. I tried running it today and have been getting an error that I'm suspecting might be associated with the update to the census? I'm basically just trying to get county subdivision files for a set of given states. The code is as follows:

# Specifying the states I want
my_states <- c("SD","ND","MI","IN","KY","WY","IA","KS","OH","NE","MO","MN","WI","IL")

# Specifying the variable I want for each subdivision
my_vars <- c(
  total_pop = "B01001_001"
  #median_income = "B19013_001"
  )

# This is just specifying the Census records we'll be pulling from. 
county_state <- tigris::counties(
  state = my_states,
  cb = TRUE,
  resolution = "20m",
  year = "2019",
  class = "sf"
)

# Pulling in county subdivision shape files
multi_state_bg_geo_list <- map2(
  county_state$STATEFP, county_state$COUNTYFP,
    ~ get_acs(
        geography = "county subdivision",
        variables = my_vars,
        state = .x,
        county = .y,
        year = 2019,
        survey = "acs5",
        geometry = TRUE,
        output = "wide"  # get data in wide format for easier mapping
        )
    )

The error that results from running this code is here:
Getting data from the 2015-2019 5-year ACS
Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
error 1 in extracting from zip fileCannot open layer cb_2019_29_cousub_500k
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
  Opening layer failed.

**Desktop:**

OS: Windows 10
R Version 3.6.1

It appears as if maybe the files have changed, but it's kind of difficult to really tell what's going on here or why? Appreciate any help folks can provide!

**Comment by mfherman** [comment]
Hi @zmoore152 -- this is the type of error message that is returned when there are issues with the Census FTP site that hosts these shapefiles. The usual fix is to just retry your code a bit later.  A good option is also to set `options(tigris_use_cache = TRUE)` so you don't have to re-download after you've downloaded successfully the first time.

I've opened an issue to improve the error messages/handling for tigris which handles the getting the geometry from the Census into R: https://github.com/walkerke/tigris/issues/117

**Comment by walkerke** [comment]
As a heads up @zmoore152 - I ran your example successfully just now.  You can also simplify your code by omitting the `county` argument and avoid iterating through counties.  For example: 

```r
library(tidycensus)
library(tidyverse)

my_states <- c("SD","ND","MI","IN","KY","WY","IA","KS","OH","NE","MO","MN","WI","IL")

my_vars <- c(
  total_pop = "B01001_001",
  median_income = "B19013_001"
)

my_data <- map_df(my_states, ~{
  get_acs(
    geography = "county subdivision",
    variables = my_vars,
    year = 2019,
    state = .x,
    output = "wide",
    geometry = TRUE
  )
})
```
