### ISSUE TITLE
Zip Code Zip FIle Error

### ISSUE THREAD

**Issue by braedenmc1** [walkerke/tidycensus#372]
Hello!

I have a question about an error I recieved while trying to gather data on Florida zip codes. I used this code to load the data:

```
zippy <- get_decennial(state = "FL",
+                          geography = "zip code tabulation area",
+                          variables = c(pop = "P013001"), 
+                          year = 2010,
+                          geometry = TRUE)
Getting data from the 2010 decennial Census
Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
 ````

I get this error after R attempts to download the data from the Census.

```
|=============================================================================================| 100%
Error: Cannot open "/private/var/folders/xd/896tb_rd24s67bmf_50ky9m00000gn/T/RtmpBF9FkH"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
```

I have used Tidycensus in the past to make maps and integrate it with other data, but this is the first time I tried to collect zip code data. 

Thank you all for the help!

Braeden McNulty

**Comment by mfherman** [comment]
Hi @braedenmc1 -- this is the type of error message that is returned when there are issues with the Census FTP site that hosts these shapefiles. The usual fix is to just retry your code a bit later.  A good option is also to set `options(tigris_use_cache = TRUE)` so you don't have to re-download after you've downloaded successfully the first time.

I've opened an issue to improve the error messages/handling for tigris which handles the getting the geometry from the Census into R: https://github.com/walkerke/tigris/issues/117
