### ISSUE TITLE
Can not parse Pima County PUMS from database

### ISSUE THREAD

**Issue by asapppp** [walkerke/tidycensus#375]
Hello, I am attempting to isolate Pima County in AZ for variables defined below, I keep getting error: your API call has errors, not informative, can someone assist? I can not find documentation on the PUMA vector/state combination. I am using AZ FIPS code = 04 and Pima county FIPS code = 019 = 04019

az_pums <-
  get_pums(variables = c("PUMA", "PWGTP","RMSP", "NP", "SCHL","ESR","FESRP","RAC1P","HISP"),  #Getting data from the 2015-2019 5-year ACS Public Use Microdata Sample
           state = 04,
           puma = c("AZ" = 04019), # AZ FIPS code = 04 and Pima county FIPS code = 019 = 04019
           year = 2019,
           recode = TRUE,
           show_call = TRUE)

**Comment by mfherman** [comment]
Hi @asapppp and thanks for the question. A couple things going here. First, is that PUMA codes are different from state/county FIPS codes so for `get_pums()` you need to specify PUMA codes. For large counties, there are multiple PUMAs contained in a single county. So for Pima, you'd want to look up all the PUMAs that are within that county. You can find more info about county to PUMA equivalency here: https://www.census.gov/programs-surveys/geography/guidance/geo-areas/pumas.html Also for reference, here is the list of all PUMA codes: https://www2.census.gov/geo/pdfs/reference/puma/2010_PUMA_Names.pdf

Here is some sample code that should get you started with Pima PUMS data (that's fun to say!):

``` r
library(tidycensus)

pima_pumas <- c("00201", "00202", "00203", "00204",
                "00205", "00206", "00207", "00208",
                "00209")

# multiple pumas in a single state
get_pums(
  variables = c("RMSP", "NP", "SCHL"),
  state = "AZ",
  puma = pima_pumas,
  survey = "acs1",
  )
#> Getting data from the 2019 1-year ACS Public Use Microdata Sample
#> # A tibble: 10,786 x 9
#>    SERIALNO      SPORDER  WGTP PWGTP  RMSP    NP PUMA  ST    SCHL 
#>    <chr>           <dbl> <dbl> <dbl> <dbl> <dbl> <chr> <chr> <chr>
#>  1 2019GQ0000434       1     0    59     0     1 00207 04    19   
#>  2 2019GQ0000946       1     0    11     0     1 00205 04    19   
#>  3 2019GQ0001793       1     0    17     0     1 00204 04    16   
#>  4 2019GQ0002522       1     0    70     0     1 00208 04    14   
#>  5 2019GQ0002855       1     0    57     0     1 00207 04    13   
#>  6 2019GQ0003998       1     0    63     0     1 00207 04    18   
#>  7 2019GQ0004159       1     0    15     0     1 00201 04    22   
#>  8 2019GQ0004349       1     0    42     0     1 00207 04    18   
#>  9 2019GQ0004379       1     0    69     0     1 00205 04    09   
#> 10 2019GQ0004544       1     0    58     0     1 00207 04    16   
#> # ... with 10,776 more rows

# pumas in different states
# set state to "multiple" and pass a named vector of state/puma pairs
get_pums(
  variables = c("RMSP", "NP", "SCHL"),
  state = "multiple",
  puma = c("AZ" = "00201", "NM" = "00500"),
  survey = "acs1"
  )
#> Getting data from the 2019 1-year ACS Public Use Microdata Sample
#> # A tibble: 3,099 x 9
#>    SERIALNO      SPORDER  WGTP PWGTP  RMSP    NP PUMA  ST    SCHL 
#>    <chr>           <dbl> <dbl> <dbl> <dbl> <dbl> <chr> <chr> <chr>
#>  1 2019GQ0004159       1     0    15     0     1 00201 04    22   
#>  2 2019GQ0005202       1     0   105     0     1 00500 35    13   
#>  3 2019GQ0011255       1     0    77     0     1 00500 35    16   
#>  4 2019GQ0046169       1     0   128     0     1 00500 35    11   
#>  5 2019GQ0084055       1     0    65     0     1 00500 35    19   
#>  6 2019GQ0089318       1     0    69     0     1 00500 35    19   
#>  7 2019GQ0091198       1     0   114     0     1 00500 35    13   
#>  8 2019GQ0096998       1     0    18     0     1 00201 04    16   
#>  9 2019GQ0116066       1     0    63     0     1 00500 35    17   
#> 10 2019GQ0116417       1     0    62     0     1 00500 35    13   
#> # ... with 3,089 more rows
```

<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by asapppp** [comment]
Dear Mr. Herman,

I really appreciate this quick and very informative response.
It is most helpful, thanks!

Amanda
