### ISSUE TITLE
Error: Your API call has errors.  The API message returned is error: error: unknown variable 'B01003E'.

### ISSUE THREAD

**Issue by banwarp** [walkerke/tidycensus#376]
Hi, When I run the get_acs command I get the above error. Here is the command. I am not sure why get_acs is appending the E to the variable.

bgs <- get_acs(geography="block group",
                          variables="B01003",
                          year=2019,
                          state="OR",
                          county="Benton",
                          geometry="True")

**Comment by banwarp** [comment]
My apologies; it has been a while since I used get_acs and I forgot to include the full variable name: B01003_001

**Comment by walkerke** [comment]
Not to worry.  By the way, in case you are doing work on Benton County - that's the county where I grew up!

**Comment by banwarp** [comment]
Are you the Kyle Walker who played soccer at CV with Peter Banwarth? (That'
me).

**Comment by walkerke** [comment]
Hi Peter - yes that's me!  Nice to hear from you, I hope you are doing well!

**Comment by banwarp** [comment]
I am doing well. I am an epidemiologist in Benton County. I have found
tidycensus to be a great help in my work. It seems like you are doing some
pretty cool work. Is developing R packages a full time job or something you
do in your spare time?
Peter

**Comment by walkerke** [comment]
Glad to hear!  I'm a professor at TCU in Fort Worth; a large part of my research is open source software development so I fit it in there.

**Comment by banwarp** [comment]
Hi Kyle,
Can you help me out with this error? Would you prefer that I post such
errors to github in the future so others can see them as well?

I'm trying to get block populations from the 2010 decennial census to
estimate vaccination rates at block-level granularity. I have not had
success with get_decennial. I tried this example you posted to a question a
couple of years ago, and I got the following error:

teton10 <- get_decennial(geography = "block", variables = "P0010001",state
= "WY", county = "Teton", geometry = TRUE)

Getting data from the 2010 decennial Census
Downloading feature geometry from the Census website.  To cache shapefiles
for use in future sessions, set `options(tigris_use_cache = TRUE)`.
Using FIPS code '56' for state 'WY'
Using FIPS code '039' for 'Teton County'
Error : Your API call has errors.  The API message returned is error:
error: unknown variable 'P0010001'.
Using Census Summary File 1
Error in gather.default(., key = variable, value = value, -GEOID, -NAME) :
  object 'NAME' not found


I also tried this code and got a slightly different error:
> blocks <- get_decennial(geography = "blocks",
+                         variables = "H010001",
+                         year = 2010,
+                         state = "OR",
+                         county = "Benton",
+                         geometry = "True")
Getting data from the 2010 decennial Census
Downloading feature geometry from the Census website.  To cache shapefiles
for use in future sessions, set `options(tigris_use_cache = TRUE)`.
Using FIPS code '41' for state 'OR'
Using FIPS code '003' for 'Benton County'
Error : Your API call has errors.  The API message returned is error:
unknown/unsupported geography heirarchy.
Using Census Summary File 1
Error in gather.default(., key = variable, value = value, -GEOID, -NAME) :
  object 'NAME' not found


Thanks,
Peter

**Comment by walkerke** [comment]
Hi @banwarp - happy to help!  In the first example, Census changed the variable IDs for the decennial Census a couple years ago.  So instead of `"P0010001"` use `"P001001"`.  `tidycensus::load_variables(2010, "sf1")` will pull down the latest variable IDs from the 2010 Census for you.  

```r
library(tidycensus)

get_decennial(
  geography = "block",
  variables = "P001001",
  state = "WY",
  county = "Teton",
  geometry = TRUE
)
```
```
Getting data from the 2010 decennial Census
Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
Using FIPS code '56' for state 'WY'
Using FIPS code '039' for 'Teton County'
Using Census Summary File 1
Downloading: 3.7 MB     Simple feature collection with 2501 features and 4 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -111.0553 ymin: 43.23499 xmax: -110.051 ymax: 44.6668
Geodetic CRS:  NAD83
# A tibble: 2,501 x 5
   GEOID    NAME              variable value                             geometry
   <chr>    <chr>             <chr>    <dbl>                   <MULTIPOLYGON [°]>
 1 5603996… Block 1014, Bloc… P001001      0 (((-111.0009 43.76389, -111.0006 43…
 2 5603996… Block 1468, Bloc… P001001      6 (((-111.0224 43.75626, -111.0222 43…
 3 5603996… Block 1045, Bloc… P001001     23 (((-111.0179 43.75734, -111.0181 43…
 4 5603996… Block 1471, Bloc… P001001      6 (((-111.0366 43.75348, -111.0364 43…
 5 5603996… Block 1528, Bloc… P001001      0 (((-111.04 44.1304, -111.04 44.1304…
 6 5603996… Block 1462, Bloc… P001001    110 (((-111.0366 43.75348, -111.0367 43…
 7 5603996… Block 1567, Bloc… P001001      7 (((-111.0194 43.77189, -111.0194 43…
 8 5603996… Block 1033, Bloc… P001001      0 (((-110.8469 44.12862, -110.847 44.…
 9 5603996… Block 1050, Bloc… P001001      0 (((-110.7884 44.12597, -110.7883 44…
10 5603996… Block 2127, Bloc… P001001      0 (((-110.9689 44.66611, -110.9687 44…
# … with 2,491 more rows
```

For the second example, the `unknown/unsupported geography heirarchy.` error suggests that the geography is incorrectly specified.  Change `"blocks"` to `"block"` and you'll be set:

```r
get_decennial(
  geography = "block",
  variables = "H010001",
  state = "OR",
  county = "Benton",
  geometry = TRUE
)
```
```
Getting data from the 2010 decennial Census
Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
Using FIPS code '41' for state 'OR'
Using FIPS code '003' for 'Benton County'
Using Census Summary File 1
Downloading: 1.8 MB     Simple feature collection with 2979 features and 4 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -123.8169 ymin: 44.27656 xmax: -123.0731 ymax: 44.7213
Geodetic CRS:  NAD83
# A tibble: 2,979 x 5
   GEOID    NAME               variable value                             geometry
   <chr>    <chr>              <chr>    <dbl>                        <POLYGON [°]>
 1 4100301… Block 3186, Block… H010001      0 ((-123.5707 44.55506, -123.5706 44.…
 2 4100301… Block 3157, Block… H010001      2 ((-123.426 44.55308, -123.4259 44.5…
 3 4100301… Block 3150, Block… H010001      0 ((-123.4245 44.55564, -123.4244 44.…
 4 4100301… Block 3220, Block… H010001      0 ((-123.4133 44.55551, -123.4132 44.…
 5 4100301… Block 1194, Block… H010001      2 ((-123.1805 44.67761, -123.184 44.6…
 6 4100301… Block 2033, Block… H010001      0 ((-123.3145 44.6769, -123.3139 44.6…
 7 4100301… Block 2032, Block… H010001      0 ((-123.3327 44.6818, -123.3328 44.6…
 8 4100301… Block 2111, Block… H010001      0 ((-123.3524 44.65208, -123.3529 44.…
 9 4100301… Block 1229, Block… H010001      7 ((-123.2815 44.66245, -123.2814 44.…
10 4100301… Block 2030, Block… H010001      0 ((-123.3124 44.67965, -123.3127 44.…
# … with 2,969 more rows
```

You can check out the full list of available geographies and how to specify them [over in the tidycensus documentation here](https://walker-data.com/tidycensus/articles/basic-usage.html#geography-in-tidycensus-1).

**Comment by banwarp** [comment]
Thanks!

**Comment by banwarp** [comment]
Hi Kyle,
I just wanted to thank you again for your help. Your work is making a
direct difference in the lives of people who struggle to equitably access
service.

Map of unvaccinated in Benton County, by block (obviously the scale doesn't
help with a static visual analysis, but the power of this analysis to reach
specific populations is extraordinary).

[image: image.png]

Peter

**Comment by walkerke** [comment]
Thanks Peter, happy to help!

**Comment by banwarp** [comment]
Hi Kyle,
Could you let me know when tidycensus is ready to pull the 2020 census
data? I tried last week, but I may have done something wrong.
Thanks!
Peter

**Comment by walkerke** [comment]
Hi Peter!  The 2020 redistricting data won't be up on the Census API until September 30 so it'll be early October when we can support it in tidycensus.  The rest of the 2020 Census data still doesn't have a release date.  In the meantime, we have to work with the raw redistricting PL files; I've been using the PL94171 package (https://corymccartan.github.io/PL94171/).

**Comment by banwarp** [comment]
Thanks, Kyle! Ive been using the PL as well. Peter
