### ISSUE TITLE
 get_pums function doesn`t work using rep_weights = "housing" option

### ISSUE THREAD

**Issue by mcbgoes** [walkerke/tidycensus#379]
I am trying to import household income data and the get_pums function doesn`t seem to work using rep_weights = "housing".
Is it possible to solve the issue?
![tidycensus_error](https://user-images.githubusercontent.com/85563784/121194023-a1b6c680-c86e-11eb-85d0-76f770d184fe.PNG)

**Comment by mfherman** [comment]
We see this error from the API frequently when trying to do such a large pull (all states). One option is to iterate through the states, requesting one by one. Alternatively, you could download the whole files from the Census FTP or IPUMS

**Comment by walkerke** [comment]
thanks @mfherman  - I wonder if we should implement this internally as those big pulls just don't seem to work.  Perhaps do the state-by-state iteration internally, but give a message telling users that it'll take a while and they might consider using the FTP site or IPUMS instead.

**Comment by mcbgoes** [comment]
Thank you for your fast replies (@mfherman and @walkerke ). 
I am requesting the data state by state. I personally prefer this way rather than downloading it from the IPUMS/ FTP site. Anyways, I believe it would be great having this implemented within the package, even if it takes a while.
