### ISSUE TITLE
Problem with cartographic boundary shapefiles when getting data for multiple states

### ISSUE THREAD

**Issue by caseytolan** [walkerke/tidycensus#380]
Hi, thank you for this fantastic package! Apologies if I'm missing something, but I'm having an issue with cartographic boundary shapefiles when using get_acs.

When I use get_acs with geometry=TRUE and cb=FALSE for a single state, it returns the correct TIGER/Line shapefile. But when I do the same call for multiple states, it appears to return the cartographic boundary shapefiles no matter what I set cb as.

So this is returning the TIGER/Line shapefiles:

`get_acs("tract",state="IL",variables="B01003_001E",geometry=TRUE,cb=FALSE)
`

But this is returning the cartographic boundary shapefiles, even though cb=FALSE:

`get_acs("tract",state=c("IL","NY"),variables="B01003_001E",geometry=TRUE,cb=FALSE)
`

The same thing happens when I do different geography levels, like block group instead of tract, and when I don't include cb at all. And I have turned Tigris caching off, so I don't think that's the problem. 

Let me know if you can help with this or if I am misunderstanding something. Thanks again!

**Comment by walkerke** [comment]
@caseytolan thanks for filing!  This is a bug and I know exactly where it is happening; I'll just need a bit of time to figure out how to patch it correctly.  In the meantime, you can use this workaround:

```r
library(tidycensus)
library(tidyverse)

output <- map_df(c("IL", "NY"), ~{
  get_acs(
    geography = "tract", 
    state = .x,
    variables="B01003_001",
    geometry=TRUE,
    cb=FALSE
  )
})
```

![image](https://user-images.githubusercontent.com/4872833/121574207-a3f25f80-c9eb-11eb-9cd6-1c935c8f6221.png)

**Comment by caseytolan** [comment]
Great, thanks so much Kyle!

**Comment by walkerke** [comment]
This is now fixed and merged to the master branch:

```r
library(tidycensus)

tract_data <- get_acs(
  geography = "tract",
  state = c("IL", "NY"),
  variables = "B01003_001E",
  geometry = TRUE,
  cb = FALSE
)

plot(tract_data$geometry)

```

![image](https://user-images.githubusercontent.com/4872833/121873434-fe314000-cccb-11eb-982d-dafb62c5c917.png)

**Comment by caseytolan** [comment]
Awesome, thanks again!
