### ISSUE TITLE
empty geometry with ZCTA's?

### ISSUE THREAD

**Issue by omarfaison** [walkerke/tidycensus#381]
I'm having a new (for me) problem with tidycensus. When I attempt to pull data at the zcta level using get_acs, I get "GEOMETRYCOLLECTION EMPTY" in the geometry column. It does not happen when I pull data at the census tract level. This is also a fairly new problem, because I was using old code that I wrote and successfully generated maps from in the past. Any thoughts? Here are some code snippets that you can run to see what I am talking about:

zcta_test<-get_acs(geography="zcta",
                       variables=(c(all_pop = "B03002_001",
                                    white_pop = "B03002_003",
                                    black_pop = "B03002_004",
                                    latin_pop = "B03002_012")),
                       geometry=T, cache=T )

ct_test<-get_acs(geography="tract", state="51",
                 variables=(c(all_pop = "B03002_001",
                              white_pop = "B03002_003",
                              black_pop = "B03002_004",
                              latin_pop = "B03002_012")),
                 geometry=T, cache=T )

Thanks in advance for any help you can provide.

**Comment by walkerke** [comment]
I am not getting that error.  Would you mind posting the results of `devtools::session_info()`?

**Comment by omarfaison** [comment]
I got it worked out. I needed to update my tidycensus package. Thanks!

**Comment by walkerke** [comment]
Glad to hear it!

**Comment by estebanlp** [comment]
Hi Paul, it looks like I have somewhat of a similar problem. I am running the following call and get: 

```
library(tidycensus)

vars<-c("B19013_001",#median income         
        "B25077_001",#median home value         
        "B25064_001", # median gross rent         
        "B03002_003E", #Estimate!!Total:!!Not Hispanic or Latino:!!White alone         
        "B15002_015", #Estimate!!Total!!Male!!Bachelor's degree         
        "B15002_032",#Estimate!!Total!!Female!!Bachelor's degree # = population with bachelors degrees         #SUM         
        "B15002_016",#Estimate!!Total!!Male!!Master's degree         
        "B15002_017",#Estimate!!Total!!Male!!Professional school degree         
        "B15002_018",#Estimate!!Total!!Male!!Doctorate degree         # +         
        "B15002_033",#Estimate!!Total!!Female!!Master's degree         
        "B15002_034",# Estimate!!Total!!Female!!Professional school degree         
        "B15002_035") #Estimate!!Total!!Female!!Doctorate degree


data_y1 <- get_acs(geography = "tract", variables = vars, state = '01', county = "007", geometry = T,year = 2009,output ='wide')

> data_y1
Simple feature collection with 4 features and 26 fields (with 4 geometries empty)
Geometry type: GEOMETRYCOLLECTION
Dimension:     XY
Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
Geodetic CRS:  +proj=longlat +datum=NAD83 +no_defs
# A tibble: 4 × 27
  GEOID                    geometry NAME   B19013_001E B19013_001M B25077_001E B25077_001M
  <chr>    <GEOMETRYCOLLECTION [°]> <chr>        <dbl>       <dbl>       <dbl>       <dbl>
1 0100701… GEOMETRYCOLLECTION EMPTY Censu…       43182       23433       61600       19830
2 0100701… GEOMETRYCOLLECTION EMPTY Censu…       49267        7808       91700       13232
3 0100701… GEOMETRYCOLLECTION EMPTY Censu…       34778        7080       88200       10061
4 0100701… GEOMETRYCOLLECTION EMPTY Censu…       39722        8487       58100       38133
# ℹ 20 more variables: B25064_001E <dbl>, B25064_001M <dbl>, B03002_003E <dbl>,
#   B03002_003M <dbl>, B15002_015E <dbl>, B15002_015M <dbl>, B15002_032E <dbl>,
#   B15002_032M <dbl>, B15002_016E <dbl>, B15002_016M <dbl>, B15002_017E <dbl>,
#   B15002_017M <dbl>, B15002_018E <dbl>, B15002_018M <dbl>, B15002_033E <dbl>,
#   B15002_033M <dbl>, B15002_034E <dbl>, B15002_034M <dbl>, B15002_035E <dbl>,
#   B15002_035M <dbl>
```

here is my session info. I am using tidycensus 1.4.4.

```
─ Session info ─────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31)
 os       macOS Ventura 13.2.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Chicago
 date     2023-08-31
 rstudio  2023.03.0+386 Cherry Blossom (desktop)
 pandoc   2.19.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
```

Do you see the same?

**Comment by walkerke** [comment]
Yes, I see the same.  I did a little digging and it seems like the 2005-2009 is using the 2010, rather than the 2000, tract definitions for Bibb County only in Alabama.  Here's your data, but for the entire state: 

![image](https://github.com/walkerke/tidycensus/assets/4872833/360471d0-fa9c-4191-87ff-b64f013f2798)

Bibb County is the hole in the middle.  

tidycensus joins the 2005-2009 ACS data to the 2000 Census tracts; even looking at the 2009 tracts there are only three tracts in Bibb County.  So the API is returning data at 2010 geographies for the 2005-09 ACS for Bibb.  

It would require some custom code to account for this.  In the meantime you'd probably need to get the Census data separately with `geometry = FALSE`, then join to 2010 tracts with `tigris::tracts()` if you need Bibb spatial + demographic data.
