### ISSUE TITLE
problem with get_decennial() in 1 county in South Dakota (SD)

### ISSUE THREAD

**Issue by markdanese** [walkerke/tidycensus#384]
I ran the code below for **every county** in every state in the US (except AK and HI) successfully, except for 1 county in SD.  I don't know what is causing the error.  

[By the way, thanks for all your hard work on this package.  It is amazing -- I can do things I didn't know were possible with just a few lines of code.]  

`get_decennial(geography = "tract", variables = "P012001", state = 46, county = 102, geometry = TRUE)`

The error I get is below:
`Getting data from the 2010 decennial Census
No encoding supplied: defaulting to UTF-8.
Error : Your API call has errors.  The API message returned is .
Using Census Summary File 1
Error in gather_(data, key_col = compat_as_lazy(enquo(key)), value_col = compat_as_lazy(enquo(value)),  : 
  unused argument (-NAME)`

**Comment by szimmer** [comment]
In South Dakota, that county did not exist in 2010. I couldn't quickly find
the FIPS code but when the county was renamed, the FIPS code also changed.
Find the code for Shannon county in South Dakota.
https://en.wikipedia.org/wiki/Oglala_Lakota_County,_South_Dakota

**Comment by walkerke** [comment]
Thanks @szimmer!

**Comment by markdanese** [comment]
For reference for others, this document provides the fips code changes over time:  https://www.ddorn.net/data/FIPS_County_Code_Changes.pdf

So, 102 (Oglala Lakota County) should be 113 (Shannon County).  Note that **both** of these codes are already in the fips_codes data.frame in the package, so I think the solution is to simply delete the row with 102 prior to 2015.

**Comment by walkerke** [comment]
@markdanese - the `fips_codes` dataset is more intended for use by the package itself for internal translation of county names to county codes.  If you want to ensure an up-to-date representation of US counties by FIPS, I recommend a call to tidycensus itself for the year you need (any variable will do), e.g.:

```r
ctys <- tidycensus::get_decennial(
  geography = "county",
  variables = "P001001",
  year = 2010
) 

cty_fips <- sort(ctys$GEOID)
```

`cty_fips` is now a character vector with the codes that uniquely represent each county that was valid for the 2010 decennial Census.

**Comment by markdanese** [comment]
Thank you very much -- I just implemented this.  I was working from someone else's example and your suggestion makes a lot more sense.  Hopefully this will also be useful to someone else who is doing similar work.
