### ISSUE TITLE
Question on choosing subpopulation from ACS

### ISSUE THREAD

**Issue by longhaivo** [walkerke/tidycensus#385]
Hi,
Thank you for this awesome package, I've enjoyed reading on its functionalities so far. 
If possible, I would like to have a query on how to extract ACS data for different subpopulations. 

In particular, according to the data displayed on the NCES website [https://nces.ed.gov/programs/edge/tableviewer/acsProfile/2010](https://nces.ed.gov/programs/edge/tableviewer/acsProfile/2010), we can extract ACS data for a population that corresponds to "Parents of Relevant Children – Enrolled Public" (please see picture attached). 
![Query on ACS 2010 data](https://user-images.githubusercontent.com/30339577/122318301-693f7880-cf51-11eb-8807-635fb0237261.png)
In the above example, I'm interested in the median worker income (inflation adjusted) for this subpopulation in 2010 at the "School District" geography level, which is 25,863 for Albertville School District, Alabama. 

However, when using 
`varlist_10 <- load_variables(2010, "acs5", cache = TRUE);
View(varlist_10)`
I was unable to find a variable that refers to this population. The closest to what I'm looking for is a variable with ID B08121_001 (median earnings) but the figures are not the same as that shown in the website.
I was wondering if `tidycensus` has incorporated an argument to allow for subpopulation filtering? Or if it is possible to get the data I need via `tidycensus`, could you please provide some advices?

Thank you for your time.
Long

**Comment by mfherman** [comment]
Hi @longhaivo and thanks for the question. I'm not familiar with the NCES data, but it appears that the data they host is based on custom tabulations that the [Census Bureau makes for NCES](https://nces.ed.gov/programs/edge/Demographic/ACS). These [custom tabulations can be purchased from the Census Bureau](https://www.census.gov/programs-surveys/acs/data/custom-tables.html) when the specific population of interest (such as parents of children in public school) is not directly available in released ACS tabulations. These custom tabulations are hosted by NCES and therefore not available via the Census Bureau API that tidycensus uses.

Another approach if you do want to create custom tabulations from publicly available data is to use ACS microdata. You can read more about this data and how to access it via tidycensus here: https://walker-data.com/tidycensus/articles/pums-data.html
