### ISSUE TITLE
Can't get data at block group level

### ISSUE THREAD

**Issue by norahluo** [walkerke/tidycensus#386]
I was trying to get 5-year ACS data for california at block group level. 

I ran 
`var2013 <- get_acs(geography = 'block group', 
        variables = c('B02001_001',  'B02001_002', 'B08301_001', 'B08301_010', 'B08301_019', 'B11001_001', 'B15003_001', 'B15003_022', 'B25044_001', 'B25044_003', 'B25044_010'),
        state = 'CA', 
        geometry = FALSE, year = 2013, survey = 'acs5') `

but get error message 
`Error: Your API call has errors. The API message returned is error: unknown/unsupported geography heirarchy.`

For year before 2013, I get error message like this
`Error: Cannot open "C:\Users\Norah\AppData\Local\Temp\Rtmpio8zg2"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.`

When I changed to tract level, it works for all these years.

The default year is 2019 so I suppose the package I used is up-to-date. It seems to me that for 2005-2009 to 2009-2013, it only provides data through API at the census tract level. Is there any other way to get data for these years at the block group level? 
Thanks!

**Comment by walkerke** [comment]
Thanks for the note!  I've been working on this over the past week.  A couple notes: 

- 2009-2013 block group data are working now in the GitHub version of the package, so if you install from GitHub your code will run correctly.  I just tested and it works.  I'll submit the patch to CRAN fairly soon.  
- You are correct - block group data earlier than 2009-2013 are not available.  I corresponded with Census and they will not be coming back to the API.  So if you need 2008-2012 and earlier, you'll need to look at NHGIS or the raw summary files (data.census.gov doesn't have it either).

**Comment by norahluo** [comment]
Thanks for the information and your effort on this!
