### ISSUE TITLE
Geometry unavailable for 2018 ZCTAs

### ISSUE THREAD

**Issue by hofmeisterk** [walkerke/tidycensus#388]
Hi there,

I am unable to pull 2018 ZCTA geography data using the following script:

```
acs_zips = get_acs(geography = 'zcta',
                   variables = c(tot = 'B17001_001',
                                 inc_below_pl = 'B17001_002'),
                   output = 'wide',
                   geometry = TRUE,
                   year = 2018)
```
The error I get is:

`Error : Cannot open "/tmp/RtmpDp6Ilq"; The source could be corrupt or not supported. See st_drivers() for a list of supported formats.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
Error: Your geometry data download failed. Please try again later or check the status of the Census Bureau website at https://www2.census.gov/geo/tiger/`

However, the script does work with `year = 2019`. Thanks for your time!

**Comment by mfherman** [comment]
Hi @hofmeisterk! This happens from time to do due to the unavailability of the Census FTP where these shapefiles are pulled from. I just ran your code successfully, so if you try again in a few minutes, it will likely work.
