### ISSUE TITLE
Missing MOE Data for S0601_C01_001M

### ISSUE THREAD

**Issue by cymonegates** [walkerke/tidycensus#389]
I'm getting all NAs for the MOE value of S0601_C01_001 (see image). A manual download of ACSST5Y2018.S0601_data has values for S0601_C01_001M.

`AZ <- get_acs(
  geography = 'county',
  state = "AZ",
  survey = 'acs5',  
  year = 2018,
  variables = "S0601_C01_001",
  geometry = FALSE,
  output = 'tidy'
)`

![image](https://user-images.githubusercontent.com/38463305/123741151-65b7c580-d85e-11eb-90b7-c06a5717795d.png)

**Comment by mfherman** [comment]
Howdy @cymonegates!

Where are you downloading the data from to compare to the API/tidycensus response? When I ping the API directly with the call that `get_acs()` generates (use `show_call = TRUE` to print the API call), I see `-555555555` as the value for the margins of error. That value [corresponds to this status](https://www.census.gov/data/developers/data-sets/acs-1year/notes-on-acs-estimate-and-annotation-values.html):

> A '*****' entry in the margin of error column indicates that the estimate is controlled. A statistical test for sampling variability is not appropriate. 

Let me know if you're seeing something different in the data that you have downloaded.

``` r
tidycensus::get_acs(
  geography = 'county',
  state = "AZ",
  survey = 'acs5',
  year = 2018,
  variables = "S0601_C01_001",
  show_call = TRUE
)
#> Getting data from the 2014-2018 5-year ACS
#> Using the ACS Subject Tables
#> Census API call: https://api.census.gov/data/2018/acs/acs5/subject?get=S0601_C01_001E%2CS0601_C01_001M%2CNAME&for=county%3A%2A&in=state%3A04
#> # A tibble: 15 x 5
#>    GEOID NAME                       variable      estimate   moe
#>    <chr> <chr>                      <chr>            <dbl> <dbl>
#>  1 04001 Apache County, Arizona     S0601_C01_001    71522    NA
#>  2 04003 Cochise County, Arizona    S0601_C01_001   126279    NA
#>  3 04005 Coconino County, Arizona   S0601_C01_001   140217    NA
#>  4 04007 Gila County, Arizona       S0601_C01_001    53400    NA
#>  5 04009 Graham County, Arizona     S0601_C01_001    37879    NA
#>  6 04011 Greenlee County, Arizona   S0601_C01_001     9504    NA
#>  7 04012 La Paz County, Arizona     S0601_C01_001    20701    NA
#>  8 04013 Maricopa County, Arizona   S0601_C01_001  4253913    NA
#>  9 04015 Mohave County, Arizona     S0601_C01_001   206064    NA
#> 10 04017 Navajo County, Arizona     S0601_C01_001   108705    NA
#> 11 04019 Pima County, Arizona       S0601_C01_001  1019722    NA
#> 12 04021 Pinal County, Arizona      S0601_C01_001   419721    NA
#> 13 04023 Santa Cruz County, Arizona S0601_C01_001    46584    NA
#> 14 04025 Yavapai County, Arizona    S0601_C01_001   224645    NA
#> 15 04027 Yuma County, Arizona       S0601_C01_001   207829    NA
```

**API response**
```
[["S0601_C01_001E","S0601_C01_001M","NAME","state","county"],
["37879","-555555555","Graham County, Arizona","04","009"],
["4253913","-555555555","Maricopa County, Arizona","04","013"],
["46584","-555555555","Santa Cruz County, Arizona","04","023"],
["20701","-555555555","La Paz County, Arizona","04","012"],
["206064","-555555555","Mohave County, Arizona","04","015"],
["140217","-555555555","Coconino County, Arizona","04","005"],
["224645","-555555555","Yavapai County, Arizona","04","025"],
["9504","-555555555","Greenlee County, Arizona","04","011"],
["419721","-555555555","Pinal County, Arizona","04","021"],
["1019722","-555555555","Pima County, Arizona","04","019"],
["53400","-555555555","Gila County, Arizona","04","007"],
["126279","-555555555","Cochise County, Arizona","04","003"],
["71522","-555555555","Apache County, Arizona","04","001"],
["207829","-555555555","Yuma County, Arizona","04","027"],
["108705","-555555555","Navajo County, Arizona","04","017"]]
```

**Comment by mfherman** [comment]
Also adding that there has been a little discussion of how tidycensus should handle these special "missing" codes (#110, #29). Currently, we convert all of these codes to `NA` when the API response is parsed:
https://github.com/walkerke/tidycensus/blob/8ea418ed9a01543277718007d93425094a82bce2/R/acs.R#L700-L709

For now, I think it's the most straightforward way to handle them, but if there are other solutions, we definitely could consider how to implement.

**Comment by cymonegates** [comment]
Thanks @mfherman! I dug a little deeper and the data are there at the census tract level but not at the aggregate county level like you stated. I'm following a CDC model that uses both S0601_C01_001M and S0601_C01_001E and it would appear that they first pulled the data by census tract level and then summed the values by county so that there were values for S0601_C01_001M. 

This is not an issue with the package, my apologies.

**Comment by mfherman** [comment]
Glad to help! I would note that if you can, using the county level estimates should be more accurate than aggregating the tracts, especially if the modeling you are doing is at the county-level.

**Comment by cymonegates** [comment]
Thank you! It's definitely something I wish to speak with them further about to understand their reasoning.
