### ISSUE TITLE
Make the variables argument optional

### ISSUE THREAD

**Issue by dkyleward** [walkerke/tidycensus#39]
Since this package wraps tigris so nicely, I'd like to be able to use it to download a shapefile without having to include `variables`. The `variables` and `table` arguments should still be required if `geometry = FALSE`.

**Comment by walkerke** [comment]
What advantage would this have over simply using tigris?

**Comment by dkyleward** [comment]
To allow people to simply have (and get familiar with) one package.

**Comment by dkyleward** [comment]
It's certainly not a critical update - just a nice to have. The user can always just toss in one variable string.

**Comment by walkerke** [comment]
Closing this as a) I'd like to keep the purposes of tidycensus and tigris fairly distinct from one another, and b) not all Census geographies are supported in tidycensus, so I don't want to introduce confusion.

**Comment by dkyleward** [comment]
Oh OK. I didn't realize that last part. Makes sense to me.
