### ISSUE TITLE
2010 5-year PUMS data bug

### ISSUE THREAD

**Issue by mfherman** [walkerke/tidycensus#392]
As discussed on the [Census Slack](https://uscensusbureau.slack.com/archives/CC7DYQ8PM/p1626119420031700), there is a bug impacting data returned by the API for the 2010 5-year PUMS. About 1/3 of records are missing and the data downloaded via API and `get_pums()` is currently incorrect. Census developers are working to correct the issue. The bug appears to be isolated to 2010 5-year PUMS data exclusively.

**Comment by walkerke** [comment]
Thanks @mfherman!

**Comment by mfherman** [comment]
Resolved by Census staff!
