### ISSUE TITLE
Error in if (combined.weights & probably.not.combined.weights) warning(paste("Data do not look like combined weights: mean replication weight is",: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by mdonova** [walkerke/tidycensus#394]
Hi!
Sorry to bother you again but do you know what an error of 

"Error in if (combined.weights & probably.not.combined.weights) warning(paste("Data do not look like combined weights: mean replication weight is",: missing value where TRUE/FALSE needed
In addition: There were 50 or more warnings (use warnings() to see the first 50)"

means? It occurs when I try to convert a data frame of 2005-2009 PUMS data from CA into tbl_svy. I've tried converting the weights to numeric and using both person and household weights but neither has helped. 

Thank you so much!

**Comment by walkerke** [comment]
Can you post your code so I can reproduce the error?

**Comment by walkerke** [comment]
I can reproduce the error.  The issue is that we're currently returning all data not in the data dictionary (so, anything older than 2017) as character strings which is not interpretable directly as weights without conversion.  This should be a quick fix!

**Comment by mdonova** [comment]
Sorry I missed your earlier comment! Is it something I can fix from my end or is it only fixable on yours?

**Comment by walkerke** [comment]
Just fixed it and confirmed it is working - we now convert all weights columns including replicate weights to numeric for the years 2016 and earlier.  Re-install from GitHub with `remotes::install_github("walkerke/tidycensus")` and try out your code to confirm that it works.

**Comment by mdonova** [comment]
I did that and now it is giving me the error: "Error: Your API call has errors.  The API message returned is There was an error while running your query.  We've logged the error and we'll correct it ASAP.  Sorry for the inconvenience." even when I try to load only one PUMA of data. 

remotes::install_github("walkerke/tidycensus", force = TRUE)

ca_pums_2005 <- get_pums(
  variables = c("SEX", "AGEP", "POVPIP", "FHISP", "SCHL", "COW", "PAP", "HINCP", "GRPIP", "RACBLK", "FS", "TEN"), 
  state = "CA",
  puma = c("01101"),
  survey = "acs5",
  year = 2009,
  rep_weights = "both", 
  key = ""
  )

Thank you so much for all your help, sorry about dragging this on

**Comment by walkerke** [comment]
That is an error on the Census website side of things - I saw that hiccup today too.  You'll just have to try again later.

**Comment by mdonova** [comment]
Ahhh of course, thank you so much!

**Comment by mdonova** [comment]
Hmmm, it's still giving me that same error. Is there anything beyond installing the GitHub package I need to do? I tried loading it using library() but that didn't work.

**Comment by mdonova** [comment]
The command worked in R but not in RStudio. Any idea why that might be the case?

**Comment by walkerke** [comment]
perhaps RStudio has a request timeout setting.  Could you post the exact code you are using so I can test it?

**Comment by walkerke** [comment]
Your request is working fine for me in RStudio.  You might consider breaking your request up into separate chunks if you are hitting timeout errors, e.g. requesting the person and housing replicate weights separately.  Also given the size of your requests IPUMS might be a better solution than tidycensus for your work, it sounds like.

**Comment by mdonova** [comment]
Cleaning out all previous installations of tidycensus fixed it -- I have a feeling it was accessing an earlier version of the package in RStudio for some reason until I reset it. Thank you so so much for all your help!
