### ISSUE TITLE
is block group for "get_acs" only available beyond a certain year?

### ISSUE THREAD

**Issue by hiyer09** [walkerke/tidycensus#396]
Hello, many thanks for this incredible resource! I am trying to obtain block group data for some census measures in the ACS from 2010.

After loading libraries and setting my census key, when I run this code:
  
  cens00sf3 <- get_acs(state="HI", geography = "block group", year = 2010,
                       variables = c("B25077_001","B19113_001",...(lots of other variables),"B19001B_017") 
  )

I get the following error:

Getting data from the 2006-2010 5-year ACS
Fetching block group data by county and combining the result.
Error: Request failed after 3 attempts

But it works fine when I change year to 2018.. does this just mean that ACS 2006-2010 doesn't have block group level data available?

Thanks so much!

**Comment by walkerke** [comment]
Unfortunately, that's correct.  Census removed block groups from the API prior to 2013 and I believe has no plans to restore them.  I'd recommend using NHGIS instead for this data.

**Comment by hiyer09** [comment]
Gotcha - thanks so much!
