### ISSUE TITLE
Geometry for LA County - Dropping Catalina Island area

### ISSUE THREAD

**Issue by bcongelio** [walkerke/tidycensus#399]
Hello - 

Not really an "issue" per se, but I have been pulling my hair out over this and am finally giving up and reaching out for help.

I am running the following code:

```
la_county <- get_acs(
  geography = "tract",
  state = "CA",
  county = "Los Angeles",
  variables = c(White = "B03002_003",
                Black = "B03002_004",
                Native = "B03002_005",
                Asian = "B03002_006",
                Hispanic = "B03002_012"),
  summary_var = "B03002_001",
  geometry = TRUE) %>%
  mutate(percent = 100 * (estimate / summary_est))
```

It works fine, except for a `shape la_county contains empty units` but running this fixes the issue:

`la_county <- la_county[-c(11721:11730), ]`

That said, the map output includes Santa Catalina Island and San Clemente Island, which really throws off the visual impact of mapping data over LA County.

**I have tried and tried but cannot figure out how to pull the tracts while also NOT including Catalina and San Clemente Islands.**

Any help is greatly appreciated.
![Rplot](https://user-images.githubusercontent.com/57458963/131563118-51286140-4ff9-47e9-bff2-233605e373dc.png)

**Comment by mfherman** [comment]
Hi @bcongelio! If I understand what you're trying to do correctly, I think the easiest way to handle this would be to remove the tracts that are on Catalina and San Clemente from the data downloaded for the entire county.

``` r
library(tidyverse)
library(tidycensus)

la_county <- get_acs(
  geography = "tract",
  state = "CA",
  county = "Los Angeles",
  variables = c(White = "B03002_003",
                Black = "B03002_004",
                Native = "B03002_005",
                Asian = "B03002_006",
                Hispanic = "B03002_012"),
  summary_var = "B03002_001",
  geometry = TRUE
  ) %>%
  mutate(percent = 100 * (estimate / summary_est))

island_tracts <- c("06037599100", "06037599000", "06037599100")

la_no_islands <- la_county %>% 
  filter(!GEOID %in% island_tracts)

la_no_islands %>% 
  ggplot() +
  geom_sf() +
  theme_void()
```

![](https://i.imgur.com/KPj0Fne.png)

<sup>Created on 2021-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bcongelio** [comment]
That is exactly what I was trying to do.

I figured I had to remove the tracts, but could not figure out which ones were associated with the islands. Is there an easy way I am overlooking to figure that out?

**Comment by mfherman** [comment]
For stuff like that, I love the [mapview package](https://r-spatial.github.io/mapview/)! If you've got an sf object, it's a simple as running:

```
library(mapview)
mapview(la_county)
```

And you get an interactive map, which I then hovered on tracts on the islands to find their GEOIDs.
