### ISSUE TITLE
School districts for 2000 decennial

### ISSUE THREAD

**Issue by markskrass** [walkerke/tidycensus#404]
Thank you so much for this amazing tool!

School district ("..(elementary)", "...(unified)", etc.) is currently supported only for the 2010 decennial. Wondering if this can be extended back to the 2000 decennial. Thanks!

**Comment by markskrass** [comment]
Sorry, realized this is an impossible request. Withdrawn!

**Comment by walkerke** [comment]
Thanks for the kind words!  Yeah, the Census API does not include school district data for 2000.
