### ISSUE TITLE
Household Pulse Survey

### ISSUE THREAD

**Issue by chrowe** [walkerke/tidycensus#412]
Are there any plans to add support for the Household Pulse Survey data to tidycensus?
If not, any suggestions on the best way to tidy that data and make it available for other to use?

**Comment by mfherman** [comment]
I think that's prob outside the scope of this package, but @UrbanInstitute has pulled the data together here: https://datacatalog.urban.org/dataset/census-pulse-public-use-files-questionnaire-two and have a [repo with all their cleaning code](https://github.com/UrbanInstitute/pulse_covid_feature_phase2).
