### ISSUE TITLE
GEOID column rename causing error with get_decennial 2020 data

### ISSUE THREAD

**Issue by dkori** [walkerke/tidycensus#415]
I'm using version 1.1.0.900, let me know if I need to provide more session info. I'm getting an error running the following:
```
tidycensus::get_decennial( geography = "block", year = 2020, variables = "P1_003N", state='PA', county='Allegheny',geometry=TRUE)
```
Returns this:
```
Getting data from the 2020 decennial Census
Using FIPS code '42' for state 'PA'
Using FIPS code '003' for 'Allegheny County'
Using the PL 94-171 Redistricting Data summary file
Downloading: 260 MB     Error : Can't rename columns that don't exist.
x Column `GEOID20` doesn't exist.
Error: Your geometry data download failed. Please try again later or check the status of the Census Bureau website at https://www2.census.gov/geo/tiger/
```
I looked at the helper function code and it looks like there's a step to rename GEOID to GEOID20, but I'm not exactly sure when its being called.

**Comment by mfherman** [comment]
Just ran this on my machine and it's working for me. Can you make sure you have the most recent version of **tigris** (`1.5.0.9000`) installed as well and test again?

**Comment by walkerke** [comment]
@mfherman is correct - this requires tigris 1.5 or higher.  This reminds me - I need to put this version dependency in `Imports` in the next tidycensus release!
