### ISSUE TITLE
Unable to load 'sf' package into R

### ISSUE THREAD

**Issue by nishikandy** [walkerke/tidycensus#416]
I've been trying to install the 'tidycensus' package into R for the past 2 hours and have been failing! It keeps giving me the following message:

[](ur
![WhatsApp Image 2021-11-26 at 22 48 42](https://user-images.githubusercontent.com/89440707/143672368-2c27d034-0b37-4608-a5e9-ca68e137141c.jpeg)
l)

I have tried updating the 'dplyr' package and also reinstalling it. I've restarted r multiple times but it's not working! What do I do from here?

**Comment by szimmer** [comment]
Did you try installing the **sf** package? That seems to be the issue. 

```
install.packages("sf")
```

**Comment by nishikandy** [comment]
I have tried that, yes. It says there’s no package called “sf” and fails to download. I have tried downloading the sf package from CRAN but I am not sure I’m not downloading the right one. Is there anything else I can try?

**Comment by walkerke** [comment]
@nishikandy sf can be tricky to install as it requires some system dependencies.  I'd recommend reading through the installation error messages you get and reviewing the instructions at https://github.com/r-spatial/sf#installing for your operating system, which can help quite a bit.
