### ISSUE TITLE
Problem with sample in  "cxy_geocode"  documentation

### ISSUE THREAD

**Issue by donojazz** [walkerke/tidycensus#417]
When running sample directly from "cxy_geocode"  documentation

x <- stl_homicides[1:10,]
# geocode
cxy_geocode(x, street = 'street_address', city = 'city', state = 'state', zip = 'postal_code',
   return = 'locations', class = 'dataframe', output = 'simple')

I get this error:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to 127.0.0.1 port 1080: Connection refused

**Comment by szimmer** [comment]
I think the `cxy_geocode` function is in the **censusxy** package and not in **tidycensus**. I recommend moving this issue to there: https://github.com/slu-openGIS/censusxy/issues

**Comment by donojazz** [comment]
You'r right.  Thank you.  I submitted there.  I wonder if there is a better geocoder available?

**Comment by mfherman** [comment]
Another option is [tidygeocoder](https://jessecambon.github.io/tidygeocoder/) which has options to use a number of geocoders like the US Census, OSM, ESRI, etc
