### ISSUE TITLE
Trying to pull table CP04 - Comparative Housing Characteristics

### ISSUE THREAD

**Issue by thomasrgomes** [walkerke/tidycensus#422]
I am trying to pull table CP04 - Comparative Housing Characteristics and have been unsuccessful, can you provide guidance on why this is? Or how to do it if the data are available? Thanks!

**Comment by walkerke** [comment]
tidycensus doesn't support the CP tables at this time, mostly because I haven't gotten requests for it.  You could take a look at censusapi which would support it; I may take a look at supporting it as well.
