### ISSUE TITLE
get_pums(state = "all", year = 2019, survey = "acs5") doesn't appear to be working

### ISSUE THREAD

**Issue by cpsievert** [walkerke/tidycensus#425]
Thanks for this great package! Here's a minimal example:

```r
tidycensus::get_pums(
  c("PUMA", "AGEP"), 
  survey = "acs5",
  year = 2019,
  state = "all",
  show_call = TRUE
)
```

```r
Getting data from the 2015-2019 5-year ACS Public Use Microdata Sample
Requesting data for the entire United States by state then combining the result.
This can take several minutes to complete.
For large data extract workflows, consider downloading data from the Census FTP server
or from IPUMS (https://ipums.org) instead.
  |======================================================================| 100%
Error: Your API call has errors.  The API message returned is There was an error while running your query.  We've logged the error and we'll correct it ASAP.  Sorry for the inconvenience..
```

**Comment by walkerke** [comment]
Hi @cpsievert!  I'm a long-time user of your packages.  

I just ran this command successfully.  The error you've encountered is on the API side that can show up when the Census PUMS API is down.  Over on the [Census Bureau Slack](https://uscensusbureau.slack.com/archives/C6DGLC05B/p1639524868141000) people have noted that the API tends to experience downtime in the evenings around when you tried it.  

If you do need to pull the full 5-year sample in a more stable way you might consider using the [raw data from Census](https://www2.census.gov/programs-surveys/acs/data/pums/2019/5-Year/) or checking out IPUMS which formats the data quite nicely.  I have given some thought to methods for caching data downloads using memoisation (https://github.com/walkerke/tidycensus/issues/346) but I haven't gotten around to implementing it.

**Comment by cpsievert** [comment]
Ahh, good to know, I suspected that might be case -- I've got it to run successfully now, thanks!
