### ISSUE TITLE
seeking within-state rural areas summary level 040 component 43

### ISSUE THREAD

**Issue by donboyd5** [walkerke/tidycensus#426]
Thanks for this really great package. I'm using it to look at selected rural areas in New York, using ACS 5-year summary files, years ending 2019, 2014, 2009.

I'd love to be able to compare to overall state rural averages -- summary level 040 component 43 but am not sure I can extract them using `tidycensus`.

If there is a way to do so, would you mind letting me know? If not, and you are able to add it, would really appreciate it.

Many thanks.

Don

**Comment by walkerke** [comment]
Hi @donboyd5,

Thanks for the note!  Components are not currently supported in tidycensus but I'd like to add that feature.  Until then consider using the censusapi package which is more flexible than tidycensus.  For example:

```r
library(censusapi)

ny_rural_income <- getCensus(
  name = "acs/acs5",
  vintage = 2019,
  region = "state:36",
  GEOCOMP = "43",
  vars = "B19013_001E"
)
```
```
> ny_rural_income
  state B19013_001E
1    36       68486
```

**Comment by donboyd5** [comment]
Sorry for the long delay. Forgot to reply. 

Meanwhile, I wanted to let you know I have used tidycensus a lot on a recent project with the ACS summary files and found it enormously valuable. I appreciate your work.
