### ISSUE TITLE
Mapping between FIPS and ZIP 

### ISSUE THREAD

**Issue by PursuitOfDataScience** [walkerke/tidycensus#427]
Hi Dr. Walker,

Thanks for `tidycensus` an amazing R package. I've been looking inside the package to see if it provides the crosswalk between county FIPS code and zipcode across the U.S. I haven't found any, but out of curiosity, does the package provide such information? If no, could you tell me where I can find it? It would be great to have a `tibble` or csv file, etc. I do have the crosswalk file, but a lot of county FIPS codes are missing. Hope you can shed some light in this regard. Thanks!

**Comment by szimmer** [comment]
ZIP codes in the United States are NOT geographic areas. They are instead a set of addresses. They are roughly approximated by zip code tabulation areas (ZCTAs). ZIP codes can cross county and even state boundaries.

https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html

I sometimes make crosswalks between areas using this tool: https://mcdc.missouri.edu/applications/geocorr2014.html

**Comment by PursuitOfDataScience** [comment]
Thanks for the input, but I still want to have a rough connection between them. Otherwise, the data aggregation work would be tricky, as some data is on county level, others associate with ZIP code.

**Comment by szimmer** [comment]
You could try using that crosswalk but it isn't a 1:1 match. Best of luck!

**Comment by RickPack** [comment]
@PursuitOfDataScience - are you using the COUNTY-ZIP crosswalk at https://www.huduser.gov/portal/datasets/usps_crosswalk.html or another one?

**Comment by PursuitOfDataScience** [comment]
Thanks @RickPack This is perfect.

![image](https://user-images.githubusercontent.com/54338793/151444664-4e47ac2a-987f-448e-941e-d823347d903f.png)

**Comment by walkerke** [comment]
Thanks all for the discussion!  There is also the [zipcodeR R package](https://gavinrozzi.github.io/zipcodeR/index.html), which may have some of this functionality built-in.
