### ISSUE TITLE
2005-2009 ACS data doesn't include some tables?

### ISSUE THREAD

**Issue by jennahgosciak** [walkerke/tidycensus#428]
Hi there,

I've found tidycensus incredibly helpful. I'm pulling 2005-2009 ACS data and I noticed that some tables (e.g. B06009) aren't included when I look for them with `load_variables(2009, "acs5")`. Is there a reason that I may have missed in the documentation for this? I am able to get the same table using other sources like Social Explorer.

Thank you!

**Comment by walkerke** [comment]
Hi!  This is an issue with the API - Census hasn't migrated all the variables to the new API endpoint.  I pinged Census about it over here: https://github.com/uscensusbureau/api/issues/14 but I don't believe there has been progress on it yet.

**Comment by jennahgosciak** [comment]
Ah got it, thank you so much!
