### ISSUE TITLE
get_acs() returns zero rows when `summary_var` parameter is included

### ISSUE THREAD

**Issue by chrismp** [walkerke/tidycensus#429]
The following code returns a data frame with Census stats.

```
get_acs(
  year = 2019,
  geography = 'zcta',
  survey = 'acs5',
  variables = c(
    'S0101_C01_030'
  )
```

But this code returns a dataframe with zero rows.

```
get_acs(
  year = 2019,
  geography = 'zcta',
  survey = 'acs5',
  variables = c(
    'S0101_C01_030'
  ),
  summary_var = 'B01001_001'
```

This didn't used to happen. Any idea what's causing the second code to return no rows?

**Comment by walkerke** [comment]
This is fixed over in the `estimates2021` branch where I'm working on a few updates that'll be merged soon, so you can install from there if you have an immediate need.  Thanks for the heads up!

**Comment by walkerke** [comment]
Note to self - this needs to be re-visited as currently the 2016-2020 ACS does not allow ZCTA queries by state.  I'll re-write this and push to the master branch.
