### ISSUE TITLE
get_pums() returning error message

### ISSUE THREAD

**Issue by jlinden19** [walkerke/tidycensus#430]
This code keeps returning an error message that says "Your API call has errors. The API message returned is There was an error while running your query. We've logged the error and we'll correct it ASAP. Sorry for the inconvenience."

 `WA_pums_h <- get_pums(variables = "HINCP",
                      state = "WA",
                      survey = "acs1",
                      year = 2019)`

Any ideas on what's going on?

**Comment by walkerke** [comment]
I just ran your code successfully.  I've noticed that the PUMS API sometimes experiences downtime right around the time you filed this issue.  A longer-term solution (for pre-downloaded data) might be to cache PUMS data and use memoisation (see https://github.com/walkerke/tidycensus/issues/346) but I haven't gotten around to it yet.

**Comment by jlinden19** [comment]
Thanks, that must have been it. Working for me again this morning as well!
