### ISSUE TITLE
fatal error when loading package

### ISSUE THREAD

**Issue by rafmbatista** [walkerke/tidycensus#432]
Once I install the 'tidycensus' package it seems I'm unable to load it via R Studio. 
library(tidycensus) produces a 'fatal error' that terminates my R session

**Comment by rafmbatista** [comment]
Hi, no it doesn't. Screenshot provided
![Screen Shot 2022-02-25 at 8 20 50 AM](https://user-images.githubusercontent.com/13202074/155730942-49b3dce5-2689-464f-a480-32eb4352a4d4.png)
t

**Comment by walkerke** [comment]
It does look like sf fails to load which tidycensus depends on.  This isn't likely a tidycensus issue but rather a system issue.  Can you share the results of your sessionInfo()?

**Comment by rafmbatista** [comment]
I think you're right. It seems to be working now. I updated the R software to the latest version (previously at 4.1.0) and had to explicitly install 'Rcpp' package. Now it appears I can go through Basic Usage steps on your website. Thank you!
