### ISSUE TITLE
Missing UR20 values

### ISSUE THREAD

**Issue by kerencrum** [walkerke/tidycensus#433]
When I download the 2020 decennial geo variables the UR20 column is blank. This data is available when I download the block data directly from the TigerLines shapefiles, though. Is there a way to get the Urban/Rural data?

Tbl <- get_decennial(geography = "block", table = "H1",cache_table = TRUE,
                     state = "MT", year = 2020, geometry = TRUE, keep_geo_vars = TRUE, output = "wide")

**Comment by walkerke** [comment]
I just downloaded the block shapefile directly from the Census website and opened it in QGIS; all I see are NULLs for that column.  What do you see?

![image](https://user-images.githubusercontent.com/4872833/155763348-0201718b-4eaf-4fc7-b6dc-f58a7093c857.png)

**Comment by kerencrum** [comment]
Thanks for sharing. I wonder if this is because I'm downloading from the 2021 TigerLine Shapefile but I get this when I open it up in ArcPro:
![UR20](https://user-images.githubusercontent.com/100436186/155785804-ea1f2936-81a4-49a2-a2f9-65e74b71f8bc.png)

**Comment by walkerke** [comment]
Looks like it's just in the 2021 file then, and not in the 2020 file which `get_decennial()` will use.  You can get the 2021 blocks with the __tigris__ package with the command `tigris::blocks(state = "MT", year = 2021)`.  __tidycensus__ won't support the 2021 blocks but you can grab them separately from __tigris__ then join to your demographic data.

**Comment by kerencrum** [comment]
Good to know. Thanks for the suggestion!
