### ISSUE TITLE
Error in View : lexical error: invalid char in json text

### ISSUE THREAD

**Issue by danielludolf** [walkerke/tidycensus#435]
Hi, I am getting the error:

> Error in View : lexical error: invalid char in json text.  
> <html><head><title>Error report 
> (right here) ------^

when running the code below. Is acs1/subject not available before 2010?

`load_variables(2009, 'acs1/subject')`

Thanks!

**Comment by walkerke** [comment]
That's correct.  There is something called "selected population profiles" for 2009 but tidycensus doesn't support that; if that's what you need, you may consider taking a look at the censusapi package.
