### ISSUE TITLE
Add geography parameter to load_variables

### ISSUE THREAD

**Issue by ethantenison** [walkerke/tidycensus#436]
It would be nice if you could add a parameter to load_variables that would allow you to specify geography, Either that, or add a column that lists which geographies each variable is available for. This issue has come up quite a few times. For example, I just recently pulled 25 variables for census tracts, but when I tried pulling the CBG's, less than half were available. I certainly know that you all are very busy though!

Keep up the good work. Appreciate you all.

**Comment by walkerke** [comment]
Thanks for the note!  I agree that this would be a great feature.  To the best of my knowledge this is not published anywhere which is why I haven't included it.  One way to do it would be to crawl the detailed tables by variable and record the smallest geography available for each variable; this might be an interesting exercise.

**Comment by mfherman** [comment]
Agree that this would be useful! There is some discussion of this as a [feature request for the Census API here](https://github.com/uscensusbureau/api/issues/1)

**Comment by szimmer** [comment]
That spreadsheet is not completely accurate, unfortunately. At my previous job, we went through the process of hitting every table for every geography to learn what was available where and it didn't match but it was close and maybe good enough with some notes that it is as accurate as Census reports.

**Comment by walkerke** [comment]
@szimmer Thank you, that's really helpful info.  I may try writing a crawler then today for the 2019 5-year and see how long it takes.  If it works we can deploy for all years and add this feature.

**Comment by walkerke** [comment]
I've got a prototype of this prepared; the idea will be to store these tables as efficiently as possible and join them to the variables information before returning a data frame in `load_variables()`.  

![image](https://user-images.githubusercontent.com/4872833/158675484-7c777d8c-64d7-41a0-9aaf-b28c2de68e8a.png)

I'll re-visit this as a feature after we make sure that 2016-2020 data is working fine after tomorrow's release.

**Comment by walkerke** [comment]
This is now implemented for the 5-year ACS Detailed Tables between 2011 and 2020:

```
> load_variables(2020, "acs5")
# A tibble: 27,850 × 4
   name       label                                    concept    geography  
   <chr>      <chr>                                    <chr>      <chr>      
 1 B01001_001 Estimate!!Total:                         SEX BY AGE block group
 2 B01001_002 Estimate!!Total:!!Male:                  SEX BY AGE block group
 3 B01001_003 Estimate!!Total:!!Male:!!Under 5 years   SEX BY AGE block group
 4 B01001_004 Estimate!!Total:!!Male:!!5 to 9 years    SEX BY AGE block group
 5 B01001_005 Estimate!!Total:!!Male:!!10 to 14 years  SEX BY AGE block group
 6 B01001_006 Estimate!!Total:!!Male:!!15 to 17 years  SEX BY AGE block group
 7 B01001_007 Estimate!!Total:!!Male:!!18 and 19 years SEX BY AGE block group
 8 B01001_008 Estimate!!Total:!!Male:!!20 years        SEX BY AGE block group
 9 B01001_009 Estimate!!Total:!!Male:!!21 years        SEX BY AGE block group
10 B01001_010 Estimate!!Total:!!Male:!!22 to 24 years  SEX BY AGE block group
# … with 27,840 more rows
```

I don't think this is as high a priority for other datasets as I _think_ all variables are typically available at all geographies in other datasets (e.g. everything is tract and up in the ACS Data Profile), though someone please correct me if I'm wrong about this.

**Comment by ethantenison** [comment]
This is so awesome! I know this feature will be used greatly in my own work and the work I do with graduate students and nonprofits.
