### ISSUE TITLE
get_acs() unable to pull zcta data from 2020 ACS 5-year

### ISSUE THREAD

**Issue by atorgerson** [walkerke/tidycensus#440]
I'm having trouble using `get_acs()` to pull ZCTA-level data from the 2020 ACS 5-Year Estimates. 

```
zcta_mo <- 
  get_acs(
    year = 2020, 
    geography = "zcta", 
    state = "MO", 
    survey = "acs5", 
    table = "B01003" # total population
  )
```

Returns: 
```
Getting data from the 2016-2020 5-year ACS
Using FIPS code '29' for state 'MO'
Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.
```

Changing to `year = 2019` returns 2019 ACS data as expected.

**Comment by walkerke** [comment]
This will work if you remove the state.  Unfortunately Census didn't include a state option for ZCTA in the 2016-2020 ACS API like they have for previous years, so you'd need to filter down.  An (admittedly inferior) option is to find the ZCTAs from the previous year, then filter for the zips you need:

```r
library(tidycensus)
library(tidyverse)

mo_zctas <- get_acs(
  geography = "zcta",
  variables = "B01001_001",
  state = "MO",
  year = 2019
)

zcta_mo_2020 <- get_acs(
  geography = "zcta",
  variables = "B01003_001",
  year = 2020
) %>%
  filter(GEOID %in% mo_zctas$GEOID)
```

You'll need the GitHub version for this at the moment, however.  I believe this will be fixed on Census's side in the near future.
