### ISSUE TITLE
Add tools and workflow for iterative proportional fitting (PUMA to tract)

### ISSUE THREAD

**Issue by plnnr** [walkerke/tidycensus#442]
With the addition of `get_pums()` to `{tidycensus}`, I am wondering if other users would find benefit of some additional tools to assign results of PUMA-level data to census tracts using iterative proportional fitting (IPF). 

There is some documentation [here](https://acsdatacommunity.prb.org/cfs-file/__key/widgetcontainerfiles/3fc3f82483d14ec485ef92e206116d49-s-AAAAAAAAAAAAAAAAAAAAAA-page-02015_5F00_acs_5F00_conference-yUeQ33zvuUaDj0K62vzDpw-html/Mortveit.pdf) and [here](https://www.sciencedirect.com/science/article/abs/pii/0965856496000043) and [here](https://www.huduser.gov/portal/periodicals/cityscpe/vol13num3/Cityscape_Nov2011_beginners_guide.pdf). Is this something @walkerke or other contributors have been thinking about? Personally, I don't have experience with IPF, but I know it would be useful to estimate specific cross-tabulations that aren't available in the base table ACS.

**Comment by walkerke** [comment]
While this isn't something I'll likely implement in tidycensus in the near future, a development branch of the mlfit R package has a vignette in progress that illustrates how to do this with tidycensus.  It might be of interest to take a look at!

https://github.com/mlfit/mlfit/blob/get-started/vignettes/get-started.Rmd
