### ISSUE TITLE
Potentially wrong brackets in helpers.R

### ISSUE THREAD

**Issue by deschen1** [walkerke/tidycensus#443]
Looking at helpers.R I'm confused about they curly brackets and if else setting, i.e.

Line 416 has the if(install) statement and opens a curly bracket.
Then there are two condition checks for file.exists and !file.exists in lines 419 and 423.
So the file either exists or doesn't. With these two conditions there can't be any other cases. Yet in line 426 there is an else command which, IMO, is still nested within the original if command from line 416.

Am I missing something here or should the else command come somewhere else?

**Comment by walkerke** [comment]
Is something not working when you are trying to install your API key?

**Comment by deschen1** [comment]
I can't say yet. I just checked the census_api_key function because I want sth. similar for my own package and encountered this issue. And I think the respective else command would never be called (but I can check).

**Comment by deschen1** [comment]
Ok, I think I just got confused by the structure a bit. So what you are essentially doing is:

- `if (!file.exists(renv))` you create renv.
- `if (file.exists(renv))` you do file.copy AND you are running the else command after the `if (!file.exists(renv))`

Right?

So if renv exists, the code in lines 419-421 AND 426-437 is run.

If that't the intention, then please close the issue.
