### ISSUE TITLE
Specify valid geography argument values

### ISSUE THREAD

**Issue by JosiahParry** [walkerke/tidycensus#445]
`get_estimates()` argument `geography` does not enumerate what valid arguments are. https://github.com/walkerke/tidycensus/blob/681eb790984c9019ee4cfec0ff9249f94c912a8f/R/estimates.R#L3

It would be helpful if the default argument was a vector of possible values, or they were listed in the argument documentation. Additionally, the use of `match.arg()` would be very informative here. 

The only location I can find the valid geography arguments are at https://walker-data.com/tidycensus/articles/basic-usage.html

**Comment by walkerke** [comment]
This is a good idea.  The PEP API is in flux at the moment (Census just released new data, but didn't release to the API and has no timetable for doing so) so I've held off on updating `get_estimates()` for that reason.  It'll be part of my next development push on the package now that version 1.2 was just released on CRAN this week.

**Comment by lpiep** [comment]
FYI I am working through a PR for this. It is unfortunately a little more complicated than I first thought, because different geographies (and even variables) are available depending on the year of the data. I'm thinking I will put together an data.frame with the availability of each geography and variable by year, similar to how `acs5` is done, then point the user to that to determine which geography to request.

This could also be used to throw a more helpful error message if the user specifies a non-existent geography, by looking up the actual available geographies for the specified year and including those in the error message.

**Comment by JosiahParry** [comment]
I think an unexported list object would be useful for checking valid
arguments. You could use it as a lookup and feed it to match.arg(). This
would probably be more efficient and useful than a data frame

**Comment by walkerke** [comment]
@lpiep appreciate this.  A couple things about any work on `get_estimates()` at this stage: 

- I'm unsure what the future of this function looks like.  [The Census Bureau just released the final batch of data for the 2021 estimates](https://www.census.gov/programs-surveys/popest/data/tables.html) but did not release to the API; I've been in some communication with them about it and they have no timetable for doing so.  I _could_ update the function using CSV downloads (similar to how the [lehdr](https://github.com/jamgreen/lehdr) package does it) but that would be a fairly significant development push and may end up being a waste of time if they ultimately release to the API anyway, as I'd then need to refactor.
- The time-series structure of the Population Estimates Program is confusing.  Users should always use the most recent year available for a given decennial series (so, `year = 2019` for the 2010s) and then use `time_series = TRUE` to get earlier years as Census revises the old estimates with each updated release.  So I'm less concerned about supporting geographies by year - 2019 is really the one that matters.  The new data, however, are 2021 with a 2020 base - supporting that, though, would depend on resolving the previous point.  

For now, some enumeration of what's available from https://api.census.gov/data/2019/pep/population/geography.html is all that is needed at the moment.  I would really like to get the new estimates into __tidycensus__ in some way - but it seems that the geographies are the same / similar for the new data and we can adjust as needed when that happens.

**Comment by lpiep** [comment]
Thanks @walkerke. I will just add the 2019 geography options to the function definition and check arguments, and add your recommendation about using 2019 data for all 2010s to the documentation.

**Comment by walkerke** [comment]
Excellent.  Census pinged me back and said that we will get population estimates for 2021 and later on the API eventually; however there is still no timetable for that .
