### ISSUE TITLE
SAIPE and SAHIE access?

### ISSUE THREAD

**Issue by mfherman** [walkerke/tidycensus#446]
Heya @walkerke! I know you've been busy adding some tremendous features to the package. Really excited to use the dot density function soon.

 Recently at work I've started to use the [SAIPE](https://www.census.gov/programs-surveys/saipe/data/api.html) and [SAHIE](https://www.census.gov/programs-surveys/sahie/data/api.html) APIs to pull poverty and health insurance data for all counties. Do you think these fit in the scope of tidycensus? If so, I can work on cleaning up my code over the next few weeks and build out `get_saipe()` and `get_sahie()` for tidycensus,.

**Comment by walkerke** [comment]
Hi @mfherman!  Of course, that'd be great!  I think that the package can continue to evolve with new features over time; it'll never cover _everything_ but incremental additions like this make sense.
