### ISSUE TITLE
Possible to Pull Down National Level Numbers?

### ISSUE THREAD

**Issue by benjaminrobinson** [walkerke/tidycensus#45]
I'm trying to pull down national numbers but the highest level of geography seems to be states, where I could get national estimates by adding up state values.  I'd rather not do that if possible given the margins of error.  Is there a way to do that within the tidycensus package?  Thanks for developing this.  Its really great stuff!

**Comment by walkerke** [comment]
Yes - use `geography = "us"`.  Available geographies and how to format them are here: https://api.census.gov/data/2015/acs/acs5/geography.html.  I had an error message pointing users there but I think it's getting superseded by another error message; I'll have to fix that.

**Comment by benjaminrobinson** [comment]
Thanks @walkerke for the quick response!
