### ISSUE TITLE
get_pums  problem with na values 

### ISSUE THREAD

**Issue by Shadi-Sadie** [walkerke/tidycensus#450]
Hi Kyle, 

First, I want to thank you for providing this package! 

I am having trouble dealing with missing data when I use get_pums to get the subset of data. When I use the pums, the NA will be receded to a numerical value that is different for different variables.

I used the following code to get a subset of 2019 data 
data <- get_pums(
        variables = c ("REGION","AGEP", "CIT" , "ENG" , "FER","HIMRKS", "HINS1", 
                       "HINS2", "HINS3" , "HINS4","HINS5", "HINS6", "HINS7", "LANX", 
                       "MAR", "SCHL", "SEX", "YOEP", "ANC1P","DIS","HICOV", "ESR", 
                       "LANP", "NATIVITY","HISP", "POBP", "POVPIP", "PUBCOV","PRIVCOV", "RAC1P"),
        state = "all",
        year = 2019, 
        survey = "acs1",
        variables_filter = list(
                AGEP = 25:64
        ),
        rep_weights = "person", 
        recode = FALSE
)

When I am looking at the YOEP (year of entry to US), I get this result in which NA are shown as 1928 

<img width="746" alt="Screen Shot 2022-04-26 at 12 48 34 PM" src="https://user-images.githubusercontent.com/62895863/165358876-3040fd56-e0f5-4bb4-b43f-1aa208ac9e0b.png">

Now, when I am looking at the LANP (Language spoken at home), the missing values are recoded as 0999 

<img width="710" alt="Screen Shot 2022-04-26 at 1 34 17 PM" src="https://user-images.githubusercontent.com/62895863/165359585-17a14236-d556-48a9-9f20-949b0b2cad9e.png">

Is there something I am missing in the get_pums ?

**Comment by walkerke** [comment]
You aren't missing anything.  It looks like Census changed its variable spec for NA values in the API, which now deviates from the flat files.  

The good news is: we now can have variable recoding and lookup for all PUMS datasets!  The bad news is I have some work to do to fix this in tidycensus.  I'll start taking a look at it.

**Comment by walkerke** [comment]
Closing this as I'll be tracking the resolution over in #451.
