### ISSUE TITLE
Transition `pums_variables` to `pums_variables()`

### ISSUE THREAD

**Issue by walkerke** [walkerke/tidycensus#451]
Tagging @mfherman and any other PUMS users - 

It was drawn to my attention in #450 that the Census API has changed the values of many "NA" categories on the API side, now deviating from the flat files.  We use the codebooks from the flat files to generate `pums_variables`, so we now have some inconsistencies to deal with.  

The good news is that Census has now posted variable and value definitions for PUMS data all the way back to 2004, e.g. https://api.census.gov/data/2004/acs/acs1/pums/variables.json.  This will allow us to enable `recode = TRUE` for all years, which is great.  

An updated `pums_variables` that includes variable and value definitions for all years could get hefty, however.  I'm proposing transitioning this to a `pums_variables()` function that works similarly to `load_variables()`.  It'd work like this: 

```r
pums_variables(year = 2020, survey = "acs5")
```

then parse the variables JSON from the Census website and format them in an identical way to how we currently have `pums_variables` set up.  This would minimize the edits we'd need to make to the existing codebase for recoding.

I'm going to start digging into this late this week / early next.

**Comment by mfherman** [comment]
Oh that’s great! Are you thinking that if a user sets `recode = TRUE` we would call `pums_variables()` within `get_pums()` and then recode based on the parsed variable results?

I might have some time later this week to take a crack as well. If I start, I’ll open up a branch.
