### ISSUE TITLE
Newest R update prevents the installation of tidycensus

### ISSUE THREAD

**Issue by Emman-Lopez-Oso** [walkerke/tidycensus#452]
It seems that it is particularly having trouble with the dependency for `rgdal`. 

R-Version: 4.2
R-Studio Version: 2022.02.1 Build 461
Platform: x86_64-apple-darwin17.0 
OS: Monterey 12.2.1 (21D62)

```> library(tidycensus)
Error in library(tidycensus) : there is no package called 'tidycensus'
> install.packages("tidycensus")

  There is a binary version available but the source version is later:
           binary source needs_compilation
tidycensus  1.1.2  1.2.1             FALSE

installing the source package 'tidycensus'

trying URL 'https://cran.rstudio.com/src/contrib/tidycensus_1.2.1.tar.gz'
Content type 'application/x-gzip' length 2163672 bytes (2.1 MB)
==================================================
downloaded 2.1 MB

* installing *source* package 'tidycensus' ...
** package 'tidycensus' successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'rgdal'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'tidycensus'
* removing '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/tidycensus'
Warning in install.packages :
  installation of package 'tidycensus' had non-zero exit status

The downloaded source packages are in
	'/private/var/folders/qm/jwhz0tlx4n597lbsp71lbrpc0000gp/T/RtmpBMdrOm/downloaded_packages'```

**Comment by walkerke** [comment]
Hmm - I haven't updated to 4.2 yet so this is helpful information.  The __rgdal__ dependency is coming through from __tigris__ and perhaps it is time to remove __sp__ support from __tigris__ so this isn't an issue any longer.  In the meantime you'll probably want to try to install __rgdal__ directly first then try installing __tidycensus__ again.

**Comment by walkerke** [comment]
I can confirm that tidycensus installs just fine on R 4.2 on Windows, so this appears to be a Mac-specific issue.  I do know that the r-spatial authors recommend installing binaries on Mac rather than from source, so you might look into that.

**Comment by Emman-Lopez-Oso** [comment]
@walkerke, sadly it's the same situation on that front as well. I'll look into installing the binaries now and let you know how that goes.

**Comment by Emman-Lopez-Oso** [comment]
By downloading the binary of RGDAL version: r-release (x86_64): [rgdal_1.5-30.tgz](https://cran.r-project.org/bin/macosx/contrib/4.2/rgdal_1.5-30.tgz), it looks like I managed to corrupt my version of RGDAL, thus rendering tidycensus inoperable. 

Version 1.5-31 doesn't operate in my instance.

**Comment by walkerke** [comment]
@Emman-Lopez-Oso I'm not a Mac user so unfortunately I'm limited in how helpful I can be here.  Perhaps this thread has some tips?  https://github.com/r-spatial/sf/issues/1536

**Comment by Emman-Lopez-Oso** [comment]
@walkerke, problem seemed to originate from the compilation option. When choosing not to compile, the installations work just fine. Closing this issue now.
