### ISSUE TITLE
Alternatives to rgdal dependency?

### ISSUE THREAD

**Issue by nadiabey** [walkerke/tidycensus#455]
I recently updated R to version 4.2.0, but I am unable to load tidycensus because rgdal is not installed. Attempting to install it gives `Warning in install.packages :
  package ‘rgdal’ is not available for this version of R`
According to [CRAN](https://cloud.r-project.org/web/checks/check_results_rgdal.html), rgdal hasn't been working on Intel-based Macs as of late. Are there any alternatives to using rgdal or workarounds for this issue?

**Comment by walkerke** [comment]
Have you read this thread? https://github.com/walkerke/tidycensus/issues/452

If those steps don't work, please let me know.  I'm planning to remove the downstream dependency on rgdal (which comes from tigris) fairly soon.

**Comment by nadiabey** [comment]
The first few steps in terminal worked, but I'm now getting an error configuring geos/gdal because geos_c.h cannot be found.

**Comment by walkerke** [comment]
Can you use the sf package, or is it the same problem there?
