### ISSUE TITLE
get_acs() unable to pull zcta data from 2019 or 2020 ACS 5-year

### ISSUE THREAD

**Issue by askay1** [walkerke/tidycensus#458]
Hello,
 The below does not work for 2019 or 2020 though it works for 2018 or 2017.  Any thoughts?

zcta_SVI_v2 <- get_acs(geography = "zip code tabulation area", variables = my_svi_vars, state = my_states,year = 2020, survey = "acs5")

Returns:

Getting data from the 2016-2020 5-year ACS
Fetching data by table type ("B/C", "S", "DP") and combining the result.
Error in stop_rate_excess():
! Request failed after 3 attempts
Backtrace:

tidycensus::get_acs(...)
purrr::map_df(...)
purrr::map(.x, .f, ...)
tidycensus .f(.x[[i]], ...)
purrr insist_get_acs(...)
purrr::rate_sleep(rate, quiet = quiet)
purrr:::stop_rate_excess(rate)
Error in stop_rate_excess(rate) :

**Comment by walkerke** [comment]
Could you please post a fully reproducible example?  Your `my_svi_vars` and `my_states` objects are not available so I can't test.

**Comment by walkerke** [comment]
That said - ZCTAs are not presently available by state for the 2016-2020 5-year ACS.  Grab the latest version of tidycensus from GitHub (`remotes::install_github("walkerke/tidycensus")`) then remove the `state` argument to pull for the entire US, and it will work.  I don't have a timeline for when Census will add state-specific ZCTA queries for 2020.

**Comment by askay1** [comment]
Thank you very much, this resolved it!  You are awesome.
