### ISSUE TITLE
get_acs() can't pull zcta level data from 2009 ACS 5-year

### ISSUE THREAD

**Issue by Vickyxu19911010** [walkerke/tidycensus#459]
Hello,

I am trying to pull 2009 ACS 5-year ZCTA level data. However, there was an error: "Getting data from the 2005-2009 5-year ACS
Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy." 

Here is my code: 

get_acs(geography="zcta", variables=c("B01003_001E",
                                                       "B02001_001E",
                                                       "B02001_002E",
                                                       "B02001_003E",
                                                       "B02001_004E",
                                                       "B02001_005E",
                                                       "B02001_006E",
                                                       "B02001_007E",
                                                       "B02001_008E",
                                                       "B02001_009E",
                                                       "B02001_010E",
                                                       "B03001_001E",
                                                       "B03001_003E",
                                                       "B01001H_001E"), year=2009)

Thanks in advance!

**Comment by walkerke** [comment]
ZCTAs are not available from the API in that dataset; I believe they start with the 2007-2011 ACS.

**Comment by Vickyxu19911010** [comment]
Thank you so much, I also have tried to pull 2017-2021 ZCTA data, but also had error: "Getting data from the 2017-2021 5-year ACS
Error: Your API call has errors.  The API message returned is <html><head><title>Error report</title></head><body><h1>HTTP Status 404 - /data/2021/acs/acs5</h1></body></html>."

Was that because 2021 data unavailable? 

Many thanks!

**Comment by walkerke** [comment]
Yes that's correct.  It won't be released until December at the earliest.
