### ISSUE TITLE
Further bug related to 2016 5-year data

### ISSUE THREAD

**Issue by camille-s** [walkerke/tidycensus#46]
Thanks for fixing the handling of acs5 vs acs/acs5 (https://github.com/walkerke/tidycensus/commit/c5114452b475baaadfd58034c4cac5007b545787) so quickly! I found a related bug but also a workaround. When I call `get_acs(geography = "state", table = "B01001", survey = "acs5", year = 2016)`, I get the error: `Error: lexical error: invalid char in json text.
                                       <html><head><title>Error report
                     (right here) ------^`

Calling `get_acs(geography = "state", table = "B01001", survey = "acs/acs5", year = 2016)` works without error.

I know the fix was to replace the survey name with `acs/acs5` in the function `load_data`, but it seems like that fix isn't carrying through to `get_acs`.

Thanks again for working on this the same day the data came out!

**Comment by walkerke** [comment]
Thanks for filing the issue!  Yes, I have some cleaning up to do regarding the new endpoint.  I'm working on a thorough walkthrough of the code as tidycensus (and tigris) will soon default to the new 2016 data as of the next CRAN version.

**Comment by walkerke** [comment]
This should be fixed as of https://github.com/walkerke/tidycensus/commit/7c6ceb84b1dc8d35c377627a95abab2ba8669e7d; however let me know if you find anything else!
