### ISSUE TITLE
Can't Install tidycensus because sf install fails

### ISSUE THREAD

**Issue by bwva** [walkerke/tidycensus#460]
Hi, I learned about tidycensus via ACS user group webinar. Installation fails on Mac OS 11.6.6 Big Sur due to repeated download issue for sf:
````
trying URL 'https://ftp.osuosl.org/pub/cran/bin/macosx/contrib/4.2/sf_1.0-7.tgz'
Content type 'application/x-gzip' length 88883512 bytes (84.8 MB)
============================
downloaded 48.1 MB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://ftp.osuosl.org/pub/cran/bin/macosx/contrib/4.2/sf_1.0-7.tgz' failed
````

It has failed at least six times with the download size reported between 40 and 50 MB.

I was able to use curl to directly download the whole sf_1.0-7.tgz file. Can I install it directly so then tidycensus can complete installing? If so, how and where to install it? Or, can I put the tgz file somewhere that the tidycensus installer will see it?

Thanks,

**Comment by walkerke** [comment]
Are you following the MacOS installation instructions for sf over at https://github.com/r-spatial/sf#macos?  For Big Sur, this also might be helpful: https://github.com/r-spatial/sf/issues/1536#issuecomment-727342736.  

I had a Mac installation conversation recently over at https://github.com/walkerke/tidycensus/issues/452, perhaps that would provide some insights as well.
