### ISSUE TITLE
5-year ACS prior to 2005

### ISSUE THREAD

**Issue by jtrac1** [walkerke/tidycensus#461]
Hello, I'm trying to get tract- and county-level income data from the 5-year ACS prior to 2005 (1990 and 2000 to be exact). Is there any chance that this data will be available for the 5-year ACS? 

````
income_data <- function(select_year){
  get_acs(geography = "county",
          variables = c("B19013_001", "B19013A_001", "B19013B_001", "B19013C_001", 
                        "B19013D_001", "B19013E_001", "B19013F_001", "B19013G_001", 
                        "B19013H_001", "B19013I_001"),
          state = "IN",
          year = select_year,
          cache_table = TRUE)  %>% 
  mutate(year = select_year)
}

income_data_by_tract <- function(select_year){
  get_acs(geography = "tract",
          variables = c("B19013_001", "B19013A_001", "B19013B_001", "B19013C_001", 
                        "B19013D_001", "B19013E_001", "B19013F_001", "B19013G_001", 
                        "B19013H_001", "B19013I_001"), 
          state = "IN",
          year = select_year,
          cache_table = TRUE) %>% 
  mutate(year = select_year)
}
````

I also tried the decennial and got this error (and don't know if decennial even has household income by race/ethnicity as a variable). I'm not sure what it means by the endpoint being removed:

````
# Error: The 1990 decennial Census endpoint has been removed by the Census Bureau. 
# We will support 1990 data again when the endpoint is updated; 
# in the meantime, we recommend using NHGIS (https://nhgis.org) and the ipumsr R package.
````

**Comment by szimmer** [comment]
The ACS began in 2005 so the earliest 5-year data available is 2005-2009.

**Comment by walkerke** [comment]
I'll add too that an "endpoint" is the resource on the Census website that __tidycensus__ connects to in order to get data.  The Census Bureau used to provide 1990 data access, but removed it a while back and I don't believe they will re-activate it.

**Comment by jtrac1** [comment]
Makes sense, everyone. Thanks for your input!
