### ISSUE TITLE
Error when using get_acs() with state legislative district as the geography

### ISSUE THREAD

**Issue by MichaelKistner** [walkerke/tidycensus#464]
I'm trying to download data from the 5 year ACS for state legislative districts. As documented [here](https://walker-data.com/census-r/an-introduction-to-tidycensus.html), there should be support for this geography for get_acs(). However, any time I try to use the command to download the data, I receive the following error message:

`Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.`

Here's a minimum working example that returns the above error:

`get_acs(geography = "state legislative district (lower chamber)",
             variables = "B05002_013E", 
              year = 2009)`

**Comment by szimmer** [comment]
You need to specify the state when using this geography. Using North Carolina (37) as an example here:

``` r
library(tidycensus)

get_acs(geography = "state legislative district (lower chamber)", variables = "B05002_013E", year = 2009, state="37")
#> Getting data from the 2005-2009 5-year ACS
#> # A tibble: 120 x 5
#>    GEOID NAME                                           variable  estimate   moe
#>    <chr> <chr>                                          <chr>        <dbl> <dbl>
#>  1 37001 State House District 1 (2006), North Carolina  B05002_0~     2212   329
#>  2 37002 State House District 2 (2006), North Carolina  B05002_0~     2249   394
#>  3 37003 State House District 3 (2006), North Carolina  B05002_0~     2318   336
#>  4 37004 State House District 4 (2006), North Carolina  B05002_0~     7456   449
#>  5 37005 State House District 5 (2006), North Carolina  B05002_0~     1004   167
#>  6 37006 State House District 6 (2006), North Carolina  B05002_0~     2654   364
#>  7 37007 State House District 7 (2006), North Carolina  B05002_0~     1246   387
#>  8 37008 State House District 8 (2006), North Carolina  B05002_0~     2144   387
#>  9 37009 State House District 9 (2006), North Carolina  B05002_0~     2933   404
#> 10 37010 State House District 10 (2006), North Carolina B05002_0~     4912   402
#> # ... with 110 more rows
```

<sup>Created on 2022-08-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by walkerke** [comment]
Thank you @szimmer!

**Comment by MichaelKistner** [comment]
Got it. I did not have to specify state when using the get_decennial() command, so I didn't realize I had to do this with the get_acs() command. Thanks for the quick response!
