### ISSUE TITLE
Aggregating zip codes to counties and states. 

### ISSUE THREAD

**Issue by SergioRodriguez26** [walkerke/tidycensus#465]
Is there a way to aggregate zip codes to their respective counties and states? I seem to only be able to collect the all the zip codes nationwide.

`zc <- get_acs(geography = "zip code tabulation area", 
              variables = c("B19013_001","H1_001N"),
              summary_var = "B01001_001",
              cache_table = T)`

**Comment by plnnr** [comment]
ZIP codes don't nest into any other geography like states or counties. You could consult the geocorr database from the Missouri Census Data Center (applies to nationwide datasets, not just Missouri datasets). They have a crosswalk that can be generated to assist you. https://mcdc.missouri.edu/applications/geocorr.html

**Comment by SergioRodriguez26** [comment]
Thank you.
