### ISSUE TITLE
Error in UseMethod("gather") no applicable method for 'gather' applied to an object of class "character"

### ISSUE THREAD

**Issue by philiporlando** [walkerke/tidycensus#467]
I'm experiencing the following issues with `tidycensus_1.2.2.9000` when calling `get_decennial()`:

```r
# Print traceback to help with debugging
options(error = function() traceback())

# Call tidycensus method
tidycensus::get_decennial(
  geography = "voting district",
  variables = "B01003_001",
  state = "CA", year = 2020,
  geometry = TRUE
  )
  
# Getting data from the 2020 decennial Census
# Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
# Using FIPS code '06' for state 'CA'
# Using the PL 94-171 Redistricting Data summary file
# Error in UseMethod("gather") : 
#   no applicable method for 'gather' applied to an object of class "character"
# 3: gather(., key = variable, value = value, -GEOID, -NAME)
# 2: sub %>% gather(key = variable, value = value, -GEOID, -NAME)
# 1: tidycensus::get_decennial(geography = "voting district", variables = "B01003_001", 
#                              state = "CA", year = 2020, geometry = TRUE)
```

This appears to be related to #403, but installing the latest development version of `tidycensus` did not resolve my issue. I'm planning to fork and submit a PR to address this issue within the next few days.

```r
sessionInfo() 
# R version 4.2.1 (2022-06-23)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Ubuntu 20.04.4 LTS
# 
# Matrix products: default
# BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
# LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
# 
# locale:
# [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
# [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
# [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
# [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] mapview_2.11.0        tidycensus_1.2.2.9000
# 
# loaded via a namespace (and not attached):
# [1] Rcpp_1.0.9         lattice_0.20-45    tidyr_1.2.0        png_0.1-7          class_7.3-20      
# [6] digest_0.6.29      utf8_1.2.2         R6_2.5.1           stats4_4.2.1       e1071_1.7-11      
# [11] httr_1.4.3         pillar_1.8.0       rlang_1.0.4        curl_4.3.2         uuid_1.1-0        
# [16] rstudioapi_0.13    raster_3.5-21      rgdal_1.5-32       webshot_0.5.3      readr_2.1.2       
# [21] stringr_1.4.0      foreign_0.8-82     htmlwidgets_1.5.4  munsell_0.5.0      proxy_0.4-27      
# [26] compiler_4.2.1     pkgconfig_2.0.3    tigris_1.6.1       base64enc_0.1-3    htmltools_0.5.2   
# [31] tidyselect_1.1.2   tibble_3.1.8       codetools_0.2-18   fansi_1.0.3        crayon_1.5.1      
# [36] dplyr_1.0.9        tzdb_0.3.0         sf_1.0-8           rappdirs_0.3.3     grid_4.2.1        
# [41] jsonlite_1.8.0     satellite_1.0.4    lifecycle_1.0.1    DBI_1.1.3          pacman_0.5.1      
# [46] magrittr_2.0.3     units_0.8-0        scales_1.2.0       KernSmooth_2.23-20 cli_3.3.0         
# [51] stringi_1.7.8      leaflet_2.1.1      sp_1.5-0           xml2_1.3.3         ellipsis_0.3.2    
# [56] generics_0.1.3     vctrs_0.4.1        tools_4.2.1        leafem_0.2.0       glue_1.6.2        
# [61] purrr_0.3.4        hms_1.1.1          crosstalk_1.2.0    fastmap_1.1.0      colorspace_2.0-3  
# [66] terra_1.5-34       maptools_1.1-4     classInt_0.4-7     rvest_1.0.2  
```

**Comment by philiporlando** [comment]
After jumping into the source code, it appears that the API call has the following errors:

```r
# [1] "Error : Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.\n"
# attr(,"class")
# [1] "try-error"
# attr(,"condition")
# <simpleError: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.>
```

This error occurs when trying to assign the result of `load_data_decennial()` to the `dat` object. I'm assuming that the `"voting district"` geography parameter is breaking things here. I will review the documentation to learn if there is a different string value that I should be passing for this geography.

**Comment by walkerke** [comment]
Hi @philiporlando,

There are a couple issues you are running into here: 
- Voting districts are only available from the API by county, so you'd need to add `county = "YOUR COUNTY"` to get that data.  I should probably surface that error from the API or just handle that internally.
- Even if you fixed that, voting districts are not available for California from the Census Bureau; I'm not sure why that is.  I'll flag that as well in an error message  .
- Additionally, you are trying to get an ACS variable from the decennial Census.  The variable for total population in the 2020 Census (the PL data that are currently available) is `P1_001N`.  You can use the `load_variables()` function to help determine variables you need (also read through https://walker-data.com/census-r/an-introduction-to-tidycensus.html#searching-for-variables-in-tidycensus).  

So if you were looking at a different location, this would work: 

```r
example <- tidycensus::get_decennial(
  geography = "voting district",
  variables = "P1_001N",
  state = "TX",
  year = 2020,
  county = "Tarrant",
  geometry = TRUE
)
```

![image](https://user-images.githubusercontent.com/4872833/183267399-5fb7848b-ad8c-4be4-a5b9-9a7929a5846d.png)

**Comment by philiporlando** [comment]
@walkerke, thank you for the feedback. I was able to run your example code and produce the same results. 

I was following [this guide](https://walker-data.com/census-r/an-introduction-to-tidycensus.html#geography-and-variables-in-tidycensus) which lists the "voting district" data being available by state. I agree that handling the missing county parameter internally is probably the best approach here. Flagging California voting district data (and any other geographies that are unavailable from the Census API) would also be helpful. Thank you for clarifying the mismatch between the ACS variables and the `get_decennial()` method. I'll be sure to read through your introduction docs as I continue to use this amazing package!
