### ISSUE TITLE
[Feature Request] Add unit tests via the testthat package

### ISSUE THREAD

**Issue by philiporlando** [walkerke/tidycensus#468]
Please correct me if I'm wrong, but it appears that this package has not incorporated any automated unit testing via the `testthat` package. Are unit tests being performed using a different method within this package? If so, please let me know so I can incorporate them into my development workflow on my forked version of this repo. If not, are there any plans to add unit testing in future releases?

**Comment by walkerke** [comment]
A test suite would be great; @mfherman and I discussed this a while back here: https://github.com/walkerke/tidycensus/issues/83#issuecomment-575857602.  If there is anyone in the user community interested in making this contribution to the package, it would be an excellent addition.  The big thing to be mindful of is handling the tests with respect to how CRAN tests the package; this presents more of a challenge with API packages.

**Comment by philiporlando** [comment]
Thank you for providing this info. I have some package development experience, but I have not worked with API packages before. Admittedly, incorporating unit tests into `tidycensus` appears to be a lot more involved than simply embracing a `testthat` worfklow. That being said, I'll do more research on this topic and if I come up with anything worthwhile then I'll be sure to submit a PR.
