### ISSUE TITLE
tracts to place

### ISSUE THREAD

**Issue by AnnaCalderon** [walkerke/tidycensus#472]
Hi Kyle, 

I work for the University of Miami and I have some sensitive data at tract level. I basically want to aggregate it at a place level and get the rate using population each place as the denominator. 

Is there a way to get the population by place joined to its corresponding tracts? That way I will know which tracts belong to each place. 

Thank you,
Anna

**Comment by walkerke** [comment]
Yep!  You'll want a spatial join.  Read this section of my book for more info on how to do it: https://walker-data.com/census-r/spatial-analysis-with-us-census-data.html#spatial-joins
