### ISSUE TITLE
Trouble loading tidycensus library

### ISSUE THREAD

**Issue by KaavyaJ3** [walkerke/tidycensus#473]
install.packages("tidyverse") 
library(tidyverse)
 install.packages("jsonlite") 
install.packages("tidycensus") 
library(jsonlite) 
library(tidycensus)

Result for this is :

library(tidycensus) Error: package or namespace load failed for ‘tidycensus’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): there is no package called ‘sf’

**Comment by walkerke** [comment]
You'll need to install sf, a core dependency of tidycensus first.  If it is not getting picked up with `install.packages("tidycensus")`, it is likely that you are missing a system dependency which will vary depending on your operating system.  [Find your operating system here](https://github.com/r-spatial/sf#installing) and follow the installation instructions, then try installing tidycensus again after you've succeeded.
