### ISSUE TITLE
Trouble with retrieving ACS 2020 data at ZCTA level by state

### ISSUE THREAD

**Issue by lyriodendron** [walkerke/tidycensus#474]
If I try get_acs() at the ZCTA level while specifying a state, trying to get 2020 data yields the following error message:

"Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy."

But if I try 2019 data or do not specify a state, it works as expected.

So this works:
get_acs(geography = "zcta",
                        variables = "B25003_002",
                        year = 2020,
                        survey = "acs5") 

And this works:
get_acs(geography = "zcta",
                        variables = "B25003_002",
                        state = "MD",
                        year = 2019,
                        survey = "acs5") 

But not this:
get_acs(geography = "zcta",
                        variables = "B25003_002",
                        state = "MD",
                        year = 2020,
                        survey = "acs5")

**Comment by walkerke** [comment]
Unfortunately Census did not enable the state parameter for ZCTAs for the 2016-2020 ACS, so you'll have to pull for all ZCTAs in the US then filter down.  I'm not sure if they plan to enable this parameter in the future.
