### ISSUE TITLE
get_acs issue returning bottom-coded values

### ISSUE THREAD

**Issue by daviswinslow** [walkerke/tidycensus#477]
Noticed an issue while working with the "Median Year Structure Built By Tenure" tables (B25037).

The query returns many zero values. What I think is going on is that the tables are bottom-coded at 1939 (for 1939 or prior), but in the data it appears as "1939-", and since the query retrieves them as numerical values, it's returning the zeroes. 

Example:

get_acs(geography = "tract",
        variables = c(median.structure.built.total = "B25037_001"),
        state = "NY",
        year = 2020,
        geometry = FALSE) %>%
  select(NAME, GEOID, estimate, variable) %>%
  spread(variable, estimate) %>%
  arrange(median.structure.built.total)

**Comment by walkerke** [comment]
I think you are correct; however `0` is how they are returned by the API: https://api.census.gov/data/2020/acs/acs5?get=B25037_001E%2CB25037_001M%2CNAME&for=tract%3A%2A&in=state%3A36.  I don't want to modify that on the tidycensus side, so I think it's up to the analyst to decide how they want to treat those values for their specific analysis.
