### ISSUE TITLE
Pulling ZCTA data and getting "no loop for break/next, jumping to top level" message

### ISSUE THREAD

**Issue by mcat18** [walkerke/tidycensus#478]
I'm trying to run this code to get zip code data:
```
get_acs(
  geography = "zcta",
  variables = "C16001_003",
  geometry = TRUE,
  year = 2020,
  cb = FALSE , 
  show_call = TRUE
) %>%
  st_transform(crs=st_crs('NAD83')) %>% #<<
  erase_water(area_threshold = 0.99)
```

However, when I'm attempting to pull the data, it runs for a very long time. Once I stop the code from running, I get this message "no loop for break/next, jumping to top level". What can I do to get this to run properly?

**Comment by walkerke** [comment]
This will be a tricky operation to get to work.  A couple things I see:

- Try running the `get_acs()` call independent of the other operations.  If you don't already have it in your tigris cache (which I recommend with `options(tigris_use_cache = TRUE)`, the TIGER/Line ZCTA shapefile can take a few minutes to download if your internet connection isn't fast.  Make sure you can do that first.  
- The file is already in the coordinate system NAD83, so the call to `st_transform()` isn't doing anything.  I'd recommend a continental projected CRS instead; a common one used is `"ESRI:102003"` (Albers Equal Area for the lower 48).  
- I've never tried using `erase_water()` for a national object, and I can't necessarily vouch for it working for that use case.  The function works by identifying counties that intersect your area of interest, then downloading water shapefiles for those counties, combining the water shapefiles as an erase layer, then removing that area.  It's pretty performant for small areas but your operation would require downloading all 3000+ water shapefiles then doing a national erase operation, which won't be fast and will be memory-intensive.  

If you need water area removed from a national ZCTA file, I'd recommend a couple things:
- Use `cb = TRUE` instead to get the cartographic boundary ZCTA file which is clipped to shoreline; that may be all you need already.
- If not, @DHLocke did a national operation like this here https://github.com/DHLocke/Census-geographies-no-water-single-part where he iteratively performed this operation; his code might be useful to you.
- NHGIS also has highly detailed shapefiles available; more detailed than Census provides.  They might meet your needs better.

**Comment by mcat18** [comment]
Thank you very much! I remove ```
st_transform(crs=st_crs('NAD83')) %>% #<<
  erase_water(area_threshold = 0.99)
``` from my code and it ran perfectly.
