### ISSUE TITLE
update load_variables docs

### ISSUE THREAD

**Issue by kellytdunn** [walkerke/tidycensus#479]
https://github.com/walkerke/tidycensus/blob/master/docs/reference/load_variables.html 
`year` argument states that 5-year ACS data is now available through 2018. Change 2018 to 2020. 
It also states that 1-year data is now available through 2019. 2021 was released yesterday.

I was going to submit a PR myself but the file says "Generated by pkgdown: do not edit by hand", so I'm unsure how/if to submit a PR in that case. Happy to do it if someone can point me in the right direction.

**Comment by walkerke** [comment]
thanks for the note!  it was easiest for me to patch it.  For future reference, the way this works is to edit the function documentation in the R script where the function is written; RStudio's build tools then auto-generate the documentation file from this.  You can learn more about this process here: https://r-pkgs.org/man.html
