### ISSUE TITLE
Lexical error: invalid char in json text when accessing 1-year ACS data for 2006-2011

### ISSUE THREAD

**Issue by dcvanriper** [walkerke/tidycensus#48]
I tried to use TidyCensus to access 1-year ACS data for 2006-2011 using the following:

`df <- get_acs(geography = "state", table = "B01001", survey = "acs1", year = 2006)`

I received the following error message at the console:

```
Error: lexical error: invalid char in json text.
                                       <html><head><title>Error report
                     (right here) ------^
```

The request works for 1-year data from 2012-2016. Possibly an issue with the census API, but I wanted to bring it to your attention.

**Comment by walkerke** [comment]
Thanks David!  Yes the ACS 1-year API only goes back to 2012 (2011 for congressional districts only).  This would merit a more informative error message I think.

**Comment by dcvanriper** [comment]
Thanks for the response! That makes sense to me.

**Comment by walkerke** [comment]
I've included a more informative error message in https://github.com/walkerke/tidycensus/commit/eb4dfed4bbd4d5d5ac7b6ef1064e4267bb5e1257.
