### ISSUE TITLE
2021 population eestimates?

### ISSUE THREAD

**Issue by ABSOD** [walkerke/tidycensus#480]
Are 2021 Population Estimates available through tidycensus?
The following call: 
get_estimates(geography = "state", product = "characteristics", breakdown = c("RACE", "HISP"),
                            year=2021)

returns an error:
Error: Your API call has errors.  The API message returned is <html><head><title>Error report</title></head><body><h1>HTTP Status 404 - /data/2021/pep/charagegroups</h1></body></html>.

I am using tidycensus version 1.2.3
TIA

**Comment by walkerke** [comment]
Closing and linking to the conversation in https://github.com/walkerke/tidycensus/issues/423

Short answer: the 2021 estimates are not on the API, so tidycensus can't get them.  Census has released them as flat files for download but there is no timetable for adding to the API, so I'm in a bit of a holding pattern.  I would love to support them when possible!
