### ISSUE TITLE
Error in state level 2020 Decennial ZCTA Population Totals

### ISSUE THREAD

**Issue by hannahkfriedrich** [walkerke/tidycensus#482]
Hello, I am trying to get the 2020 decennial ZCTA population totals for all of Texas. 

tx_ztca_pop <- get_decennial(
                             geography = "zcta", 
                             state = "TX",
                             variables = "P1_001N", 
                             year = 2020,
                             sumfile = "pl")

#head(tx_ztca_pop)

Which returns this error:

Error in UseMethod("gather") : 
  no applicable method for 'gather' applied to an object of class "character"

I'm still getting this error after installing tidycensus from GitHub. I suspect the issue has something to do with the summary file not containing zcta data, but any help would be appreciated. Thanks!

**Comment by walkerke** [comment]
Unfortunately ZCTA is not an available geography for the 2020 Census.  You can view the available geographies for 2020 here: https://api.census.gov/data/2020/dec/pl/geography.html

I'd bet when they do the full 2020 data release next year they'll have ZCTAs available.  For now, you'll need to use the ACS or "roll up" data from a smaller geography with spatial overlay and geometries obtained with `tigris::zctas()`.
