### ISSUE TITLE
get_flows() at the county level

### ISSUE THREAD

**Issue by Arthur-Langlois** [walkerke/tidycensus#486]
Hi I am trying to do a simple pull of all county-level migration flows but keep getting the following error: 
```
library(tidycensus)
library(tidyverse)
library(tigris)
library(sf)
library(glue)

API_KEY_CENSUS <- 'xyz'
census_api_key(API_KEY_CENSUS)

b <- data.frame(get_flows(geography = "county",
                          year = 2013,
                          geometry = FALSE))
```
```
Error: Your API call has errors.  The API message returned is error: wildcard not allowed for 'state' in geography heirarchy.
```
The documentation says that county level migration is available, and checked [this issue](https://github.com/walkerke/tidycensus/issues/136), but without success. 
Thanks!

**Comment by walkerke** [comment]
It appears the ability to pull migration flows for all counties like that starts with the 2012-2016 ACS.  In your case, you would need to iterate through all the states and combine.  For example:

```r
library(tidycensus)
library(tidyverse)

state_codes <- c(state.abb, "DC")

all_flows <- map_dfr(state_codes, ~{
  get_flows(
    geography = "county",
    state = .x,
    year = 2013
  )
})
```
