### ISSUE TITLE
can get_acs() pull in 5 year data from 2016?

### ISSUE THREAD

**Issue by bigck2** [walkerke/tidycensus#49]
It seems like the get_acs() function can pull in the "acs5" survey from 2015, but not the most recent 2016 survey. Is this feature going to be available in a future release of tidycensus?

This doesn't seem to work:
`state_pop <- get_acs(geography = "state",  
                                    variables = "B01003_001", 
                     survey = "acs5", 
                     year = 2016) `

But the data for the 1-year survey is available:
`state_pop <- get_acs(geography = "state", 
                     variables = "B01003_001", 
                     survey = "acs1", 
                     year = 2016) `

**Comment by mfherman** [comment]
Hey there -- I think Kyle is waiting to make some other changes before he pushes the new version of the package to CRAN, but if you install the development version from GitHub, the 2016 estimates are available:

`devtools::install_github("walkerke/tidycensus")`

**Comment by bigck2** [comment]
Hi mfherman, thanks so much for your response. I downloaded the development version and it works great. The tidycensus package is awesome thanks again.

**Comment by walkerke** [comment]
Thanks @mfherman for answering!  Yes that is correct.  I'm going to be working on the package over the next month and the new CRAN version of tidycensus will default to the 2012-2016 estimates.
