### ISSUE TITLE
Metro data call returns unknown/unsupported geography heirarchy

### ISSUE THREAD

**Issue by lauracrosswhite** [walkerke/tidycensus#490]
When I try to pull data for metro areas I'm getting the error below. Has there been a change, or am I just not specifying the geography correctly?

get_acs(geography = "metropolitan statistical area/micropolitan statistical area", 
        variables = glue("B01001_00{i}"), 
        year = year)
Getting data from the 2017-2021 5-year ACS
Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.

**Comment by mfherman** [comment]
I just saw this note on the [Census Slack](https://uscensusbureau.slack.com/archives/C6DGLC05B/p1670511053879209) that is the reason this call is failing for 2021:

> With the 2021 ACS 5-Year data now available, please note that there are label changes to some geographies found in the 2021 5-Year ACS API. While there are no underlying changes to how these geographies are defined, the change in the label does impact the syntax of the geography portion of the API queries, meaning that queries using these geographies from the 2020 5-Year ACS or earlier will not work. If you use any of these geographies in your queries, please be sure to update the geographic syntax prior to retrieving data from the 2021 5-Year ACS API.
The impacted geographies are shown in the attached table.

![image (5)](https://user-images.githubusercontent.com/24945757/206517531-a7149cbf-0cf4-4e42-8d2e-9d6cb5ee463b.png)

Given those changes the following are examples of 2020 and 2021 code that work and the change in the geography that is required. This is pretty annoying and prob something we could handle under the hood of tidycensus.

I'm traveling today, so might have a bit a time to play around

**Comment by mfherman** [comment]
Sorry, here's a repex with working code examples for MSAs in 2020 and 2021

``` r
library(tidycensus)

get_acs(
  geography = "metropolitan statistical area/micropolitan statistical area",
  variables = "B01003_001",
  year = 2020,
  survey = "acs5"
  )
#> Getting data from the 2016-2020 5-year ACS
#> # A tibble: 939 × 5
#>    GEOID NAME                             variable   estimate   moe
#>    <chr> <chr>                            <chr>         <dbl> <dbl>
#>  1 10100 Aberdeen, SD Micro Area          B01003_001    42864    NA
#>  2 10140 Aberdeen, WA Micro Area          B01003_001    73769    NA
#>  3 10180 Abilene, TX Metro Area           B01003_001   171354    NA
#>  4 10220 Ada, OK Micro Area               B01003_001    38385    NA
#>  5 10300 Adrian, MI Micro Area            B01003_001    98310    NA
#>  6 10380 Aguadilla-Isabela, PR Metro Area B01003_001   295172    NA
#>  7 10420 Akron, OH Metro Area             B01003_001   703286    NA
#>  8 10460 Alamogordo, NM Micro Area        B01003_001    66804    NA
#>  9 10500 Albany, GA Metro Area            B01003_001   147431    NA
#> 10 10540 Albany-Lebanon, OR Metro Area    B01003_001   127216    NA
#> # … with 929 more rows

get_acs(
  geography = "metropolitan/micropolitan statistical area",
  variables = "B01003_001",
  year = 2021,
  survey = "acs5"
)
#> Getting data from the 2017-2021 5-year ACS
#> # A tibble: 939 × 5
#>    GEOID NAME                             variable   estimate   moe
#>    <chr> <chr>                            <chr>         <dbl> <dbl>
#>  1 10100 Aberdeen, SD Micro Area          B01003_001    42476    NA
#>  2 10140 Aberdeen, WA Micro Area          B01003_001    74737    NA
#>  3 10180 Abilene, TX Metro Area           B01003_001   175241    NA
#>  4 10220 Ada, OK Micro Area               B01003_001    38102    NA
#>  5 10300 Adrian, MI Micro Area            B01003_001    99346    NA
#>  6 10380 Aguadilla-Isabela, PR Metro Area B01003_001   311049    NA
#>  7 10420 Akron, OH Metro Area             B01003_001   702464    NA
#>  8 10460 Alamogordo, NM Micro Area        B01003_001    67298    NA
#>  9 10500 Albany, GA Metro Area            B01003_001   149298    NA
#> 10 10540 Albany-Lebanon, OR Metro Area    B01003_001   127200    NA
#> # … with 929 more rows
```

<sup>Created on 2022-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by walkerke** [comment]
I've got a fix for this in https://github.com/walkerke/tidycensus/pull/488, I'll merge a bit later but you can install from that branch if you want.  If you use `geography = "cbsa"` it'll format the data pull correctly under the hood for any year.

**Comment by walkerke** [comment]
``` r
remotes::install_github("walkerke/tidycensus#488")
library(tidycensus)

get_acs(
  geography = "cbsa",
  variables = "B19013_001",
  year = 2021
)
#> Getting data from the 2017-2021 5-year ACS
#> # A tibble: 939 × 5
#>    GEOID NAME                             variable   estimate   moe
#>    <chr> <chr>                            <chr>         <dbl> <dbl>
#>  1 10100 Aberdeen, SD Micro Area          B19013_001    64194  2992
#>  2 10140 Aberdeen, WA Micro Area          B19013_001    53615  1957
#>  3 10180 Abilene, TX Metro Area           B19013_001    57356  2033
#>  4 10220 Ada, OK Micro Area               B19013_001    55862  4035
#>  5 10300 Adrian, MI Micro Area            B19013_001    60656  1641
#>  6 10380 Aguadilla-Isabela, PR Metro Area B19013_001    17785   590
#>  7 10420 Akron, OH Metro Area             B19013_001    63331   711
#>  8 10460 Alamogordo, NM Micro Area        B19013_001    46949  2707
#>  9 10500 Albany, GA Metro Area            B19013_001    49500  1671
#> 10 10540 Albany-Lebanon, OR Metro Area    B19013_001    63313  2179
#> # … with 929 more rows
```

<sup>Created on 2022-12-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lauracrosswhite** [comment]
> Sorry, here's a repex with working code examples for MSAs in 2020 and 2021
> 
> ```r
> library(tidycensus)
> 
> get_acs(
>   geography = "metropolitan statistical area/micropolitan statistical area",
>   variables = "B01003_001",
>   year = 2020,
>   survey = "acs5"
>   )
> #> Getting data from the 2016-2020 5-year ACS
> #> # A tibble: 939 × 5
> #>    GEOID NAME                             variable   estimate   moe
> #>    <chr> <chr>                            <chr>         <dbl> <dbl>
> #>  1 10100 Aberdeen, SD Micro Area          B01003_001    42864    NA
> #>  2 10140 Aberdeen, WA Micro Area          B01003_001    73769    NA
> #>  3 10180 Abilene, TX Metro Area           B01003_001   171354    NA
> #>  4 10220 Ada, OK Micro Area               B01003_001    38385    NA
> #>  5 10300 Adrian, MI Micro Area            B01003_001    98310    NA
> #>  6 10380 Aguadilla-Isabela, PR Metro Area B01003_001   295172    NA
> #>  7 10420 Akron, OH Metro Area             B01003_001   703286    NA
> #>  8 10460 Alamogordo, NM Micro Area        B01003_001    66804    NA
> #>  9 10500 Albany, GA Metro Area            B01003_001   147431    NA
> #> 10 10540 Albany-Lebanon, OR Metro Area    B01003_001   127216    NA
> #> # … with 929 more rows
> 
> get_acs(
>   geography = "metropolitan/micropolitan statistical area",
>   variables = "B01003_001",
>   year = 2021,
>   survey = "acs5"
> )
> #> Getting data from the 2017-2021 5-year ACS
> #> # A tibble: 939 × 5
> #>    GEOID NAME                             variable   estimate   moe
> #>    <chr> <chr>                            <chr>         <dbl> <dbl>
> #>  1 10100 Aberdeen, SD Micro Area          B01003_001    42476    NA
> #>  2 10140 Aberdeen, WA Micro Area          B01003_001    74737    NA
> #>  3 10180 Abilene, TX Metro Area           B01003_001   175241    NA
> #>  4 10220 Ada, OK Micro Area               B01003_001    38102    NA
> #>  5 10300 Adrian, MI Micro Area            B01003_001    99346    NA
> #>  6 10380 Aguadilla-Isabela, PR Metro Area B01003_001   311049    NA
> #>  7 10420 Akron, OH Metro Area             B01003_001   702464    NA
> #>  8 10460 Alamogordo, NM Micro Area        B01003_001    67298    NA
> #>  9 10500 Albany, GA Metro Area            B01003_001   149298    NA
> #> 10 10540 Albany-Lebanon, OR Metro Area    B01003_001   127200    NA
> #> # … with 929 more rows
> ```
> 
> Created on 2022-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)

This worked, thanks for the quick reply!
