### ISSUE TITLE
Problem with pulling MSA-level data

### ISSUE THREAD

**Issue by ericvmai** [walkerke/tidycensus#494]
Trying to pull down data similar to the following:
`B25119_PULL <- get_acs(
  geography = "metropolitan statistical area/micropolitan statistical area",
  state = "VA",
  table = "B25119",
  year = 2021,
  survey = "acs5"
)`

Returns the following error for me:
Getting data from the 2017-2021 5-year ACS
Using FIPS code '51' for state 'VA'
Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.

Should this not work fine? I can see the data clearly on data.census.gov

**Comment by szimmer** [comment]
There's 2 things going on making your call wrong. MSAs are not nested within states so a state can't be included in the call. You can later filter for areas that are in Virginia. 

Secondly, the name for the area changed in 2021. See: https://www2.census.gov/data/api-documentation/label-changes-to-2021-acs-5-year-geographies.pdf We might want to handle this in the tidycensus package to change the name in the R package before sending to the API.

A reprex to show working code where you can see some areas include multiple states:

``` r
library(tidycensus)
library(tidyverse)

B25119_20_PULL <- get_acs( geography = "metropolitan statistical area/micropolitan statistical area", table = "B25119", year = 2020, survey = "acs5" )
#> Getting data from the 2016-2020 5-year ACS
#> Loading ACS5 variables for 2020 from table B25119. To cache this dataset for faster access to ACS tables in the future, run this function with `cache_table = TRUE`. You only need to do this once per ACS dataset.

B25119_21_PULL <- get_acs( geography = "metropolitan/micropolitan statistical area", table = "B25119", year = 2021, survey = "acs5" )
#> Getting data from the 2017-2021 5-year ACS
#> Loading ACS5 variables for 2021 from table B25119. To cache this dataset for faster access to ACS tables in the future, run this function with `cache_table = TRUE`. You only need to do this once per ACS dataset.

B25119_20_PULL %>%
  filter(str_detect(NAME, "VA"))
#> # A tibble: 45 × 5
#>    GEOID NAME                                     variable   estimate   moe
#>    <chr> <chr>                                    <chr>         <dbl> <dbl>
#>  1 13720 Big Stone Gap, VA Micro Area             B25119_001    39886  4215
#>  2 13720 Big Stone Gap, VA Micro Area             B25119_002    50434  3111
#>  3 13720 Big Stone Gap, VA Micro Area             B25119_003    19403  2892
#>  4 13980 Blacksburg-Christiansburg, VA Metro Area B25119_001    55475  1527
#>  5 13980 Blacksburg-Christiansburg, VA Metro Area B25119_002    73058  2245
#>  6 13980 Blacksburg-Christiansburg, VA Metro Area B25119_003    29781  2118
#>  7 14140 Bluefield, WV-VA Micro Area              B25119_001    41979  2025
#>  8 14140 Bluefield, WV-VA Micro Area              B25119_002    47418  2550
#>  9 14140 Bluefield, WV-VA Micro Area              B25119_003    28624  3630
#> 10 16820 Charlottesville, VA Metro Area           B25119_001    75176  2128
#> # … with 35 more rows

B25119_21_PULL %>%
  filter(str_detect(NAME, "VA"))
#> # A tibble: 45 × 5
#>    GEOID NAME                                     variable   estimate   moe
#>    <chr> <chr>                                    <chr>         <dbl> <dbl>
#>  1 13720 Big Stone Gap, VA Micro Area             B25119_001    44131  4541
#>  2 13720 Big Stone Gap, VA Micro Area             B25119_002    53166  4271
#>  3 13720 Big Stone Gap, VA Micro Area             B25119_003    22611  5036
#>  4 13980 Blacksburg-Christiansburg, VA Metro Area B25119_001    57381  1828
#>  5 13980 Blacksburg-Christiansburg, VA Metro Area B25119_002    74957  2425
#>  6 13980 Blacksburg-Christiansburg, VA Metro Area B25119_003    32278  2429
#>  7 14140 Bluefield, WV-VA Micro Area              B25119_001    43842  1942
#>  8 14140 Bluefield, WV-VA Micro Area              B25119_002    50190  2892
#>  9 14140 Bluefield, WV-VA Micro Area              B25119_003    29050  2279
#> 10 16820 Charlottesville, VA Metro Area           B25119_001    79660  2262
#> # … with 35 more rows
```

<sup>Created on 2022-12-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ericvmai** [comment]
Thanks @szimmer! I was under the impression that you could also filter by state based on the "Available by" column at this page: https://walker-data.com/tidycensus/articles/basic-usage.html

But perhaps I was reading that incorrectly. Thank you though!

**Comment by walkerke** [comment]
Hi @ericvmai and thanks @szimmer!

I'll push a fix to remove `state` from "Available by" in the docs, @szimmer is correct.  In the GitHub version of tidycensus, specifying `geography = "cbsa"` will translate to the correct year-specific notation for MSAs.  Though we probably should translate `"metropolitan statistical area/micropolitan statistical area"` to the new 2021 version as well.  

I'll push those corrections and submit to CRAN when submissions re-open after their winter break.
