### ISSUE TITLE
Data for S2503_C02_027 in 2014 return as NA

### ISSUE THREAD

**Issue by jnigrineFlint** [walkerke/tidycensus#496]
Hi - For some reason, in only 2014 (I've looked at 2014-2021 5-year ACS), only the column S2503_C02_027 returns as NA. This is true for several geographies that I've tried.  Here's one example:

 YearRangeEnd = 2014

  StateData <- get_acs(
    geography="state", state="MI"
    , survey='acs5'
    , year = YearRangeEnd
    , variables = c(
     'S2503_C02_025'
      , 'S2503_C02_026'
      , 'S2503_C02_027'
      , 'S2503_C02_028'
      , 'S2503_C02_029'
      , 'S2503_C02_030'
      , 'S2503_C02_031'

    )
  )
print (StateData)

However, the value exists in the Census [online lookup](https://data.census.gov/table?q=s2503&g=0400000US26&tid=ACSST5Y2014.S2503).

That isn't true for other columns or other years.

**Comment by szimmer** [comment]
When I look at the table you linked, the value
for S2503_C02_027 (Owner-occupied housing units!!Estimate!!MONTHLY HOUSING
COSTS!!No cash rent ) is (X). That is set to be NA in R.

**Comment by walkerke** [comment]
@szimmer is correct.  For reference, you can check the raw result from the Census API with the argument `show_call = TRUE`.  For example, [this is what your query looks like on the API side](https://api.census.gov/data/2014/acs/acs5/subject?get=S2503_C02_025E%2CS2503_C02_025M%2CS2503_C02_026E%2CS2503_C02_026M%2CS2503_C02_027E%2CS2503_C02_027M%2CS2503_C02_028E%2CS2503_C02_028M%2CS2503_C02_029E%2CS2503_C02_029M%2CS2503_C02_030E%2CS2503_C02_030M%2CS2503_C02_031E%2CS2503_C02_031M%2CNAME&for=state%3A26).  You'll notice that the variable comes in as `-888888888.0`, which means the estimate is either not applicable or unavailable ([see here for more information](https://www.census.gov/data/developers/data-sets/acs-1year/notes-on-acs-estimate-and-annotation-values.html)).  In tidycensus, we set all of those values to `NA` before returning to the user.

**Comment by jnigrineFlint** [comment]
Apologies!  An error on our side.  Thank you for the quick response, and sorry to waste your time.

Jon


___________________________________
Jon Nigrine, (810) 287-0438,  StateOfFlintKids.com<http://stateofflintkids.com/>.

**Comment by walkerke** [comment]
@jnigrineFlint not a waste of time at all, and no apology needed!  Chances are other users have similar questions, and they can refer to our exchange now as a reference.
