### ISSUE TITLE
Custom variable names in get_acs() do not work properly when specifying if the variable is an estimate, percent, etc.

### ISSUE THREAD

**Issue by djn34** [walkerke/tidycensus#498]
Hi all,

I wanted to used get_acs() to download several variables all at once. I'm able to automatically name the variables within the get_acs() function, but when I specify that the variable is a percent estimate by ending the variable with "PE", it returns the code for the code for the variable as its name, rather than the name I specified.

For example (as seen below), when I try to name "DP05_0002PE" from 2021 as "percent_male", it comes back in my table named "DP05_0002PE". However, naming "DP05_0002" as "males" works as intended.

Is there something I can do to automatically name these variables in my get_acs() function? Or is this something that I have to change after the function?

Thank you!

```
get_acs(geography = "state",
         state = "MD",
         variables = c(males = "DP05_0002",
                       percent_male = "DP05_0002PE"),
         year = 2021)

>Getting data from the 2017-2021 5-year ACS
>Using the ACS Data Profile
>Using FIPS code '24' for state 'MD'

# A tibble: 2 × 5
  GEOID NAME     variable    estimate   moe
  <chr> <chr>    <chr>          <dbl> <dbl>
1 24    Maryland males      2995146   602  
2 24    Maryland DP05_0002P      48.7   0.1
```

**Comment by djn34** [comment]
Update: I just realized that dropping the "E" from the end of the variable name works. So this is just an issue that I'm running into with "PE" at the end.

**Comment by walkerke** [comment]
Yes, that's correct.  In tidycensus you won't typically put the "E" or the "M" on the end of a requested variable name as that designates the estimate, or margin of error, associated with a given variable.  So "DP05_002P" gets you both the estimate and margin of error automatically, and will work with downstream features (like custom renaming) as well.

**Comment by djn34** [comment]
Thank you for the explanation! I think this is now permanently etched in my brain from this experience :)
