### ISSUE TITLE
More closure issues

### ISSUE THREAD

**Issue by TBleess** [walkerke/tidycensus#50]
For some reason when I try this command, I get the result after:
acstab <- get_acs(geography = "us", variables = c("B00001_001","B00001_002"), year = 2016, output = "wide", survey = "acs5")
[1] "Client error Bad Request Client error: (400) Bad Request"
Error in as.character(x) : 
  cannot coerce type 'closure' to vector of type 'character'

But this works:
acstab <- get_acs(geography = "us", variables = c("B01001_001","B01001_002"), year = 2016, output = "wide", survey = "acs5")

Both tables are listed in load_variables for 2016, so I'm not sure what is happening

**Comment by walkerke** [comment]
You've identified an interesting wrinkle in tidycensus that I hadn't accounted for.  The two variables you are requesting are the unweighted sample counts of the US population and households, respectively - so the number of people and households included in the survey before sampling weights are applied.  As such, these variables do not have margins of error.  tidycensus, however, always requests the margin of error along with the estimate for all ACS variables - so that is why this is not working at the moment.  

I'll write an exception for those two variables so that tidycensus does not attempt to request their margins of error and return `NA` in the `moe` column.

**Comment by TBleess** [comment]
Thank you! Is it possible do this for any value lacks a margin of error? (B98001, B98002 and imputation tables I believe have the same issue) I was able to download these variables successfully for the 2010 ACS back in October, this library is saving me a ton of time from my previous method of extracting this data.

**Comment by walkerke** [comment]
I've pushed a fix in https://github.com/walkerke/tidycensus/commit/8e4efb0f86886f322890c363e10fa134b8b71ce8.  tidycensus now checks to see if a requested variable does not have an associated margin of error, and does not attempt to fetch the margin of error in those instances.  For example, if you were to request the sample count and sample housing unit variables by state for the 2012-2016 ACS: 

```r
library(tidycensus)

samples <- get_acs(geography = "state", year = 2016, 
                   variables = c(samplecount = "B00001_001", 
                                        samplehousing = "B00002_001"))

head(samples)

# A tibble: 6 x 4
  GEOID    NAME      variable estimate
  <chr>   <chr>         <chr>    <dbl>
1    01 Alabama   samplecount   404611
2    01 Alabama samplehousing   186580
3    02  Alaska   samplecount   100966
4    02  Alaska samplehousing    46368
5    04 Arizona   samplecount   503986
6    04 Arizona samplehousing   219267
```

tidycensus does not include a margin of error column in this instance.  However, if you were to add a variable _with_ a margin of error: 

```r
df <- get_acs(geography = "state", year = 2016, 
                   variables = c(samplecount = "B00001_001", 
                                        samplehousing = "B00002_001", 
                                        medincome = "B19013_001"))

head(df)

# A tibble: 6 x 5
  GEOID    NAME      variable estimate   moe
  <chr>   <chr>         <chr>    <dbl> <dbl>
1    01 Alabama   samplecount   404611    NA
2    01 Alabama samplehousing   186580    NA
3    01 Alabama     medincome    44758   314
4    02  Alaska   samplecount   100966    NA
5    02  Alaska samplehousing    46368    NA
6    02  Alaska     medincome    74444   809
```

Those margins of error return NA.  

Would you mind testing and seeing if this meets your needs?  I've included checks for all of the variables I _believe_ to be without MOEs but more can be added if found.
