### ISSUE TITLE
Getting errors for load_variables() and get_decennial() with 2020 Census

### ISSUE THREAD

**Issue by jlgodwin** [walkerke/tidycensus#500]
I wrote a script that executed Thursday, 1/26, but on Friday 1/27 and today, 1/30. I get the following errors for both the following lines of code:

**Code**

`decennial_var <- load_variables(2020, data = "pl")`

**Error**

Error in call_with_cleanup(map_impl, environment(), .type, .progress,  : 
  object 'cleancall_call' not found

**Code**
`decennial_hu <- get_decennial(geography = "block",
                              variables = c("H1_001N", "H1_002N"),
                              year = 2020,
                              state = "WA",
                              county = "King",
                              geometry = TRUE,
                              key = myKey)`

**Error**

Getting data from the 2020 decennial Census
Using the PL 94-171 Redistricting Data summary file
Error in UseMethod("gather") : 
  no applicable method for 'gather' applied to an object of class "character"

I updated tidycensus today to version 1.3.2.

**Comment by walkerke** [comment]
Hi @jlgodwin,

I just ran both of your lines of code without problems.  Could you post the results of your `sessionInfo()`?

**Comment by jlgodwin** [comment]
Thanks for the quick reply! Adding a screen shot...
![Screen Shot 2023-01-30 at 5 33 28 PM](https://user-images.githubusercontent.com/18407697/215636639-194658bb-5f9a-4e10-a7c6-67cebbcbb9cb.png)

**Comment by walkerke** [comment]
I don't see anything obvious, and I just tested your code on a clean Posit Cloud instance and it worked fine.  My strong hunch is that your system is having trouble connecting to the Census website - I have seen instances (though rare) when Windows Server-based installations of R get blocked.  

Can you try this, and see if it returns `200`?

```r
req <- httr::GET("https://api.census.gov/data/2021/acs/acs5?get=B01003_001E%2CB01003_001M%2CNAME&for=state%3A%2A")

req$status_code
```

**Comment by jlgodwin** [comment]
Interesting re: Windows Server-based, I can reach out to my IT. 

It does return 200.

**Comment by walkerke** [comment]
Hmm.  Are all tidycensus calls returning errors, or just the 2020 decennial?

**Comment by jlgodwin** [comment]
Yeah, unfortunately. I just tried

`load_variables(2019, dataset = "acs1")` and `load_variables(2019, dataset = "acs5")` and got the same `cleancall_call` error

**Comment by walkerke** [comment]
Unfortunately I'm stumped.  Does the __censusapi__ package work?  By chance is the UW server making heavy use of __tidycensus__ at the moment, potentially with a common API key?

**Comment by walkerke** [comment]
Did you ever get this working @jlgodwin?

**Comment by jlgodwin** [comment]
Hi Kyle,

Sorry for the delay in reply. It was a complicated issue with our shared
servers as you expected, and unrelated to package!

Thanks for all you support on this!  All the best, Jessica
