### ISSUE TITLE
Dead link for PUMS in vignette

### ISSUE THREAD

**Issue by defuneste** [walkerke/tidycensus#502]
The first link to PUMS in the vignette (https://walker-data.com/tidycensus/articles/pums-data.html) return a 404. I assume they moved it here : https://www.census.gov/programs-surveys/acs/microdata.html

Do you take PR for small issue like that! 

Thanks a lot of all your work! Tidycensus is a great package!

**Comment by walkerke** [comment]
Thanks for the heads up!  I appreciate the offer of the PR - I'll just take care of that myself as I'll want to rebuild on the pkgdown side of things.

**Comment by defuneste** [comment]
Yup, vignette are weird objet in R packages!
