### ISSUE TITLE
Error with get_pums() and puma = ... argument

### ISSUE THREAD

**Issue by lighthouseenergy** [walkerke/tidycensus#504]
I seem to be having an issue with `get_pums()` and specifying specific PUMAs in the call. At first, I thought it was that I was specifying the PUMAs as numbers (per examples in help file) while the function seems to return them as characters, but that didn't seem to fix it.

The following code works if the `puma = ...` argument is excluded, but does not if it is included.
```
my_pums <-  get_pums(
  variables = c("RT", "SERIALNO", "PUMA", "ST", "WGTP", "TYPEHUGQ", "BLD", "FINCP", "HINCP", "NP", "HFL"),
  state = "WA",
  survey = "acs1",
  year = 2021,
  #puma = c("11701", "11702", "11703", "11704", "11705", "11706"), 
  recode = TRUE
)
```

Here's what shows in the console:

```
> # Get PUMS data
> my_pums <-  get_pums(
+   variables = c("RT", "SERIALNO", "PUMA", "ST", "WGTP", "TYPEHUGQ", "BLD", "FINCP", "HINCP", "NP", "HFL"),
+   state = "WA",
+   survey = "acs1",
+   year = 2021,
+   puma = c("11701", "11702", "11703", "11704", "11705", "11706"), 
+   recode = TRUE
+ )
Getting data from the 2021 1-year ACS Public Use Microdata Sample
Using FIPS code '53' for state 'WA'
Downloading: 730 kB     Error in `dplyr::mutate()`:
! Can't transform a data frame with duplicate names.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Error in `dplyr::mutate()`:
! Can't transform a data frame with duplicate names.
---
Backtrace:
 1. tidycensus::get_pums(...)
 5. dplyr:::mutate.data.frame(., dplyr::across(.cols = dplyr::contains("WGTP"), as.numeric))
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Error in `dplyr::mutate()`:
! Can't transform a data frame with duplicate names.
---
Backtrace:
    ▆
 1. ├─tidycensus::get_pums(...)
 2. │ └─tidycensus:::load_data_pums(...)
 3. │   └─dat %>% ...
 4. ├─dplyr::mutate(...)
 5. └─dplyr:::mutate.data.frame(., dplyr::across(.cols = dplyr::contains("WGTP"), as.numeric))
 6.   └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
 7.     └─DataMask$new(.data, caller_env, "mutate", error_call = error_call)
 8.       └─dplyr (local) initialize(...)
 9.         └─rlang::abort(...)

```

**Comment by lighthouseenergy** [comment]
I'm not sure if this is a related issue or not, but `get_pums()` also seems to return every record as a "person" record or maybe only person records. Pulling data for WA as above yields ~78k records, whereas if I pull the same ACS 1-year housing file for WA I see only ~35k records.

**Comment by walkerke** [comment]
Yes the first issue you mentioned is a bug.  To get this working for now, don't request `PUMA` as one of your variables, as you'll get it anyway if you are requesting data for specific PUMAs.  You also don't need to request `SERIALNO`, `ST`, or `WGTP` as those are variables we return by default.

For the second issue, housing-specific PUMS is tricky from the API as the API mixes the person and housing files.  [I'd recommend reading through Chapter 9 of my book for context](https://walker-data.com/census-r/introduction-to-census-microdata.html#using-microdata-in-tidycensus).  

Here's one way to get a housing unit dataset; you'll need to specify `return_vacant = TRUE` to ensure that vacant units are also returned, then drop duplicated household serial numbers.  The downloaded dataset has about 35k records as you're expecting.  

```r
library(tidycensus)
library(tidyverse)

wa_pums_housing <- get_pums(
  variables = c("TYPEHUGQ", "BLD", "NP", "PUMA"),
  state = "WA",
  survey = "acs1",
  year = 2021,
  return_vacant = TRUE,
  recode = TRUE
) %>%
  distinct(SERIALNO, .keep_all = TRUE)
```

**Comment by walkerke** [comment]
Just confirmed - my workflow described above yields the exact same number of rows (35,712) as the 2021 1-year ACS PUMS housing CSV for Washington.

**Comment by walkerke** [comment]
This is now fixed, thanks for flagging!
