### ISSUE TITLE
Cannot get county-level PEP data > 2019

### ISSUE THREAD

**Issue by alamstein** [walkerke/tidycensus#506]
This code works:

```
get_estimates(
  geography            = "county",
  product                 = "characteristics",
  breakdown            = "AGEGROUP",
  breakdown_labels = TRUE)
```

This code does not:

```
get_estimates(
  geography             = "county",
  product                 = "characteristics",
  breakdown            = "AGEGROUP",
  breakdown_labels = TRUE,
  year                       = 2021) # 2020 fails too - same error as below
```

It generates the following error:

```
Error in `map()`:
ℹ In index: 1.
Caused by error in `rate_sleep()`:
! Request failed after 3 attempts.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/purrr_error_indexed>
Error in `map()`:
ℹ In index: 1.
Caused by error in `rate_sleep()`:
! Request failed after 3 attempts.
---
Backtrace:
  1. tidycensus::get_estimates(...)
  2. purrr::map_df(...)
  3. purrr::map(.x, .f, ...)
  4. purrr:::map_("list", .x, .f, ..., .progress = .progress)
  8. tidycensus (local) .f(.x[[i]], ...)
 11. purrr (local) insist_get_estimates(...)
 12. purrr::rate_sleep(rate, quiet = quiet)
```

This would seem to indicate that there is an issue getting the 2021 county-level PEP data. According to this [this](https://www.census.gov/data/tables/time-series/demo/popest/2020s-counties-detail.html) link the dataset has been published. Is it perhaps not available via the API? Or is there some other issue?

Note: the default `year` is 2019. I get the same error for 2020 as well.

**Comment by walkerke** [comment]
Hi Ari!

Yes, you are correct that the 2020, 2021, and 2022 PEP are not fully available via the API, so they are not supported in tidycensus at the moment.  This is a good reminder that I should include an informative error message for this, so I'll patch that soon.  

I was told over a year ago by Census employees that they hope to support these datasets on the API in the future, but there are no immediate plans to do so / no timeline for this work.  I've been mulling over building in support in tidycensus to download and parse the flat files, returning results that are consistent with past years.  I just haven't had the time to get to this but I may look at putting it on my development agenda.

**Comment by walkerke** [comment]
Closing to handle in #423
