### ISSUE TITLE
Error for get_decennial() state legislative districts in 2000

### ISSUE THREAD

**Issue by bwilden** [walkerke/tidycensus#508]
I am trying to get the population in every state legislative district in California in the year 2000:

`get_decennial(geography = "state legislative district (lower chamber)", 
              variables = "P001001", 
              state = "CA",
              year = 2000)`

This give an error "unknown/unsupported geography heirarchy." But shouldn't population data for state legislative districts be available for the year 2000?

**Comment by walkerke** [comment]
Yes it is, but it looks like it's in a separate summary file, which is available but I don't currently have supported.  It'll be a quick fix and I'll post here to show you how to do it when I fix it.

**Comment by walkerke** [comment]
This now works as of tidycensus 1.4.1!  Try this:

```r
get_decennial(geography = "state legislative district (lower chamber)",  variables = "P001001",  state = "CA", year = 2000, sumfile = "sldh")
```
