### ISSUE TITLE
Get_pums for 2021 not working with RNTP and Vacant Units (VACS)

### ISSUE THREAD

**Issue by acardelle** [walkerke/tidycensus#509]
Not sure if something is off on the API side, but this code has been working for me for months until just today. I've tried making the call with and without using VACS and return_vacant, but after removing all filters and variables, I came to the conclusion that making any request that calls for joining RNTP and VACS produces a error.

`> US_pums_bld_vct_ten_rntp <- get_pums(
+   variables = c("PUMA", "BLD", "TEN", "RNTP"),
+   state = "VT",
+   survey = "acs1",
+   
+ #Filtering here means a faster data pull, but reduces future flexibility.
+   variables_filter = list(TEN = (3:4), SPORDER = 1),
+   
+   return_vacant = TRUE,
+   rep_weights = "housing",
+   year = 2021,
+   recode = FALSE)
Getting data from the 2021 1-year ACS Public Use Microdata Sample
You have requested information on vacant units; setting `return_vacant` to TRUE
Using FIPS code '50' for state 'VT'
Downloading: 140 kB     Using FIPS code '50' for state 'VT'
Downloading: 130 kB     Using FIPS code '50' for state 'VT'
Downloading: 170 kB     Using FIPS code '50' for state 'VT'
Downloading: 150 kB     Error in `stop_vctrs()`:
! Can't combine `..1$RNTP` <double> and `..2$RNTP` <character>.
Backtrace:
 1. tidycensus::get_pums(...)
 2. dplyr::bind_rows(pums_data, vacant_data)
 3. vctrs::vec_rbind(!!!dots, .names_to = .id)
 4. vctrs (local) `<fn>`()
 5. vctrs::vec_default_ptype2(...)
 6. vctrs::stop_incompatible_type(...)
 7. vctrs:::stop_incompatible(...)
 8. vctrs:::stop_vctrs(...)`

**Comment by walkerke** [comment]
Your code works for me.  Do you have the latest version of tidycensus installed (1.3.2)?
