### ISSUE TITLE
Blocks an invalid geography for Census2000?

### ISSUE THREAD

**Issue by matt439miller** [walkerke/tidycensus#51]
library(tidycensus)
library(tidyverse)
library(viridis)
library(ggplot2)
library(dplyr)

#------Get Decennial Census Data
ut2000tract <- get_decennial(geography = "tract", variables = "P001001", year = 2000, sumfile = "sf1",
                        key = mykey, state = "49", county = "035", geometry = FALSE)
ut2000BG <- get_decennial(geography = "block group", variables = "P001001", year = 2000, sumfile = "sf1",
                        key = mykey, state = "49", county = "035", geometry = FALSE)
ut2000block <- get_decennial(geography = "block", variables = "P001001", year = 2000, sumfile = "sf1",
                          key = mykey, state = "49", county = "035", geometry = FALSE)
Third case fails.

**Comment by walkerke** [comment]
At the moment, yes.  This is due to a limitation of the Census 2000 API as block data are only available by tract for 2000, and I don't have functionality in the package to handle this right now.  In the meantime I'd suggest using NHGIS (http://www.nhgis.org) for this kind of data.

**Comment by walkerke** [comment]
I've now included a more informative error message for this: `Error: At the moment, block data is only available for 2010. I recommend using NHGIS (http://www.nhgis.org) and the ipumsr package for block data for other years.`.  It is possible that I would include this functionality in the future but it would require including tract lookup tables for every county in the US in the package, so it isn't a top priority at the moment.  NHGIS and the new ipumsr package is my recommended alternative.
