### ISSUE TITLE
unexpected number of county FIPS codes 

### ISSUE THREAD

**Issue by jaskdb** [walkerke/tidycensus#515]
I have been using the built-in `fips_codes` dataset and has been extremely helpful. I am trying to understand is why the `fips_codes` dataset has 3,155 unique 5-digit FIPS codes (state-county, excluding: American Samoa, Guam, Northern Mariana Islands, Puerto Rico, U.S. Minor Outlying Islands and U.S. Virgin Islands). Based on census [tally documentation](https://www.census.gov/geographies/reference-files/time-series/geo/tallies.2010.html#list-tab-1626061381) I would expect it to be 3,143. Does anyone have any ideas? I attempted to compare the dataset with a list of the 2010 vintage [FIPS codes](https://www.census.gov/library/reference/code-lists/ansi.html) myself but found that they were only available to be downloaded individually by state.

**Comment by walkerke** [comment]
The dataset includes FIPS codes that are defunct to allow for translation of county names that don't exist anymore.  For example, Shannon County, SD is now Oglala Lakota County but both have entries in the `fips_codes` dataset.
