### ISSUE TITLE
Add new 2020 CT Counties to fips_codes

### ISSUE THREAD

**Issue by szimmer** [walkerke/tidycensus#516]
Seeing #515  made me check if the CT counties are included yet and they aren't. It would be great to have these appended. I could make a PR but it won't be any time soon.

https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.2020.html#list-tab-957819518

**Comment by walkerke** [comment]
@szimmer Ah yes we should get ahead of that as future data products will be using the new CT counties.  I'm not sure if the upcoming 2020 DHC file will be using the new CT counties, but 2022 ACS definitely will as well as the new 2022 Population Estimates.
