### ISSUE TITLE
2010 decennial variables vs. 2020 decennial variable

### ISSUE THREAD

**Issue by Yingt2023** [walkerke/tidycensus#517]
I'm trying to analyze sex by age in the 2020 census data, but when I used the load_variables() function with the parameters year = 2020 and dataset = 'pl', I couldn't find any related variables. Additionally, when I checked the number of observations in the resulting table, there were only 301, which seems too low. This is strange, since the 2010 decennial data had up to 27,850 variables.

Could you please advise me on how to obtain the sex by age variables for the 2020 census data? Thank you for your help.

**Comment by walkerke** [comment]
Sex by age has not yet been released.  We only have the PL-94171 redistricting data for the 2020 Census, which is a limited subset of variables.  The Census Bureau will be releasing the rest of the 2020 Census data (which includes age, sex, and detailed race / ethnicity) over the remainder of 2023 in the new DHC files.  The first batch should be coming out in two weeks, and I'll have support in tidycensus for the new data as soon as I can after that.

**Comment by Yingt2023** [comment]
Thank you very much, Dr. Walker! As someone who is new to working with census data, your answer has been extremely helpful.
