### ISSUE TITLE
get_decennial for the year 2000 at zcta geography is returning "Column `GEOID00` doesn't exist" when geometry = TRUE

### ISSUE THREAD

**Issue by Dakotah-Geog** [walkerke/tidycensus#518]
I am trying to get the ZCTA geometry associated with my 2000 census variables and I'm getting the following error. 

## Code:

library(tidycensus)
library(tidyverse)
library(sf)
census_api_key("")

Med_Inc <- c("P053001")

Med_Inc_00 <- get_decennial(sumfile = "sf3", geography = "zcta", variables = Med_Inc, year = 2000,
                         summary_var = "P053001", geometry = TRUE) %>%
                         mutate(pct = 100 * (value / summary_value))

## Error: 

Getting data from the 2000 decennial Census
Using Census Summary File 3
Error in chr_as_locations(x, vars) : 
  Can't rename columns that don't exist.
✖ Column `GEOID00` doesn't exist.
Error: Your geometry data download failed. Please try again later or check the status of the Census Bureau website at https://www2.census.gov/geo/tiger/

**Comment by walkerke** [comment]
Thanks for flagging.  I know how to fix this but the issue has some roots going down to the tigris package, so I'll keep you posted on when it's ready to go.

**Comment by walkerke** [comment]
This is now fixed, though you might want to use the argument `cb = FALSE` as the 2000 CB files give you separate polygons for each discontiguous part of a ZCTA.  I considered fixing this on the tigris side but it was too expensive of an operation so I throw a warning instead.
