### ISSUE TITLE
error: unknown variable 'GEO_IDE'

### ISSUE THREAD

**Issue by MikeeBakes** [walkerke/tidycensus#520]
**When using the following code:** 

bernalillo_tracts <- get_acs(geography = "tract",
                              variables = "GEOID",
                              state = "NM",
                              county = "Bernalillo",
                              geometry = TRUE)

**It returns the following error message:**

Error: Your API call has errors.  The API message returned is error: error: unknown variable 'GEOIDE'.

**The ACS codebook lists the variable as "GEO_ID". When I use the following code:** 

bernalillo_tracts <- get_acs(geography = "tract",
                              variables = "GEO_ID",
                              state = "NM",
                              county = "Bernalillo",
                              geometry = TRUE)

**It returns a similar error message:**

Error: Your API call has errors.  The API message returned is error: error: unknown variable 'GEO_IDE'.

**Comment by walkerke** [comment]
tidycensus can't return that column, though it does return GEOIDs by default which is the latter part of what is returned by `GEO_ID`.  Consider the censusapi R package or the pygris package in Python for more nuanced queries if you need that variable.
