### ISSUE TITLE
Error for get_pums() Acs5 2021

### ISSUE THREAD

**Issue by afleming9796** [walkerke/tidycensus#523]
I am trying to pull PUMS for the Vermont for Acs5 year 2021. When I execute the code below, I get an error 'cols must select at least one column'. It looks like there was a similar issue when trying to pull state='all', which was resolved. Could the issues be related? I'm using R version 4.2.2 (2022-10-31 ucrt)

library(tidycensus)
options(tigris_use_cache = TRUE)

vt_pums <- get_pums(
  variables = c("PUMA", "POVPIP", "AGEP"),
  state = "VT",
  survey = "acs5",
  year = 2021
)

 Error in `build_longer_spec()`:
! `cols` must select at least one column.

**Comment by walkerke** [comment]
I can't reproduce your error.  What version of tidycensus do you have installed?  Perhaps try updating the package?

**Comment by afleming9796** [comment]
Ah sorry about that. Updating the package resolved the issue. Thanks for your quick reply
