### ISSUE TITLE
congressional districts for 118th congress

### ISSUE THREAD

**Issue by ylelkes** [walkerke/tidycensus#525]
hi there, 
is it possible to get congressional district profiles for the most recent congress? ACS indicates they released the information: https://www.census.gov/newsroom/press-releases/2023/acs-1-year-congressional-district-profiles.html

but tidycensus pulls based on the previous district boundaries.

**Comment by mfherman** [comment]
Looks like they are not releasing these estimates to the API, so they wouldn't be available through tidycensus. [This post notes](https://www.census.gov/library/stories/2023/01/district-profiles-of-118th-congress.html):
> The cycle directly following a decennial census requires additional time to allow states to finalize their plans, resolve litigation surrounding those plans, and for the Census Bureau to collect and verify the plans.
>
>This extended collection period and the two-year cadence for collecting and reporting data on updated congressional and state legislative districts prevented the Census Bureau from including statistics on the 118th congressional and 2022 state legislative districts in its 2021 ACS 1-year or 2017-2021 ACS 5-year data releases last September and December, respectively.
>
>Following our normal production cycle, data for the 118th congressional and 2022 state legislative districts would not have been available until the 2022 ACS 1-year and 2018-2022 ACS 5-year releases, respectively, later in 2023.

So it appears that the estimates for the 118th congress for the full ACS universe of variables will be available with the 2022 1-year release. In the meantime, the data profiles referenced in the article above are available on the [Census FTP](https://www2.census.gov/programs-surveys/acs/data/2021/CD118_Data_Profiles/).

**Comment by ylelkes** [comment]
thanks!
