### ISSUE TITLE
Error on trying to pull DHC variable

### ISSUE THREAD

**Issue by hubbelk1** [walkerke/tidycensus#528]
I am trying to pull this DHC variable from the 2020 Census:
P11_001N, !!Total:,"HISPANIC OR LATINO, AND NOT HISPANIC OR LATINO BY RACE FOR THE POPULATION 18 YEARS AND OVER"
My R code is:
 ak <- get_acs(geography = "county", sumfile="dhc",
+               variables = c(tothh = "H10_001N"), 
+               state = "AK", 
+               year = 2020)
I'm getting the error
Getting data from the 2016-2020 5-year ACS
Using FIPS code '02' for state 'AK'
Error: Your API call has errors. The API message returned is error: error: Unknown variable 'H10_001NE'.

Why is it trying to use 5-year ACS and why is it putting an e on the end of my variable?

Katie Hubbell, Westat

**Comment by szimmer** [comment]
Use the function `get_decennial` instead of `get_acs`
