### ISSUE TITLE
Cannot get table B02001 (race demographics table) by Zip code

### ISSUE THREAD

**Issue by zaynaib** [walkerke/tidycensus#529]
Hello everyone,
I'm trying to get race demographics by zip code.  I get this error
`Getting data from the 2017-2021 5-year ACS
Using FIPS code '17' for state 'IL'
Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.
`

When I try to execute this code
`
library(tidycensus)
library(tidyverse)
race_IL_2 <- get_acs(
  geography = "zcta", 
  variables = c("B02001_001", "B02001_002","B02001_003", "B02001_004", "B02001_005", 
                "B02001_006","B02001_007","B02001_008","B02001_009","B02001_010"
  ),
  state = "IL",
  year = 2021
)
`

But I am able to get this data from the census reporter website. And if I remove the state argument then it works. And I change the year to earlier to 2020 then it works.

**Comment by sebastianrowan** [comment]
I was able to reproduce this. The issue seems to be on the census API side rather than with tidycensus as the issue also occurs when using the [censusapi](https://github.com/hrecht/censusapi) package, and when putting the api call into my browser directly.

**Comment by sebastianrowan** [comment]
Conformed in the census api developer forum that this functionality was not implemented for the acs endpoint for 2020 and 2021. The developers are aware of this difference, but I don't know if there are any plans to address this.

**Comment by walkerke** [comment]
see https://github.com/walkerke/tidycensus/issues/492
