### ISSUE TITLE
SLDU/SLDL call returns unknown/unsupported geography hierarchy

### ISSUE THREAD

**Issue by mbuenov** [walkerke/tidycensus#530]
Having issues similar to #490. The following code returns "Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography hierarchy."

```r
state_senate_districts <- get_acs(
  geography = "state legislative district (upper chamber)",
  variables = "B03003_003",
  geometry = TRUE,
  year = 2020,
  resolution = "20m",
  progress_bar = FALSE
)
#Getting data from the 2016-2020 5-year ACS
#Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
#Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.
``` 

Assistance/tips much appreciated, thank you!

**Comment by walkerke** [comment]
You have to specify a state for that geography, you can't pull for the entire US at once.  So add the argument `state = "CA"` or another state, and it should work.

**Comment by mbuenov** [comment]
Yup that worked, thank you!
