### ISSUE TITLE
Mapping Honolulu and Hawaii State Choropleths - Small Output

### ISSUE THREAD

**Issue by ConnorFlynn** [walkerke/tidycensus#532]
Hi, really enjoying using tidycensus! 

When making choropleth maps for Hawaii county, Maui county, or Kauai County the sizing is perfect (pictured below)![image](https://github.com/walkerke/tidycensus/assets/76076246/025a60c9-4725-4fb9-89d3-1f944d6a67b6)

However, when trying to visualize all of Hawaii (as a state) or Honolulu County, the size of the output map is extremely small (pictured below)![image](https://github.com/walkerke/tidycensus/assets/76076246/8b969b57-4539-451f-9c15-410880c5bfeb)

Here is my code:
```{r}
hi_pct_college_data <- get_acs(
  geography = "tract",
  variables = c(pct_college = "DP02_0068P"),
  state = "HI",
  geometry = TRUE,
  output = "wide",
  year = 2020)
```

```{r}

hi_pct_college_data_map <- ggplot(hi_pct_college_data, aes(fill = pct_collegeE)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c() + 
  theme_void() + 
  labs(fill = "Percent over 25 with College Degree")

hi_pct_college_data_hist <- ggplot(hi_pct_college_data, aes(x = pct_collegeE)) + 
  geom_histogram(alpha = 0.5, fill = "navy", color = "navy",
                 bins = 50) + 
  theme_minimal() + 
  scale_x_continuous() + 
  labs(x = "Percent over 25 with College Degree")

hi_pct_college_data_map + hi_pct_college_data_hist
```

Also note, removing the histogram does not change anything 
![image](https://github.com/walkerke/tidycensus/assets/76076246/dd850336-525e-42b0-bb26-c7f1683a343f)

Would greatly appreciate a way to solve this, thanks!

**Comment by walkerke** [comment]
There is a Census tract in Honolulu County that covers the uninhabited islands that stretch well west of the state into the Pacific.  If you remove that tract, you'll get the results you want:

```r
hi_pct_college_data <- get_acs(
  geography = "tract",
  variables = c(pct_college = "DP02_0068P"),
  state = "HI",
  geometry = TRUE,
  output = "wide",
  year = 2020
) |>
  dplyr::filter(GEOID != "15003981200")
```
