### ISSUE TITLE
CD118 and DHC-A file for 2020 Decennial; ACS 2022 single year

### ISSUE THREAD

**Issue by chuckpurvis** [walkerke/tidycensus#533]
What is your update strategy for three fairly significant US Census datasets that have been released, or will be released in the next couple of weeks?

CD118 (decennial census 2020): file released August 31, 2023
DHC-A (decennial census 2020): file scheduled for release September 21, 2023
ACS-2022 (American Community Survey, single year 2022): file scheduled for release September 14, 2023

Do you have access to the embargoed datasets? As in, you're doing some work on the behest of your local news outlet? That would be ideal for you to get early access to embargoed data.

Thanks in advance! Chuck Purvis in California.

**Comment by walkerke** [comment]
CD118 for the decennial Census is now available on Github, use `sumfile = "cd118"`.  The 2022 1-year ACS should just work out of the box, I don't anticipate any issues.  For the DHC-A file, I need to see what the URL structure looks like but I think it'll be straightforward.

No, I don't get the embargoed datasets.  It would be nice to get an API preview, for sure!

**Comment by mpadge** [comment]
Thanks for the awesome package @walkerke! A hopefully minor issue that the acs1 data for 2022 don't yet "just work out of the box":

``` r
tarr <- tidycensus::get_acs(
    geography = "tract",
    variables = "B19013_001",
    state = "TX",
    county = "Tarrant",
    geometry = TRUE,
    year = 2022,
    survey = "acs1"
)
#> Getting data from the 2022 1-year ACS
#> The 1-year ACS provides data for geographies with populations of 65,000 and greater.
#> Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
#> Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.
```

<sup>Created on 2023-09-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by szimmer** [comment]
You can't get tract data with 1-year data, only 5-year data.

**Comment by chuckpurvis** [comment]
Mark: If you want tract-level data, what's currently available is the 2017-2021 (5-year) ACS. These are using 2010 Census Tract geographies. If you want the 2018-2022 (5-year) ACS data, you'll have to wait until the Census Bureau releases it on December 7, 2023. Be sure to code: survey="acs5" ... tract-level data will never, ever be available for single-year ACS. The sample size is too small to support tract-level geography..... And the tract-level data released in December will be using the new, 2020 Census geographies.
