### ISSUE TITLE
get_acs zcta by state not working for 2021

### ISSUE THREAD

**Issue by dillgm** [walkerke/tidycensus#534]
When trying to query median household income by zip code and state (code below), error occurs when trying to obtain 2021 data. It does seem to work for 2019 and older data. Is there an issue with sorting the 2021 acs data by zip code and state?

get_acs(geography = "zcta", 
               variables = c(medincome = "B19013_001"), 
               state = "ME", 
               year = 2021, geometry = TRUE)

**Comment by walkerke** [comment]
Correct, the Census Bureau doesn't support ZCTAs by state in the 2020 and 2021 5-year ACS, but does for earlier years.  See here: https://github.com/walkerke/tidycensus/issues/475
