### ISSUE TITLE
Hispanic variables switched in 2010 Census

### ISSUE THREAD

**Issue by walinchus** [walkerke/tidycensus#537]
I’m not sure why, but this package has P004002 labeled “Total!! Hispanic or Latino” and has “P004003 labeled Total!!**Not** Hispanic or Latino” when it should be the other way around according to the [variable list](https://api.census.gov/data/2010/dec/sf1/variables.html) in the Census API [website.](https://www.census.gov/library/stories/state-by-state/delaware-population-change-between-census-decade.html) 
<img width="613" alt="image" src="https://github.com/walkerke/tidycensus/assets/25959269/1b4a6d92-2401-4207-888e-c59bb7d3478a">

2020 is labeled correctly. Or at least jives with their website.

**Comment by walkerke** [comment]
I'm not seeing what you see when I run `load_variables(2010, "sf1")`: 

![image](https://github.com/walkerke/tidycensus/assets/4872833/4f6c6e74-ffaa-48e6-ad35-a35172f76915)

What specific code did you run, and what is your version of tidycensus?

**Comment by walkerke** [comment]
I am noticing that the variables are swapped in the 2000 SF1.  Any chance you accidentally ran `load_variables(2000, "sf1")`?

**Comment by walinchus** [comment]
1.4.5 (Tidycensus version) 

Hmm no it looks like I only used the load_variables() function with 2020 or 2010: 
<img width="609" alt="image" src="https://github.com/walkerke/tidycensus/assets/25959269/ccf1fd79-fecf-4089-ba35-9ab34c6743e9">

Specifically, I ran this code: 
`decennial_2010_vars <- load_variables(
                              year = 2010, 
                              "pl", 
                              cache = TRUE)`

<img width="609" alt="image" src="https://github.com/walkerke/tidycensus/assets/25959269/b16a5b35-f6c2-49eb-8f87-a2e61713d92e">
Weird that I keep getting this. Thanks for your help.

**Comment by walkerke** [comment]
Noting this code you used: 

`decennial_2010_vars <- load_variables( year = 2010,  dataset = "pl",  cache = TRUE)`

That means you are pulling from the PL 94-171 redistricting file, not Summary File 1 as you wanted.  You'd want instead: 

`decennial_2010_vars <- load_variables( year = 2010,  dataset = "sf1",  cache = TRUE)`

And yes, it is annoying that Census does not keep variable names consistent across the different datasets.  To mitigate this, use the `sumfile` argument (e.g. `sumfile = "sf1"`) and the variables pulled from a corresponding call to `load_variables()` for that dataset and year.  This inconsistency between the PL and DHC files for 2020 is present as well, as a heads up.

**Comment by walinchus** [comment]
Great thanks for your help.
