### ISSUE TITLE
Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.

### ISSUE THREAD

**Issue by KennyLizzy** [walkerke/tidycensus#539]
I am trying to get the race composition for zip codes in Maryland using the code below. However, I kept getting this error message "Error: Your API call has errors. The API message returned is error: unknown/unsupported geography heirarchy.” I would appreciate any suggestion to resolve this issue. 

library(tidyverse)
library(tidycensus)
race_vars_1 <- c(
  white = "S0601_C01_014E",
  Black = "S0601_C01_015E",
  Native_Alaska = "S0601_C01_016E",
  Asian = "S0601_C01_017E",
  Native_Hawaaiian="S0601_C01_018E",
  Some_other_race = "S0601_C01_019E",
  Two_or_more_race = "S0601_C01_020E",
  Hispanic = "S0601_C01_021E",
  Not_Hispanic ="S0601_C01_022E"
)
  

md_race <- get_acs(
  geography = "zcta",
  state = "MD",
  variables = race_vars_1,
  summary_var = "S0601_C01_001E",
  survey = "acs5"
)

**Comment by camille-s** [comment]
Check the [available geographies](https://api.census.gov/data/2021/acs/acs5/subject/geography.html) for the API: ZCTAs aren't subsets of states.
