### ISSUE TITLE
Error while installing tidycensus package in R on Mac

### ISSUE THREAD

**Issue by Tarunedx** [walkerke/tidycensus#540]
Steps :
1. Install the package from R studio using install.packages("tidycensus",dependencies = TRUE).
2. the error we encountered is shown below.

checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
configure error: libproj or sqlite3 not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/opt/homebrew/lib/R/4.3/site-library/sf’
ERROR: dependency ‘sf’ is not available for package ‘tigris’
* removing ‘/opt/homebrew/lib/R/4.3/site-library/tigris’.

3. we have the packages sqlite3 already installed and updated in the system. But somehow R is not able to find the location.
4. Even i tried to install this tidycensus package from GITHUB using the below command 
remotes::install_github("walkerke/tidycensus")

But, the error is still the same.

**Comment by walkerke** [comment]
You'll need to install and configure the sf package first; when you see "configuration failed for package 'sf'" that's your hint.  

Follow the instructions here: https://github.com/r-spatial/sf
