### ISSUE TITLE
voting district geography incompatible with dhc tables?

### ISSUE THREAD

**Issue by ayurcaba** [walkerke/tidycensus#541]
I'm attempting to pull data from 2020 `dhc` tables at the `voting district` level. So far I've been able to successfully run my base code to obtain the data when I switch the geography to `county subdivision` or `county`, or when I preserve the `voting district` geography and query data from the `pl` tables. Unfortunately, when I try to query data from the `dhc` tables at the `voting district` level, I receive the `Error : Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.` error message. My sample code is included below for reference! I've attempted to use some other states' geographies to correct for anything wrong with New Jersey in particular, but received the same error message.

`get_decennial(geography = "voting district", 
variables = c("P12_007N", "P12_008N"), 
year = 2020, 
sumfile = "dhc",
state = "NJ",
county = c("Essex", "Hudson"), show_call = T)`

**Comment by walkerke** [comment]
That's correct - voting districts are not available as a geography for the DHC file.  You'll need to stick with `sumfile = "pl"` to get data at the voting district level.

**Comment by ayurcaba** [comment]
Understood, thank you for the quick clarification! Is there any expectation that voting district-level queries will be possible for the dhc tables at some point in the future, or is that not realistic at this time?
