### ISSUE TITLE
congressional district from ACS1 giving an error

### ISSUE THREAD

**Issue by jose-m-maciasiii** [walkerke/tidycensus#543]
Hello,

I was trying to download data for 2022 and I wanted congressional district data plus the geometry but there is an error:

income_geom_data <- 
+   get_acs(
+   geography = "congressional district",
+   variables = acs_vars,
+   year = 2022, # 
+   survey = "acs1",
+   geometry = TRUE) 
Getting data from the 2022 1-year ACS
The 1-year ACS provides data for geographies with populations of 65,000 and greater.
Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.
**Cannot open layer cb_2022_us_cd116_500k
Error : Opening layer failed.**

**In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
Error: Your geometry data download failed. Please try again later or check the status of the Census Bureau website at https://www2.census.gov/geo/tiger/**

It appears also that they still have the 116th congress and not 118th shapefiles

**Comment by walkerke** [comment]
I don't have shapefiles for the 118th Congress supported in tigris (and consequently tidycensus), unfortunately.  While these files are available they are found in a separate file that does not follow the regular TIGER/Line URL structure.  I've been awaiting the 2023 shapefile release (which should have the updates) but that appears to be delayed.

**Comment by jose-m-maciasiii** [comment]
Thanks for letting me know!
