### ISSUE TITLE
Possible Issue with get_decennial block level variables

### ISSUE THREAD

**Issue by jmwestenberg** [walkerke/tidycensus#545]
I was able to successfully pull 2010 populations with the following code

get_decennial(
  geography = "block", 
  variables = "P001001",
  state="WI",
  year = 2010,
  geometry = TRUE
) 

However once I try to start pulling other variables such as:
get_decennial(
  geography = "block", 
  variables = "P001002",
  state="WI",
  year = 2010,
  geometry = TRUE
) 

I get the following error message:
Error : Your API call has errors.  The API message returned is error: error: unknown variable 'P001002'.

But looking around online it appears this data is available at the block level. Is there something I am missing?

**Comment by walkerke** [comment]
I don't believe this is a variable available in 2010.  Where are you seeing this?
