### ISSUE TITLE
2022 ACS will require 2023 TIGER geometries for congressional districts

### ISSUE THREAD

**Issue by walkerke** [walkerke/tidycensus#548]
The 2022 TIGER/Line shapefiles use the 116th Congress boundaries, but the 2022 ACS data use the 118th Congress.  So our usual way of matching geometries to geographies won't work in this case.  We'll need 2023 TIGER files instead (acknowledging that the CB files aren't yet released for '23).    

Add logic to fix before the next CRAN release.

**Comment by kateham** [comment]
Just to be clear, 2022 5-year data is available for CD118? And it can still be combined manually with the CD118 geographies from the FTP site?

**Comment by walkerke** [comment]
@kateham yes, that's a good workaround until I fix this.

**Comment by walkerke** [comment]
Census fixed this - the 2022 TIGER files now use CD118.  The updated tigris package is necessary to get this to work.
