### ISSUE TITLE
ACS 1-year survery: error when downloading 2010 or 2011

### ISSUE THREAD

**Issue by kitsoho** [walkerke/tidycensus#55]
I received the following error when trying to download 2010 and 2011 data using the ACS 1-year survey. I was able to download 2010-2016 with no problems using the ACS 5-year survey.

![34618696-914ce2c4-f20d-11e7-9948-ff469dc3b75e](https://user-images.githubusercontent.com/4572420/34723834-e7b41128-f519-11e7-83fc-f05f2ed9cfb2.png)

**Comment by walkerke** [comment]
1-year ACS data are only available beginning in 2012, as addressed in https://github.com/walkerke/tidycensus/issues/48.  The newest version of tidycensus gives the following error message: 

> Error: The acs1 data is currently available beginning in 2012. Please select a different year.

**Comment by kitsoho** [comment]
Ah thanks for clarifying! Sorry I missed that previous issue.

**Comment by walkerke** [comment]
No problem, thank you for using the package!
