### ISSUE TITLE
"dp" dataset not working

### ISSUE THREAD

**Issue by phcantis** [walkerke/tidycensus#551]
Some time ago (this year) i was able to use "dp" as a variable in the sumfile argument to retrieve sex and age data at the tract level for the 2020 decennial census. However, it seems to not work anymore. When I use "dp" in the load_variables function, I get the following error: 

> Error: lexical error: invalid char in json text.
>                                        <!doctype html><html lang="en">
>                      (right here) ------^

When using "dp" as input in the get_decennial() function, it reports that the PL dataset is being queried instead: 

get_decennial(geography = "tract", variables = "DP1_0001C" , sumfile = "dp", state = "36", county = c("005", "047", "061", "081", "085"), year = 2020)

> Getting data from the 2020 decennial Census
> Using the PL 94-171 Redistricting Data summary file
> Error in UseMethod("gather") : 
>   no applicable method for 'gather' applied to an object of class "character"

**Comment by walkerke** [comment]
This works fine for me, tested against the most recent GitHub version.  Perhaps try updating the package?

**Comment by phcantis** [comment]
It seems like that-s it. I run the line in another laptop and it worked, so they probably have different versions. Thank you for the catch!
