### ISSUE TITLE
Clarify replicate weights method for pums data

### ISSUE THREAD

**Issue by apeterson91** [walkerke/tidycensus#552]
Hi, the [argument setting](https://github.com/walkerke/tidycensus/blob/95e45ee2cd2998e8b5e33f0f3bca7f2f877ec1c8/R/pums.R#L468) on line 468 of the R/pums.R file is a little unclear for one digging into the innards of the package.

As written in [chapter 10](https://walker-data.com/census-r/analyzing-census-microdata.html) of your book the type of weights produced for this data are [successive difference replicate weights](https://www150.statcan.gc.ca/n1/pub/12-001-x/2014001/article/14029/02-eng.htm), _not_ jackknife weights. You set the other arguments according to the [docs](https://github.com/cran/survey/blob/2c67911426c5128dc4016e7866aa27d35188f98b/man/svrepdesign.Rd#L76) I see in the R survey package for producing correct ACS estimates but it isn't clear to me that this will produce an equivalent answer.  I'm hoping to get some clarity on why the Jackknife 1 "type" is appropriate here, or equivalently if there's any difference between using this setting with the `srvyr` package and the `successive-difference` argument setting with the `survey` package.

I'm hoping we can add a comment in the code and the documentation for the function that could clarify to a future reader why this choice was made if the current choice is appropriate, or make the needed change if not.

**Comment by walkerke** [comment]
Good question.  When @mfherman and I implemented the `to_survey()` function we aligned our work with the recommended workflows by IPUMS (see https://usa.ipums.org/usa/repwt.shtml#q50) and Anthony D'Amico's work (see http://asdfree.com/american-community-survey-acs.html).  

When we've tested this method against the Census Bureau's user verification files, our results check out.  Some examples are here: https://walker-data.com/tidycensus/articles/pums-data.html#verification-of-pums-estimates.   

That said, I'd need to comb through the survey package's source code in greater detail to see what differences may exist between the `successive-difference` type and the workflows cited above.

**Comment by apeterson91** [comment]
Thanks for linking to the IPUMS docs. Looks like the clarification I'm looking for is there:

> Correspondence with StataCorp statisticians and IPUMS testing revealed that successive difference replicate weights can be treated as jackknife replicate weights if the options are specified correctly.

I've sent you a pull request with a comment clarifying this for future users. Thanks for your speedy reply!
