### ISSUE TITLE
"HISP" breakdown labels in `get_estimates(geography = "state")` return miscoded 

### ISSUE THREAD

**Issue by soubhikbarari** [walkerke/tidycensus#554]
Hi there, it looks like `HISP` variable values of "Both Hispanic Origins" are miscoded in state-level ACS pop totals broken down by RACE/HISP (both 2020 and 2022 as far as I can reproduce). 

Reproducible example:
```
state_age_race <-
	tidycensus::get_estimates(
            geography = "state", 
            product = "characteristics", year = 2020, 
	    variables = "POPESTIMATE", 
            breakdown = c("HISP"), 
	    breakdown_labels = TRUE
	 )
state_age_race %>%
	filter(NAME == "Alabama") %>% 
	arrange(desc(value))
```
Output:
![image](https://github.com/walkerke/tidycensus/assets/5015674/a6671bbb-c98e-4114-b060-a21ed7630293)

Here it is again with `breakdown_labels = FALSE`:

![image](https://github.com/walkerke/tidycensus/assets/5015674/1b36be28-de21-4fe0-b163-2e5b083e8cc1)

Clearly, the "Both Hispanic Origins" number (coded as 0) is implausibly large for Alabama (or any state). 

Cross-checking [census cross-tabs](https://www.census.gov/library/stories/state-by-state/alabama-population-change-between-census-decade.html), it seems like summing "Both Hispanic Origins" and "Non-Hispanic" together gets us the Non-Hispanic white population, while the "Hispanic" population count looks correct. Anyhow, that's my current treatment of the variable, but I'm hoping someone can confirm and/or fix and/or correct me if I've made a mistake.

**Comment by walkerke** [comment]
Alabama's population is 5.03 million, which is what is represented in "Both Hispanic Origins."  What did you expect to see?

**Comment by soubhikbarari** [comment]
OK, I clearly misinterpreted "Both Hispanic Origins" to mean something like "of two different Hispanic origins (Latino? different countries)". Thanks for clarifying.
