### ISSUE TITLE
get_pums and/or Census API issue 

### ISSUE THREAD

**Issue by crb61** [walkerke/tidycensus#556]
I was originally trying to pull 1-Year PUMS data for a specific county in the US for multiple years, which was working earlier last week, but now I am getting 'Your API call has errors' whenever I try to pull anything with weights using get_pums(). Here is my latest pull:

```
dat <- get_pums(variables = c("SEX", "AGEP", "TEN", "NP", "PUMA"), 
           state = "NC", 
           year = 2022, 
           survey = "acs1", 
           rep_weights = "person", 
           show_call = TRUE)
```
 
When I paste the Census API call into the browser, sometimes it loads what I requested. Other times, it gives me an API error message.

When I try to pull the data without the weights like the one below, then sometimes it works. An example of it working without the weights. 
```
dat <- get_pums(variables = c("SEX", "AGEP", "TEN", "NP", "PUMA"), 
           state = "NC", 
           year = 2022, 
           survey = "acs1", 
           show_call = TRUE)
```

I have had no issues getting anything with get_acs( ), so I am not sure what is going on with get_pums( ).

**Comment by walkerke** [comment]
I just pasted the raw query into my browser, and got the same error.  So it appears that the PUMS API is having some performance issues with respect to large queries.  Usually this is temporary but if it persists I'll send them a note to find out what is going on.

**Comment by crb61** [comment]
Sounds good, thank you!

**Comment by walkerke** [comment]
No problem!  I was just able to run your code successfully so perhaps try again?  I do think the PUMS API is a bit slow right now, so you might consider saving the output as an RDS file if you'll need it again in future sessions (or using qs::qcache(), which I like).

**Comment by crb61** [comment]
Yep everything is working!
