### ISSUE TITLE
geography column empty for load_variables() for 2022 ACS 5-year estimate variables

### ISSUE THREAD

**Issue by profLuna** [walkerke/tidycensus#559]
The following code provides four populated variables: "name"      "label"     "concept"   "geography"
`v21 <- load_variables(year = 2021, "acs5")`
> head(v21)
A tibble: 6 × 4
  name        label                                   concept                  geography
  <chr>       <chr>                                   <chr>                    <chr>    
1 B01001A_001 Estimate!!Total:                        SEX BY AGE (WHITE ALONE) tract    
2 B01001A_002 Estimate!!Total:!!Male:                 SEX BY AGE (WHITE ALONE) tract    
3 B01001A_003 Estimate!!Total:!!Male:!!Under 5 years  SEX BY AGE (WHITE ALONE) tract    
4 B01001A_004 Estimate!!Total:!!Male:!!5 to 9 years   SEX BY AGE (WHITE ALONE) tract    
5 B01001A_005 Estimate!!Total:!!Male:!!10 to 14 years SEX BY AGE (WHITE ALONE) tract    
6 B01001A_006 Estimate!!Total:!!Male:!!15 to 17 years SEX BY AGE (WHITE ALONE) tract 

The following code generates the same four variables, but "geography" values are all NA
`v22 <- load_variables(year = 2022, "acs5")`
> head(v22)
A tibble: 6 × 4
  name        label                                   concept                  geography
  <chr>       <chr>                                   <chr>                    <chr>    
1 B01001A_001 Estimate!!Total:                        Sex by Age (White Alone) NA       
2 B01001A_002 Estimate!!Total:!!Male:                 Sex by Age (White Alone) NA       
3 B01001A_003 Estimate!!Total:!!Male:!!Under 5 years  Sex by Age (White Alone) NA       
4 B01001A_004 Estimate!!Total:!!Male:!!5 to 9 years   Sex by Age (White Alone) NA       
5 B01001A_005 Estimate!!Total:!!Male:!!10 to 14 years Sex by Age (White Alone) NA       
6 B01001A_006 Estimate!!Total:!!Male:!!15 to 17 years Sex by Age (White Alone) NA

**Comment by walkerke** [comment]
Be sure you have the latest version of tidycensus installed with `install.packages("tidycensus")`, this should fix that.
