### ISSUE TITLE
return_vacant and 'VACS' variable not working for get_pums

### ISSUE THREAD

**Issue by willyrcoder** [walkerke/tidycensus#560]
I am trying to grab the new PUMs data using tidycensus and I need vacancies to do the analysis. However, whenever I use the latest year for PUMS,  get_pums throws and error if I include the variable 'VACS' or use 'return_vacant = TRUE'.  Below is the code I am using:
```r
OR_housing <- c(  "ADJHSG",
                  "ADJINC",
                  "BLD",
                  "NP",
                  "CONP",
                  "ELEP",
                  "FULP",
                  "GASP",
                  "MHP",
                  "MRGP",
                  "RNTP",
                  "SMP",
                  "TEN",
                  "VACDUR",
                  "VALP",
                  "WATP",
                  "YRBLT")


or_hh_data <- get_pums(
  variables = OR_housing, 
  state = "OR",
  year = 2022,
  survey = "acs1",
  return_vacant = TRUE,
  recode = TRUE
) 

``` 
When running the above code, I receive this error: Error: Can't combine `..1$NP` <double> and `..2$NP` <character>.

If I remove return_vacant or the 'VACS' variable, the code works fine. Is this a bug arising from the changes to the 2020 PUMs geographies? Is there a way to get vacancy with the new geographies?

**Comment by walkerke** [comment]
Thanks for flagging!  The PUMS API appears to be down right now so I can't test, but I will do so when it's back up.

**Comment by walkerke** [comment]
Just fixed one bug - this now works when `recode = FALSE`.  However it's failing with recoding, so I'm still chasing that down.

**Comment by walkerke** [comment]
@willyrcoder try out the GitHub version (`remotes::install_github("walkerke/tidycensus")` - this is now fixed.

**Comment by willyrcoder** [comment]
Thank you!!!
