### ISSUE TITLE
Failed with error:  ‘lazy-load database 'C:/R/win-library/4.0/tidycensus/data/Rdata.rdb' is corrupt’

### ISSUE THREAD

**Issue by doh-FXX0303** [walkerke/tidycensus#561]
Hi, 
I tried to install the package using pacman and got the following error. 

`
Failed with error:  ‘lazy-load database 'C:/R/win-library/4.0/tidycensus/data/Rdata.rdb' is corrupt’
In addition: Warning messages:
1: In FUN(X[[i]], ...) : restarting interrupted promise evaluation
2: In FUN(X[[i]], ...) : internal error -3 in R_decompress1
Warning message:
In pacman::p_load(tidycensus, install = T) : Failed to install/load:
tidycensus
`

`pacman::p_load(tidycensus, install = T)
`

**Comment by walkerke** [comment]
Try restarting R then try to install again.
