### ISSUE TITLE
Connecticut data absent in county-level geography request

### ISSUE THREAD

**Issue by ILSR-GIS-DATA** [walkerke/tidycensus#569]
I recently used get_acs to get some county-level data for the whole country, using the newest 2018-2022 data. I discovered that Connecticut counties are missing! When I searched for Connecticut in the dataframe I created (see below), I found several CT "regions" instead. It doesn't seem to be an issue for other states. 

This is the code I used: 
`HHincome_county.1 <- get_acs(survey = "acs5", geography = "county", table = "B19001", year = 2022, geometry = FALSE, moe_level = 95, state = NULL,cache_table = FALSE)`

![ct](https://github.com/walkerke/tidycensus/assets/99908618/9ee1876b-12d1-4b25-8675-eaeface93ec9)

**Comment by szimmer** [comment]
This is not an issue with tidycensus. Connecticut changed its county-equivalents recently. https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.html

**Comment by ILSR-GIS-DATA** [comment]
> This is not an issue with tidycensus. Connecticut changed its county-equivalents recently. https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.html

OH! That clears it up - thanks for the quick response.
