### ISSUE TITLE
Does `interpolate_pw` use population-weighted areal interpolation? 

### ISSUE THREAD

**Issue by kaseyzapatka** [walkerke/tidycensus#571]
Hi @walkerke, 

Just wanted to flag a small discrepancy in documentation between your book and the `tidycensus` documentation. 

In [chapter 7 of your book](https://walker-data.com/census-r/spatial-analysis-with-us-census-data.html?q=interpo#population-weighted-areal-interpolation), it suggests that the 'tidycensus' function, `interpolate_pw`, uses population-weighted areal interpolation, but this isn't clear from the [tidycensus reference documentation.](https://walker-data.com/tidycensus/reference/interpolate_pw.html) I think you mentioned to me in a Census slack that it does, but wanted to confirm/harmonize the documentation.

**Comment by walkerke** [comment]
Yes it does!  I'll clarify this in the docs.
