### ISSUE TITLE
Issue with accessing table B05001 at census tract level

### ISSUE THREAD

**Issue by chad-fisher** [walkerke/tidycensus#572]
This is my first time using tidycensus and I'm trying to get a bunch of data on foreign-born populations downloaded into R and would rather not have to download each table individually. 

I have confirmed that data exists on https://data.census.gov/table/ACSDT5Y2021.B05001?t=Native%20and%20Foreign-Born&g=010XX00US$1400000, but can't seem to call this specific geography in R. I've confirmed calling at the county level works. Curious if you have any insight!

```
FB_2021_cnty <- get_acs(geography = "tract",
              variables = c("B05001_001","B05001_005","B05001_006"),
              output = "wide",
              year=2021,
              geometry = TRUE,
              cache_table = TRUE)
```
Getting data from the 2017-2021 5-year ACS
Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.

**Comment by chad-fisher** [comment]
Following up to say, it seems I just have to explicitly name each state abbreviation as a list. Is there a more elegant way to do this? Thanks for supporting a great package!

```
FB_2021_ct <- get_acs(geography = "tract",
                      variables = c("B05001_001","B05001_005","B05001_006"),
                      output = "wide",
                      state=c("AL","AK","AZ","AR","CA","CO","CT",
                              "DE","FL","GA","HI","ID","IL","IN",
                              "IA","KS","KY","LA","ME","MD","MA",
                              "MI","MN","MS","MO","MT","NE","NV",
                              "NH","NJ","NM","NY","NC","ND","OH",
                              "OK","OR","PA","RI","SC","SD","TN",
                              "TX","UT","VT","VA","WA","WV","WI",
                              "WY"),
                      year=2021,
                      geometry = TRUE,
                      cache_table = TRUE)
```

Getting data from the 2017-2021 5-year ACS
Fetching tract data by state and combining the result.
  |=====================================================================| 100%
  |=====================================================================| 100%
  |=====================================================================| 100%
  |=====================================================================| 100%
  |=====================================================================| 100%

**Comment by walkerke** [comment]
I tend to pass `c(state.abb, "DC")` to avoid typing out all the states when I want a national pull like this.
