### ISSUE TITLE
DP04 Missing DP04_0005P Variable

### ISSUE THREAD

**Issue by colinc1994** [walkerke/tidycensus#574]
I keep trying to pull the DP04_0005P variable from the Dp04 Table but it seems to be missing for every year

get_acs(geography = "zcta",
        year = 2017,
        state = "MA",
        table = "DP04",
        keep_geo_vars = T,
        cache_table = T) %>%
filter(grepl("DP04_0005P",variable))

**Comment by szimmer** [comment]
It might help to look at the table as a bigger picture and how it's
displayed online. The Vacancy rate itself is a percentage so the Percentage
column isn't applicable.
https://data.census.gov/table/ACSDP1Y2022.DP04?q=DP04 - note it's listed as
(x).
