### ISSUE TITLE
decennial 1990 not available?

### ISSUE THREAD

**Issue by hussaifm** [walkerke/tidycensus#576]
Is 1990 decennial census not available in tidycensus or am I missing something? What do you recommend as an alternative to obtain it?

Thanks

**Comment by mfherman** [comment]
The earliest available [decennial data in the Census API is 2000](https://www.census.gov/data/developers/data-sets/decennial-census.html) so it is not available via tidycensus. You can download [1990 data from the Census website](https://www.census.gov/programs-surveys/decennial-census/data/datasets.1990.List_327707051.html#list-tab-List_327707051).

[IPUMS/NHGIS](https://www.nhgis.org/) are also very good sources of historical census data.
