### ISSUE TITLE
get_decennial(): GEOCOMP: inconsistent behavior

### ISSUE THREAD

**Issue by rcragun** [walkerke/tidycensus#577]
# Problem

This code works:
```
library(tidycensus)

get_decennial(
  geography = 'block',
  variables = 'GEOCOMP',
  state = "AL",
  county = 'Jefferson',
  geometry = F,
  sumfile = 'sf1',
  year = 2010
)
```
But this code does not:
```
get_decennial(
  geography = 'block',
  variables = 'GEOCOMP',
  state = "AL",
  # county = 'Jefferson',
  geometry = F,
  sumfile = 'sf1',
  year = 2010
)

# Response:
Error in load_data_decennial(geography, variables, key, year, sumfile,  : 
  No content was returned from the API.  Please refine your selection.”
```
Oddly, though, the second command works if I replace `GEOCOMP` with a different variable, so it is not generally true that the `block` `geography` requires a `county`. Example:
```
get_decennial(
  geography = 'block',
  variables = 'PCT012E073',
  state = "AL",
  # county = 'Jefferson',
  geometry = F,
  sumfile = 'sf1',
  year = 2010
)
```

**Comment by walkerke** [comment]
GEOCOMP is a predicate, and not intended to be used as a variable in the ways that other variables are in tidycensus - so it's not going to be configured to work, unfortunately.  You can use `load_variables(2010, "sf1")` to get a full list of variables that will work for 2010's SF1.
