### ISSUE TITLE
get_estimates show_call is not displaying

### ISSUE THREAD

**Issue by rdev-kb** [walkerke/tidycensus#578]
I am unable to see the API call when show_call=TRUE in get_estimates. I am running tidycensus 1.6.3 and R 4.4.0. For example:

```
get_estimates(geography = c("state"),  product = "characteristics", 
               breakdown = c("SEX", "AGEGROUP"), breakdown_labels = TRUE,
               vintage =2022, year=2022, show_call = TRUE) %>% 
     head()
```

**Comment by walkerke** [comment]
The issue there is that you aren't actually making an API call.  The Population Estimates are no longer available via API, so tidycensus instead downloads the flat files and parses them for you.  I'll deprecate this argument for the function for recent years, as it's unlikely that PEP will be re-added to the API.

**Comment by rdev-kb** [comment]
Thank you very much!
