### ISSUE TITLE
Getting population estimates with get_decennial function

### ISSUE THREAD

**Issue by bbrewington** [walkerke/tidycensus#58]
Is it possible to get the yearly population estimates using the get_decennial function?  It currently limits the year to the actual census year (1990, 2000, 2010)

Link to "popest" dataset: https://www.census.gov/data/developers/data-sets/popest-popproj/popest.Vintage_2015.html

The R package "censusapi" can grab this info with the getCensus function:
```r
censusapi::getCensus(
    name = "pep/population", 
    vintage = 2015, 
    region = "state", 
    vars = c("POP", "GEONAME", "SUMLEV")
)
```

**Comment by walkerke** [comment]
Closing this as I'll be handling it in https://github.com/walkerke/tidycensus/issues/59.  Stay tuned for a new `get_estimates()` function that will handle data from the estimates APIs.

**Comment by walkerke** [comment]
@bbrewington this is now supported in the estimates branch of the dev version of the package.  I'll merge to master once the API is stable.  If you install from that branch, this code works: 

```r
> get_estimates(geography = "state", year = 2017, variables = "POP")
# A tibble: 52 x 4
   NAME                 GEOID variable    value
   <chr>                <chr> <chr>       <dbl>
 1 Alabama              01    POP       4874747
 2 Alaska               02    POP        739795
 3 Arizona              04    POP       7016270
 4 Arkansas             05    POP       3004279
 5 California           06    POP      39536653
 6 Colorado             08    POP       5607154
 7 Connecticut          09    POP       3588184
 8 Delaware             10    POP        961939
 9 District of Columbia 11    POP        693972
10 Florida              12    POP      20984400
# ... with 42 more rows
```
