### ISSUE TITLE
Finding ZCTA variables

### ISSUE THREAD

**Issue by anderelm** [walkerke/tidycensus#584]
Hello, I am trying to identify the variables associated with the zcta levels. However, I get this error when I try to search for variables at that geographic level. 

acs_vars <- load_variables(year = 2020, "acs5")  
zcta_vars <- acs_vars[acs_vars$geography == "zcta", ] 

This produces an empty dataframe. Additionally:
table(acs_vars$geography)

block group      county       state       tract          us 
       4085        1346        1052       13033        6305

**Comment by walkerke** [comment]
The table only shows geographies in the core Census hierarchy (see here: https://walker-data.com/census-r/the-united-states-census-and-the-r-programming-language.html#census-hierarchies).  A rule of thumb: if the variable is available at the block group or tract level, it will be available at the ZCTA level.  If it is only available at the county or state level, it won't be.
