### ISSUE TITLE
get_acs() for counties pulls non-county data for Connecticut

### ISSUE THREAD

**Issue by richardsalex** [walkerke/tidycensus#592]
For example:

get_acs(geography = "county",
        variables = "DP03_0062",
        survey = "acs5",
        year = 2022,
        state = "CT")

Retrieves "planning regions" in CT rather than county data for the most recent 5-yr ACS.

**Comment by szimmer** [comment]
These are the county equivalents for Connecticut. 

See https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.2020.html#list-tab-957819518
