### ISSUE TITLE
Change api calls from http to https

### ISSUE THREAD

**Issue by austensen** [walkerke/tidycensus#6]
You are probably also on the mailing list for this, but just in case, Census is changing their api from http to https.

> To improve security and privacy, and by federal government mandate, the U.S. Census Bureau will stop receiving Application Programming Interface (API) calls at<http://api.census.gov/data/> on August 28, 2017.

[HttpsChangeDocument.pdf](https://github.com/walkerke/tidycensus/files/1042932/HttpsChangeDocument.pdf)

**Comment by walkerke** [comment]
Yes, thank you!  I'll get this fixed before its CRAN release.

**Comment by walkerke** [comment]
Fixed in https://github.com/walkerke/tidycensus/commit/7d9d8b681c3a696a103e03026d0296274ec345da.
