### ISSUE TITLE
Kusilvak Census Area (Alaska) Disappears When Using shift_geo = T

### ISSUE THREAD

**Issue by llpuente** [walkerke/tidycensus#61]
When pulling data and geo files and using the `shift_geo = T` feature, the Kusilvak Census Area, Alaska disappears (fips code = 02158). 

Example: 
```
get_acs(geography = "county", 
                  variables = "S1701_C02_001", geometry = T,
                  shift_geo = T)
```

**Comment by walkerke** [comment]
Ah yes I forgot that one.  Fixed now.
