### ISSUE TITLE
Query data for a list of GEOID (tracts)?

### ISSUE THREAD

**Issue by vinhdizzo** [walkerke/tidycensus#62]
Hi,

Suppose I have a list of tract level GEOID's, and I want to query census data via `get_decennial` for this list.  Can I do this within tidycensus?  Or do I have to pull tract data for all states via `get_decennial` with the `geography='tract'` option, then subset the GEOID's that I am interested?  The latter is inefficient, so would like to know if there is any way around this.  Thanks!

**Comment by walkerke** [comment]
Right now this isn't supported.  Would you mind explaining the use case a bit more?  Would you need data for tracts that are potentially scattered around the US?  

Tract-specific data are currently available from the API if a state and county are specified.  Getting data for specific tracts at a time isn't currently available as I haven't had a request for it, but you could conceivably write a wrapper function for this.  For example: 

```r
tract_ids <- c("36103158710", "12103027704", "47145030202", "37119005914", 
               "24003731201", "24017851400", "47105060301", "42045401200", 
               "39153502700", "55079120202")


get_tracts <- function(tracts, variables) {
  map_df(tracts, function(x) {
    state <- str_sub(x, 1, 2)
    county <- str_sub(x, 3, 5)
    get_decennial(geography = "tract", 
                  variables = variables, 
                  state = state, 
                  county = county) %>%
      filter(GEOID == x)
  })
}

get_tracts(tract_ids, "P0010001")

# A tibble: 10 x 4
   GEOID       NAME                 variable value
   <chr>       <chr>                <chr>    <dbl>
 1 36103158710 Census Tract 1587.10 P0010001 3686.
 2 12103027704 Census Tract 277.04  P0010001 2423.
 3 47145030202 Census Tract 302.02  P0010001 7319.
 4 37119005914 Census Tract 59.14   P0010001 5563.
 5 24003731201 Census Tract 7312.01 P0010001 6354.
 6 24017851400 Census Tract 8514    P0010001 8176.
 7 47105060301 Census Tract 603.01  P0010001 3332.
 8 42045401200 Census Tract 4012    P0010001 3636.
 9 39153502700 Census Tract 5027    P0010001 6574.
10 55079120202 Census Tract 1202.02 P0010001 3173.
```

On my machine, this runs quickly: 

```r
> system.time(get_tracts(tract_ids, "P0010001"))
   user  system elapsed 
   0.37    0.00    1.75 
```

Given the structure of the Census API, I'm not sure the time savings would be substantial as tidycensus would need to do something similar under the hood to stitch together different API calls.

**Comment by vinhdizzo** [comment]
Thanks for the prompt response Kyle.

My use case case is to use census variables in building a predictive model.

1. I geocoded each address to get lat/long.
2. For each lat/long, tie to to a census tract.
3. Get list of unique census tracts.
4. Leverage your package to pull relevant census variables.

Thanks for the suggested code. I was going to do it brute Force similar to
your code, repeating by state. Sounds like I will have to do this.

**Comment by walkerke** [comment]
Thanks for the reply!  Yes I think that is the best move.  We can check what this would look like by using the censusapi package, which allows for the acquisition of specific tract data.  tidycensus would need to implement something like this under the hood.  

```r
library(censusapi)

Sys.setenv(CENSUS_KEY = Sys.getenv("CENSUS_API_KEY"))

get_tracts2 <- function(tracts, variables) {
  map_df(tracts, function(x) {
    getCensus(name = "sf1", 
              vintage = 2010, 
              vars = variables, 
              region = paste0("tract:", 
                              str_sub(x, 6, 11)), 
              regionin = paste0("state:", 
                                str_sub(x, 1, 2), 
                                "+county:", 
                                str_sub(x, 3, 5))
              )
  })
}

> get_tracts2(tract_ids, "P0010001")
   state county  tract P0010001
1     36    103 158710     3686
2     12    103 027704     2423
3     47    145 030202     7319
4     37    119 005914     5563
5     24    003 731201     6354
6     24    017 851400     8176
7     47    105 060301     3332
8     42    045 401200     3636
9     39    153 502700     6574
10    55    079 120202     3173
```

This runs a bit slower than the earlier code sample from tidycensus: 

```r
> system.time(get_tracts2(tract_ids, "P0010001"))
   user  system elapsed 
   0.30    0.03    2.31 
```

**Comment by josiekre** [comment]
Thanks for this tip. I am one of the contributors to the `censusr` package, and this is a key feature for the development of the package. 

My colleague and I run travel models on metropolitan regions all over the US. A region is usually defined by a set of counties, sometimes in one state and sometimes not. 

We are considering deprecating that package and sending users over here so we can consolidate efforts.
