### ISSUE TITLE
Documentation:  ACS Flows

### ISSUE THREAD

**Issue by jabowery** [walkerke/tidycensus#63]
In "[Working with ACS data](https://walkerke.github.io/tidycensus/articles/basic-usage.html#working-with-acs-data)" I see no way to answer the question of how one can acquire State to State (or any other geography), migrations via tidycensus.  I've located [the variable names in the Census Data API](https://api.census.gov/data/2015/acs/flows/variables.html), but it seems no combination of arguments to `get_acs` works.  Usually what comes back is something like:

```
Success No Content Success: (204) No Content
Error in as.character(x) : 
  cannot coerce type 'closure' to vector of type 'character'
```

I hesitate to provide a code that "should" work simply because I am at a loss as to what "should" work, hence the "Documentation" designation of this issue.

What is the "table" for this and how can one derive its name from the aforelinked Census Data API documentation?  I tried simply "flows" for the table but that was no help.  I tried specifying the survey as "acs1" as well as the default "acs5" but that didn't help.   Why is it that whenever I specify more than one variable, as is obviously necessary in specifying any "flow", instead of specifying a table, I get the coerce error?

**Comment by walkerke** [comment]
The ACS flows API is not currently supported in tidycensus.  I'm currently working on supporting new datasets (see #59) so this might be something I could include in the future.  

If you want a package that fully exposes the Census APIs, I recommend the censusapi package (https://github.com/hrecht/censusapi) which presumably could get you migration flow data.
