### ISSUE TITLE
scales = "free" and theme(aspect.ratio = 1) Not working on your example

### ISSUE THREAD

**Issue by Hamed51** [walkerke/tidycensus#65]
@walkerke 
Hi , 
At your website, one your , "Compare US metropolitan area characteristics in R with tidycensus and tigris", which link is: http://walkerke.github.io/2017/06/comparing-metros/ , at end of  example, you created facet map and instruct to  set scales = "free" and theme(aspect.ratio = 1) if you want this to work correctly.
but i got this message by R: Error: Free scales are only supported with `coord_cartesian()` and `coord_flip()`

i could not make your date in R . i got the above error. please advise. 
Thank You

**Comment by walkerke** [comment]
you are correct, an update to ggplot2 broke that blog post.  I need to remove it but I've since upgraded my operating system and my old blogdown configuration hasn't been working, and I haven't had the time to debug it.
