### ISSUE TITLE
Not able to install tidycensus

### ISSUE THREAD

**Issue by k10sj02** [walkerke/tidycensus#66]
Hello, I'm new to R and unable to install tidycensus. See error below:

> library(tidycensus)
Error in library(tidycensus) : there is no package called ‘tidycensus’

**Comment by walkerke** [comment]
In R, packages are installed with the `install.packages()` command.  So do this first: 

```r
install.packages("tidycensus")
```

Then: 

```r
library(tidycensus)
```

**Comment by k10sj02** [comment]
Hi Walker, I forgot to say that I put the initial script to download it:

> installed.packages("tidycensus")
     Package LibPath Version Priority Depends Imports LinkingTo
     Suggests Enhances License License_is_FOSS License_restricts_use
     OS_type Archs MD5sum NeedsCompilation Built
> library(tidycensus)
Error in library(tidycensus) : there is no package called ‘tidycensus’

**Comment by k10sj02** [comment]
My bad. I was in a rush replicating this. This is the correct error message now:

> install.packages("tidycensus")

  There is a binary version available but the source version
  is later:
           binary source needs_compilation
tidycensus    0.4  0.4.1             FALSE

installing the source package ‘tidycensus’

trying URL 'https://cran.rstudio.com/src/contrib/tidycensus_0.4.1.tar.gz'
Content type 'application/x-gzip' length 41198 bytes (40 KB)
==================================================
downloaded 40 KB

* installing *source* package ‘tidycensus’ ...
** package ‘tidycensus’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘rgdal’
ERROR: lazy loading failed for package ‘tidycensus’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/tidycensus’
Warning in install.packages :
  installation of package ‘tidycensus’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/rk/4bv4zlhj323dbkksm1t50kp40000gn/T/Rtmp5TpnZM/downloaded_packages’
> library(tidycensus)
Error in library(tidycensus) : there is no package called ‘tidycensus’

**Comment by mfherman** [comment]
Looks like your system is running into a problem when it tries install `tidycensus` from source. It seems to need another package, `rgdal`, to complete the installation. You could try to install `rgdal` first and then install `tidycensus`.

```
install.packages(c("rgdal", "tidycensus"))
```

**Comment by k10sj02** [comment]
Oh man. I tried that and still nothing. Sorry for the back and forth. I'm new to R.

> install.packages("tidycensus")

  There is a binary version available but the source version
  is later:
           binary source needs_compilation
tidycensus    0.4  0.4.1             FALSE

installing the source package ‘tidycensus’

trying URL 'https://cran.rstudio.com/src/contrib/tidycensus_0.4.1.tar.gz'
Content type 'application/x-gzip' length 41198 bytes (40 KB)
==================================================
downloaded 40 KB

* installing *source* package ‘tidycensus’ ...
** package ‘tidycensus’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘rgdal’
ERROR: lazy loading failed for package ‘tidycensus’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/tidycensus’
Warning in install.packages :
  installation of package ‘tidycensus’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/rk/4bv4zlhj323dbkksm1t50kp40000gn/T/Rtmp5TpnZM/downloaded_packages’
> library(tidycensus)
Error in library(tidycensus) : there is no package called ‘tidycensus’
> install.packages(c("rgdal", "tidycensus"))

  There are binary versions available but the source versions
  are later:
           binary source needs_compilation
rgdal      1.2-16 1.2-18              TRUE
tidycensus    0.4  0.4.1             FALSE

Do you want to install from sources the package which needs compilation?
y/n: y
installing the source packages ‘rgdal’, ‘tidycensus’

trying URL 'https://cran.rstudio.com/src/contrib/rgdal_1.2-18.tar.gz'
Content type 'application/x-gzip' length 1650578 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

trying URL 'https://cran.rstudio.com/src/contrib/tidycensus_0.4.1.tar.gz'
Content type 'application/x-gzip' length 41198 bytes (40 KB)
==================================================
downloaded 40 KB

* installing *source* package ‘rgdal’ ...
** package ‘rgdal’ successfully unpacked and MD5 sums checked
configure: CC: clang
configure: CXX: clang++
configure: rgdal: 1.2-18
checking for /usr/bin/svnversion... yes
configure: svn revision: 718
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘rgdal’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rgdal’
Warning in install.packages :
  installation of package ‘rgdal’ had non-zero exit status
* installing *source* package ‘tidycensus’ ...
** package ‘tidycensus’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘rgdal’
ERROR: lazy loading failed for package ‘tidycensus’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/tidycensus’
Warning in install.packages :
  installation of package ‘tidycensus’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/rk/4bv4zlhj323dbkksm1t50kp40000gn/T/Rtmp5TpnZM/downloaded_packages’
> library(tidycensus)
Error in library(tidycensus) : there is no package called ‘tidycensus’
>

**Comment by mfherman** [comment]
I know I've had some trouble installing `rgdal` from source on certain machines. Another option would be to select `n` when it asks you:
```
Do you want to install from sources the package which needs compilation?
y/n:
```
You will get the earlier version of `tidycensus` that has a binary on CRAN, but it should work fine.

**Comment by walkerke** [comment]
@mfherman is correct, you need to install GDAL first.  This will allow you to use all of R's spatial packages so it will be worth the headache once it's done.  

I'm a Windows & Linux user so I don't know as much about OSX.  However this post may be of use: https://stackoverflow.com/questions/34333624/trouble-installing-rgdal.  

If you use Homebrew, the simplest path seems to be: 

In your Terminal: 

```
brew update
brew install gdal
```

Then, in R: 

```r
install.packages("rgdal")
install.packages("tidycensus")
```

**Comment by arwclark** [comment]
I'm a MAC user and I've spent hours trying to load Tidycensus.  I've read the previous posts and I've loaded "units" "rgdal" and get this message:
The downloaded binary packages are in
	/var/folders/rk/s0crss2j4gl4rhl6j1t92f_r0000gn/T//Rtmp4d37rw/downloaded_packages
> library(tidycensus)
Error: package or namespace load failed for ‘tidycensus’:
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found

**Comment by murphy99** [comment]
I am on a mac intel and Brew install update and Brew Install gdal worked for me.
