### ISSUE TITLE
Latitude for continental US wrong with shift_geo

### ISSUE THREAD

**Issue by nriley** [walkerke/tidycensus#69]
The continental US seems to be at the wrong latitude when I use `shift_geo`.  Obviously I'm not expecting Alaska and Hawaii to be in the right places, but the rest of it is way off.

Here's a simple example of what I'm trying:

```r
hispanic_by_state <- get_acs(geography = 'state', variables = c(
  hispanic_or_latino = 'B03003_003' # Estimate - Hispanic or Latino Origin
  ), summary_var = 'B03002_001', # Estimate - Total - Hispanic or Latino Origin
  year = 2016, geometry = TRUE, shift_geo = TRUE)

hispanic_by_state %>%
  mutate(prop = (estimate / summary_est)) %>%
  ggplot(aes(fill = prop, color = prop)) +
  geom_sf() +
  coord_sf(crs = 6350) + # NAD83(2011) / Conus Albers
  scale_fill_viridis('Hispanic', labels = scales::percent) +
  scale_color_viridis('Hispanic', labels = scales::percent)
```

gives me:

![image](https://user-images.githubusercontent.com/68303/39078038-5b6e1b72-44d4-11e8-84f9-63ca119a5a81.png)

which is off by quite a lot.

I am quite new to `sf` so don't discount that I might be doing something wrong!

…or am I supposed to always use `coord_sf(datum = NA)` with this option and hide the latitude/longitude lines entirely?

**Comment by walkerke** [comment]
`shift_geo` returns data pre-packaged with a custom coordinate system designed for cartographic display of the US - the coordinate system of this data should not be transformed.  Yes, I would always recommend using `coord_sf(datum = NA)` as the graticule is misleading.  

If you need an accurate graticule, I'd advise against using `shift_geo()` and instead putting Alaska and Hawaii in their own insets.
