### ISSUE TITLE
Leaflet issue with get_acs data frame for iowa tracts

### ISSUE THREAD

**Issue by fischertr** [walkerke/tidycensus#73]
When I execute the following code I get this error:

Error in if (length(nms) != n || any(nms == "")) stop("'options' must be a fully named list, or have no names (NULL)") : 
  missing value where TRUE/FALSE needed

I only get this error when I select 2014 as the year, any other years seem to work just fine.

Here is the code:

require(tidyverse)
require(tidycensus)
require(viridis)
require(tigris)
require(sp)
require(sf)
require(leaflet)
require(magrittr)
require(stringr)

  variables = c( "B01001_001E", "C17002_002E", "C17002_003E", "C17002_004E", "C17002_005E", "C17002_006E", "C17002_007E",
                 "B15003_001E", "B15003_002E", "B15003_003E", "B15003_004E", "B15003_005E", "B15003_006E", "B15003_007E", 
                 "B15003_008E", "B15003_009E", "B15003_010E", "B15003_011E", "B15003_012E", "B15003_013E", 
                 "B15003_014E", "B15003_015E", "B15003_016E")
  
  options(tigris_use_cache = TRUE)
  
  rawCensusData <- get_acs(geography="tract", variables = variables, state = "IA", 
                           county = c("Polk", "Dallas", "Warren"), year=2013, 
                           output="wide", survey="acs5", geometry = T, cache_table = T) 
  
  pal=colorBin("magma", rawCensusData$B01001_001E, 6, pretty=T)

  rawCensusData %<>% st_transform(crs = "+init=epsg:4326")
  
  rawCensusData %>%
    leaflet() %>%
    setView(lng=-93.78,lat=41.52, zoom=11) %>%
    addTiles() %>%
  leaflet::addPolygons(data=rawCensusData,
                         weight = 0,
                         smoothFactor = 0,
                         fillOpacity = 0.5,
                         fillColor = ~ pal(rawCensusData$B01001_001E))

  rawCensusData <- get_acs(geography="tract", variables = variables, state = "IA", 
                           county = c("Polk", "Dallas", "Warren"), year=2014, 
                           output="wide", survey="acs5", geometry = T, cache_table = T) 
  
  pal=colorBin("magma", rawCensusData$B01001_001E, 6, pretty=T)
  
  rawCensusData %<>% st_transform(crs = "+init=epsg:4326")
  
  rawCensusData %>%
    leaflet() %>%
    setView(lng=-93.78,lat=41.52, zoom=11) %>%
    addTiles() %>%
    leaflet::addPolygons(data=rawCensusData,
                         weight = 0,
                         smoothFactor = 0,
                         fillOpacity = 0.5,
                         fillColor = ~ pal(rawCensusData$B01001_001E))
  
  
tidycensus v 0.4.6
leaflet v 1.1.0
r v 3.4.4

Thanks for your help,
Tom...

**Comment by walkerke** [comment]
Here's the issue: https://github.com/rstudio/leaflet/issues/482.  Leaflet can't map POLYGON Z data at the moment - and 2014 cartographic boundary files from the Census Bureau are distributed as POLYGON Z.  

I'll clean this up under the hood in __tidycensus__.  In the meantime you can use `st_zm()`: 

```r
rawCensusData %>%
    st_zm() %>%
    leaflet() %>%
    setView(lng=-93.78,lat=41.52, zoom=11) %>%
    addTiles() %>%
    addPolygons(data=rawCensusData,
    weight = 0,
    smoothFactor = 0,
    fillOpacity = 0.5,
    fillColor = ~ pal(rawCensusData$B01001_001E))
```
