### ISSUE TITLE
Erratic get_decennial for counties generating error

### ISSUE THREAD

**Issue by matt439miller** [walkerke/tidycensus#74]
library(sf)
library(tidyverse)
library(tidycensus)
census_api_key(mykey)
options(tigris_use_cache = TRUE)
m90 <- get_decennial(geography = "state",  variables = "H043A001", year = 1990)
m90 <- get_decennial(geography = "county", variables = "H043A001", year = 1990)
m90 <- get_decennial(geography="county",state="49", county="049", variables = "H043A001", year = 1990) #yes
m90 <- get_decennial(geography="county",state="49", county="049", variables = "H043A001", year = 2000) #no
m90 <- get_decennial(geography="county",state="49", county="049", variables = "H043A001", year = 2010) #no

m90 <- get_decennial(geography="county",state="49", county="049", variables = "P001001", year = 1990) #no
m90 <- get_decennial(geography="county",state="49", county="049", variables = "P001001", year = 2000) #yes
m90 <- get_decennial(geography="county",state="49", county="049", variables = "P001001", year = 2010) #no
#is this just a variable name issue?
#P0010001 from: v10 <- load_variables(2010, "sf1", cache = TRUE)
....so no....?

**Comment by walkerke** [comment]
Variable IDs are generally not repeated across decennial Censuses.  For example - note in your code how you are trying `P001001` (four zeroes) for 2010, but identify `P0010001` from `load_variables()` (five zeroes).

**Comment by matt439miller** [comment]
Ah! That clarifies things wonderfully! I am obliged!

Matt Miller <http://www.linkedin.com/pub/matthew-miller/4/392/583/>
PhD Student; Metropolitan Policy, Planning and Design, City and Metro
Planning Department, University of Utah
Graduate Research Assistant, Metropolitan Research Center
Planner, Metro Analytics
millermm@arch.utah.edu
matt439miller@gmail.com

**Comment by walkerke** [comment]
No problem. Thanks for using the package!
