### ISSUE TITLE
support for ACS data profiles

### ISSUE THREAD

**Issue by knaaptime** [walkerke/tidycensus#8]
currently tidycensus only supports access to summary files from the ACS. It would be great to also include variables from the [data profile](http://api.census.gov/data/2015/acs5/profile/variables.html)

**Comment by walkerke** [comment]
agreed, and I don't think it would take too much work to do this.  I'll take a look at it.

**Comment by walkerke** [comment]
I've added support for the data profile in https://github.com/walkerke/tidycensus/commit/2c54a627e24be349f4a667d90a3b425ea9f9a858.
