### ISSUE TITLE
Version 1.0 roadmap

### ISSUE THREAD

**Issue by walkerke** [walkerke/tidycensus#83]
I'm of the mindset that tidycensus is starting to mature as a package.  The intention of the package __is__ to provide access to data on characteristics of the US _population_ in a tidy format, facilitating integration with the tidyverse and sf.  It __is not__ intended to be a wrapper for all of the Census APIs, as the censusapi package already does that.  

As such I'm seeing a stable 1.0 release of tidycensus in the near future.  New features in the package will include: 

* Access to the Population Estimates API __for products that make data available at geographies smaller than the entire US__.  This means that the projections API will not be supported; users should go to censusapi for that.  
* Access to the ACS migration flows API: this makes sense as it fits within the larger project that is funding tidycensus development.  

Datasets on economic characteristics of the US (e.g. the Economic Census, QWI, etc.) won't be supported in this package as they are formatted differently and would make more sense in a standalone package and/or through censusapi.  

__Goal:__ version 1.0 released to CRAN by the end of August or around the same time that the tidycensus DataCamp course is released.

**Comment by tiernanmartin** [comment]
I'm excited to hear that a DataCamp course is on the horizon.

Have you given any thought to the best way to enable `tidycensus` users to perform [longitudinal analyses at the census tract level](https://community.rstudio.com/t/tidycensus-applied-longitudinally/5034?u=tiernan)?

**Comment by tiernanmartin** [comment]
I was hesitant to suggest it because I know you've been working hard to keep `tidycensus` focused on the Census API. Glad to hear you're already tracking this as a potential use case!

I'm just starting a project that will pull census tract data with `tidycensus` and normalize 2000 tracts to the 2010 boundaries using the Longitudinal Tract Database crosswalk files. As I proceed I'll see if I can come up with a minimal example that might work for your book 👍

**Comment by walkerke** [comment]
Updating this - I'll need to send to CRAN this week before reaching 1.0 to account for changes in the Census API endpoint.   This CRAN release will have Population Estimates API support but will not have support yet for the Flows API.

**Comment by walkerke** [comment]
Update, April 2019: 

tidycensus 1.0 will be released this summer and I'll consider the API stable after that.  It will include: 
- Geometry support for ALL available geographies in the API
- Migration flows support _with_ linked geometry so users can map migration flows quickly.  

I'll then put tidycensus into maintenance mode and finish up the book, though I will still entertain pull requests for new features.

**Comment by walkerke** [comment]
@mfherman I'm bumping this as I think we're finally getting closer to the long-awaited tidycensus 1.0.  I'm going to send 0.9.5 up to CRAN which includes your edits and an updated default year in `get_acs()` to 2018.  

The one thing I absolutely want to do for version 1.0 is support `geometry = TRUE` for all geographies.  I'm going to get moving on this next week.  Beyond that, a possibility I'm entertaining is the ability to do custom subsets of data through internal spatial overlay.  For example, if someone wanted to get all ZCTAs that intersect a custom geometry of interest (related to #177).  

Let's have this discussion here in case there are any other community suggestions.

**Comment by mfherman** [comment]
Sounds great! Here are some thoughts and ideas:

**Test Suite (gulp)**
This seems like a big project and candidly, I don't know much about it. I've read a bit about approaches to unit testing for packages that rely on web resources and it seems like there are some good options. But if we're able to implement, it would make me feel much more confident that I'm not inadvertently breaking things when I'm making changes!

Here are some useful resources/packages I've explored on the topic:

https://enpiar.com/r/httptest/
https://docs.ropensci.org/webmockr/
https://docs.ropensci.org/vcr/
https://blog.r-hub.io/2019/10/29/mocking/
https://discuss.ropensci.org/t/best-practices-for-testing-api-packages/460/12

**Additional Vignettes**
- How to diagnose errors from `get_*()` calls
-- Is it an API or tidycensus error/bug?
-- How to use `show_call`
- How to determine which variables are available at which geographic levels
-- Pointers about using the Census API documentation (https://api.census.gov/data/2018/acs/acs1.html)
- Anything else?

**Automate deploy of pkgdown site**
It seems like you manually generate the pkgdown site and push changes to github pages? I've set up Travis CI to build and deploy my pkgdown site whenever I push a commit to GitHub. Here's my travis config for this: https://travis-ci.org/mfherman/nycgeo/builds/489067637/config

Let me know what you think about these and which (if any) you think should be a priority.

**Comment by walkerke** [comment]
Closing this as we've ended up going in some different directions since then.
