### ISSUE TITLE
Suggest rather than import sf package

### ISSUE THREAD

**Issue by MaxGhenis** [walkerke/tidycensus#84]
`tidycensus` is awesome, but took me a ton of time to figure out how to install it due to its `sf` dependency. I tried all the recommendations from various Stackoverflow answers, but these ended up messing up my `conda` environment.

I think I'm set now but I wonder if enough people would be OK using `tidycensus` without the mapping functionality that it would be OK to suggest `sf` instead, given how commonplace issues installing it seem to be.

**Comment by walkerke** [comment]
Does the conda availability solve your problem then?  I'm disinclined to remove the sf dependency as I see the spatial component as a core function of the package.  If you need a Census package that does not depend on sf, the censusapi and acs packages may meet your needs.

**Comment by MaxGhenis** [comment]
Yes, conda availability solved it, though I had to wipe my machine. Including it in installation instructions alongside `install.packages` might save others some difficulty.

Makes sense that spatial is core, and thanks for the info on `censusapi` and `acs`.
