### ISSUE TITLE
Interest in LODES?

### ISSUE THREAD

**Issue by berdaniera** [walkerke/tidycensus#89]
Thank you for making tidycensus! We are using it at TransLoc to explore demographic patterns in public transit usage. We have also found value in the [LODES](https://lehd.ces.census.gov/data/) data for commute origin-destination patterns as a complement to the ACS data.

@angela-li and I have been working on a function `get_lodes` (based on [hrbrmstr/lodes](https://github.com/hrbrmstr/lodes)) that mirrors `get_acs` for our own use. **Is there interest in adding something like this to tidycensus?** If so, we could develop a draft and open a pull request. I know that the current functions access the Census API and that the LODES data are not from that same source, so it is no problem if this is outside of the package scope. But, we are interested in contributing if there is interest.

**Comment by walkerke** [comment]
Thanks for your note!  Pinging here @jamgreen as he's been working on an LEHD/LODES package as well at https://github.com/jamgreen/lehdr and has been incorporating other economic data functions from the Census Bureau.  

I appreciate the pull request offer!  However I think this is outside the package scope, as I've decided to keep the focus for this package on population characteristics - which will ultimately cover the decennial/ACS APIs, the population estimates APIs, and the migration flows API.

**Comment by berdaniera** [comment]
Sure that sounds good, I get the focus on the population aspects. 👍 

I didn't know about lehdr, so thanks for sharing that! Definitely don't need to duplicate work there and I'm excited to check out @jamgreen's work :)

**Comment by jamgreen** [comment]
Please let me know if lehdr is able to do what you need it to @berdaniera. We're hoping to submit to CRAN this summer so having folks who are doing some more heavy lifting with it would be great.
