### ISSUE TITLE
Class of get_acs depends on value of geometry object

### ISSUE THREAD

**Issue by davechilders** [walkerke/tidycensus#9]
`get_acs()` appears to return a tibble iff `geometry = TRUE`:

```
nc <- get_acs(geography = "county", state = "NC", variables = "B19013_001")
class(nc)
[1] "tbl_df"     "tbl"        "data.frame"

nc_geom <- get_acs(geography = "tract", state = "NC", variables = "B19013_001", geometry = TRUE)
class(nc_geom)
[1] "sf"         "data.frame"
```

Should the second call above also return a tibble?

**Comment by walkerke** [comment]
Thanks for your note - I'll take a look at this.

**Comment by walkerke** [comment]
This is updated in https://github.com/walkerke/tidycensus/commit/bb810788ae5b8fa7791d7c37ac85ac7ead6c32a3.  Thanks for using the package!
