### ISSUE TITLE
Upcoming decennial Census API changes

### ISSUE THREAD

**Issue by walkerke** [walkerke/tidycensus#91]
> About a year ago, the U.S. Census Bureau began the process of centralizing all data in the Census API into a uniform and consistent format across all datasets and surveys. We are continuing with that transformation by releasing a more consistent format for the 2010 Decennial Summary File 1 (SF1) counts. We understand that standardization means changes for our developers, but the tradeoff will be greater data accessibility in an easier, more customer-focused experience.
>
> We released new endpoints as a Beta to allow time for you to become familiar with the new format and adjust your programs to reflect these changes. In addition to new endpoints, you also will see changes to variable names and new annotation fields. To accommodate this format change, the endpoints will change to add program name (e.g., '/dec/') into the URL after the year. The old endpoints will be removed on August 30th.
> 
> ENDPOINT CHANGE:
> Old endpoint: https://api.census.gov/data/2010/sf1
> New endpoint: https://api.census.gov/data/2010/dec/sf1
> 
> VARIABLE NAME CHANGES: Please note the changes to some variable names.
> H00010001 is now H001001, and PCT0210001 is now PCT021001, for example.  A complete variable mapping is not available.
> 
> 
> ANNOTATION FIELDS: These endpoints now include annotation fields for many counts. This will enable the counts to be numeric and the character overrides to be stored in corresponding annotation fields. For example, the annotation field for H001001 is H001001ERR. The variables with corresponding annotation fields include:
> H001001,H002001,H003001,H003002,H003003,H004001,H005001,H006001,H007001,
> H010001,H011001,H013001,H014001,H015001,H016001,H017001,H018001,H019001,
> H020001,H021001,HCT001001,HCT002001,HCT003001,HCT004001,P001001,P002001,
> P003001,P004001,P005001,P008001,P009001,P012001,P013G002,P013H001,P013H002,
> P015001,P016001,P018001,P019001,P020001,P021001,P022001,P023001,P024001, P025001,P026001,P027001,P028001,P029001,P029002,P029026,P030001,P042001,
> P043001,P044001,P051001,PCO001001,PCT011001,PCT012001,PCT013001,PCT014001,
> PCT015001,PCT016001,PCT020001
> 
> Please let us know if you have questions at cnmp.developers@census.gov.

**Comment by walkerke** [comment]
The endpoints are addressed in https://github.com/walkerke/tidycensus/commit/1b707e9e3ea6bb0e5ff082c470b55e1a60095902; `load_variables()` will need to be refreshed for decennial Census variable pulls

**Comment by walkerke** [comment]
The problem is that https://api.census.gov/data/2010/sf1/variables.html has not been updated and these variable IDs no longer work.  Without a reference table from the Census Bureau there's not much I can do aside from plug in an error message.

**Comment by loganpowell** [comment]
Sorry for the confusion on this. It is hard when the organization makes these kinds of changes and we very much appreciate the work of library builders. You can find the new variable ids at the new endpoint here: https://api.census.gov/data/2010/dec/sf1/variables.html

**Comment by bbrewington** [comment]
Looks like this R filr needs to be updated with the link that Logan provided: https://github.com/walkerke/tidycensus/blob/master/R/search_variables.R

I wonder if there are other similar variable list links that need updated?

**Comment by walkerke** [comment]
This is now fixed in https://github.com/walkerke/tidycensus/commit/0a987f86f40580f8313e31e51b732eb3962be57c.
