### ISSUE TITLE
in readme: is github version of ggplot2 still required?

### ISSUE THREAD

**Issue by arvi1000** [walkerke/tidycensus#97]
The readme states:
``# Requires the installation of the GitHub version and ggplot2``

...but I think that may no longer be true, since v3 is on CRAN now (as of July). If so, I suggest removing the comment block at the top of the first example. It may lower the barrier to test driving this excellent package!

This is the comment block I mean:
```
# Requires the installation of the GitHub version and ggplot2
# library(devtools)
# install_github("tidyverse/ggplot2")
```

**Comment by walkerke** [comment]
it is no longer required, good suggestion!
